// Regenerates The Gaffer's Android icons and store icon from web/src/brand.ts (the one BRAND switch).
//   node games/the-gaffer/scripts/brand-assets.mjs            (Node 22.18+; reads brand.ts directly)
// Writes, for BOTH options, android/app/src/brand{A,B}/res: the adaptive foreground vector and the legacy launcher PNGs
// (mdpi..xxxhdpi); build.gradle adds the folder that matches BRAND. Writes the shared adaptive background + monochrome
// vectors into src/main/res, and store/icon.svg + store/play-store-icon-512.png for the current BRAND.
// PNGs need Playwright + Chromium: set PLAYWRIGHT_DIR to a folder whose node_modules has playwright and, if needed,
// CHROMIUM to the browser binary. Without them the vectors are still written and the PNG step is skipped.
import { mkdirSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as brand from '../web/src/brand.ts';

const HERE = dirname(fileURLToPath(import.meta.url));
const ANDROID = resolve(HERE, '../android');
const RES = (dir) => resolve(ANDROID, 'app/src', dir, 'res');
const write = (file, text) => { mkdirSync(dirname(file), { recursive: true }); writeFileSync(file, text); console.log('wrote', file.replace(resolve(HERE, '..') + '/', '')); };

// Bake translate+scale into an absolute SVG path (M L H V Q C Z, as fontTools writes them) for Android vectors.
function bake(d, { x, y, scale }) {
  const tok = d.match(/[MLHVQCZ]|-?\d*\.?\d+(?:e-?\d+)?/gi);
  let out = '', cmd = '', axis = 0;
  const n = (v) => String(Math.round(v * 100) / 100);
  for (const t of tok) {
    if (/[A-Z]/i.test(t)) { cmd = t; axis = 0; out += t; continue; }
    const v = Number(t);
    if (cmd === 'H') out += n(v * scale + x) + ' ';
    else if (cmd === 'V') out += n(v * scale + y) + ' ';
    else { out += n(axis === 0 ? v * scale + x : v * scale + y) + (axis === 0 ? ',' : ' '); axis ^= 1; }
  }
  return out.trim();
}
const poly = (pts) => 'M' + pts.split(' ').join('L') + 'Z';
const g = brand.ADAPTIVE.g;
const gPath = bake(brand.G_PATH, brand.gTransform(g.scale, g.cx, g.baseline));
const bannerPath = poly(brand.ADAPTIVE.banner);
const HEAD = '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by games/the-gaffer/scripts/brand-assets.mjs from web/src/brand.ts. Do not edit by hand. -->\n';
const vector = (body, extra = '') => `${HEAD}<vector xmlns:android="http://schemas.android.com/apk/res/android"${extra}
    android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">
${body}
</vector>
`;

for (const opt of ['A', 'B']) {
  const p = brand.PALETTES[opt];
  write(resolve(RES(`brand${opt}`), 'drawable/ic_launcher_foreground.xml'), vector(
    `    <path android:fillColor="${p.banner}" android:pathData="${bannerPath}"/>\n    <path android:fillColor="${p.text}" android:pathData="${gPath}"/>`));
}
write(resolve(RES('main'), 'drawable/ic_launcher_monochrome.xml'), vector(
  `    <path android:fillColor="#FFFFFFFF" android:fillType="evenOdd" android:pathData="${bannerPath}${gPath}"/>`));
write(resolve(RES('main'), 'drawable/ic_launcher_background.xml'), vector(`    <path android:pathData="M0,0h108v108h-108z">
        <aapt:attr name="android:fillColor">
            <gradient android:type="linear" android:startX="54" android:startY="0" android:endX="54" android:endY="108">
                <item android:offset="0" android:color="${brand.GROUND}"/>
                <item android:offset="1" android:color="${brand.GROUND_DEEP}"/>
            </gradient>
        </aapt:attr>
    </path>
    <path android:pathData="M0,0h108v108h-108z">
        <aapt:attr name="android:fillColor">
            <gradient android:type="radial" android:centerX="54" android:centerY="0" android:gradientRadius="97">
                <item android:offset="0" android:color="#52${brand.GLOW.slice(1)}"/>
                <item android:offset="1" android:color="#00${brand.GLOW.slice(1)}"/>
            </gradient>
        </aapt:attr>
    </path>`, '\n    xmlns:aapt="http://schemas.android.com/aapt"'));
write(resolve(ANDROID, 'store/icon.svg'), brand.iconSvg() + '\n');

// Legacy launcher PNGs (Android 7.0-7.1 and launchers without adaptive icons) + the Play Store icon.
let chromium;
try {
  const req = createRequire(resolve(process.env.PLAYWRIGHT_DIR || process.cwd(), 'noop.js'));
  ({ chromium } = req('playwright'));
} catch { console.warn('playwright not found (set PLAYWRIGHT_DIR): skipped the PNGs'); process.exit(0); }
const browser = await chromium.launch(process.env.CHROMIUM ? { executablePath: process.env.CHROMIUM } : {});
const png = async (svg, size, file) => {
  const page = await browser.newPage({ viewport: { width: size, height: size } });
  await page.setContent(`<style>html,body{margin:0;background:transparent}</style><img src="${brand.svgDataUri(svg)}" width="${size}" height="${size}">`);
  await page.waitForTimeout(50);
  mkdirSync(dirname(file), { recursive: true });
  await page.screenshot({ path: file, omitBackground: true, clip: { x: 0, y: 0, width: size, height: size } });
  await page.close();
  console.log('wrote', file.replace(resolve(HERE, '..') + '/', ''));
};
const DENSITIES = { mdpi: 48, hdpi: 72, xhdpi: 96, xxhdpi: 144, xxxhdpi: 192 };
for (const opt of ['A', 'B']) for (const [d, px] of Object.entries(DENSITIES)) await png(brand.iconSvg(opt), px, resolve(RES(`brand${opt}`), `mipmap-${d}/ic_launcher.png`));
await png(brand.iconSvg(), 512, resolve(ANDROID, 'store/play-store-icon-512.png'));
await browser.close();
