// @ts-nocheck -- verbatim port of Tier One's intro script (plain ES5); generated by scripts/extract-semba-intro.mjs.
/* Semba Studios intro: a real-time, resolution-independent animation of the real logo (design #17 Neon Ring, the exact PNG, never redrawn)
   with a pre-rendered trailer soundtrack (source: games/tier-one/intro-sound/render.js). Beats: neon strike 0-0.45s, dim, riser 1.35-2.46,
   silent beat, IMPACT 2.53 (flash, shockwave, debris, dust, shake), neon re-ignites 2.7-3.4, wordmark, out at 4.25s. */
import { LOGO, BOOT_SND } from './assets';

export const BOOT_MARKUP = "<div class=\"bsh\"><canvas class=\"bbg\" aria-hidden=\"true\"></canvas><div class=\"bstage\"><img class=\"blogo\" alt=\"\" decoding=\"sync\"><div class=\"bword\" aria-hidden=\"true\"><b>SEMBA</b><span>STUDIOS</span></div></div><canvas class=\"bfx\" aria-hidden=\"true\"></canvas></div>";

// Runs the intro once on the #boot element (index.html); fires "sembaboot" on window when it starts to fade out.
export function playIntro(){
 var b=document.getElementById('boot'); if(!b) return;
 function gone(){ try{ window.dispatchEvent(new Event('sembaboot')); }catch(e){} }
 if(/[?&]session_id=/.test(location.search)){ b.remove(); window.__bootDone=true; return; }
 var DUR=4.25, T=2.53;
 var sh=b.querySelector('.bsh'), bg=b.querySelector('.bbg'), fx=b.querySelector('.bfx'), img=b.querySelector('.blogo'), word=b.querySelector('.bword'), wb=word.firstChild, ws=word.lastChild;
 var gb=bg.getContext('2d'), gf=fx.getContext('2d'), done=false, started=false, raf=0, t0=0, au=null, silent=false, lastT=0;
 var soundOn=true;
 img.src=LOGO;
 // ---- helpers
 function cl(x){ return x<0?0:x>1?1:x; } function sm(a,c,t){ var x=cl((t-a)/(c-a)); return x*x*(3-2*x); } function eo(x){ x=cl(x); return 1-Math.pow(1-x,3); }
 var seed=7; function R(){ seed=(seed*16807)%2147483647; return (seed-1)/2147483646; } function rr(a,c){ return a+R()*(c-a); }
 function mk(w,h){ var c=document.createElement('canvas'); c.width=w; c.height=h; return c; }
 // ---- sprites
 var dot=mk(64,64); (function(){ var g=dot.getContext('2d'), r=g.createRadialGradient(32,32,0,32,32,32); r.addColorStop(0,'rgba(255,255,255,1)'); r.addColorStop(.25,'rgba(255,255,255,.55)'); r.addColorStop(1,'rgba(255,255,255,0)'); g.fillStyle=r; g.fillRect(0,0,64,64); })();
 var puff=mk(128,128); (function(){ var g=puff.getContext('2d'), r=g.createRadialGradient(64,64,0,64,64,64); r.addColorStop(0,'rgba(168,170,140,.9)'); r.addColorStop(.5,'rgba(120,128,100,.45)'); r.addColorStop(1,'rgba(90,100,80,0)'); g.fillStyle=r; g.fillRect(0,0,128,128); })();
 var flare=mk(512,48); (function(){ var g=flare.getContext('2d'), d=g.createImageData(512,48); for(var y=0;y<48;y++) for(var x=0;x<512;x++){ var u=(x-256)/256, v=(y-24)/24, k=Math.exp(-u*u*5)*Math.exp(-v*v*9), c=Math.exp(-u*u*60)*Math.exp(-v*v*30), i=(y*512+x)*4; d.data[i]=Math.min(255,190+65*c); d.data[i+1]=255; d.data[i+2]=Math.min(255,130+125*c); d.data[i+3]=Math.min(255,255*(k*.8+c)); } g.putImageData(d,0,0); })();
 var grain=mk(160,160); (function(){ var g=grain.getContext('2d'), d=g.createImageData(160,160); for(var i=0;i<d.data.length;i+=4){ var v=R()*255; d.data[i]=d.data[i+1]=d.data[i+2]=v; d.data[i+3]=22; } g.putImageData(d,0,0); })();
 var grainPat=gb.createPattern(grain,'repeat');
 var bloom=null, shim=mk(8,8), sg=shim.getContext('2d');
 var hi=null;
 function makeBloom(){ try{ var Z=512, a=mk(Z,Z), ga=a.getContext('2d'); ga.imageSmoothingQuality='high'; ga.beginPath(); ga.arc(Z/2,Z/2,Z*.47,0,6.2832); ga.clip(); ga.drawImage(img,0,0,Z,Z);
   /* highlights only: alpha = brightness above a threshold, so additive light never darkens or covers the crisp DOM logo */
   var d=ga.getImageData(0,0,Z,Z), px=d.data; for(var i=0;i<px.length;i+=4){ var l=Math.max(px[i],px[i+1],px[i+2]), k=l<60?0:Math.min(1,(l-60)/170); px[i+3]=Math.round(px[i+3]*k); } ga.putImageData(d,0,0); hi=a;
   var c=mk(32,32), gc=c.getContext('2d'); gc.imageSmoothingQuality='high'; gc.drawImage(a,0,0,32,32); var o=mk(128,128), go=o.getContext('2d'); go.imageSmoothingQuality='high'; go.drawImage(c,0,0,128,128); bloom=o; }catch(e){} }
 // ---- particles (all analytic in t, so any frame is a pure function of time)
 var motes=[], streaks=[], sparks=[], shards=[], puffs=[], embers=[], rays=[], i;
 for(i=0;i<85;i++) motes.push({x:R(),y:R(),vx:rr(-.012,.012),vy:rr(-.03,-.006),s:rr(.6,2.4),a:rr(.12,.5),f:rr(1,4),p:rr(0,6.3),z:rr(.4,1)});
 for(i=0;i<80;i++){ var u=R(); streaks.push({t:1.35+1.05*Math.sqrt(u),a:rr(0,6.283),d:rr(.4,.62),l:rr(.08,.2),w:rr(.6,1.6),r0:rr(.85,1.15)}); }
 for(i=0;i<150;i++){ var an=rr(0,6.283); sparks.push({ox:rr(-.3,.3),oy:rr(-.3,.3),vx:Math.cos(an),vy:Math.sin(an)-.25,v:rr(.5,1.9)*Math.pow(R(),.35),k:rr(1.6,3.2),life:rr(.35,1.3),w:rr(.7,2),h:R()}); }
 for(i=0;i<64;i++){ var an2=rr(Math.PI*1.03,Math.PI*1.97), big=R()<.14, pts=[], n=4+Math.floor(R()*3); for(var j=0;j<n;j++){ var aa=j/n*6.283+rr(-.4,.4), rd=rr(.55,1); pts.push(Math.cos(aa)*rd,Math.sin(aa)*rd); }
   if(R()<.35) an2=rr(0,6.283); shards.push({ox:rr(-.35,.35),oy:rr(.05,.42),vx:Math.cos(an2),vy:Math.sin(an2),v:rr(.35,1.35)*(big?1.4:1),s:big?rr(9,18):rr(2.2,7),r0:rr(0,6.28),vr:rr(-9,9),pts:pts,big:big}); }
 for(i=0;i<18;i++){ var side=i%2?1:-1, an3=i<14?(side>0?rr(-.35,.12):Math.PI+rr(-.12,.35)):rr(-2.2,-.9); puffs.push({ox:rr(-.25,.25),oy:rr(.22,.42),vx:Math.cos(an3),vy:Math.sin(an3),d:rr(.5,1.35),s0:rr(.25,.45),g:rr(.45,.9),a:rr(.18,.32),front:i%3===0}); }
 for(i=0;i<46;i++) embers.push({x:R(),y0:rr(.35,1.05),vy:rr(.03,.11),f:rr(1.2,3),amp:rr(.004,.02),p:rr(0,6.3),s:rr(.8,2.2),t:rr(2.6,3.4),gold:R()<.3});
 for(i=0;i<16;i++) rays.push({a:i/16*6.283+rr(-.15,.15),w:rr(.012,.05),l:rr(.6,1.05),sp:rr(.04,.12)*(i%2?1:-1)});
 // ---- layout
 var W=1,H=1,cx=0,cy=0,S=200,sc=1,MR=1,dB=1,dF=1,gGlow,gAmb,gRay;
 function layout(){ var vw=innerWidth||360, vh=innerHeight||640, land=vw>vh*1.15; S=Math.round(Math.max(96,Math.min(vw*.58,vh*(land?.46:.34),320))); sc=S/220; b.style.setProperty('--s',S+'px');
  var r=sh.getBoundingClientRect(); W=r.width||vw; H=r.height||vh; var dpr=window.devicePixelRatio||1; dB=Math.min(dpr,1.5); dF=Math.min(dpr,2);
  bg.width=Math.round(W*dB); bg.height=Math.round(H*dB); fx.width=Math.round(W*dF); fx.height=Math.round(H*dF);
  var lr=img.getBoundingClientRect(); cx=lr.left+lr.width/2-r.left; cy=lr.top+lr.height/2-r.top; MR=Math.sqrt(W*W+H*H)/2+40;
  gGlow=gb.createRadialGradient(cx,cy,S*.3,cx,cy,S*2.1); gGlow.addColorStop(0,'rgba(150,230,60,.5)'); gGlow.addColorStop(.3,'rgba(90,170,30,.14)'); gGlow.addColorStop(1,'rgba(40,90,10,0)');
  gAmb=gb.createRadialGradient(cx,cy*1.05,0,cx,cy*1.05,MR); gAmb.addColorStop(0,'rgba(16,38,20,.8)'); gAmb.addColorStop(.5,'rgba(5,14,9,.45)'); gAmb.addColorStop(1,'rgba(0,0,0,0)');
  gRay=gb.createRadialGradient(cx,cy,S*.2,cx,cy,MR); gRay.addColorStop(0,'rgba(200,255,130,.55)'); gRay.addColorStop(.4,'rgba(160,240,80,.14)'); gRay.addColorStop(1,'rgba(120,200,40,0)');
  var L=Math.ceil(S*1.25*dF); if(shim.width!==L){ shim.width=L; shim.height=L; } }
 // ---- timeline
 function neon(t){ var k,v;
  if(t<.1) return 0;
  if(t<.42){ var on=[[.10,.13,.7],[.165,.19,.45],[.24,.30,.95],[.325,.345,.55],[.37,.42,1.05]]; for(k=0;k<on.length;k++) if(t>=on[k][0]&&t<on[k][1]) return on[k][2]*(.88+.12*Math.sin(t*310)); return .05; }
  if(t<1.35) return (.52+.63*Math.exp(-(t-.42)/.2))*(1+.035*Math.sin(t*81.7));
  if(t<2.40) return .52+.5*sm(1.35,2.40,t)+.04*Math.sin(t*97)*sm(1.8,2.4,t);
  if(t<2.46) return 1.02-.9*cl((t-2.40)/.06);
  if(t<T) return .07;
  if(t<2.72) return .42+1.25*Math.exp(-(t-T)/.07);
  if(t<2.93){ var f=[[2.72,2.755,1.05],[2.79,2.83,.9],[2.86,2.885,.75]]; for(k=0;k<f.length;k++) if(t>=f[k][0]&&t<f[k][1]) return f[k][2]; return .32; }
  if(t<3.3) return .78+.5*sm(2.93,3.3,t);
  v=1+.28*Math.exp(-(t-3.3)/.28)+.025*Math.sin(t*9.3); return v; }
 function kscale(t){ if(t<1.35) return .9+.1*eo(t/1.35); if(t<2.40) return 1+.05*sm(1.35,2.40,t); if(t<T) return 1.05-.08*eo((t-2.40)/.1); var a=t-T; return 1+.13*Math.exp(-a/.13)*Math.cos(a*17)+.025*sm(2.8,4.3,t); }
 function shake(t){ if(t<T) return t<2.46?3.2*sm(1.8,2.44,t):0; return 20*Math.exp(-(t-T)/.17)+1.2*Math.exp(-(t-T)/.6); }
 function rayI(t){ if(t<2.46) return .45*sm(1.35,2.4,t)+.12*sm(.2,.45,t)*(1-sm(.6,1.3,t)); if(t<T) return 0; var a=t-T; return .35+.9*Math.exp(-a/.35)+.35*Math.exp(-Math.pow((t-3.3)/.25,2)); }
 // ---- draw one frame at time t (seconds)
 function draw(t){
  var N=Math.max(0,neon(t)), K=kscale(t), vis=t<2.44?sm(.05,.7,t):t<T?.15:1, a=t-T, j, p, x, y;
  // shake the whole scene
  var A=shake(t)*sc; sh.style.transform=A>.05?'translate('+(A*(Math.sin(t*83.1)+.6*Math.sin(t*137.7))/1.6).toFixed(2)+'px,'+(A*(Math.sin(t*97.3+1)+.5*Math.sin(t*151.9))/1.5).toFixed(2)+'px) rotate('+(A*.035*Math.sin(t*71)).toFixed(3)+'deg)':'';
  // logo + wordmark (DOM: crisp at native resolution)
  img.style.opacity=cl(N*1.9).toFixed(3); img.style.transform='scale('+K.toFixed(4)+')'; img.style.filter='brightness('+(.3+N*.78).toFixed(3)+') saturate('+(.75+N*.35).toFixed(3)+')';
  var wo=sm(3.0,3.45,t), wo2=sm(3.2,3.65,t); word.style.opacity=wo>0?1:0;
  wb.style.opacity=wo.toFixed(3); wb.style.letterSpacing=wb.style.paddingLeft=(.34+.55*(1-eo((t-3.0)/.6))).toFixed(3)+'em'; wb.style.filter=wo<1?'blur('+(8*(1-wo)).toFixed(2)+'px)':'';
  ws.style.opacity=(wo2*.92).toFixed(3); ws.style.letterSpacing=ws.style.paddingLeft=(.62+.5*(1-eo((t-3.2)/.6))).toFixed(3)+'em';
  // ---------- background canvas
  var g=gb; g.setTransform(dB,0,0,dB,0,0); g.globalCompositeOperation='source-over'; g.globalAlpha=1; g.fillStyle='#010302'; g.fillRect(0,0,W,H);
  g.globalAlpha=vis*(.55+.45*cl(N)); g.fillStyle=gAmb; g.fillRect(0,0,W,H);
  g.globalCompositeOperation='lighter';
  g.globalAlpha=cl(.12+.5*N)*(t<T&&t>2.44?.2:1); g.fillStyle=gGlow; g.fillRect(0,0,W,H);
  var ri=rayI(t); if(ri>.01){ g.globalAlpha=Math.min(1,ri); g.fillStyle=gRay; g.beginPath(); for(j=0;j<rays.length;j++){ var r0=rays[j], an=r0.a+t*r0.sp, L=MR*r0.l*(t>T?.7+.3*eo(a/.4):1); g.moveTo(cx,cy); g.lineTo(cx+Math.cos(an-r0.w)*L,cy+Math.sin(an-r0.w)*L); g.lineTo(cx+Math.cos(an+r0.w)*L,cy+Math.sin(an+r0.w)*L); g.closePath(); } g.fill(); }
  // dust motes (pushed outward by the blast)
  for(j=0;j<motes.length;j++){ var m=motes[j]; x=((m.x+m.vx*t)%1+1)%1*W; y=((m.y+m.vy*t)%1+1)%1*H; if(t>T){ var dx=x-cx, dy=y-cy, dd=Math.sqrt(dx*dx+dy*dy)+1, push=90*sc*(1-Math.exp(-a*5))*Math.min(1,260*sc/dd); x+=dx/dd*push; y+=dy/dd*push; }
   var al=m.a*vis*(.6+.4*Math.sin(t*m.f+m.p))*(.5+.6*cl(N)); if(al<=.01) continue; g.globalAlpha=Math.min(1,al); var s=m.s*m.z*6*sc; g.drawImage(dot,x-s/2,y-s/2,s,s); }
  // riser streaks rushing in
  if(t>1.35&&t<2.46){ g.lineCap='round'; for(j=0;j<streaks.length;j++){ var st=streaks[j], q=(t-st.t)/st.d; if(q<0||q>1) continue; var e=q*q*q, rd=MR*st.r0*(1-e)+S*.45*e, ln=MR*st.l*(.4+q); g.globalAlpha=(.25+.6*q)*sm(0,.15,q)*(1-sm(.85,1,q)); g.strokeStyle='rgba(205,255,150,1)'; g.lineWidth=st.w*sc*(.6+q);
   var ca=Math.cos(st.a), sa=Math.sin(st.a); g.beginPath(); g.moveTo(cx+ca*rd,cy+sa*rd); g.lineTo(cx+ca*(rd+ln),cy+sa*(rd+ln)); g.stroke(); } }
  // dust clouds behind the logo
  g.globalCompositeOperation='source-over';
  if(t>T){ for(j=0;j<puffs.length;j++){ var pf=puffs[j]; if(pf.front) continue; drawPuff(g,pf,a); } }
  g.globalAlpha=.55; g.fillStyle=grainPat; var ox=(t*997%160)|0, oy=(t*661%160)|0; g.translate(-ox,-oy); g.fillRect(0,0,W+160,H+160); g.setTransform(dB,0,0,dB,0,0);
  // ---------- front canvas
  g=gf; g.setTransform(dF,0,0,dF,0,0); g.globalAlpha=1; g.globalCompositeOperation='source-over'; g.clearRect(0,0,W,H);
  g.globalCompositeOperation='lighter';
  if(bloom&&N>.02){ var bs=S*K*1.06; g.globalAlpha=Math.min(1,.5*N); g.drawImage(bloom,cx-bs/2,cy-bs/2,bs,bs); bs=S*K*1.22; g.globalAlpha=Math.min(1,.3*N); g.drawImage(bloom,cx-bs/2,cy-bs/2,bs,bs); }
  // impact: flash, lime burst, shockwaves, anamorphic streak
  if(a>=0){
   if(a<.7){ g.globalAlpha=.9*Math.exp(-a/.07); g.fillStyle='#eaffd6'; g.fillRect(0,0,W,H); }
   if(a<1.2){ g.globalAlpha=.85*Math.exp(-a/.25); g.fillStyle=gGlow; g.fillRect(0,0,W,H); }
   for(j=0;j<2;j++){ p=(a-j*.08)/(.8+j*.25); if(p<=0||p>=1) continue; var rr2=MR*1.15*eo(p)+S*.3; g.globalAlpha=(j?.35:.6)*Math.pow(1-p,1.4); g.strokeStyle='rgba(215,255,170,1)'; g.lineWidth=((j?10:28)*(1-p)+1.5)*sc; g.beginPath(); g.arc(cx,cy,rr2,0,6.2832); g.stroke(); }
  }
  var fl=a>=0?1.1*Math.exp(-a/.3):0; fl+=.55*Math.exp(-Math.pow((t-3.3)/.12,2)); if(fl>.01){ g.globalAlpha=Math.min(1,fl); var fw=W*1.9*(a>=0&&a<.8?1:.7), fh=S*.26; g.drawImage(flare,cx-fw/2,cy-fh/2,fw,fh); g.globalAlpha=Math.min(1,fl*.5); g.drawImage(dot,cx-S*.35,cy-S*.35,S*.7,S*.7); }
  // shimmer sweep across the logo at full glow (luminance-weighted: only bright parts catch the light)
  if(hi&&t>3.2&&t<3.8){ p=(t-3.2)/.6; var Lp=shim.width, sg2=sg; sg2.setTransform(1,0,0,1,0,0); sg2.globalCompositeOperation='source-over'; sg2.globalAlpha=1; sg2.clearRect(0,0,Lp,Lp);
   var li=Lp/1.25*K; sg2.drawImage(hi,(Lp-li)/2,(Lp-li)/2,li,li);
   var u=(-0.35+p*1.7)*Lp, lg=sg2.createLinearGradient(u-Lp*.2,u-Lp*.2,u+Lp*.2,u+Lp*.2); lg.addColorStop(0,'rgba(255,255,255,0)'); lg.addColorStop(.5,'rgba(255,255,255,1)'); lg.addColorStop(1,'rgba(255,255,255,0)');
   sg2.globalCompositeOperation='destination-in'; sg2.fillStyle=lg; sg2.fillRect(0,0,Lp,Lp); sg2.globalCompositeOperation='source-atop'; sg2.fillStyle='rgba(235,255,210,.6)'; sg2.fillRect(0,0,Lp,Lp);
   g.globalAlpha=Math.sin(p*Math.PI); g.drawImage(shim,cx-S*.625,cy-S*.625,S*1.25,S*1.25); g.drawImage(shim,cx-S*.625,cy-S*.625,S*1.25,S*1.25); }
  // sparks
  if(a>0&&a<1.4){ g.lineCap='round'; for(j=0;j<sparks.length;j++){ var sp=sparks[j]; if(a>sp.life) continue; var V=sp.v*S*3.2, e1=(1-Math.exp(-sp.k*a))/sp.k, e0=(1-Math.exp(-sp.k*Math.max(0,a-.035)))/sp.k, gy=260*sc;
    var x1=cx+sp.ox*S+sp.vx*V*e1, y1=cy+sp.oy*S+sp.vy*V*e1+gy*a*a, x0=cx+sp.ox*S+sp.vx*V*e0, y0=cy+sp.oy*S+sp.vy*V*e0+gy*Math.pow(Math.max(0,a-.035),2), lf=1-a/sp.life;
    g.globalAlpha=Math.min(1,lf*1.3); g.strokeStyle=sp.h<.45?'rgb(235,255,200)':sp.h<.85?'rgb(182,255,58)':'rgb(255,200,90)'; g.lineWidth=sp.w*sc*(.5+lf*.8); g.beginPath(); g.moveTo(x0,y0); g.lineTo(x1,y1); g.stroke(); } }
  // embers drifting up after the re-ignite
  for(j=0;j<embers.length;j++){ var em=embers[j], ea=t-em.t; if(ea<0) continue; x=(em.x+Math.sin(ea*em.f+em.p)*em.amp)*W; y=(em.y0-em.vy*ea)*H; var ealpha=sm(0,.4,ea)*(.45+.45*Math.sin(ea*em.f*3+em.p)); if(ealpha<.02) continue; g.globalAlpha=ealpha; var es=em.s*5*sc; g.drawImage(dot,x-es/2,y-es/2,es,es); }
  // debris + front dust (normal blending, in front of the logo)
  g.globalCompositeOperation='source-over';
  if(a>0&&a<1.8){ for(j=0;j<shards.length;j++){ var sd=shards[j], V2=sd.v*S*3, e2=(1-Math.exp(-1.2*a))/1.2; x=cx+sd.ox*S+sd.vx*V2*e2; y=cy+sd.oy*S+sd.vy*V2*e2+900*sc*a*a; if(y>H+40||x<-40||x>W+40) continue; var ss=sd.s*sc*(sd.big?1+a*.8:1), rot=sd.r0+sd.vr*a;
    g.save(); g.translate(x,y); g.rotate(rot); g.globalAlpha=Math.min(1,(1-a/1.8)*1.6); g.beginPath(); for(var k2=0;k2<sd.pts.length;k2+=2){ var px=sd.pts[k2]*ss, py=sd.pts[k2+1]*ss; if(k2) g.lineTo(px,py); else g.moveTo(px,py); } g.closePath(); g.fillStyle='#0d120c'; g.fill(); g.strokeStyle='rgba(182,255,58,'+(.35+.4*Math.exp(-a/.3)).toFixed(2)+')'; g.lineWidth=Math.max(.6,ss*.14); g.stroke(); g.restore(); } }
  if(t>T){ for(j=0;j<puffs.length;j++){ if(puffs[j].front) drawPuff(g,puffs[j],a,.6); } }
  g.globalAlpha=1;
 }
 function drawPuff(g,pf,a,mul){ var e=1-Math.exp(-a*2.6), x=cx+pf.ox*S+pf.vx*pf.d*S*1.6*e, y=cy+pf.oy*S+pf.vy*pf.d*S*.9*e-a*S*.08, s=S*(pf.s0+pf.g*Math.sqrt(a))*1.6, al=pf.a*(mul||1)*sm(0,.08,a)*Math.exp(-a/1.6); if(al<.01) return; g.globalAlpha=al; g.drawImage(puff,x-s/2,y-s/2,s,s); }
 // ---- clock + lifecycle
 function now(){ return (window.performance&&performance.now)?performance.now():Date.now(); }
 function clock(){ var tn=(now()-t0)/1000; if(au&&!au.paused&&au.currentTime>0.05&&au.currentTime<4.5){ var d=tn-au.currentTime; if(d>.06||d<-.06){ t0=now()-au.currentTime*1000; tn=au.currentTime; } } return tn; }
 function frame(){ raf=0; if(done&&!b.isConnected) return; var t=clock(); lastT=t; try{ draw(Math.min(t,DUR+1)); }catch(e){} if(t>=DUR) end(); if(!b.isConnected) return; raf=requestAnimationFrame(frame); }
 function end(){ if(done) return; done=true; window.__bootDone=true; b.classList.add('out'); setTimeout(function(){ if(raf) cancelAnimationFrame(raf); raf=0; b.remove(); removeEventListener('resize',onRs); },900); gone(); }
 function still(ms){ if(done||b.classList.contains('still')) return; b.classList.remove('playing'); b.classList.add('still'); layout(); try{ draw(3.95); }catch(e){} setTimeout(end,ms); }
 function begin(){ if(started||done) return; started=true; b.classList.add('playing'); t0=now()-(au&&!silent?au.currentTime*1000:0); layout(); if(!raf) raf=requestAnimationFrame(frame); setTimeout(end,(DUR+1.5)*1000); }
 function beginSilent(){ if(started||done) return; silent=true; if(au){ try{ au.pause(); }catch(e){} } begin(); }
 /* Silent play (autoplay with sound was refused): the first tap anywhere on the intro starts the soundtrack in sync with the animation.
    Taps on the intro are swallowed so they never reach the game underneath. The intro itself cannot be skipped or shortened. */
 function syncSound(e){ if(e){ e.preventDefault(); e.stopPropagation(); } if(!silent||done||!au||au._synced) return; au._synced=true; try{ var el=Math.max(0,Math.min(DUR,(now()-t0)/1000)); au.currentTime=el; silent=false; var pr=au.play(); if(pr&&pr.catch) pr.catch(function(){ silent=true; }); }catch(x){ silent=true; } }
 b.addEventListener('pointerdown',syncSound); b.addEventListener('click',function(e){ e.preventDefault(); e.stopPropagation(); });
 function onRs(){ if(!done) layout(); if(!raf&&!done){ try{ draw(started?lastT:(b.classList.contains('still')?3.95:.5)); }catch(e){} } }
 addEventListener('resize',onRs);
 var reduce=window.matchMedia&&matchMedia('(prefers-reduced-motion: reduce)').matches;
 function ready(fn){ var called=false; function go(){ if(called) return; called=true; makeBloom(); fn(); } if(img.complete&&img.naturalWidth) go(); else { img.addEventListener('load',go); img.addEventListener('error',go); if(img.decode) img.decode().then(go,go); setTimeout(go,600); } }
 layout(); try{ draw(0); }catch(e){}
 if(reduce){ ready(function(){ still(1600); }); return; }
 // The animation always plays and never waits for a tap. Sound without a gesture is only allowed when the page was reached by a
 // click-through (e.g. from sembagames.app); if au.play() is refused the intro plays silently and a tap syncs the soundtrack in.
 if(soundOn){ try{ var bin=atob(BOOT_SND), u8=new Uint8Array(bin.length); for(var q=0;q<bin.length;q++) u8[q]=bin.charCodeAt(q); au=new Audio(URL.createObjectURL(new Blob([u8],{type:'audio/mpeg'}))); au.preload='auto'; au.setAttribute('playsinline',''); }catch(e){ au=null; } }
 if(au){ au.addEventListener('playing',function(){ if(!started&&!done){ silent=false; begin(); } }); au.addEventListener('error',function(){ if(!started) beginSilent(); }); }
 ready(function(){
  if(!au){ begin(); return; }
  var pr; try{ pr=au.play(); }catch(e){ beginSilent(); return; }
  if(pr&&pr.catch) pr.catch(function(){ beginSilent(); });
  setTimeout(function(){ if(!started&&!done) beginSilent(); },1800);
 });
}
