// Saves from before the fictional-names build (Sep 2026) carry near-real star names, near-real sponsor brands and
// real surnames on generated players and staff. renameSave maps every one of them to today's fictional names,
// everywhere a name is stored: world.players, the academy, staff, sponsor deals and offers, transfers, loans,
// rumours, records, news, the inbox and the staff log. Ids, stats and everything else stay untouched.
// It is idempotent (a save with today's names comes back unchanged) and runs only after the checksum is verified.
// The old names are kept as hashes only, so they never appear in the game's text.
import type { Career, LocalizedName } from '../model/types';
import { NICKS, STARS } from '../data/stars';
import { _POOLS } from '../data/names';
import { _BRAND_LISTS } from '../data/sponsors';
import type { World } from './world';

// cyrb53: a 53-bit string hash, written base 36.
function h(str: string): string {
  let h1 = 0xdeadbeef, h2 = 0x41c6ce57;
  for (let i = 0; i < str.length; i++) {
    const ch = str.charCodeAt(i);
    h1 = Math.imul(h1 ^ ch, 2654435761);
    h2 = Math.imul(h2 ^ ch, 1597334677);
  }
  h1 = Math.imul(h1 ^ (h1 >>> 16), 2246822507) ^ Math.imul(h2 ^ (h2 >>> 13), 3266489909);
  h2 = Math.imul(h2 ^ (h2 >>> 16), 2246822507) ^ Math.imul(h1 ^ (h1 >>> 13), 3266489909);
  return (4294967296 * (2097151 & h2) + (h1 >>> 0)).toString(36);
}

// @@TABLES generated by the gf-names lane script from the pre-2026-09 data (hashes only, no old names in plain text).
const OLD_STAR: Record<string, number> = { '16bibf2ixdp': 0, '9v37t4847f': 0, '14wa0zm63g8': 1, '1r4cph1m8ur': 1, '1wyohlxigal': 2, '2dkdmgxx02l': 2, q5yfhnyh2d: 3, '1v0y1ssjnbz': 3, '35ke6vi1s': 4, '4u3pkvnkgx': 4, '1tkf79wcell': 5, '9h6v67x1v5': 5, ii7u72umqd: 6, fg5w96sfei: 6, '1eq8b5901ho': 7, '1x0bu30hnp9': 7, '1gsvl2eqcw8': 8, '2c82r6vd597': 8, '2cpypmlqa28': 9, '1tg9aymogw7': 9, '2fx4m46ph0p': 10, ajwr0yaflv: 10, grnfsdj7a5: 11, '2903x6x2x8d': 11, z3ulzbk9gj: 12, '20loyzh70xh': 12, '2fkhgl3yw6n': 13, nsx8nwrq4q: 13, '1pf0ggimfv1': 14, '13navs9oplx': 14, '2bflb7yztl0': 15, '1u2x1vm32gq': 15, '13az8q5phrj': 16, '1jvxyk4doma': 16, '1wq21b1nlw6': 17, imqheq33jv: 17, lt9zfldqal: 18, '6pvu8azxmy': 18, '1c0czf34na9': 19, '153s6p93a5i': 19, '1ox1ma0twwh': 20, '13onx0tr34g': 20, '11ka31v4xs5': 21, '1d3eek74rjk': 21, xeof2ortj5: 22, jd9h9jd885: 22, '1chjhpzmpvw': 23, egsz7agds6: 23, '1tyjz8jydna': 24, '284u135u8x4': 24, '1omvfj80yf1': 25, '1236p3ua28p': 25, '1gbp5ufqbfe': 26, '1aytif31qv9': 26, '1l8feau4xth': 27, '27x4dcuip6w': 27, '28a1az4eixd': 28, '38gw1f5piv': 28, '6tcr5tf9i7': 29, vdpgcf4cs8: 29, '1rcg004z04a': 30, ay5num8q1y: 30, '1uvfwbny0a3': 31, '1n6lf0ks5fz': 31, '281ll7itkf2': 32, '26pgrllif7o': 32, '36eysgvaej': 33, '1x5j9rql0nd': 33, '25mcpsrtr1y': 34, vrpbwwckoj: 34, '3s55cwwclz': 35, '1jy1up5e4ax': 35, '18wt6vryvjj': 36, '16mkgnovodn': 36, '1wj2wcjptyq': 37, r0cprqookz: 37, '1jqtqeeheth': 38, ox033k4hwh: 38, x76smz6ohm: 39, r1yjppl0hu: 39, '177y32f62l2': 40, '8qlbh7fl6g': 40, '1toas3eprhr': 41, '25d6n8nrsx1': 41, '1cmdi3r7vbs': 42, '1o2521dljal': 42, '21aadjbgmk4': 43, '1b9m6jpkh7z': 43, '9ei1kad9fd': 44, '1pssvwy01xz': 44, '20s2pvimopo': 45, '1nw6kpl5qcd': 45, vsowb35fla: 46, '1yvnx7rwm2p': 46, ueb7yqj3xh: 47, '1f0ajzotkt': 47, '1yrz1crpwi2': 48, '100jhbas4yx': 48, '2lv81zkrh2': 49, '1cun3uf15me': 49, '2ejs9y0owl6': 50, '1blz74bgzoy': 50, '26g72gv08oz': 51, '21isitqj2um': 51, f532wmj5vz: 52, orohwi2wc6: 52, wmd93fh0c: 53, z2y9wy564i: 53, jeguks6lkh: 54, p49hmt596v: 54, '1mvrj2hv7m8': 55, '130zfkfja7x': 55, '2ujpz41dg3': 56, '1os315v2ms5': 56, '76zuwrzihp': 57, '20tbyjb5gzb': 57, '14pir8d8f6n': 58, '1ru270q1g3t': 58 };
const OLD_NICK = new Set<string>(['2d8pe47e5ri','w76g85w5v1','1nwq9nuxtm2','1ld3g09opwk','7syyqhdjae','2co5ipilenz','1sf7thv3ykh','n1eidqohl1','2frqr493y33','sw533pmq1z']);
const OLD_BRAND: Record<string, string> = { ylpyzny1ll: 'KIT:0', '9g0w9bro26': 'KIT:0', '2gorck3va85': 'KIT:1', iv0q092dgx: 'KIT:1', '1v4y13xdphw': 'KIT:2', '1849o1umw48': 'KIT:2', '1idjweg4guq': 'KIT:3', ax0jxreojv: 'KIT:3', '1c0w3rghd3r': 'KIT:4', vgfc8a541w: 'KIT:4', zwbhhq5e7n: 'KIT:5', '1bocr3fcfdu': 'KIT:5', mwf2dtvqx3: 'KIT:6', qct4oq47vx: 'KIT:6', k85jdolm3c: 'KIT:7', '179a1f6b1cx': 'KIT:7', a1sz05sr6z: 'GLOBAL:0', '1yz2hgg2iv2': 'GLOBAL:0', dpxhe74dh3: 'GLOBAL:1', '3h1ir9sagm': 'GLOBAL:1', '1w5icaeiwi8': 'GLOBAL:2', '136nz472fya': 'GLOBAL:2', m654hnwbj5: 'GLOBAL:3', ffy7bdouh6: 'GLOBAL:3', '1sx4sa7pq7h': 'GLOBAL:4', '10zpgfnrvl7': 'GLOBAL:4', '287ao7zi9au': 'GLOBAL:5', '1ov515f1u2k': 'GLOBAL:5', '22rljekiffc': 'GLOBAL:6', '1ot6yddph2q': 'GLOBAL:6', a40sx0vhpw: 'GLOBAL:7', '1gw80w0awcm': 'GLOBAL:7', '1a19d126f1s': 'LOCAL_EGY:0', '1lflja8i5hp': 'LOCAL_EGY:0', '28e9yvqnk62': 'LOCAL_EGY:1', '1apcia7s3im': 'LOCAL_EGY:1', '1eihhbmmxwe': 'LOCAL_EGY:2', oiauyx2v8m: 'LOCAL_EGY:2', '1viousdsxhr': 'LOCAL_EGY:3', tukp26vawe: 'LOCAL_EGY:3', '1gtlczmcdo7': 'LOCAL_EGY:4', '5hf8iqfp2i': 'LOCAL_EGY:4', '1e1bhsuj9xm': 'LOCAL_EGY:5', n7p0miobr1: 'LOCAL_EGY:5', vljirmtpie: 'LOCAL_EGY:7', '2vnu8dre7l': 'LOCAL_EGY:7', '2fbahfeto4t': 'LOCAL_KSA:0', nb1eu7azhx: 'LOCAL_KSA:0', '29bkxqwshf4': 'LOCAL_KSA:1', '1r4ytdty0a5': 'LOCAL_KSA:1', '103ug1w4zad': 'LOCAL_KSA:2', z7qb82scq3: 'LOCAL_KSA:2', '29rrew8dajq': 'LOCAL_KSA:3', '2evuw4i9h2u': 'LOCAL_KSA:3', '46wf9or0lj': 'LOCAL_QAT:1', '1k9ashpkzxs': 'LOCAL_QAT:1', hk8w4tf165: 'LOCAL_QAT:2', '1vmw60v17sk': 'LOCAL_QAT:2', o21j6k4rds: 'LOCAL_UAE:2', iodpspnfn: 'LOCAL_UAE:2', '1vozemtka23': 'LOCAL_MAR:0', '1v03q2ficxk': 'LOCAL_MAR:0', '5yqck7te35': 'LOCAL_MAR:1', uuc8b4eup2: 'LOCAL_MAR:1', '1q8vf22fk4c': 'LOCAL_MAR:2', '1d9oodaab0s': 'LOCAL_MAR:2', '2bpc4cbw2gr': 'LOCAL_TUN:0', x9zl772879: 'LOCAL_TUN:0', pw63any15v: 'LOCAL_TUN:2', '4avv9jot8l': 'LOCAL_TUN:2', '1e3ss43rpwv': 'LOCAL_ALG:0', '19zo10gxi5c': 'LOCAL_ALG:0', pcof3kvi2k: 'LOCAL_ALG:2', saak1ffzxa: 'LOCAL_ALG:2', '26g9wvyp18a': 'SLOT_stadium:0', '1f6ij7g2c5c': 'SLOT_stadium:0', xhgs6h68pf: 'SLOT_stadium:1', '18cccrqpg5b': 'SLOT_stadium:1', '1fpuutkjyj1': 'SLOT_stadium:2', '26o893looja': 'SLOT_stadium:2', '1uoxs384072': 'SLOT_stadium:3', '1voc1jmolxy': 'SLOT_stadium:3' };
const OLD_SURNAME: Record<string, string> = { '15mh2m2cgii': 'ENG:0', fskedj9klk: 'ENG:1', '2asc34cqs4k': 'ENG:2', '2ef7dg0waef': 'ENG:3', '2egzru8tdan': 'ENG:4', '10tu925rv9g': 'ENG:5', '1eexgdpayt5': 'ENG:6', '1ux3x69gpn1': 'ENG:7', n78a3bv8ox: 'ENG:8', lgrcjupy12: 'ENG:9', ul4z85b4on: 'ENG:10', '1fz8ufwggij': 'ENG:11', '2fr61x11hjg': 'ENG:12', '2bpxtrhanc1': 'ENG:13', '5rwdn3ozx4': 'ENG:14', xvdns17szp: 'ENG:15', '1wbw812kjre': 'ENG:16', pgs8qxc3ei: 'ENG:17', '1xxmcbfwdii': 'ENG:18', blenf1e1hf: 'ENG:19', al975wrfx9: 'ENG:20', '1y0r2vwjdv8': 'ENG:21', '224z1qah6jt': 'ENG:22', '1dnzdwvky32': 'ENG:23', '95rsy8y7gm': 'ENG:24', '1mrc822s24h': 'ESP:0', '7wop969mhc': 'ESP:1', '21ar42zotdm': 'ESP:2', h3p7g4e69a: 'ESP:3', nhyth5qigu: 'ESP:4', '2g66d4n253o': 'ESP:5', '13zyod62bia': 'ESP:6', vxyjojt7x6: 'ESP:7', '2520hav0ymo': 'ESP:8', '8irydhoyh3': 'ESP:9', '1bu0vl15yrb': 'ESP:10', '29swxylmmbx': 'ESP:11', qu74m0g1t2: 'ESP:12', c92rtag1w4: 'ESP:13', zxnv9wfqk7: 'ESP:14', gu7mzkbulw: 'ESP:15', n034ja0phb: 'ESP:16', '26xfd6jogfg': 'ESP:17', '2e7wsnpqdb1': 'ESP:18', zw6lg633cz: 'ESP:19', scn4716l7z: 'ESP:20', '1be5rwyxt80': 'ESP:21', '1lmdqkp0xs8': 'ESP:22', '1etlwcis5qf': 'ESP:23', '1skojyheegm': 'ESP:24', uikmy2yyhr: 'ITA:0', '1mvpiclvpj3': 'ITA:1', '1wxzxhjuzvc': 'ITA:2', '190juw6qhio': 'ITA:3', '16by5y6z4x3': 'ITA:4', '8ho7oi6kvg': 'ITA:5', '1mnrdsrpvnq': 'ITA:6', idgp87g6t4: 'ITA:7', '13wfuynl9bk': 'ITA:8', '29k8zzxqbnr': 'ITA:9', x4krvnpozt: 'ITA:10', '1lyfar4wh2k': 'ITA:11', '13xtnnsjpec': 'ITA:12', '1tqwd4c2qhv': 'ITA:13', '8t3zm3wt9u': 'ITA:14', '1ofu8k4l9vf': 'ITA:15', '2431roguq0f': 'ITA:16', fdb98iw9ks: 'ITA:17', '12yxfl1ari6': 'ITA:18', '1p3chfzc4e1': 'ITA:19', n5vbhp6v1s: 'ITA:20', '1utorcm9nm2': 'ITA:21', c02cdholtq: 'ITA:22', '1e5a23wq5ri': 'ITA:23', '1549dqzbzrw': 'ITA:24', '21yfb2pppeu': 'GER:0', kghmjtf5cf: 'GER:1', '1f9206n70um': 'GER:2', oylzqhuixc: 'GER:3', '1l03w910661': 'GER:4', o68pmo2ewx: 'GER:5', '2118d7r1z2b': 'GER:6', q4mxttunae: 'GER:7', s8an08ci3x: 'GER:8', '282d5lz3321': 'GER:9', '15ddizwdtkf': 'GER:10', meqlmuiudo: 'GER:11', wv6cgd0b95: 'GER:12', '45x26pa7xk': 'GER:13', '1jhccyb2lte': 'GER:14', qi8mndpxh3: 'GER:15', '1wbni51o7de': 'GER:16', '13aaex4nz16': 'GER:17', p7uxcwv9gj: 'GER:18', '26gkisacabn': 'GER:19', u570ok4l9e: 'GER:20', '1wz2n1yf36b': 'GER:21', '7day1q7s0k': 'GER:22', '3aeh45iey': 'GER:23', '21jmk456wdy': 'GER:24', '1xt3zmvluzd': 'FRA:0', '2c2pe1b1eu3': 'FRA:1', '19sckvwuiz2': 'FRA:2', '1tjpd5zc8i4': 'FRA:3', qwv0c5lcgm: 'FRA:4', '1g7xpp6t13d': 'FRA:5', j7tbykcql0: 'FRA:6', '23ss5s6mpt3': 'FRA:7', '12tiqw8bo7': 'FRA:8', wtim1jq8h4: 'FRA:9', i60la2dno2: 'FRA:10', '1bsz3st3z2t': 'FRA:11', '19xb76xyklu': 'FRA:12', edf01o37b8: 'FRA:13', '1ves40sylbe': 'FRA:14', f8zqaqm7fm: 'FRA:15', '31tod3uzxw': 'FRA:16', zkbw2hoiig: 'FRA:17', '1xrzln9xrpb': 'FRA:18', vs9e3lz0pr: 'FRA:19', vinaznwf6g: 'FRA:20', e1x1nh4947: 'FRA:21', '1uhv6p2erg2': 'FRA:22', '28lv95jnqmk': 'FRA:23', '1n0hsj3nrul': 'FRA:24', c8qsimn6v4: 'POR:0', '1ez0drqd2eo': 'POR:1', '13r5ilps2bp': 'POR:2', '1816xduggxh': 'POR:3', '19wwrwma7qj': 'POR:4', '1ye59k08qou': 'POR:5', akebihns2e: 'POR:6', '14xqbvfjtnh': 'POR:7', ln91m7r6mu: 'POR:8', ug4d5g5odm: 'POR:9', '8otuaiayfc': 'POR:10', '2anpluw87ra': 'POR:11', osjxm5qkcg: 'POR:12', '16xknn1uy72': 'POR:14', owcqmxd0ko: 'POR:15', qchdsfwwxf: 'POR:16', '83tjpr25bu': 'POR:17', '1ix0mixb04c': 'POR:18', '20e88qtddue': 'POR:19', lw17ep0v6n: 'POR:20', z5f7k0rbbt: 'POR:21', es1kimv0za: 'POR:22', '1wgew5l85g1': 'POR:23', '2eke6kd8hsy': 'POR:24', '49efvqzlye': 'AFR:0', n0mu7b4eld: 'AFR:1', '28iwbjv3le4': 'AFR:2', h0udx4948f: 'AFR:3', '14y83anrbw1': 'AFR:4', l9s3jyi9cu: 'AFR:5', '2b8v6uwv4lp': 'AFR:6', kl3zz93o8h: 'AFR:7', '11ovqvsesly': 'AFR:8', '6e74e83mne': 'AFR:9', '1sixp2otprf': 'AFR:10', '14rh0irmgko': 'AFR:11', '1hw9plt2l9q': 'AFR:12', brk26ipfyx: 'AFR:13', '1j7ji98dr0': 'AFR:14', '9h6wrsoaox': 'AFR:15', '123sdjq01uv': 'AFR:16', '1xmhyhoamx3': 'AFR:17', '1l14a9h4twv': 'AFR:18', '1hwvkg2y2gt': 'AFR:19', '1ziaxqukk0c': 'AFR:20', g1wqbxdsma: 'AFR:21', rurxhxnhgc: 'AFR:22', lcq5w9v954: 'AFR:23', '24hej4zsmaj': 'AFR:24', '11cxmowefwl': 'ARAB:0', '178kaxpdkx7': 'ARAB:1', '1wgg2h1asc0': 'ARAB:2', '1cm2udw0pb5': 'ARAB:3', '2mdm3sexam': 'ARAB:4', j0rrn17ffe: 'ARAB:5', '1x9dog6yu1f': 'ARAB:6', '1wkvx1ln5cc': 'ARAB:7', '2a5xxcosq6s': 'ARAB:8', '1cfozk20kak': 'ARAB:9', '3nfarw1fnl': 'ARAB:10', '2ecb7lse47r': 'ARAB:11', '1pz5fjaq8pc': 'ARAB:12', '2bidoeu3kvo': 'ARAB:13', '6seyjamde5': 'ARAB:14', ebd9bhvupw: 'ARAB:15', '1mue7df6t4z': 'ARAB:16', '2gc032k3pe5': 'ARAB:17', '25b5x8ldx66': 'ARAB:18', '1phcnk41o7r': 'ARAB:19', '14i5qolvsgg': 'ARAB:20', '1dw51jk1fg2': 'ARAB:21', '7rhuds9ssz': 'ARAB:22', '8c4zhb9zod': 'ARAB:23', '1misq24rtro': 'ARAB:24', '1fuvam4c1uk': 'ARAB:25', e6fnweetz9: 'ARAB:26', '4mezs0y374': 'ARAB:27', vfgblclv12: 'ARAB:28', '1vu5icuvapn': 'ARAB:29', '7mp02nbn90': 'ARAB:30', '1o54wxdfux6': 'ARAB:31', '1889m3zaspv': 'ARAB:32', rbon3uczzq: 'ARAB:33', '44lup6h166': 'ARAB:34', '7l3uce7w53': 'ARAB:35', '128nazfnpf6': 'ARAB:36', '1lv1gvneunu': 'ARAB:37', '29kjpifk4ew': 'ARAB:38', '2a4bnqs1lgj': 'ARAB:39', n60j4h9w16: 'MAGHREB:0', '2tg4bjjatz': 'MAGHREB:1', '21tvy188bq7': 'MAGHREB:2', '1z5cd6ivhct': 'MAGHREB:3', pcdzemay30: 'MAGHREB:4', ddyeyfayd6: 'MAGHREB:5', '2cweqb3ij0u': 'MAGHREB:6', '28j324llzez': 'MAGHREB:7', '1zu2gsoww8x': 'MAGHREB:8', ozkxmmwu1i: 'MAGHREB:10', '184jq3gve89': 'MAGHREB:11', '4vjp9v4fqb': 'MAGHREB:12', '25e6hulz1st': 'MAGHREB:13', '1aaeo59qnxl': 'MAGHREB:14', '60cxsbf26h': 'MAGHREB:15', '2557a2mjgk1': 'MAGHREB:16', '97x8g7cndq': 'MAGHREB:17', '12fl4eg7ayq': 'MAGHREB:18', i7mbxingkf: 'MAGHREB:19', '1st4jztlfyj': 'MAGHREB:20', '1hi5eviac5a': 'MAGHREB:21', '1opbn5c0se0': 'MAGHREB:22', joe8r2lx7l: 'MAGHREB:23', aar4ila41j: 'MAGHREB:24' };
// @@TABLES end

const isLoc = (x: unknown): x is LocalizedName => {
  if (!x || typeof x !== 'object' || Array.isArray(x)) return false;
  const k = Object.keys(x);
  return k.length === 2 && typeof (x as LocalizedName).en === 'string' && typeof (x as LocalizedName).ar === 'string';
};
const hasOwn = (o: object, k: string) => Object.prototype.hasOwnProperty.call(o, k);
const brandAt = (ref: string): [string, string] | undefined => {
  const [list, i] = ref.split(':');
  return _BRAND_LISTS[list]?.[+i];
};
const surnameAt = (ref: string): [string, string] | undefined => {
  const [pool, i] = ref.split(':');
  return _POOLS[pool]?.last[+i];
};
const SHORT = /^(\S+)\. (.+)$/;

interface Ctx { generated: Set<string> } // ids of generated (non-star) players: a homonym of a star is not the star

function renameLoc(n: LocalizedName, id: string | undefined, ctx: Ctx): LocalizedName {
  // 1. A star (unless this is a generated player who happened to share the star's short name).
  const si = hasOwn(OLD_STAR, h(n.en)) ? OLD_STAR[h(n.en)] : hasOwn(OLD_STAR, h(n.ar)) ? OLD_STAR[h(n.ar)] : undefined;
  if (si !== undefined && !(id && ctx.generated.has(id))) {
    const row = STARS[si];
    return {
      en: hasOwn(OLD_STAR, h(n.en)) ? row[1] : n.en,
      ar: hasOwn(OLD_STAR, h(n.ar)) ? row[2] : n.ar,
    };
  }
  // 2. A sponsor brand.
  const bref = hasOwn(OLD_BRAND, h(n.en)) ? OLD_BRAND[h(n.en)] : hasOwn(OLD_BRAND, h(n.ar)) ? OLD_BRAND[h(n.ar)] : undefined;
  const brand = bref ? brandAt(bref) : undefined;
  if (brand) return { en: brand[0], ar: brand[1] };
  // 3. A generated name ("B. Surname") whose surname came from the old pools.
  const m = SHORT.exec(n.en);
  const sref = m && hasOwn(OLD_SURNAME, h(m[2])) ? OLD_SURNAME[h(m[2])] : undefined;
  const sur = sref ? surnameAt(sref) : undefined;
  if (m && sur) {
    const ma = SHORT.exec(n.ar);
    return { en: `${m[1]}. ${sur[0]}`, ar: ma ? `${ma[1]}. ${sur[1]}` : n.ar };
  }
  return n;
}

function renameString(s: string): string {
  const k = h(s);
  if (hasOwn(OLD_STAR, k)) { const row = STARS[OLD_STAR[k]]; return row[1]; }
  if (hasOwn(OLD_BRAND, k)) { const b = brandAt(OLD_BRAND[k]); if (b) return b[0]; }
  return s;
}

// Rebuilds only what changed; unchanged branches keep their identity.
function walk(node: unknown, id: string | undefined, ctx: Ctx): unknown {
  if (typeof node === 'string') return renameString(node);
  if (!node || typeof node !== 'object') return node;
  if (Array.isArray(node)) {
    let out: unknown[] | null = null;
    node.forEach((x, i) => {
      const y = walk(x, id, ctx);
      if (y !== x) { out ??= node.slice(); out[i] = y; }
    });
    return out ?? node;
  }
  if (isLoc(node)) return renameLoc(node, id, ctx);
  const o = node as Record<string, unknown>;
  // The object's own player (transfers, loans, rumours, news, inbox) or its own id (players, staff).
  const own = typeof o.playerId === 'string' ? o.playerId : typeof o.player === 'string' ? o.player : typeof o.id === 'string' ? o.id : id;
  let out: Record<string, unknown> | null = null;
  for (const [k, v] of Object.entries(o)) {
    let y: unknown;
    if (k === 'nick' && isLoc(v)) {
      // Old nicknames pointed at real players: the star gets his new generic one, anyone else loses it.
      if (!OLD_NICK.has(h(v.en)) && !OLD_NICK.has(h(v.ar))) continue;
      const star = typeof o.id === 'string' && o.id.startsWith('star_') ? STARS[+o.id.slice(5)] : undefined;
      const nn = star ? NICKS[star[1]] : undefined;
      y = nn ? { en: nn[0], ar: nn[1] } : undefined;
    } else y = walk(v, own, ctx);
    if (y !== v) { out ??= { ...o }; if (y === undefined) delete out[k]; else out[k] = y; }
  }
  return out ?? node;
}

export function renameSave<W extends World, C extends Career | null>(world: W, career: C): { world: W; career: C } {
  const ctx: Ctx = { generated: new Set() };
  for (const p of world.players) if (!p.id.startsWith('star_')) ctx.generated.add(p.id);
  for (const p of career?.ops?.academy ?? []) ctx.generated.add(p.id);
  return { world: walk(world, undefined, ctx) as W, career: walk(career, undefined, ctx) as C };
}
