// v2 copy in Spanish (Spain): the banquillo talking. Type-checked against English (lang-v2.ts).
import type { XStrings } from './lang-v2';

const P = (n: number, one: string, many: string) => (n === 1 ? one : many);
const WORDS = ['Nada', 'Una cosa', 'Dos cosas', 'Tres cosas', 'Cuatro cosas', 'Cinco cosas'];

export const X_ES: XStrings = {
  nav: { today: 'Hoy', squad: 'Plantilla', match: 'Partido', transfers: 'Fichajes', club: 'Club', career: 'Carrera', pass: 'Club Pass' },
  back: 'Atrás',
  close: 'Cerrar',
  cont: 'Continuar',
  open: (n: number) => (n ? `· ${n} pendientes` : '· todo listo'),
  wk: (season: string, n: number) => `${season} · Sem. ${n}`,
  seasonLabel: (y: number) => `${y}/${String((y + 1) % 100).padStart(2, '0')}`,
  place: (n: number) => `${n}.º`,
  wdl: ['V', 'E', 'D'],
  saved: 'Guardado',
  notNowShort: 'Ahora no',

  title: {
    tag: 'Dirige el club. Manda en el banquillo.',
    season: 'La temporada 2026/27',
    lead: 'Todas las plantillas de la Premier League, LaLiga, la Serie A, la Bundesliga y la Ligue 1 tal y como quedan tras el mercado de verano, más los seis grandes de Egipto y Arabia Saudí. Nombres reales. Valoraciones nuestras.',
    newCareer: 'Empieza una carrera 2026/27',
    newSub: 'Elige club. La directiva te dirá qué espera.',
    slots: 'Tus carreras',
    slot: (n: number) => `Hueco ${n}`,
    empty: 'Hueco libre',
    cont: 'Continuar',
    oldWorld: 'Mundo antiguo · nombres ficticios',
    oldTitle: 'Tu carrera de antes de la reforma',
    oldBody: 'Se jugó en el mundo generado antiguo, así que conserva sus nombres y clubes ficticios. No se pierde nada: sigue con ella o empieza una carrera 2026/27 en el otro hueco.',
    contOld: 'Seguir la carrera antigua',
    startNew: 'Empezar una carrera 2026/27 nueva',
    full: 'Los dos huecos están ocupados. Elige uno para sustituir.',
    replace: 'Sustituir esta carrera',
    replaceAsk: (club: string) => `¿Sustituir tu carrera con el ${club}?`,
    replaceBody: 'Esa carrera se borra de este dispositivo. Expórtala antes desde Ajustes si puede que la quieras.',
    cancel: 'Mantenerla',
    quick: 'Partido rápido',
    quickSub: 'Dos clubes cualesquiera, un partido, no cuenta.',
    foot: 'Juego no oficial. Los nombres reales de clubes y jugadores se usan solo como hechos; escudos y equipaciones son dibujos nuestros; las valoraciones son criterio de The Gaffer, no de nadie más. Sin relación con ningún club, liga ni jugador.',
    badSave: 'Una partida de este dispositivo no pasó la comprobación y se ha dejado tal cual. Tu otro hueco está bien.',
    loading: 'Abriendo el despacho…',
    matchday: (n: number) => `Jornada ${n}`,
  },
  pick: {
    league: '¿Dónde quieres trabajar?',
    leagueSub: 'Siete ligas con las plantillas reales de 2026/27. El resto de la pirámide está para jugar contra ella.',
    covered: 'Plantillas reales',
    generated: 'Plantillas generadas',
    club: 'Elige tu club',
    clubSub: 'Los grandes exigen títulos. Los pequeños te dan tiempo.',
    search: 'Busca un club',
    strength: 'Nivel',
    budget: 'Presupuesto',
    expects: 'La directiva espera',
    job: 'El puesto',
    you: 'Tú',
    name: 'Tu nombre',
    nameDefault: 'El Míster',
    age: 'Edad',
    ageRule: 'Entre 20 y 80.',
    nation: 'Nacionalidad',
    sign: 'Firma el contrato',
    signSub: (club: string) => `El ${club} te espera.`,
    slotNote: (n: number) => `Se guarda en el hueco ${n}.`,
    tiers: ['Primera', 'Segunda'],
    stars: 'Los mejores',
    clubs: (n: number) => `${n} clubes`,
  },

  today: {
    eyebrow: (md: string, opp: string, days: string) => `${md} · ${opp} ${days}`,
    inDays: (n: number) => (n <= 0 ? 'hoy' : n === 1 ? 'mañana' : `en ${n} días`),
    head: (n: number, day0: string) => { const day = day0.replace(/\.$/, ''); return (n === 0 ? ['Nada en tu mesa.', ` Solo importa el ${day}.`, ''] : [`${WORDS[Math.min(5, n)]} `, P(n, 'te necesita', 'te necesitan'), ` antes del ${day}.`]) as [string, string, string]; },
    headCup: (n: number) => (n === 0 ? ['Noche de copa.', ' Nada más te necesita.', ''] : [`${WORDS[Math.min(5, n)]} `, P(n, 'te necesita', 'te necesitan'), ' antes de la eliminatoria.']) as [string, string, string],
    seasonDone: ['Temporada terminada.', ' A ver cómo acaba.', ''],
    sacked: ['La directiva te ha despedido.', ' El teléfono sigue sonando.', ''],
    week: 'Las próximas semanas',
    more: (n: number) => `+${n} más en la mesa`,
    fewer: 'Ver menos',
    nothing: 'Nada más te necesita. El cuerpo técnico lleva el resto.',
    nothingSub: (list: string) => (list ? `${list} van solos` : 'Todos los departamentos te esperan'),
    review: 'Revisar',
    staffDid: (n: number) => (n ? `El cuerpo técnico tomó ${n} ${P(n, 'decisión', 'decisiones')} desde el último partido` : 'El cuerpo técnico no ha decidido nada desde el último partido'),
    fit: (day: string) => `Disponibles para el ${day}`,
    tiredN: (n: number) => `${n} sin estar al cien`,
    restedTag: 'Descansa',
    fitOf: (a: number, b: number) => `${a} de ${b}`,
    allFit: 'Están todos. Elige de toda la plantilla.',
    doubt: 'Duda', banned: 'Sancionado', injured: (n: number) => `Baja ${n} ${P(n, 'sem.', 'sem.')}`, tired: (n: number) => `${n}% físico`,
    pulse: 'El pulso del club', office: 'Despacho',
    board: 'Directiva', fans: 'Afición', room: 'Vestuario',
    mood: (v: number) => (v >= 75 ? 'Encantada' : v >= 60 ? 'Confiada' : v >= 45 ? 'Vigilante' : v >= 30 ? 'Inquieta' : 'Sin paciencia'),
    fansMood: (v: number) => (v >= 80 ? 'Entregada' : v >= 60 ? 'Contigo' : v >= 40 ? 'Murmurando' : 'En contra'),
    roomMood: (v: number) => (v >= 75 ? 'Volando' : v >= 62 ? 'Tranquilo' : v >= 50 ? 'Inquieto' : 'Apagado'),
    boardWhy: (obj: string, pos: string) => `${pos} ahora. Quieren: ${obj.toLowerCase()}.`,
    fansWhy: (res: string) => res,
    roomWhy: (low: string | null) => (low ? `Ojo con ${low}` : 'Nadie de morros esta semana'),
    table: 'La clasificación', after: (n: number) => `Tras ${n}`, next: 'Próximo',
    headlines: 'Titulares', allNews: 'Todas las noticias',
    lastResult: 'Último partido',
    home: 'En casa', away: 'Fuera', at: (v: string) => v,
    ourGround: 'En casa', theirGround: 'A domicilio',
  },
  fixture: {
    comp: (c: string, md: string) => `${c} · ${md}`,
    win: 'Victoria', draw: 'Empate', loss: 'Derrota',
    pick: 'Elige el once', report: 'Informe', getReport: 'Pedir el informe',
    assistant: 'Segundo', analyst: 'Analista',
    advice: {
      scoutFirst: 'Todavía no los hemos visto. Dame la semana con el vídeo y te digo dónde hacerles daño.',
      mismatch: (ph: string) => `Están montados para ganar a nuestro juego. Cambia a ${ph} y seremos nosotros los que pregunten.`,
      edge: 'Tenemos el plan adecuado para ellos. Mantenlo y cuida las piernas.',
      lowMastery: (n: number) => `Los chicos solo dominan este plan al ${n}%. Otra semana de entreno o algo que conozcan.`,
      tired: (n: number) => `${n} titulares van con la reserva. Rota o a la hora estaremos persiguiendo sombras.`,
      outOfPos: (n: number) => `${n} ${P(n, 'jugador está', 'jugadores están')} fuera de posición en el once. Lo pagaremos.`,
      underdog: 'Sobre el papel son mejores. Recula un poco y que vengan ellos.',
      trap: 'Pon la presión para cazarlos donde les gusta jugar. El informe dice que les duele.',
      fine: 'Nada llama la atención. Lo mismo, y a salir fuertes.',
    },
  },
  dec: {
    due: { kickoff: 'Antes del partido', days: (n: number) => (n <= 1 ? 'Antes de la próxima jornada' : `Quedan ${n} jornadas`), week: 'Esta semana', season: 'Antes del verano', window: 'El mercado cierra esta noche', windowIn: (n: number) => `El mercado cierra en ${n} jornadas` },
    tag: { welcome: 'Primer día', offer: 'Oferta', condition: 'Físico', contract: 'Contrato', staff: 'Propuesta', job: 'Oferta de trabajo', tape: 'Análisis', focus: 'Semana de entreno', deadline: 'Último día de mercado' },
    staffPick: 'Elección del cuerpo técnico',
    yourCall: 'Decides tú. Nadie más.',
    done: (label: string) => `Hecho: ${label}`,
    undo: 'Deshacer',
    swipe: 'Desliza a la derecha para aceptar la propuesta',
    open: 'Abrir',
    titles: {
      offer: (club: string, fee: string, pn: string) => `El ${club} ofrece ${fee} por ${pn}`,
      tired: (pn: string, n: number) => `${pn} va al ${n}%`,
      expiring: (pn: string, y: number) => `El contrato de ${pn} acaba en ${y}`,
      job: (club: string) => `El ${club} quiere hablar contigo`,
      tape: (club: string) => `El vídeo del ${club} está listo`,
      focus: () => '¿Cambiar el enfoque del entreno esta semana?',
      deadline: (g: string) => `Último día de mercado y vamos cortos en ${g}`,
      ask_signed: (pn: string, fee: string) => `¿Fichar a ${pn} por ${fee}?`,
      ask_renewed: (pn: string, years: number) => `¿Renovar a ${pn} ${years} ${P(years, 'año', 'años')} más?`,
      ask_listed: (pn: string) => `¿Poner a ${pn} en venta?`,
      ask_capRaise: (pn: string, v: string, n: number) => `¿Subir el tope salarial ${v} al mes para retener a ${pn}${n > 1 ? ` y ${n - 1} más` : ''}?`,
      ask_out: (pn: string, club: string) => `¿Ceder a ${pn} al ${club}?`,
      ask_sold: (pn: string) => `¿Vender los derechos de ${pn}?`,
      ask_rejected: (pn: string) => `¿Rechazar la oferta por ${pn}?`,
      ask_load: (load: string) => `¿Entreno ${load} esta semana?`,
      ask_focus: (f: string) => `¿Semana de ${f.toLowerCase()}?`,
      ask_rehab: (pn: string) => `¿Pagar la rehabilitación de ${pn}?`,
      ask_talk: () => '¿Reunir a la plantilla para una charla?',
      ask_promote: (pn: string) => `¿Subir a ${pn} de la cantera?`,
      ask_scouted: () => '¿Hacer una jornada de pruebas en la cantera?',
      ask_plan: (ph: string) => `¿Jugar a ${ph} el próximo partido?`,
      ask_formation: (f: string) => `¿Cambiar el dibujo a ${f}?`,
      ask_mentality: () => '¿Cambiar la actitud para el próximo partido?',
      ask_price: (s: string) => `¿Poner la entrada a ${s}?`,
      ask_report: () => 'El analista tiene un informe listo',
      welcome: () => '¿Cómo quieres llevar esto?',
    },
    advice: {
      offer_accept: (pn: string, v: string) => `Es más de lo que vale para nosotros. ${pn} está valorado en ${v}. Acéptala.`,
      offer_counter: (_pn: string, v: string) => `Cerca, pero no. Vale ${v}. Apriétalos y a ver si parpadean.`,
      offer_reject: (pn: string, v: string) => `Ni de lejos para un jugador como ${pn}. Vale ${v}. Diles que no.`,
      offer_accept_money: (pn: string) => `Un dinero así no llega todos los días. Yo vendería a ${pn}.`,
      offer_counter_money: () => 'Yo vendería, pero apriétalos primero.',
      offer_reject_money: () => 'Ni yo vendería a ese precio.',
      offer_accept_loyal: (pn: string) => `Me duele perder a ${pn}, pero es una oferta seria.`,
      offer_counter_loyal: (pn: string) => `${pn} es parte de la casa. Si lo quieren, que paguen.`,
      offer_reject_loyal: (pn: string) => `${pn} no se vende. Diles que no.`,
      rest: (_pn: string, n: number, sub: string) => `Nos daría el ${n}% de sí mismo. ${sub} está fresco. Descánsalo y la semana que viene estará bien.`,
      rest_cautious: (pn: string, _n: number, sub: string) => `No arriesgo a ${pn} con las piernas cansadas. ${sub} cumple.`,
      rest_bold: (_pn: string, _n: number, sub: string) => `Hasta yo lo sentaría esta vez. ${sub} está listo.`,
      play: (_pn: string, n: number) => `Está al ${n}% y aun así es mejor que lo del banquillo. Que juegue y dosifica sus minutos.`,
      renew_yes: (_pn: string, age: number, years: string) => `Tiene ${age} años. ${years} años y firma esta semana. Si lo dejamos, su agente empieza a coger llamadas.`,
      renew_no: (_pn: string, age: number) => `Con ${age} años yo no me comprometería. Que acabe y traemos a alguien más joven.`,
      renew_cap: () => 'Su nuevo sueldo no cabe bajo el tope. Sube el tope o deja que acabe.',
      tape: (club: string) => `Dame la semana con el ${club} en el portátil y te enseño por dónde se abren.`,
      focus_recovery: () => 'Las piernas pesan. Una semana de recuperación devuelve cuatro puntos de físico a todos.',
      focus_tactical: () => 'A machacar el plan. Cuanto mejor lo conozcan, mejor lo jugamos.',
      focus_opposition: () => 'Tenemos su vídeo. Una semana con ellos vale medio punto de calidad el día del partido.',
      focus_development: () => 'Los chavales aprenden más rápido cuando la semana es para ellos. Nadie está cansado.',
      deadline: (g: string) => `Vamos cortos en ${g}. Uno más antes de medianoche o a rezar para que nadie se lesione.`,
      why_signed: (pn: string, fee: string) => `${pn} tapa nuestro punto más débil y vale ${fee}. Su agente firma hoy.`,
      why_renewed: (pn: string) => `${pn} merece la pena y el sueldo cuadra.`,
      why_listed: (pn: string) => `La plantilla es demasiado larga. ${pn} es al que menos echaríamos de menos.`,
      why_capRaise: (pn: string) => `${pn} merece la pena, pero estamos en el tope salarial. Subirlo cuesta un año del aumento por adelantado.`,
      why_out: (pn: string) => `${pn} necesita partidos, no un asiento en la grada.`,
      why_sold: (pn: string) => `${pn} no va a triunfar aquí. Sus derechos aún valen algo.`,
      why_rejected: (pn: string) => `La oferta por ${pn} se queda corta. Yo diría que no.`,
      why_load: () => 'Lo dice el estado de la plantilla.',
      why_focus: () => 'Es lo que pide la semana.',
      why_rehab: (pn: string) => `${pn} tiene para rato. La rehabilitación lo trae antes.`,
      why_talk: () => 'El vestuario está apagado. Una palabra tuya lo levanta.',
      why_promote: (pn: string) => `${pn} está listo. Entrenar con el primer equipo terminará el trabajo.`,
      why_scouted: () => 'La cantera está corta. Una jornada de pruebas saca dos o tres.',
      why_plan: (ph: string) => `El informe dice que ${ph} es la forma de hacerles daño.`,
      why_formation: (f: string) => `Nuestro mejor once encaja mejor en ${f}.`,
      why_mentality: () => 'Los números dicen que cambiemos la actitud.',
      why_price: () => 'Más dinero en taquilla sin vaciar la grada.',
      why_report: () => 'Está en tu mesa.',
      welcome: () => 'Dinos cuánto quieres estar encima. Lo que dejes lo llevamos nosotros, y puedes cambiarlo cuando quieras en la sala del cuerpo técnico.',
    },
    choices: {
      accept: (fee: string) => `Aceptar ${fee}`, counter: (fee: string) => `Pedir ${fee}`, reject: () => 'Rechazar',
      restHim: (pn: string) => `Descanso · juega ${pn}`, playHim: () => 'Que juegue',
      renewYears: (n: number) => `Negociar · ${n} ${P(n, 'año', 'años')}`, wait: () => 'Dejar que acabe',
      takeJob: () => 'Aceptar el puesto', stay: () => 'Me quedo',
      watchTape: () => 'Ver el vídeo', skipTape: () => 'Esta semana no',
      focus_recovery: () => 'Recuperación', focus_tactical: () => 'Táctica', focus_opposition: () => 'Rival', focus_development: () => 'Desarrollo',
      findCover: () => 'Buscar recambio', standPat: () => 'Seguir así',
      approve: () => 'Sí, hazlo', notNow: () => 'Ahora no',
      runUsual: () => 'El reparto de siempre', handsOn: () => 'Encima de todo: el once lo elijo yo', leaveIt: () => 'Que lo lleve el cuerpo técnico',
    },
    fx: {
      cash: (v: string) => `+${v}`, loseStarter: () => 'Perdemos un titular', loseSquad: () => 'Plantilla −1', mayWalk: () => 'Pueden irse', stays: () => 'Se queda',
      freshNext: (n: number) => `${n}% la semana que viene`, slotLevel: (n: number) => (n >= 0 ? `Nivel +${n}` : `Nivel ${n}`), playsAt: (n: number) => `Juega al ${n}%`, legs: () => 'Piernas al final',
      wagesYear: (v: string) => `Sueldos ${v}/año`, moraleUp: () => 'Moral ↑', rivalsCall: () => 'Pueden llamar rivales',
      newClub: () => 'Club nuevo, directiva nueva', loyalty: () => 'La directiva valora la lealtad',
      knowThem: () => 'Su plan, sus peligros y un antídoto', noPrep: () => 'Vamos a ciegas',
      signingsAsk: () => 'Los fichajes te esperan', moreCalls: () => 'Más decisiones en tu mesa', fewestCalls: () => 'Las mínimas decisiones', staffSign: () => 'El cuerpo técnico puede fichar',
      focusFx_recovery: () => 'Físico +4', focusFx_tactical: () => 'Dominio +2', focusFx_opposition: () => 'Ventaja ante ellos', focusFx_development: () => 'Progreso ×1,25',
      toMarket: () => 'Abre el mercado', thin: () => 'A una lesión del problema',
      fee: (v: string) => `Traspaso ${v}`, listed: () => 'En venta', minutes: () => 'Minutos de verdad', monthly: (v: string) => `+${v}/mes`, backSooner: () => 'Vuelve antes', plan: () => 'Plan nuevo',
      nothingChanges: () => 'No cambia nada',
    },
    groups: ['portería', 'defensa', 'el centro del campo', 'arriba'],
  },
  desk: {
    title: (n: number) => (n ? `${n} ${P(n, 'decisión sigue', 'decisiones siguen')} en tu mesa` : 'Mesa despejada'),
    body: 'Si continúas ahora, el cuerpo técnico sigue su propio consejo en lo que quede abierto. No se firma nada que no hayas visto.',
    take: 'Aceptar lo del cuerpo técnico y seguir',
    leave: 'Dejarlas como están',
    stay: 'Déjame mirar antes',
  },

  pre: {
    crowd: (n: string, club: string) => `${n} · el ${club} a pleno pulmón`,
    crowdAway: (n: string) => `${n} · la grada visitante, llena`,
    stakesUp: (club: string, pos: string) => `Si ganamos, subimos a ${pos}. El ${club} es quien se interpone.`,
    stakesCup: (round: string) => `${round}. El que pierde, a casa.`,
    stakesPlain: 'Tres puntos. Un sábado no importa nada más.',
    sheets: 'Alineaciones', confirmed: 'Confirmadas',
    talk: 'La última palabra en el vestuario',
    talks: [
      ['«Id y quitádselo.»', 'Los de partidos grandes se crecen. Los jóvenes pueden bloquearse.'],
      ['«Al plan.»', 'Serenos. Nadie se pasa de vueltas.'],
      ['«Sin presión. Disfrutad.»', 'Los jóvenes se sueltan. Los que quieren más se apagan.'],
    ],
    winChance: 'Opciones de ganar', ourXg: 'Nuestros xG previstos', theirXg: 'Los suyos',
    walk: 'Salir al campo', result: 'Dame el resultado', sim: 'Simular hasta la próxima decisión', simSub: 'Resultados rápidos hasta que algo te necesite',
    resume: (m: number) => `Volver al ${m}′`,
    report: 'Informe del analista',
    threats: 'Cuidado con estos', weak: 'Por dónde se abren', counter: 'El plan para ellos', apply: 'Usarlo', using: 'En ello',
    weakWhy: { slow: 'Lento al girar', tired: 'Sin gasolina', weak: 'El eslabón débil' },
    accuracy: (n: number) => `${n}% seguros`,
  },
  live: {
    ht: 'Descanso', ft: 'Final', min: (n: number) => `${n}′`,
    moments: 'Momentos clave', numbers: 'Los números', touchline: 'Desde la banda', takes: 'Surte efecto ya',
    where: 'Dónde ha estado el balón', whereSub: 'Últimos 10 min',
    views: ['Campo', 'Territorio', 'Nuestros tiros', 'Los suyos'],
    momentum: 'Dominio', momentumKey: (a: string, b: string) => `${a} arriba · ${b} abajo`,
    xg: 'Goles esperados', attack: (club: string) => `${club} ataca →`,
    stats: ['Posesión', 'Tiros', 'A puerta', 'Córners', 'Faltas', 'Amarillas'],
    changes: 'Cambios', pause: 'Pausa', play: 'Seguir', key: 'Claves', speed: 'Velocidad',
    shouts: [['Seguid así', 'mentality', 0], ['Abridla a banda', 'width', 2], ['Calma', 'tempo', 0], ['Apretad arriba', 'pressing', 2], ['Atrás', 'line', 0], ['A por ellos', 'mentality', 2]],
    assistant: 'Segundo',
    planB: 'Pasar al plan B', planBOn: 'Plan B activado',
    subsLeft: (n: number) => `${n} ${P(n, 'cambio', 'cambios')} restantes`,
    off: 'Sale', on: 'Entra', makeSub: 'Hacer el cambio', pickTwo: 'Elige quién sale y luego quién entra.',
    confirm: (a: string, b: string) => `Entra ${b} por ${a}`,
    skip: 'Ir al final',
    goal: 'GOL', sound: 'Sonido',
    ev: {
      goal: (p: string) => `GOL · ${p}`, pen: (p: string) => `Penalti · ${p}`, chance: (p: string) => `Ocasión clara · ${p}`, save: (p: string) => `Parada · ${p}`,
      red: (p: string) => `Expulsado · ${p}`, injury: (p: string) => `Lesión · ${p}`,
      goalSub: (xg: string) => `xG ${xg}`, chanceSub: (xg: string) => `xG ${xg}, y no entró`, redSub: 'Con diez', injurySub: 'No puede seguir',
    },
    noMoments: 'Nada digno de contar todavía.',
    resumed: (m: number) => `Retomado donde lo dejaste: ${m}′`,
  },
  ht: {
    eyebrow: 'Por qué ha pasado · los analistas',
    change: 'Lo que cambiaríamos', tapApply: 'Toca para aplicar',
    win: (a: number, b: number) => `${a}% → ${b}%`, winLine: (n: number) => `Opciones de ganar con ${n} ${P(n, 'cambio', 'cambios')}`,
    yourChange: 'Tu cambio', second: 'Segunda parte', teamTalk: 'Charla',
    noTips: 'El motor no ve nada mejor que lo que hacemos. Seguid así.',
    applied: 'Hecho. Lo sabrán al reanudar.',
    cause: {
      source: ['Aquí les hacemos daño', 'Aquí nos hacen daño'], setpiece: ['El balón parado es nuestra arma', 'El balón parado nos está matando'],
      midfield: ['El centro del campo es nuestro', 'El centro del campo es suyo'], pressed: ['Su presión no muerde', 'Su presión muerde'], pressing: ['Nuestra presión muerde', 'Nuestra presión no muerde'],
      duel: ['Ganamos el uno contra uno', 'Perdemos el uno contra uno'], finish: ['La definición está de nuestro lado', 'La definición nos cuesta caro'],
      keeper: ['Un portero nos sostiene', 'Su portero está en racha'], tired: ['Se han quedado sin piernas', 'Nos hemos quedado sin piernas'],
      red: ['Están con diez', 'Estamos con diez'], change: ['El cambio funciona', 'El cambio no ha funcionado'], theyChanged: ['Han cambiado y no les ha servido', 'Han cambiado algo'],
    },
    evid: { shots: (n: number) => `${n} ${P(n, 'tiro', 'tiros')}`, xg: 'xG', of: (a: number, b: number) => `${a} de ${b}`, pct: (n: number) => `${n}%`, won: 'recuperados arriba', saves: 'paradas', fit: 'físico al final', min: (n: number) => `${n}′`, through: 'de las jugadas pasan' },
    subIdea: (a: string, b: string) => `Entra ${b} por ${a}`, subWhy: (a: string, n: number) => `${a} está al ${n}%. El banquillo está fresco.`,
    heads: {
      deserved: 'Nos lo hemos ganado.', robbed: 'Hacemos lo suficiente. El marcador no opina igual.', smash: 'Vamos ganando, pero con suerte.',
      beaten: 'Han sido mejores. Sin más.', even: 'No hay nada.', clinical: 'Hemos aprovechado lo nuestro.', wasteful: 'Deberíamos ir más arriba.', level: 'Empate, y parece justo.',
    },
  },
  ft: {
    rematch: 'Revancha', changeTeams: 'Cambiar equipos', back: 'Volver', quickNote: 'Partido rápido: nada de esto cuenta para una carrera.',
    eyebrow: (ground: string) => `Final · ${ground}`,
    xg90: 'Goles esperados · 90 min',
    changed: 'Lo que ha cambiado',
    league: 'Liga', board: 'Directiva', fans: 'Afición', room: 'Vestuario',
    ratings: 'Notas', all: (n: number) => `Los ${n}`, motm: 'Mejor del partido',
    heads: {
      W: (club: string, opp: string) => [`El ${club} gana al ${opp}.`, 'Un resultado serio.', 'Tres puntos al bolsillo.'],
      D: (club: string, opp: string) => [`${club} y ${opp} se reparten los puntos.`, 'Un punto para cada uno.', 'Tablas.'],
      L: (club: string, opp: string) => [`El ${opp} gana al ${club}.`, 'Para olvidar.', 'El lunes, a trabajar.'],
    },
    tail: { up: (p: string) => ` Subimos a ${p}.`, down: (p: string) => ` Bajamos a ${p}.`, same: (p: string) => ` Seguimos ${p}.` },
    boardQuote: (d: number) => (d >= 2 ? '«Un golpe en la mesa.»' : d >= 0 ? '«Lo esperado.»' : d > -2 ? '«Esperábamos más.»' : '«Eso no puede repetirse.»'),
    fansQuote: (d: number) => (d >= 2 ? 'Coreaban tu nombre' : d >= 0 ? 'Se fueron contentos' : 'Algún pitido al final'),
    roomQuote: (d: number) => (d >= 2 ? 'Ahí dentro hay fiesta' : d >= 0 ? 'Tranquilo y sereno' : 'Cabezas gachas'),
    out: (n: number) => `Bajas: ${n}`,
    injuredFor: (pn: string, n: number) => `${pn}, baja ${n} ${P(n, 'semana', 'semanas')}`,
    bannedFor: (pn: string, n: number) => `${pn}, sancionado ${n}`,
    record: 'Nuevo récord del club',
    press: 'Compartir la crónica', done: 'Continuar',
    note: 'Segundo',
  },
  digest: {
    title: 'Mientras no estabas',
    sub: (a: string, b: string) => `${a} a ${b}`,
    results: 'Resultados', staff: (n: number) => `${n} ${P(n, 'decisión', 'decisiones')} del cuerpo técnico`,
    stopped: { decision: 'Parado: algo te necesita.', season: 'Parado: la temporada ha terminado.', max: 'Parado: ocho jornadas de golpe son suficientes.', big: 'Parado: viene un partido grande.', window: 'Parado: se ha abierto el mercado.' },
    back: 'Volver a Hoy',
  },

  squad: {
    title: 'La plantilla',
    sub: (n: number) => `Primer equipo · ${n} jugadores`,
    facts: { age: 'edad media', wages: 'sueldos al mes', unhappy: 'descontentos', holes: (n: number) => P(n, 'hueco por cubrir', 'huecos por cubrir') },
    lens: { all: 'Todos', starters: 'Titulares', ending: 'Contratos que acaban', unhappy: 'Descontentos', injured: 'Lesionados', loans: 'Cedidos', listed: 'En venta' },
    depth: 'Fondo de armario', depthSub: 'Titular · recambio',
    covered: 'Cubierto', thin: 'Justo', hole: 'A una lesión del problema',
    noCover: (pn: string) => `Nadie detrás de ${pn}`, noCoverSub: 'La secretaría técnica está lista cuando tú digas.', shortlist: 'Lista',
    thenNobody: 'y después nadie en forma',
    player: 'Jugador', fit: 'Físico', mood: 'Ánimo', yrs: 'Años',
    desk: 'En la mesa', deskSub: 'Contratos y movimientos',
    ending: (n: number) => `${n} ${P(n, 'contrato acaba', 'contratos acaban')} esta temporada`, endingNone: 'Ningún contrato acaba esta temporada.',
    loansOut: (n: number) => `${n} cedidos`, listedN: (n: number) => `${n} en venta`,
    training: 'Semana de entreno', medical: 'Servicio médico', academy: 'Cantera',
    find: 'Buscar',
    form: (v: string) => `forma ${v}`,
    sub2: { captain: 'capitán', inj: (n: number) => `baja ${n} sem.`, ban: 'sancionado', loan: 'cedido', listed: 'en venta', talks: 'quiere hablar', young: 'cantera' },
  },
  player: {
    back: 'Plantilla',
    ability: 'Nivel', ceiling: 'Techo', form: 'Forma', value: 'Valor', apps: (n: number) => `${n} partidos`,
    dev: 'Progresión', devHead: (age: number, peak: number, up: boolean) => (age >= 31 ? 'Sigue rindiendo. Los años le van alcanzando.' : !up ? 'Está en su nivel. Lo que ves es lo que hay.' : peak <= age + 1 ? 'Casi está. Un último empujón.' : `Todavía crece. Su mejor versión, hacia los ${peak}.`),
    known: 'Conocido', own: 'Jugador propio', scouted: (k: number) => `Ojeadores seguros al ${k}%`,
    good: 'En qué destaca', groups: ['Con balón', 'Sin balón', 'Cabeza y físico'],
    attrs: ['Velocidad', 'Disparo', 'Pase', 'Regate', 'Defensa', 'Físico', 'Portería'],
    fits: 'Dónde encaja',
    man: 'La persona', captain: 'Capitán', morale: (v: string) => `Moral: ${v}`, moods: ['baja', 'plana', 'bien', 'buena', 'por las nubes'],
    contract: 'Contrato', expires: 'Vence en junio', perMonth: 'Al mes', secure: 'Asegurado', ending: 'Acaba', release: 'Cláusula', none: 'Ninguna', rank: 'Puesto en sueldos',
    renew: 'Ofrecer renovación', list: 'Poner en venta', unlist: 'Quitar de la venta', talk: 'Hablar con él', rest: 'Descansa el próximo partido', unrest: 'Disponible otra vez',
    bid: 'Hacer una oferta', shortlist: 'A la lista', unshortlist: 'Quitar de la lista', loanIn: 'Pedirlo cedido', loanOut: 'Cederlo',
    rename: 'Renombrar',
    season: 'Esta temporada', seasonStats: (a: number, g: number, as: number) => `${a} partidos · ${g} goles · ${as} asistencias`,
    ageNat: (age: number) => `${age}`,
    free: 'Libre',
    onLoan: (club: string) => `Cedido en el ${club}`,
    ability2: 'Proyección', abilityLine: 'Nivel', projLine: 'Proyección del cuerpo técnico', avgLine: 'Media de la plantilla',
  },
  train: {
    title: 'Semana de entreno', sub: 'Intensidad y enfoque',
    load: 'Intensidad', loads: ['Suave', 'Normal', 'Fuerte'], loadFx: ['Las piernas se recuperan. Se aprende más lento.', 'La semana de siempre.', 'Se aprende más rápido, piernas más pesadas y algún golpe.'],
    focus: 'Enfoque de la semana', focusNames: { recovery: 'Recuperación', tactical: 'Táctica', opposition: 'Rival', development: 'Desarrollo' },
    focusFx: { recovery: 'Todos +4 de físico para el sábado.', tactical: 'El plan cala: +2 de dominio tras el partido.', opposition: 'Con el informe del analista: una pequeña ventaja el día del partido.', development: 'Los jugadores aprenden un 25% más rápido esta semana.' },
    report: 'La semana pasada', improved: (n: number) => `${n} ${P(n, 'mejoró', 'mejoraron')}`, hurt: (n: number) => `${n} con molestias`,
    individual: 'Trabajo individual', choose: 'Elige un jugador', attr: 'Trabajo extra en',
    none: 'Nada extra',
    medical: 'Servicio médico', injuredN: (n: number) => (n ? `${n} ${P(n, 'lesionado', 'lesionados')}` : 'Todos sanos'), rehab: 'Rehabilitación', specialist: 'Especialista', out: (n: number) => `Baja ${n} sem.`,
    academy: 'Cantera', prospects: (n: number) => `${n} ${P(n, 'promesa', 'promesas')}`, trial: (cost: string) => `Jornada de pruebas · ${cost}`, promote: 'Subir', release: 'Descartar', sellRights: (v: string) => `Vender derechos · ${v}`,
    trialsLeft: (n: number) => `${n} ${P(n, 'jornada de pruebas', 'jornadas de pruebas')} esta temporada`,
  },

  tac: {
    title: (opp: string) => `Táctica · contra el ${opp}`, titleFree: 'Táctica',
    styles: { balanced: 'Equilibrado', possession: 'Tener el balón', counter: 'Esperar y salir', gegenpress: 'Presionar y correr a la espalda', bus: 'Autobús', wings: 'Por las bandas', direct: 'Juego directo' },
    forecast: 'Previsión',
    how: 'Cómo jugamos', changes: (n: number) => `${n} ${P(n, 'cambio', 'cambios')}`, changed: 'Cambiado',
    style: 'Estilo', shape: 'Dibujo',
    ins: {
      press: ['Presión', ['Esperar', 'Bloque medio', 'Arriba']],
      line: ['Línea defensiva', ['Baja', 'Media', 'Alta']],
      width: ['Por dónde atacamos', ['Por dentro', 'Equilibrado', 'Por fuera']],
      tempo: ['Ritmo', ['Pausado', 'Normal', 'Rápido']],
      passing: ['Pase', ['Corto', 'Mixto', 'Directo']],
      mentality: ['Actitud', ['Autobús', 'Prudente', 'Equilibrada', 'Ofensiva', 'Todo al ataque']],
    },
    gain: 'Gana', risk: 'Riesgo',
    trade: {
      press: [['Juntos y atrás: piernas frescas en el 80′.', 'Tienen el balón y tiempo para pensar.'], ['Difíciles de superar, sin gastar piernas.', 'Ni fu ni fa.'], ['Recuperamos cerca de su área.', 'Las piernas se van hacia el 70′ y nos encaran.']],
      line: [['Nada a la espalda para sus delanteros.', 'Se instalan en nuestra área.'], ['Nuestros centrales están cómodos.', 'Un hueco entre líneas cuando presionamos.'], ['Se les encoge el campo.', 'Un balón a la espalda y es una carrera.']],
      width: [['Superioridad por dentro.', 'Fácil de cerrar.'], ['Nada evidente que frenar.', 'Nada evidente que temer.'], ['Los abre; nuestros extremos van al uno contra uno.', 'Débiles por dentro si la perdemos.']],
      tempo: [['Balón y orden.', 'Se colocan antes de que lleguemos.'], ['Equilibrado.', 'Equilibrado.'], ['Les pillamos descolocados.', 'La perdemos más.']],
      passing: [['Corto y seguro: es nuestra.', 'Lento para hacer daño.'], ['Un poco de todo.', 'Un poco de todo.'], ['Directos a su defensa.', 'Balones divididos en el centro.']],
    },
    mentality: ['Autobús', 'Prudente', 'Equilibrada', 'Ofensiva', 'Todo al ataque'],
    board: 'Pizarra táctica. Toca un jugador y luego un hueco u otro jugador para cambiarlos.',
    hint: 'Toca para elegir · otra vez para cambiar',
    theirPress: (club: string) => `El dibujo del ${club}`,
    bench: 'Banquillo', lock: 'Fijar el plan', locked: 'Plan fijado', undo: 'Deshacer', reset: 'Mi mejor once', outPos: (pn: string, pos: string, v: number, alt: string, av: number) => `${pn} de ${pos.toLowerCase()} (${v} ahí): ${alt}, el mejor ${pos.toLowerCase()} fuera del once, daría ${av}.`, outPosNone: (pn: string, pos: string, v: number) => `${pn} de ${pos.toLowerCase()} (${v} ahí): no hay otro ${pos.toLowerCase()} disponible.`, xiMine: 'Tu once: se queda hasta que lo cambies. Los lesionados o sancionados se sustituyen solo para el partido.', xiStaff: 'El segundo elige el once antes del partido.', xiAuto: 'El mejor once al empezar el partido.', xiHand: 'Que elija el segundo',
    role: (pos: string) => `Rol · ${pos}`, fitFor: 'Cómo encaja en cada puesto',
    opp: (f: string, st: string) => `Rival · ${f} · ${st}`, oppHow: (club: string) => `Cómo juega el ${club}`,
    ours: 'Nuestro', theirs: 'Suyo', even: 'Igualado',
    lanes: ['Nuestra izquierda', 'Centro', 'Nuestra derecha'],
    danger: 'el peligro', engine: 'el motor', oppManager: (n: string) => `${n} elige su once`,
    noReport: 'Aún no hay informe. El analista necesita la semana con ellos.',
    familiar: 'Dominio', familiarSub: (n: number) => (n >= 80 ? 'Se lo saben de memoria' : n >= 55 ? 'Van cogiéndolo' : 'Todavía aprendiéndolo'),
    planB: 'Plan B', planBSet: 'Guardar como plan B', planBNone: 'Aún no hay plan B. Prepara un segundo plan al que cambiar durante el partido.', planBClear: 'Borrar el plan B', useB: 'Usar el plan B ya',
    setPieces: 'Balón parado', captain: 'Capitán', penalties: 'Penaltis', freeKicks: 'Faltas', corners: 'Córners', auto: 'El mejor disponible',
    swapped: (a: string, b: string) => `${a} y ${b} intercambiados`,
    outOfPos: (n: number) => `Rinde a ${n}`,
    philosophy: 'Filosofía',
  },
  table: {
    tabs: ['Táctica', 'Calendario', 'Clasificación', 'Copas'],
    pos: '#', club: 'Club', p: 'PJ', gd: 'DG', pts: 'Pts', w: 'G', d: 'E', l: 'P',
    scorers: 'Goleadores', assists: 'Asistentes', zones: { up: 'Ascenso', down: 'Descenso', top: 'Plazas europeas' },
    round: (n: number) => `Jornada ${n}`, noCups: 'Sin eliminatorias esta temporada.', group: (g: string) => `Grupo ${g}`,
    bye: 'Exento', tbd: 'Por sortear', winnerGoes: 'El ganador pasa',
    finished: 'Jugado', upcoming: 'Próximo', you: 'Tú',
  },

  tr: {
    title: 'Fichajes', window: (open: boolean, left: number) => (open ? `Mercado abierto · quedan ${left} ${P(left, 'jornada', 'jornadas')}` : `Mercado cerrado · abre en ${left} ${P(left, 'jornada', 'jornadas')}`),
    deadline: 'Último día de mercado',
    hero: { need: (pos: string) => `Busca un ${pos.toLowerCase()}`, none: 'No hay nadie que buscar. De momento.' },
    budget: 'Presupuesto de fichajes', wageRoom: 'Margen salarial / mes', onList: 'En la lista',
    why: 'Por qué esta búsqueda', needHead: (pos: string) => `Vamos justos de ${pos.toLowerCase()}.`, noNeed: 'Todos los puestos tienen recambio. Busca calidad, no cantidad.',
    chief: 'Jefe de ojeadores',
    scoutLine: (pn: string, k: number) => `${pn} es el que queremos. Lo conocemos al ${k}%.`,
    scoutNone: 'Mete unos cuantos nombres en la lista y mando a alguien a verlos.',
    fog: 'Lo que sabemos · nivel', fogHead: 'Cuanto más ancha la barra, menos sabemos.', fogKey: 'Rango de los ojeadores', ref: (pn: string, n: number) => `${pn} hoy (${n})`,
    tabs: ['Lista', 'Buscar', 'Ofertas', 'Operaciones', 'Cesiones'],
    known: 'conocido', likely: 'Traspaso probable', wants: 'Pide / mes', interest: 'Interés',
    interestL: ['Con ganas', 'Abierto', 'Frío', 'Desconocido'],
    ability: 'Nivel', ceiling: 'Techo', fit: 'Encaje',
    bid: 'Hacer oferta', inTalks: 'Negociando', report: 'Informe', ask: 'Preguntar precio',
    empty: 'La lista está vacía. Busca en el mercado y marca a los que te gusten: los ojeadores empiezan a seguirlos al momento.',
    search: 'Buscar jugadores', filters: { pos: 'Posición', league: 'Liga', age: 'Edad', value: 'Precio máx.' }, any: 'Cualquiera', results: (n: number) => `${n} jugadores`,
    sort: ['Nota de ojeadores', 'Precio', 'Edad', 'Sueldo'],
    bids: 'Ofertas por tus jugadores', noBids: 'Nadie pregunta. Eso cambia rápido con el mercado abierto.',
    deals: 'Operaciones de la temporada', noDeals: 'Todavía ninguna.', inOut: { in: 'Alta', out: 'Baja', free: 'Libre', released: 'Rescindido' },
    loans: 'Cesiones', noLoans: 'Nadie cedido.', loanedIn: 'Cedidos a nosotros', loanedOut: 'Cedidos fuera',
    closed: 'El mercado está cerrado. Solo agentes libres hasta que abra.',
  },
  bid: {
    title: (pn: string) => `Oferta por ${pn}`, fee: 'Traspaso', wage: 'Sueldo al mes', years: 'Años', role: 'Rol',
    roles: { star: 'Estrella', regular: 'Titular', rotation: 'Rotación', prospect: 'Promesa' },
    ask: (v: string) => `Piden ${v}`, demand: (v: string) => `Él pide ${v}`, send: 'Enviar oferta',
    afford: 'Tras la operación', budgetLeft: 'Presupuesto restante', wageLeft: 'Margen salarial restante',
    no: {
      budget: 'No nos llega para ese traspaso.', wageCap: 'Ese sueldo rompe el tope.', squadFull: 'La plantilla está llena (32).', fee: 'Quieren más.', wage: 'Él quiere más.',
      ambition: 'No va a bajar a nuestro nivel.', role: 'Es demasiado mayor para ser promesa.', injured: 'Está lesionado.', sellerThin: 'No pueden prescindir de él: van justos.',
      gone: 'No está disponible.', window: 'El mercado está cerrado.', limit: 'Límite de cesiones alcanzado.', loaned: 'Ya está cedido.', squad: 'Nuestra plantilla va justa.', key: 'Es clave para ellos.',
      club: 'Elige un club.', free: 'No es nuestro para cederlo.', lenderThin: 'No pueden prescindir de él.', unhappy: 'No habla mientras esté tan descontento.', years: 'Demasiados años para su edad.',
      terms: 'Esas condiciones no valen.', counter: 'Quieren más.', wait: 'Demasiado pronto para otra charla.', fee2: 'Eso no es subir.',
    },
    counter: (v: string) => `Aceptarían ${v}`,
    renewTitle: (pn: string) => `Renovación de ${pn}`, renewSend: 'Ofrecerla',
    offersTitle: 'Ofertas por tus jugadores', accept: 'Aceptar', reject: 'Rechazar', counterBtn: (v: string) => `Pedir ${v}`,
  },
  note: {
    signed: (pn: string) => `${pn} firma.`, sold: (pn: string) => `${pn}, vendido.`, renewed: (pn: string) => `${pn} renueva.`,
    loanedIn: (pn: string) => `${pn} llega cedido.`, loanedOut: (pn: string) => `${pn} sale cedido.`, counterOk: 'Aceptan tu precio.', counterNo: 'Se han retirado.',
    haggleOk: 'Han subido un 10%.', haggleNo: 'Han retirado la oferta.', rightsSold: (v: string) => `Derechos vendidos por ${v}.`, scoutFound: (n: number) => `${n} ${P(n, 'promesa encontrada', 'promesas encontradas')}.`,
    tactics: 'Plan fijado.', done: 'Hecho.', refused: 'No es posible:',
  },

  office: {
    title: 'Despacho del club', hero: 'El dinero, la directiva, los ladrillos.',
    tabs: ['Dinero', 'Directiva', 'Instalaciones', 'Cuerpo técnico', 'Comercial'],
    runway: (to: string) => `Caja · hasta ${to}`,
    runwayHead: (ok: boolean, low: string) => (ok ? `Sana toda la temporada. El punto más bajo, ${low}.` : `Entramos en números rojos hacia ${low}. Algo tiene que cambiar.`),
    cash: 'Caja hoy', wageUse: 'Sueldos / tope', transfer: 'Presupuesto de fichajes',
    projected: 'Caja prevista', floor: 'Línea de cero',
    income: 'Ingresos al mes', spend: 'Gastos al mes',
    lines: { gate: 'Taquilla', tv: 'Televisión', sponsors: 'Comercial', wages: 'Sueldos', staff: 'Cuerpo técnico', upkeep: 'Mantenimiento' },
    ledger: 'Esta temporada',
    capT: 'Tope salarial', capMove: 'Mover el tope', capUp: (v: string) => `Cuesta ${v} ahora`, capDown: (v: string) => `Devuelve ${v}`,
    board: 'Lo que quiere la directiva', trust: 'Confianza', trustWhy: (n: number) => (n < 30 ? 'Por debajo de 30 empiezan a buscar sustituto.' : n < 50 ? 'Te vigilan.' : 'Están contigo.'),
    obj: { league: 'Liga', cup: 'Copa', youth: 'Cantera', finance: 'Finanzas' },
    onTrack: 'En camino', close: 'Cerca', behind: 'Por detrás',
    youthLine: (n: number, of: number) => `${n} de ${of} partidos de liga para sub-21`,
    financeLine: (ok: boolean) => (ok ? 'En positivo' : 'En negativo'),
    facilities: 'Instalaciones', level: (n: number) => `Nivel ${n}`, upgrade: (v: string) => `Construir · ${v}`, maxed: 'Lo mejor que existe',
    fac: { stadium: 'Estadio', medical: 'Centro médico', training: 'Ciudad deportiva', academy: 'Cantera', scouting: 'Red de ojeadores' },
    facFx: { stadium: 'Más asientos, más taquilla', medical: 'Las lesiones curan antes', training: 'Los jugadores mejoran antes', academy: 'Mejores promesas', scouting: 'Más jornadas de pruebas' },
    staff: 'La sala del cuerpo técnico', staffSub: 'Quién hace qué y cuánto les dejas',
    levels: { me: 'Yo', ask: 'Consúltame', staff: 'Ellos' },
    levelHelp: { me: 'No pasa nada sin ti.', ask: 'Lo preparan y esperan tu sí.', staff: 'Lo hacen y te lo cuentan después.' },
    depts: { matchprep: 'Preparación', opposition: 'Rival', fitness: 'Físico y médico', development: 'Desarrollo', recruitment: 'Fichajes', contracts: 'Contratos y ventas', commercial: 'Comercial' },
    deptSub: { matchprep: 'Once y plan', opposition: 'Informes y plan para el rival', fitness: 'Carga, enfoque, rehabilitación', development: 'Cantera y moral', recruitment: 'Fichajes y cesiones', contracts: 'Renovaciones y ofertas', commercial: 'Patrocinios y entradas' },
    roles: { assistant: 'Segundo entrenador', director: 'Director deportivo', fitness: 'Preparador físico', doctor: 'Médico', psychologist: 'Psicólogo', scout: 'Jefe de ojeadores' },
    bias: { cautious: 'Prudente', bold: 'Atrevido', youth: 'Apuesta por la cantera', veteran: 'Confía en la experiencia', money: 'Primero el dinero', loyal: 'Leal' },
    biasWhy: { cautious: 'Va a lo seguro: descansa pronto, ofrece poco y puede perder objetivos.', bold: 'Va a por todas: exprime las piernas y paga de más.', youth: 'Respalda a los jóvenes.', veteran: 'Quiere jugadores contrastados.', money: 'Vende cuando el precio es bueno, y a veces antes.', loyal: 'No suelta a los suyos; renueva a casi todos.' },
    quality: (n: number) => `Calidad ${n}`, hire: 'Contratar', candidates: 'Candidatos', wage: (v: string) => `${v}/mes`,
    all: 'Ajustar todos los departamentos', log: 'Lo que hizo el cuerpo técnico', logEmpty: 'Nada todavía.',
    sponsors: 'Patrocinadores', offers: 'Ofertas', sign: 'Firmar', haggle: 'Pedir un 10% más', extend: 'Ampliar', end: 'Rescindir',
    slots: { shirt: 'Camiseta', kit: 'Marca deportiva', stadium: 'Nombre del estadio', sleeve: 'Manga', commercial: 'Socio comercial' },
    months: (n: number) => `${n} meses`,
    tickets: 'Entradas', price: 'Precio de la entrada', attendance: (n: string, c: string) => `${n} de ${c} asientos`, setPrice: 'Fijar el precio',
    settings: 'Ajustes y partidas',
  },

  career: {
    title: 'Tu carrera', hero: (n: number) => (n ? `${n} ${P(n, 'título', 'títulos')} y subiendo.` : 'El primer título es el más difícil.'),
    totals: { matches: 'Partidos', wins: 'Victorias', trophies: 'Títulos', rep: 'Reputación' },
    tier: (r: number) => (r < 30 ? 'Desconocido' : r < 50 ? 'Regional' : r < 70 ? 'Nacional' : r < 85 ? 'Continental' : 'Mundial'),
    badge: 'Licencia de entrenador', badgeNext: (b: string, n: number) => `${b} tras ${n} partidos dirigidos`, badgeTop: 'La licencia máxima',
    seasons: 'Temporada a temporada', now: 'Ahora', noSeasons: 'Tu primera temporada se está escribiendo.',
    records: 'Récords', recs: { bigWin: 'Mayor goleada', mostPoints: 'Más puntos', mostGoals: 'Más goles', unbeaten: 'Racha invicta más larga', scorer: 'Máximo goleador en una temporada', bestFinish: 'Mejor puesto', bestBuy: 'Fichaje récord', bestSale: 'Venta récord' },
    jobs: 'Clubes que preguntan por ti', noJobs: 'Nadie llama. Gana algo y llamarán.', take: 'Aceptar el puesto', decline: 'No me interesa',
    courses: 'Cursos', courseBuy: (v: string) => `Matricularse · ${v}`, done: 'Hecho',
    wallet: 'Tu propio dinero',
    lift: (season: string, club: string) => `${season} · ${club}`,
    trophyKinds: { league: 'Liga', cup: 'Copa', continental: 'Copa continental', promotion: 'Ascenso' },
    milestones: 'Hitos',
    sacked: 'Despedido', objMet: 'Objetivo cumplido', objMissed: 'Objetivo fallado',
  },

  pass: {
    concept: 'Concepto · aquí no se vende nada',
    title: 'El Semba Club Pass', lead: 'Para quien quiera apoyar al estudio. Nunca compra resultados, jugadores ni forma.',
    price: '4,99 $', per: 'al mes, para The Gaffer y Tier One',
    perks: [['Sin anuncios en ninguno de los dos juegos', 'También desaparecen los anuncios con recompensa'], ['400 Semba Credits al mes', 'Para equipaciones, escudos y estilos'], ['Un estilo al mes, tuyo para siempre', 'Aunque lo dejes'], ['La insignia del pase', 'En tu tarjeta de entrenador']],
    cta: 'Muy pronto',
    note: 'En la web, el pase y los créditos son una vista previa. Las compras solo se abrirán cuando se puedan verificar.',
    credits: 'Semba Credits', balance: (n: number) => `${n} cr`, creditsSub: 'Guardados solo en este dispositivo. Compartidos con Tier One en el mismo navegador.',
    earn: 'Ver un anuncio · +25 cr', earned: '+25 créditos.', adsOff: 'Los anuncios no están activados en esta versión.', daily: (n: number) => `${n} de 4 hoy`,
    never: 'Lo que el dinero nunca compra', nevers: ['Mejores jugadores o valoraciones', 'Resultados o forma', 'Progresión más rápida', 'Nada del reto diario ni de las clasificaciones'],
    looks: 'Estilos', lookNames: ['Noche granate', 'Azul puerto', 'Oro del desierto'], lookPrice: '250 cr · concepto',
    items: 'También previsto', itemList: [['Diseñador de equipaciones y escudos', '400 cr'], ['Hueco de partida extra', '300 cr'], ['Pack de escenarios: tres rescates', '500 cr']],
  },

  set: {
    title: 'Ajustes', lang: 'Idioma', names: 'Nombres de jugadores y clubes', namesReal: 'Nombres reales', namesFictional: 'Nombres ficticios',
    namesHelp: 'La opción ficticia conserva cada valoración, número y color y cambia solo los nombres. Puedes volver.',
    namesLocked: 'Esta carrera se creó en el antiguo mundo ficticio; sigue siendo ficticia.',
    sim: '«Simular hasta la próxima decisión» se detiene en', stopAll: 'Cualquier decisión', stopImportant: 'Las importantes', stopBig: 'También partidos grandes',
    match: 'Partido', speed: 'Velocidad por defecto', speeds: ['1×', '2×', '4×'], sound: 'Afición y silbato',
    balance: 'Dificultad', saves: 'Partidas', export: 'Exportar esta carrera', import: 'Importar una carrera', exportSub: 'Un archivo .gaffer para guardar', importSub: 'Desde un archivo .gaffer',
    reset: 'Borrar esta carrera', resetAsk: '¿Borrar esta carrera de este dispositivo?', resetBody: 'No se puede deshacer. Expórtala antes si puede que la quieras.', del: 'Borrarla', keep: 'Mantenerla',
    about: 'Acerca de', howTo: 'Cómo se juega', privacy: 'Privacidad', version: (v: string, b: number) => `The Gaffer ${v} · build ${b}`,
    motion: 'El movimiento sigue el ajuste de movimiento reducido de tu dispositivo.',
    world: 'Editor del mundo', worldSub: 'Renombrar clubes, mover ligas', quick: 'Partido rápido',
    menu: 'Pantalla de inicio', importOk: 'Carrera importada.', recovered: 'El último guardado de esta carrera no cargaba, así que se abrió el anterior.', importBad: 'Ese archivo no pasó la comprobación.',
  },
  log: {
    'training:focus': (f: string) => `Semana de ${f.toLowerCase()}.`,
    'tactics:plan': (ph: string) => `Nos pasó a ${ph} para el próximo partido.`,
    'tactics:mentality': () => 'Cambió nuestra actitud para el próximo partido.',
    'tactics:formation': (f: string) => `Cambió el dibujo a ${f}.`,
    'scouting:report': (club: string) => `Vio al ${club} en vídeo y escribió el informe.`,
    'morale:talk': (n: number) => `Habló con la plantilla: el vestuario estaba en ${n}.`,
  },
  news: { title: 'Noticias y buzón', inbox: 'Buzón', news: 'Noticias', empty: 'Día tranquilo.', read: 'Marcar todo como leído' },
  season: {
    title: (y: string) => `${y}, cerrada`, finish: (p: string, obj: string) => `Terminamos ${p}. La directiva quería: ${obj.toLowerCase()}.`,
    met: 'Trabajo hecho.', missed: 'No es suficiente.', up: 'Ascenso', down: 'Descenso', stay: 'Nos quedamos',
    next: (y: string) => `Empezar ${y}`, finishRest: 'Terminar las otras ligas', left: 'Se van del club', kids: 'Suben de la cantera', retired: (n: number) => `${n} jugadores se retiraron por el mundo.`,
  },
  common: {
    free: 'Libre', perMonth: '/mes', yrs: (n: number) => `${n} ${P(n, 'año', 'años')}`, matchday: (n: number) => `Jornada ${n}`,
    pos: { GK: 'POR', CB: 'DFC', LB: 'LI', RB: 'LD', CDM: 'MCD', CM: 'MC', CAM: 'MCO', LW: 'EI', RW: 'ED', ST: 'DC' },
    posLong: { GK: 'Portero', CB: 'Central', LB: 'Lateral izquierdo', RB: 'Lateral derecho', CDM: 'Mediocentro defensivo', CM: 'Centrocampista', CAM: 'Mediapunta', LW: 'Extremo izquierdo', RW: 'Extremo derecho', ST: 'Delantero' },
    group: ['Porteros', 'Defensas', 'Centrocampistas', 'Delanteros'],
    none: 'Ninguno', yes: 'Sí', no: 'No', cancel: 'Cancelar', save: 'Guardar', done: 'Hecho',
  },
};
