// v0.12 text in Spanish.
import type { NewStrings } from './lang-new';

const P = (n: number, one: string, many: string) => (n === 1 ? one : many);

export const NEW_ES: NewStrings = {
  tabs: ['Inicio', 'Plantilla', 'Partido', 'Fichajes', 'Club'],
  hospitalT: 'Servicio médico',
  hospitalSub: (n: number) => (n ? `${n} ${P(n, 'lesionado', 'lesionados')}` : 'Todos en forma'),
  settingsMore: 'Ajustes y más',
  settingsMoreSub: 'Idioma, partidas, editor, partido rápido, privacidad',

  today: (n: number) => (n ? `Hoy: ${n} ${P(n, 'cosa te necesita', 'cosas te necesitan')}` : 'Todo en orden'),
  allClear: 'Nada te necesita antes del próximo partido.',
  todayItems: {
    offers: (n: number) => `${n} ${P(n, 'oferta', 'ofertas')} por tus jugadores`,
    contracts: (n: number) => `${n} ${P(n, 'contrato acaba', 'contratos acaban')} esta temporada`,
    unavailable: (n: number) => `${n} ${P(n, 'titular lesionado o sancionado', 'titulares lesionados o sancionados')}`,
    tired: (n: number) => `${n} ${P(n, 'titular está cansado', 'titulares están cansados')}`,
    windowOpen: (left: number) => `Mercado abierto: ${P(left, 'queda', 'quedan')} ${left} ${P(left, 'jornada', 'jornadas')}`,
    deadline: 'Último día de mercado: cierra tras esta jornada',
    sponsors: (n: number) => `${n} ${P(n, 'hueco de patrocinio libre', 'huecos de patrocinio libres')}`,
    red: 'El club está en números rojos',
    thin: (n: number) => `Solo ${n} jugadores en la plantilla`,
    jobs: (n: number) => `${n} ${P(n, 'club quiere', 'clubes quieren')} hablar contigo`,
    dev: (n: number) => `${n} puntos de desarrollo por gastar`,
    staff: (n: number) => `Tu cuerpo técnico hizo ${n} ${P(n, 'cosa', 'cosas')} desde el último partido`,
  },
  todayActions: { offers: 'Responder', contracts: 'Renovar', unavailable: 'Arreglar XI', tired: 'Rotar', windowOpen: 'Mercado', deadline: 'Mercado', sponsors: 'Firmar', red: 'Finanzas', thin: 'Fichar', jobs: 'Ver ofertas', dev: 'Entrenar', staff: 'Ver' },
  formT: 'Forma',
  nextMatchT: 'Próximo partido',

  ev2: {
    goal: [
      (p: string, c: string) => `¡GOL! ${p} marca para el ${c}.`,
      (p: string, c: string) => `¡GOL! ${p} la pone en la escuadra. El ${c} lo celebra.`,
      (p: string, c: string) => `¡Gol del ${c}! ${p} no perdona.`,
      (p: string, c: string) => `¡GOL! ${p} la manda al fondo. La afición del ${c} ruge.`,
      (p: string, c: string) => `¡GOL! Frialdad total de ${p}. Golpea el ${c}.`,
    ],
    miss: [
      (p: string) => `${p} dispara fuera.`,
      (p: string) => `${p} la manda junto al palo.`,
      (p: string) => `Por encima del larguero, de ${p}.`,
      (p: string) => `${p} se precipita. Fuera.`,
      (p: string) => `${p} prueba desde lejos. Ni cerca.`,
      (p: string) => `Media ocasión para ${p}, pero fuera.`,
    ],
    save: [
      (p: string) => `¡Paradón de ${p}!`,
      (p: string) => `${p} se estira bien y la saca.`,
      (p: string) => `¡Con la yema de los dedos! ${p} la manda a córner.`,
      (p: string) => `${p} aguanta y tapa el disparo.`,
      (p: string) => `Manos firmes de ${p}.`,
      (p: string) => `${p} la lee y la atrapa.`,
    ],
    yellow: [
      (p: string) => `Amarilla para ${p}.`,
      (p: string) => `${p} ve la tarjeta.`,
      (p: string) => `Llega tarde ${p}. Amarilla.`,
      (p: string) => `Amonestado ${p} por agarrar a su rival.`,
    ],
    red: [
      (p: string) => `¡ROJA! ${p} se va a la calle.`,
      (p: string) => `¡Roja! ${p} tiene que irse. Se quedan con diez.`,
      (p: string) => `A la ducha: roja para ${p}.`,
    ],
    injury: [
      (p: string) => `${p} está lesionado y no puede seguir.`,
      (p: string) => `${p} se para. El fisio pide el cambio.`,
      (p: string) => `Mala noticia: ${p} se retira cojeando.`,
    ],
    sub: [
      (off: string, on: string) => `Cambio: entra ${on} por ${off}.`,
      (off: string, on: string) => `Cambio: sale ${off}, entra ${on}.`,
      (off: string, on: string) => `Piernas frescas: ${on} sustituye a ${off}.`,
    ],
  },
  ratingT: 'Nota',
  ratingsT: 'Notas',
  motm: 'Jugador del partido',
  motmN: (n: number) => `${n}× jugador del partido`,
  avgRatingT: 'Nota media',
  xgT: 'Goles esperados (xG)',
  ftTitle: { W: 'Victoria', D: 'Empate', L: 'Derrota' },
  ftSub: 'Lo que cambió el resultado',
  ftPos: 'Posición en liga',
  ftBoard: 'Confianza de la directiva',
  ftFans: 'Afición',
  ftDev: 'Puntos de desarrollo',
  ftOut: (name: string, n: number) => `${name}: baja ${n} ${P(n, 'jornada', 'jornadas')}`,
  ftBan: (name: string) => `${name}: sancionado`,
  ftRecord: 'Nuevo récord del club',
  ftMilestone: 'Hito conseguido',
  ftContinue: 'Continuar',

  windowNames: { summer: 'Mercado de verano', winter: 'Mercado de invierno' },
  windowOpenT: (left: number) => `Abierto: ${P(left, 'queda', 'quedan')} ${left} ${P(left, 'jornada', 'jornadas')}`,
  windowShutT: (n: number) => `Mercado cerrado: abre en ${n} ${P(n, 'jornada', 'jornadas')}`,
  deadlineT: 'Último día de mercado',
  deadlineSub: 'Última oportunidad: el mercado cierra tras esta jornada. Hoy los clubes pujan más.',
  windowClosedBid: 'El mercado está cerrado. Aún puedes fichar agentes libres.',

  transfersT: 'Fichajes',
  trTabs: ['Mercado', 'Seguidos', 'Ofertas', 'Cesiones', 'Operaciones'],
  shortlistAdd: 'Seguir',
  shortlistRemove: 'Dejar de seguir',
  shortlistEmpty: 'No sigues a ningún jugador. Los que sigas aparecen aquí y tus ojeadores afinan su nivel real.',
  findPlayers: 'Buscar jugadores',
  offersEmpty: 'Ahora no hay ofertas por tus jugadores. Llegan con el mercado abierto, más a menudo por los transferibles.',
  answerBids: 'Responder ofertas',
  dealsEmpty: 'Aún no hay operaciones. Fichajes, ventas y libres aparecerán aquí.',
  loansInT: 'Cedidos aquí',
  loansOutT: 'Cedidos fuera',
  loansEmpty: 'Sin cesiones esta temporada. Pide jugadores que no sean titulares en su club o manda a los jóvenes a jugar.',
  loanHint: 'Las cesiones duran la temporada. Paga el sueldo el club que lo recibe. Los jóvenes vuelven mejores.',
  loanInBtn: (fee: string) => `Cesión por la temporada · ${fee}`,
  loanOutBtn: 'Ceder',
  loanTo: 'Cederlo a',
  loanFrom: (club: string) => `Cedido por el ${club}`,
  loanAt: (club: string) => `Cedido al ${club}`,
  loanReason: {
    window: 'Las cesiones solo con el mercado abierto.', budget: 'No hay presupuesto para la tasa de cesión.', wageCap: 'Su sueldo rompería el tope salarial.',
    squad: 'Plantilla completa.', key: 'Es titular allí: no se cede.', limit: 'Ya tienes 4 cesiones en ese sentido.',
    free: 'Los libres se fichan, no se ceden.', loaned: 'Ya está cedido.', injured: 'Un lesionado no puede salir cedido.',
  },
  loanedIn: (name: string) => `${name} llega cedido.`,
  loanedOut: (name: string, club: string) => `${name} se va cedido al ${club}.`,
  noLoanClubs: 'Ningún club de su nivel lo quiere cedido ahora.',
  estimateT: 'Estimación de los ojeadores',
  estHint: 'Síguelo y tus ojeadores sabrán su nivel real en 2 jornadas.',

  showT: 'Ver',
  squadViews: ['Media', 'Forma física', 'Contrato', 'Valor', 'Notas'],

  matchTabs: ['Próximo', 'Clasificación', 'Resultados', 'Copas', 'Datos'],
  leaderTabs: ['Goles', 'Asistencias', 'Notas'],
  worldRankings: 'Ranking mundial',

  boardT: 'Directiva y objetivos',
  staffRoomT: 'Cuerpo técnico',
  staffRoomSub: (n: number, all: number) => (n ? `${n} de ${all} tareas delegadas` : 'Lo llevas todo tú. Delega lo que quieras.'),
  financesT: 'Finanzas',
  ticketsT: 'Entradas',
  sponsorsT: 'Patrocinadores',
  facilitiesT: 'Instalaciones',
  hireStaffT: 'Contratar personal',
  historyT: 'Historia y récords',
  historySub: 'Temporadas, récords, títulos, canteranos',

  staffIntro: 'Pasa cualquier tarea a tu cuerpo técnico. La harán cada jornada, tan bien como les permita su calidad. Los partidos siempre los juegas tú.',
  staffYours: 'Tu cuerpo técnico',
  qualityT: 'Calidad',
  dutiesT: 'Tareas',
  dutyGroups: { matchday: 'Día de partido', squad: 'Plantilla', transfers: 'Fichajes', club: 'Club' },
  duties: {
    lineup: ['Alineación y cambios', 'Elige el mejor XI para cada partido.'],
    tactics: ['Táctica', 'Elige sistema y mentalidad para cada rival.'],
    scouting: ['Informes del rival', 'Compra un informe antes de los partidos duros y usa su plan.'],
    training: ['Entrenamiento', 'Fija la carga y gasta los puntos de desarrollo.'],
    medical: ['Servicio médico', 'Paga rehabilitación en las lesiones largas.'],
    morale: ['Moral', 'Habla al vestuario cuando la moral cae.'],
    academy: ['Cantera', 'Busca promesas, sube a las listas y vende el resto.'],
    contracts: ['Contratos', 'Renueva a quien merece la pena desde la jornada 5.'],
    selling: ['Ventas', 'Responde ofertas y pone en venta a los que sobran.'],
    signing: ['Fichajes', 'Ficha para la posición más corta con el mercado abierto.'],
    loans: ['Cesiones', 'Cede a los jóvenes para que jueguen.'],
    sponsors: ['Patrocinadores', 'Firma la mejor oferta para cada hueco libre.'],
    tickets: ['Precio de entradas', 'Pone el precio que más recauda sin vaciar la grada.'],
  },
  matchDuty: ['Jugar el partido', 'Siempre tú.'],
  meT: 'Yo',
  staffT: 'Staff',
  delegateAll: 'Delegar todo',
  takeAll: 'Controlarlo todo yo',
  needStaff: (role: string) => `Primero contrata: ${role.toLowerCase()}`,
  staffLogT: 'Lo que hizo tu cuerpo técnico',
  staffLogEmpty: 'Nada todavía. Delega una tarea y tu personal anotará aquí lo que hace.',
  staffLog: {
    'training:load': (a) => `Carga de entrenamiento: ${['recuperación', 'equilibrada', 'dura'][a.n] ?? 'equilibrada'}.`,
    'training:dev': (a) => `Puntos de desarrollo para ${a.pn} (+1 de media).`,
    'medical:rehab': (a) => `Pagó la rehabilitación de ${a.pn}.`,
    'morale:talk': (a) => `Charla al vestuario: la moral estaba en ${a.n}.`,
    'academy:promote': (a) => `Subió a ${a.pn} desde la cantera.`,
    'academy:sold': (a) => `Vendió los derechos de ${a.pn} por ${a.money(a.n)}.`,
    'academy:scouted': (a) => `Encontró ${a.n} ${P(a.n, 'promesa nueva', 'promesas nuevas')}.`,
    'selling:sold': (a) => `Vendió a ${a.pn} al ${a.club} por ${a.money(a.n)}.`,
    'selling:rejected': (a) => `Rechazó ${a.money(a.n)} por ${a.pn}.`,
    'selling:listed': (a) => `Puso a ${a.pn} en la lista de transferibles.`,
    'contracts:renewed': (a) => `Renovó a ${a.pn} ${a.n} ${P(a.n, 'temporada', 'temporadas')} más.`,
    'signing:signed': (a) => `Fichó a ${a.pn} ${a.club ? `del ${a.club}` : 'libre'} por ${a.n ? a.money(a.n) : '0'}.`,
    'loans:out': (a) => `Cedió a ${a.pn} al ${a.club}.`,
    'sponsors:signed': (a) => `Firmó con ${a.pn}: ${a.money(a.n)} al mes.`,
    'tickets:price': (a) => `Precio de la entrada: ${a.s}.`,
    'tactics:formation': (a) => `Cambió al ${a.s}.`,
    'scouting:report': (a) => `Compró un informe del ${a.club}.`,
  },
  staffNames2: { director: 'Director deportivo' },
  staffEffects2: { director: 'Contratos, ofertas, fichajes, cesiones, patrocinios y entradas cuando se los delegas' },
  ledgerKeys2: { loans: 'Tasas de cesión' },

  histTabs: ['Temporadas', 'Récords', 'Títulos', 'Cantera'],
  seasonsEmpty: 'Tu primera temporada sigue en marcha. Las terminadas se guardan aquí.',
  recordsEmpty: 'Los récords aparecen tras jugar algunos partidos.',
  trophiesEmpty: 'Aún no hay títulos. Gana una liga o una copa y entra en la vitrina.',
  gradsEmpty: 'Aún no hay canteranos. Sube una promesa y sigue su historia aquí.',
  recordNames: {
    bigWin: 'Mayor victoria', mostPoints: 'Más puntos en liga', mostGoals: 'Más goles en liga', unbeaten: 'Racha más larga sin perder',
    scorer: 'Máximo goleador en una temporada', bestFinish: 'Mejor puesto en liga', bestBuy: 'Fichaje récord', bestSale: 'Venta récord',
  },
  gamesN: (n: number) => `${n} ${P(n, 'partido', 'partidos')}`,
  gradLine: (apps: number, goals: number) => `${apps} PJ · ${goals} goles esta temporada`,
  trophyKinds: { league: 'Liga', cup: 'Copa', continental: 'Copa continental', promotion: 'Ascenso' },

  updWeb: (v: string) => `The Gaffer ${v} está listo: arreglos y novedades.`,
  updWebBtn: 'Actualizar',
  updApk: (v: string) => `Ya está la versión ${v} de la app. Instálala para seguir recibiendo novedades.`,
  updApkBtn: 'Descargar',
  updLater: 'Luego',
  supportT: 'Apoya a The Gaffer',
  supportBody: 'Un pack de Socio de pago único: todos los estilos de club, insignia de Socio en tu tarjeta y sin anuncios. El juego sigue completo para todos.',
  supportBtn: 'Conseguir el pack de Socio',
  supportSoon: 'El pack de Socio llega pronto.',
  supporterBadge: 'Socio',
  supportThanks: 'Gracias por apoyar a The Gaffer. Todo desbloqueado.',
  looksT: 'Estilo',
  looks: ['Violeta', 'Focos', 'Césped', 'Rojo derbi'],
  looksLocked: 'Pack de Socio',
  rewardedBtn: 'Ver un anuncio corto: informe gratis',
  rewardedHint: 'Opcional. Siempre puedes pagar el informe con dinero del club.',
  adFailed: 'Ahora no hay anuncios. Prueba más tarde.',
  sponsoredT: 'Patrocinado',
  howToBody2: [
    ['Tu trabajo', 'Elige un club y firma el contrato. La directiva fija objetivos de liga y copa. Cúmplelos y tu reputación crece; fállalos y te pueden echar.'],
    ['Inicio', 'Inicio muestra lo que te necesita hoy, cada cosa con un botón. Despéjalo y juega el próximo partido.'],
    ['Jornadas', 'Pulsa Jugar el partido para verlo en directo, o elige resultado rápido. Cada partido acaba con notas, jugador del partido y una tarjeta con lo que cambió el resultado.'],
    ['Táctica', 'Elige sistema, XI, mentalidad, presión y pase. Las filosofías se ganan entre sí como piedra, papel o tijera, y tu dominio crece cada partido. Espía al rival antes de los grandes.'],
    ['Tu cuerpo técnico', 'Club › Cuerpo técnico: delega cualquier tarea (alineación, entrenamiento, contratos, fichajes y más) o hazla tú. Los partidos siempre los juegas tú.'],
    ['Fichajes', 'Compra y vende con el mercado abierto (verano e invierno, con último día). Los libres se fichan cuando quieras. Sigue jugadores para que tus ojeadores sepan su nivel real, y cede o pide cedidos por la temporada.'],
    ['Dinero', 'Entran taquilla, TV y patrocinio; salen sueldos, personal y mantenimiento. Mejora instalaciones, contrata personal y acaba la temporada en positivo.'],
    ['Copas', 'La copa nacional es eliminatoria desde el inicio. Las continentales empiezan con grupos de cuatro: pasan los dos primeros.'],
    ['Tu carrera', 'Gana XP y licencias, haz cursos, suma hitos y títulos y bate récords del club. Te llamarán clubes más grandes.'],
    ['Guardado', 'La carrera se guarda sola tras cada partido y se comprueba al cargar. Exporta una partida desde Club › Ajustes y más.'],
  ],
  privacyBody2: [
    ['Qué guardamos', 'Tu carrera, ajustes y foto de entrenador se guardan solo en este dispositivo. La comprobación de versiones pide a Semba Games el último número de versión y no envía datos de tu carrera.'],
    ['Funciones en línea', 'Anuncios y compras, cuando estén activos, van claramente marcados. Los anuncios web son de Google AdSense, que puede usar cookies para mostrarlos y medirlos. Las compras las gestiona Stripe; nunca vemos tu tarjeta.'],
    ['Sin cuenta', 'The Gaffer no tiene inicio de sesión. Tu carrera vive en tu dispositivo y puedes exportarla cuando quieras desde Ajustes.'],
    ['Partidas', 'Una partida exportada va donde tú elijas. Importar solo lee el archivo que eliges.'],
    ['Fotos', 'La foto de tu tarjeta de entrenador se queda en este dispositivo y solo sirve para dibujar la tarjeta.'],
    ['Borrar tus datos', 'Empieza de nuevo desde Ajustes o borra los datos de la app, y todo desaparece.'],
    ['Contacto', '¿Dudas? sembagames.app'],
  ],
};
