// Recruitment copy in French. Type-checked against lang-recruit.ts.
import type { RStrings } from './lang-recruit';

const P = (n: number, one: string, many: string) => (n === 1 ? one : many);

export const R_FR: RStrings = {
  tabs: ['Cibles', 'Chercher', 'Négociations', 'Opérations', 'Prêts', 'Besoins', 'Recruteurs'],
  stages: ['Besoins et recrutement', 'Liste et recherche', 'Négociations', 'Opérations et prêts'],
  hero: { need: (pos: string) => `Trouver un ${pos.toLowerCase()}`, none: 'Chaque poste est doublé.' },
  kpi: { room: 'Marge de dépense', wageRoom: 'Marge salariale / mois', committed: 'Engagé' },
  talksBtn: (n: number) => `Négociations · ${n}`,

  why: {
    noCover: 'Pas de doublure', thin: 'Juste', old: 'Titulaire 32+', expiring: 'Fin de contrat du titulaire', loanee: 'Titulaire prêté',
    weak: 'Maillon faible', style: 'Pas dans notre style', manual: 'Ton choix',
  },
  needHead: {
    noCover: (pos: string) => `Aucune doublure au poste de ${pos.toLowerCase()}.`,
    thin: (pos: string) => `Une blessure et on est à court de ${pos.toLowerCase()}.`,
    old: (pn: string) => `${pn} ne jouera pas éternellement.`,
    expiring: (pn: string) => `${pn} arrive en fin de contrat l’été prochain.`,
    loanee: (pn: string) => `${pn} retourne dans son club en mai.`,
    weak: (pos: string) => `${pos} : c’est là qu’on est le plus faible.`,
    style: (pn: string) => `${pn} ne colle pas à notre jeu.`,
    manual: (pos: string) => `Tu veux un ${pos.toLowerCase()} de plus.`,
  },
  needEyebrow: 'Pourquoi on cherche',
  board: 'Les trous du plan', boardSub: (f: string) => `Plan A · ${f}. Change le plan, les trous changent avec.`,
  legend: { red: 'Pas de doublure', amber: 'À surveiller', ok: 'Couvert' },
  depth: (d: number, want: number) => `${d} sur ${want}`,
  starter: 'Titulaire',
  picksBtn: 'Choix du recruteur', assignBtn: 'Envoyer un recruteur', pin: 'Ajouter un besoin', pinned: 'Ton choix', unpin: 'Retirer',
  noNeeds: 'Chaque poste du plan est doublé. Cherche la qualité, pas le nombre.',
  addNeed: 'Ajoute un besoin toi-même',

  scout: {
    pick: (pn: string, k: number) => `${pn}, c’est lui. On le connaît à ${k} %.`,
    unsure: (pn: string, k: number) => `${pn} pourrait être le bon, mais on ne le connaît qu’à ${k} %. Envoie-moi le voir avant de payer à l’aveugle.`,
    none: 'Personne ne colle encore. Envoie-moi sur un championnat et laisse-moi quelques semaines.',
    title: 'Chef recruteur',
  },
  picks: 'Les choix du recruteur pour tes besoins',
  whyFits: (pos: string, natural: boolean, age: number, k: number) => `${natural ? 'Couvre' : 'Peut couvrir'} ${pos.toLowerCase()} dans le plan A · ${age} ans · connu à ${k} %`,
  shortlist: 'Ta liste',
  emptyList: 'La liste est vide. Marque des joueurs dans Chercher et les recruteurs commencent à les suivre.',

  ability: 'Niveau', ceiling: 'Plafond', fit: 'Style', known: 'connu',
  asking: 'Prix demandé', free: 'Libre', wants: 'Demande / mois', interest: 'Intérêt',
  interestL: ['Rêve', 'Motivé', 'Ouvert', 'Réservé', 'Pas en arrière'],
  prioLabel: 'Ce qui compte pour lui', prio: { money: 'L’argent', role: 'Jouer', ambition: 'L’ambition', security: 'La sécurité' },
  unsettled: 'Mal dans son club',
  unknown: '?',
  offer: 'Faire une offre', inTalks: 'En négociation', report: 'Rapport', star: 'Sur la liste', unstar: 'Retirer de la liste', loan: 'Prêt',
  compare: { eyebrow: 'Ce qu’on sait · niveau', head: 'Plus la barre est large, moins on en sait.', key: 'Fourchette estimée', ref: (pn: string, n: number) => `${pn} aujourd’hui (${n})` },

  talks: 'Opérations en cours', noTalks: 'Aucune négociation. Fais une offre depuis tes cibles.', recent: 'Récemment',
  stage: { club: 'Indemnité', terms: 'Contrat', done: 'Signé', collapsed: 'Échoué' },
  status: {
    waiting: (day: string) => `Offre sur la table · réponse ${day}`,
    counter: (v: string) => `Ils veulent ${v}`,
    rejected: 'Ils ont dit non',
    rival: (club: string, v: string) => `${club} offre ${v}`,
    terms: (n: number, m: number) => `Agent · tour ${n} sur ${m}`,
    due: (day: string) => `Réponse avant ${day}`,
  },
  ends: {
    signed: 'Signé', walked: 'L’agent est parti', frozen: 'Négociation gelée', hijacked: 'Doublé', window: 'Mercato fermé',
    withdrawn: 'Tu t’es retiré', gone: 'Parti ailleurs', rejected: 'Refusé',
  },

  room: {
    title: (pn: string) => `Négociation · ${pn}`,
    stages: ['Indemnité', 'Contrat', 'Signé'],
    clubHead: 'Indemnité de transfert', termsHead: 'Contrat du joueur', doneHead: 'Signé', offHead: 'Négociation rompue',
    withClub: (club: string, n: number, m: number) => `Avec ${club} · offre ${n} sur ${m}`,
    withAgent: (name: string, style: string, n: number, m: number) => `Avec son agent, ${name} (${style}) · tour ${n} sur ${m}`,
    styles: { fair: 'réglo', hardball: 'coriace', greedy: 'gourmand' },
    agreed: (club: string, fee: string) => `Indemnité conclue avec ${club} · ${fee}`,
    onTable: 'Offre sur la table', freeAgent: 'Joueur libre · pas d’indemnité',
    table: 'Où en est la table',
    you: (n: number) => `Toi · ${n}`,
    them: (who: string) => who,
    board: (club: string) => `Direction de ${club}`,
    bidLine: (fee: string, seasons: number, sellOn: number) => `${fee}${seasons > 1 ? ` sur ${seasons} saisons` : ' comptant'}${sellOn ? ` + ${sellOn} % à la revente` : ''}.`,
    clubSays: {
      accept: 'Marché conclu. Voyez son agent.',
      counter: (v: string) => `Pas assez. ${v} et il est à vous.`,
      reject: 'Il n’est pas à vendre à ce prix.',
      insult: 'C’est une blague ? Revenez avec une vraie offre.',
      rival: (club: string, v: string) => `${club} propose ${v}. Faites mieux avant la prochaine journée.`,
    },
    agentSays: {
      open: 'Voilà ce qu’il faut.', close: 'On y est presque.', notThere: 'On n’y est pas encore.', insulted: 'Vous insultez mon client.',
      walk: 'C’est terminé. Il écoutera d’autres offres.', accept: 'Marché conclu.',
    },
    ourLine: 'Voici notre offre.',
    chip: {
      wage: (v: string) => `${v}/mois`, years: (n: number) => `${n} ${P(n, 'an', 'ans')}`,
      signOn: (v: string) => `${v} de prime à la signature`, release: (v: string) => `clause de ${v}`, noRelease: 'Pas de clause',
      bonus: (v: string) => `${v} par match`,
    },
    roles: { star: 'Star', regular: 'Titulaire', rotation: 'Rotation', prospect: 'Espoir' },
    patienceClub: 'Patience de la direction', patienceAgent: 'Patience de l’agent',
    yourBid: (n: number) => `Offre ${n} · la tienne`, yourOffer: (n: number) => `Tour ${n} · ton offre`,
    fee: 'Indemnité', feeZone: 'Dans le vert, ils accepteraient', pay: 'Paiement', payOpts: ['Tout de suite', 'Sur 2 saisons', 'Sur 3 saisons'],
    upfront: 'Comptant', upOpts: ['40 %', '60 %', '80 %'], sellOn: 'Revente', sellOpts: ['Non', '10 %', '15 %', '20 %'],
    sellOnWhy: 'Une part de ce qu’on touchera en le revendant. Ça vaut moins que du cash pour eux.',
    instWhy: (v: string) => `${v} la saison suivante. Ça réduit la marge dès maintenant, en entier.`,
    wage: 'Salaire mensuel', wageZone: 'Dans le vert, il signerait sans doute', years: 'Durée', role: 'Rôle', roleWhy: 'Le rôle que tu promets, il te le rappellera.',
    clauses: 'Clauses', clausesSub: 'Ce que chacune te coûte',
    signOn: 'Prime à la signature', signOnWhy: (v: string) => `${v} maintenant. De l’argent en poche dès le premier jour.`,
    release: 'Clause libératoire', releaseWhy: (v: string) => `N’importe quel club qui paie ${v} peut le prendre, sans qu’on puisse l’empêcher.`, releaseOff: 'Désactivée : il reste à nous jusqu’à ce qu’on le vende.',
    bonus: 'Prime de match', bonusWhy: (v: string) => `${v} pour chaque match de championnat joué.`,
    his: 'Sa demande',
    verdict: 'Si tu envoies ça',
    clubV: { accept: 'Ils accepteront', counter: 'Attends-toi à une contre-offre', reject: 'Ils diront non', insult: 'Ils le prendront mal' },
    clubWhy: (e: string) => `Ça vaut ${e} pour eux : les échéances comptent moins, la revente encore moins.`,
    chance: (p: number) => (p >= 0.75 ? 'Il signera sans doute' : p >= 0.5 ? 'Ça peut passer' : p > 0 ? 'Peu probable' : 'Il ne signera pas ça'),
    chanceWhy: (known: boolean) => (known ? 'On sait ce qui compte pour lui.' : 'On ne sait pas encore ce qui compte pour lui. C’est notre meilleure lecture.'),
    roomAfter: 'Marge après', wageRoomAfter: 'Marge salariale après', later: 'Engagé, saisons suivantes', agentFee: 'Commission d’agent', bill: 'Masse salariale', perYear: '/an',
    send: (n: number) => `Envoyer le tour ${n}`, sendBid: 'Envoyer l’offre', walk: 'Quitter la table', meet: 'Accepter ses demandes', takeCounter: 'Accepter sa contre-offre',
    payCounter: (v: string) => `Payer ${v}`, top: (v: string) => `Surenchérir : ${v}`, waiting: (day: string) => `Réponse ${day}`,
    back: 'Transferts',
    signed: (pn: string) => `${pn} est à nous.`,
    frozenFor: (n: number) => `Négociation gelée ${n} ${P(n, 'journée', 'journées')}.`,
    adv: {
      clubLow: 'Sous leur prix, au mieux une contre-offre. Trois offres et ils ne décrochent plus.',
      clubOk: 'C’est leur prix. Ils toperont.',
      deadline: 'Dernier jour du mercato : ils répondent tout de suite.',
      termsHigh: (v: string) => `Ne dépasse pas ${v}. Ça fixe la barre pour toutes les prolongations.`,
      termsOk: 'Juste pour les deux parties. Moi, j’envoie.',
      termsLow: 'Il n’acceptera pas ça. Bouge sur ce qui compte pour lui.',
      waiting: 'Il n’y a plus qu’à attendre leur réponse.',
    },
    agentFree: 'Pas d’indemnité : il est libre. L’agent prend quand même sa part.',
  },

  bidsFor: 'Offres pour tes joueurs',
  aiWhy: { unhappy: 'Il n’est pas heureux', expiring: 'Son contrat se termine', request: 'Il a demandé à partir', need: 'Ils en ont besoin' },
  committed: 'Ce qu’on doit', commitRow: (season: string, club: string) => `${season} · à ${club}`, noCommit: 'Rien à payer. Tout est réglé.',
  stories: 'Les histoires',
  loans: {
    in: 'Prêté chez nous', out: 'Prêté ailleurs', none: 'Aucun prêt.',
    share: (p: number) => `On paie ${p} % de son salaire`, shareOut: (p: number) => `Ils paient ${p} % de son salaire`,
    minutes: { starter: 'Clause de titulaire', rotation: 'Clause de rotation', none: 'Pas de clause de temps de jeu' },
    progress: (apps: number, need: number, days: number) => `${apps} matchs en ${days} journées · il en faut ${need}`,
    broken: 'Clause non respectée', trust: (n: number) => `Leur confiance en nous ${n}`, recall: 'Le rappeler',
    ask: (pn: string) => `Prêt de ${pn}`, shareQ: 'Part du salaire qu’on paie', minutesQ: 'Temps de jeu promis', send: 'Le demander',
    needs: (s: string) => `Ils le prêteraient si on paie ${s} de son salaire.`, noWay: 'Ils ne le prêteront à aucune condition possible.',
    outTitle: (pn: string) => `Prêter ${pn}`, where: 'Où', theyPay: 'Part du salaire qu’ils paient', outSend: 'L’envoyer',
    fee: (v: string) => `Frais de prêt ${v}`, takes: 'Le prendraient', wontTake: 'Refusent ces conditions',
  },

  scouts: {
    head: 'Où sont les recruteurs', slots: (n: number, max: number) => `${n} ${P(n, 'mission', 'missions')} sur ${max} en cours`,
    slotsWhy: 'Le centre de recrutement fixe le nombre de missions possibles.',
    scope: { league: 'Championnat', country: 'Pays', world: 'Monde entier' },
    pos: 'Poste', any: 'Tous postes', send: 'L’envoyer', remove: 'Le rappeler',
    coverage: (n: number, k: number) => `${n} joueurs · ${k} bien connus`,
    rate: (v: number, t: number) => `+${v} de connaissance par journée · +${t} pour la liste`,
    empty: 'Aucun recruteur dehors. On n’en apprend que par la liste et nos matchs.',
    worldPos: 'Le monde entier demande un poste.', full: 'Tous les recruteurs sont dehors. Rappelle-en un d’abord.',
    newOne: 'Nouvelle mission',
    quote: (n: number, k: number) => `${n} noms là-dehors, et je mettrais ma main au feu pour ${k}. Laisse-moi du temps.`,
    best: 'Ceux qu’on connaît le mieux', none: 'Personne de bien connu hors de l’effectif pour l’instant.',
  },

  tag: { bidAnswer: 'Réponse', agent: 'Agent', rival: 'Offre rivale', loanClause: 'Prêt', recall: 'Prêt' },
  dec: {
    rival: (pn: string, club: string, v: string, day: string) => `${club} offre ${v} pour ${pn}. Fais mieux avant ${day}.`,
    counter: (pn: string, club: string, v: string) => `${club} veut ${v} pour ${pn}.`,
    rejected: (pn: string, club: string, v: string) => `${club} refuse ${v} pour ${pn}.`,
    insulted: (pn: string, club: string) => `${club} a ri de notre offre pour ${pn}.`,
    agreed: (pn: string, day: string) => `Indemnité conclue pour ${pn}. Son agent veut une réponse avant ${day}.`,
    agentDue: (pn: string, day: string) => `L’agent de ${pn} veut une réponse avant ${day}.`,
    clauseRisk: (pn: string, club: string, n: number) => `${pn} doit jouer ${n} ${P(n, 'match', 'matchs')} de plus pour contenter ${club}.`,
    recallQ: (pn: string, club: string) => `${club} ne fait pas jouer ${pn}. On le rappelle ?`,
    rivalBid: (pn: string, club: string, v: string, why: string) => `${club} offre ${v} pour ${pn}.${why ? ` ${why}.` : ''}`,
    askBid: (pn: string, v: string) => `Offrir ${v} pour ${pn} ?`,
  },
  adv: {
    top: (v: string) => `Monte à ${v}. On n’en trouvera pas d’autre comme lui ce mercato.`,
    letGo: 'Laisse-le partir. On ne lance pas d’enchères.',
    pay: (v: string) => `${v}, c’est cher mais juste. Paie.`,
    walk: (v: string) => `${v}, c’est trop. Lève-toi.`,
    rejected: (n: number) => (n > 0 ? `Ils ne bougent pas encore. Encore ${n} ${P(n, 'essai', 'essais')} et ils ne décrochent plus.` : 'Ils ne décrochent plus.'),
    meet: (v: string) => `Donne-lui ${v} par mois et c’est bouclé aujourd’hui.`,
    counter: 'La contre-offre de l’agent nous va. Prends-la.',
    talk: 'Il y a de la marge pour le faire baisser. Ouvre la négociation.',
    clause: (club: string) => `On a promis à ${club} qu’il jouerait. Si on manque à notre parole, ils ne nous prêteront plus personne.`,
    recall: 'Il pourrit sur leur banc. Fais-le revenir.',
    bid: (v: string) => `Le meilleur profil pour notre besoin principal, dans nos moyens. ${v}, c’est une bonne ouverture.`,
  },
  choice: {
    top: (v: string) => `Surenchérir : ${v}`, letGo: 'Le laisser partir', pay: (v: string) => `Payer ${v}`, improve: 'Améliorer l’offre', walk: 'Quitter la table',
    meet: 'Accepter ses demandes', takeCounter: 'Accepter sa contre-offre', talk: 'Ouvrir la négociation', playHim: 'Le faire jouer', riskIt: 'Tenter le coup', recall: 'Le rappeler', leave: 'Le laisser là-bas',
  },
  fx: {
    room: (v: string) => `Reste ${v}`, fees: (v: string) => `Frais ${v}`, patience: (n: number) => `Encore ${n} ${P(n, 'essai', 'essais')}`,
    noDeal: 'Pas d’accord', rounds: (n: number) => `${n} ${P(n, 'tour', 'tours')} de patience`, rivalGets: 'Il part chez le rival',
    parentHappy: 'Son club satisfait', parentAngry: 'Ils ne nous prêtent plus', back: 'De retour dans l’effectif', benchWarm: 'Encore un mois sur leur banc',
  },

  news: {
    bid: (pn: string, club: string, club2: string, v: string) => [`${club} offre ${v} pour ${pn}`, `${club2} réfléchit.`],
    agreed: (pn: string, club: string, club2: string, v: string) => [`${club} trouve un accord pour ${pn}`, `${v} à ${club2}. Reste le contrat.`],
    done: (pn: string, club: string, club2: string, v: string) => [`${pn} rejoint ${club}`, v ? `En provenance de ${club2} pour ${v}.` : 'Libre de tout contrat.'],
    walk: (pn: string, club: string) => [`Les discussions pour ${pn} capotent`, `Son agent a claqué la porte de ${club}.`],
    hijack: (pn: string, club: string, club2: string, v: string) => [`${club} double tout le monde pour ${pn}`, `${v} à ${club2}. Quelqu’un a été trop lent.`],
    aiBid: (pn: string, club: string, v: string, why: string) => [`${club} offre ${v} pour ${pn}`, why],
    aiWhy: { unhappy: 'Il ne sourit plus depuis des semaines.', expiring: 'Son contrat arrive à terme.', request: 'Il a demandé à partir.', need: 'Ils cherchent un joueur comme lui.' },
    release: (pn: string, club: string, club2: string, v: string) => [`${club} lève la clause de ${pn}`, `${v}, et ${club2} ne peut pas refuser.`],
    loanIn: (pn: string, club: string, club2: string) => [`${pn} prêté à ${club}`, `Par ${club2}, pour la saison.`],
  },
  msg: {
    answer: (pn: string, club: string, s: string, v: string) => [
      s === 'accept' ? `${club} accepte notre offre pour ${pn}` : s === 'counter' ? `Contre-offre de ${club} pour ${pn}` : `${club} refuse notre offre pour ${pn}`,
      s === 'accept' ? `${v} conclus. Son agent attend.` : s === 'counter' ? `Ils veulent ${v}.` : s === 'insult' ? 'Ils l’ont mal pris.' : 'Améliore-la ou retire-toi.',
    ],
    hijack: (pn: string, club: string, v: string) => [`${pn} signe à ${club}`, `Ils ont payé ${v} pendant que notre offre attendait.`],
    rival: (pn: string, club: string, v: string) => [`${club} s’intéresse à ${pn}`, `${v} sur la table. Fais mieux avant la prochaine journée.`],
    release: (pn: string, club: string, v: string) => [`${club} lève la clause de ${pn}`, `${v}. Il est parti.`],
    instalments: (v: string, n: number) => [`Échéances payées : ${v}`, `${n} ${P(n, 'paiement tombait', 'paiements tombaient')} avec la nouvelle saison.`],
    picks: (pn: string, n: number, pos: string) => [`Rapport du recruteur : ${pn}`, `Premier choix au poste de ${pos.toLowerCase()} · ${n} ${P(n, 'nom', 'noms')} sur la liste.`],
    loanReport: (pn: string, club: string, apps: number, goals: number, days: number) => [`Rapport de prêt : ${pn}`, `${apps} matchs en ${days} journées à ${club}, ${goals} ${P(goals, 'but', 'buts')}.`],
    brokenIn: (pn: string, club: string) => [`${club} furieux au sujet de ${pn}`, 'On avait promis du temps de jeu. Ils le reprendront au mercato.'],
    brokenOut: (pn: string, club: string) => [`${club} ne fait pas jouer ${pn}`, 'Ils ont rompu la clause de temps de jeu. On peut le rappeler au mercato.'],
    takenBack: (pn: string, club: string) => [`${club} reprend ${pn}`, 'Le prêt est terminé.'],
    sellOn: (pn: string, club: string, v: string) => [`Pourcentage de revente versé pour ${pn}`, `${v} à ${club}, comme prévu à l’achat.`],
  },
  log: {
    rcbid: (pn: string, v: string) => `Offre de ${v} pour ${pn}.`, rcPay: (pn: string, v: string) => `A payé leur prix pour ${pn} : ${v}.`,
    rcTop: (pn: string, v: string) => `A surenchéri pour ${pn} : ${v}.`, rcSigned: (pn: string, v: string) => `Contrat conclu avec ${pn} : ${v} par mois.`,
    rcWalk: (pn: string) => `S’est retiré du dossier ${pn}.`,
  },
  steps: {
    bid: 'Offre', agreed: 'Indemnité conclue', counter: 'Contre-offre', reject: 'Refus', insult: 'Vexés', frozen: 'Gelée', rival: 'Offre rivale', topped: 'Surenchère',
    hijacked: 'Doublé', signed: 'Signé', walked: 'L’agent part', window: 'Mercato fermé', withdrawn: 'Retrait', gone: 'Parti ailleurs', talks: 'Négociation ouverte',
    loanIn: 'Arrive en prêt', loanOut: 'Part en prêt', brokenIn: 'Clause rompue', brokenOut: 'Ils rompent la clause', recalled: 'Rappelé', takenBack: 'Repris',
    release: 'Clause levée', bid_need: 'Offre : ils en ont besoin', bid_unhappy: 'Offre : pas heureux', bid_expiring: 'Offre : fin de contrat', bid_request: 'Offre : veut partir',
  },
  ledger: { agentFees: 'Commissions d’agents', signOn: 'Primes à la signature', instalments: 'Échéances de transferts', loanWages: 'Salaires des prêts', bonuses: 'Primes de match', sellOn: 'Pourcentages de revente' },
  no: {
    frozen: 'La négociation est gelée.', waiting: 'Notre offre est encore sur la table.', agreed: 'L’indemnité est conclue. Parle à son agent.',
    trust: 'Ils ne nous prêtent plus personne après la dernière fois.', loanTerms: 'Ils veulent qu’on paie plus de salaire, ou une promesse de temps de jeu.', minutes: 'Il n’aurait pas ce temps de jeu là-bas.',
    buyerBudget: 'Ils n’ont pas les moyens.', release: 'La clause ne peut pas être sous sa valeur.', slots: 'Tous les recruteurs sont dehors.', scope: 'Choisis où l’envoyer.',
    done: 'Déjà couvert.', noClause: 'Pas de clause de temps de jeu à invoquer.', loaned: 'Il est prêté.',
  },
  note: {
    bidSent: (pn: string) => `Offre envoyée pour ${pn}.`, talks: (pn: string) => `Négociation ouverte avec l’agent de ${pn}.`, agreed: (pn: string) => `Indemnité conclue pour ${pn}.`,
    assigned: 'Le recruteur est en route.', recalled: (pn: string) => `${pn} rentre à la maison.`,
    close: 'On y est presque.', notThere: 'Pas encore.', insulted: 'Il est vexé.', walk: 'L’agent est parti.',
  },
};
