// Copy for V2.6 Training & pathway (training week, medical, academy & pathway, Intake Day, the development curve, their
// Today decisions, news and inbox lines). English is the reference; lang-youth-{ar,es,fr}.ts are type-checked against it.
// Voice: the training ground and the physio's room. The answer in the headline, the evidence underneath.
const P = (n: number, one: string, many: string) => (n === 1 ? one : many);
const NUM = ['No one', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine'];
const num = (n: number) => NUM[n] ?? String(n);

export const Y_EN = {
  doors: { train: 'Training week', medical: 'Medical', academy: 'Academy & pathway' },
  bands: ['Low', 'Elevated', 'High'] as [string, string, string],
  intens: ['Light', 'Normal', 'Heavy'] as [string, string, string],
  tiers: ['a steady', 'a promising', 'an exciting', 'a special'] as [string, string, string, string],

  // ---------- training week ----------
  tw: {
    title: 'Training week',
    head: (i: number, focus: string, plans: number): string => `${['A light', 'A normal', 'A heavy'][i]} week, ${focus.toLowerCase()} focus. ${plans ? `${num(plans)} on extra work.` : 'Nobody on extra work.'}`,
    intensity: 'Intensity',
    intFx: ['Growth ×0.7. Legs recover faster.', 'Growth ×1.0. The usual week.', 'Growth ×1.4. Load +4 a day, and knocks happen.'] as [string, string, string],
    congested: 'Two matches this week: Heavy is off the table.',
    dropped: 'Heavy was dropped last week: we had two matches.',
    focus: 'The week’s focus',
    load: 'Load',
    loadSub: 'Who can take another ninety',
    loadHidden: 'A fitness coach rated 60+ gives you the exact numbers.',
    loadN: (n: number): string => `Load ${n}`,
    fragile: (n: number): string => `Fragile · ${n} ${P(n, 'match', 'matches')}`,
    riskX: (x: string): string => `×${x} injury risk`,
    allFresh: 'Everyone can go again.',
    plans: 'Individual plans',
    plansN: (n: number, max: number): string => `${n} of ${max}`,
    plansNone: 'Nobody on extra work. Up to five players can be.',
    plansFull: 'Five is the limit. Take someone off first.',
    add: 'Add a plan',
    who: 'Player',
    attr: 'Sharpen an attribute',
    pos: 'Learn a new position',
    attrFx: 'Growth +10%, the extra point lands on this attribute, load +2 a day.',
    posFx: 'About eleven matchdays of extra work. Growth −10% meanwhile.',
    learning: (pos: string, pct: number): string => `Learning ${pos} · ${pct}%`,
    sharpening: (a: string): string => `Sharpening ${a}`,
    also: (pos: string): string => `Also plays ${pos}`,
    remove: 'Take off',
    save: 'Start the plan',
    report: 'Last week',
    up: (n: number): string => `${num(n)} stepped up`,
    near: 'Close to their next step',
    knocks: (n: number): string => `${num(n)} picked up a knock`,
    academyUp: (n: number): string => `${num(n)} in the academy stepped up`,
    quiet: 'Nothing moved this week. It will.',
  },

  // ---------- medical ----------
  md: {
    title: 'Medical',
    head: (out: number, edge: number): string => (out || edge ? `${num(out)} out, ${edge ? `${num(edge).toLowerCase()} on the edge` : 'nobody on the edge'}.` : 'A clean bill of health.'),
    out: 'Treatment room',
    back: (lo: number, hi: number): string => (lo === hi ? `Back in ${lo} ${P(lo, 'matchday', 'matchdays')}` : `Back in ${lo}–${hi} matchdays`),
    orig: (n: number): string => `Out for ${n} when it happened`,
    fog: (who: string): string => `${who}’s estimate. A better doctor narrows it.`,
    fogNone: 'No club doctor: this is a guess.',
    rush: 'Rush back',
    rushFx: (gain: number, risk: number): string => `${gain} ${P(gain, 'matchday', 'matchdays')} sooner · ${risk}% he breaks down again`,
    rushNotYet: (n: number): string => `Rush-back possible at ${n} ${P(n, 'matchday', 'matchdays')} left`,
    edge: 'On the edge',
    edgeSub: 'Loaded legs and fragile ones',
    thisMatch: (n: number): string => `~${n}% this match`,
    none: 'Nobody on the treatment table.',
    noEdge: 'Nobody carrying too much. Keep rotating.',
    rest: 'Rest him',
    unrest: 'Pick him again',
  },

  // ---------- academy & pathway ----------
  ac: {
    title: 'Academy & pathway',
    head: (n: number, loans: number, grads: number): string => `${num(n)} in the academy, ${num(loans).toLowerCase()} out on loan, ${num(grads).toLowerCase()} in the first team.`,
    countdown: (n: number): string => `Intake Day in ${n} ${P(n, 'matchday', 'matchdays')}`,
    countdownSub: 'The Head of Youth hasn’t seen this year’s group yet.',
    preview: (tier: string, pos: string): string => `${tier.charAt(0).toUpperCase()}${tier.slice(1)} ${pos.toLowerCase()} in this year’s group`,
    previewSub: (n: number): string => `Intake Day in ${n} ${P(n, 'matchday', 'matchdays')}. The Head of Youth has seen them.`,
    arrived: (n: number): string => `Intake Day. ${num(n)} new ${P(n, 'face', 'faces')}.`,
    classOf: (y: string): string => `The class of ${y}`,
    reveal: 'Meet them',
    standout: 'Standout',
    nextYear: 'Next Intake Day is next season.',
    cap: (n: number, cap: number): string => `${n} of ${cap} places`,
    over: 'Over capacity: every kid grows 15% slower.',
    squad: 'The academy',
    empty: 'The academy is empty until Intake Day.',
    ready: 'Ready',
    late: 'Time is short',
    grown: (n: number): string => (n > 0 ? `+${n} this season` : n < 0 ? `${n} this season` : 'Level this season'),
    promote: 'Promote',
    loan: 'Loan out',
    release: 'Release',
    word: 'A word',
    recall: 'Bring him home',
    loanTitle: (pn: string): string => `Where should ${pn} play?`,
    loanSub: 'A club where he starts gives him real minutes, and minutes are what grow him.',
    roles: ['Would start', 'Rotation', 'Mostly bench'] as [string, string, string],
    windowShut: 'The window is shut. Loans go through in summer and mid-season.',
    tooYoung: 'Too young to go out on loan (17+).',
    noSpots: 'No club at his level wants him yet.',
    releaseQ: (pn: string): string => `Let ${pn} go? He becomes a free agent and anyone can sign him.`,
    loans: 'Out on loan',
    loansNone: 'Nobody out on loan. In a window, send the next ones where they’ll play.',
    mins: (n: number): string => `${n} min this season`,
    run: (n: number): string => `${n} full ${P(n, 'game', 'games')} running`,
    grads: 'Graduates',
    gradsNone: 'No homegrown player in the first team yet.',
    since: (from: number, now: number): string => `${from} → ${now}`,
    apps: (n: number): string => `${n} ${P(n, 'app', 'apps')}`,
    path: ['Academy', 'On loan', 'First team'] as [string, string, string],
  },

  // ---------- profile curve ----------
  cv: {
    real: 'Real history',
    proj: 'Where he’s heading',
    avg: 'Our XI average',
    starts: (s: string): string => `History from ${s}`,
    one: 'History starts here: every matchday from now on is on record.',
    academy: 'Academy',
    homegrown: 'Homegrown',
    load: 'Load',
    minutes: (n: number): string => `${n} min this season`,
  },

  // ---------- Today ----------
  tag: { risk: 'Medical', rush: 'Medical', intake: 'Intake Day', ready: 'Academy', loanee: 'Loan report', benched: 'Loan report', full: 'Academy', ageout: 'Academy' } as Record<string, string>,
  titles: {
    y_risk: (pn: string, n: number): string => `${pn} can play, but his load is ${n}`,
    y_rush: (pn: string, n: number): string => `${pn} could be back sooner than ${n} ${P(n, 'matchday', 'matchdays')}`,
    y_intake: (n: number): string => `Intake Day: ${num(n).toLowerCase()} new ${P(n, 'face', 'faces')}`,
    y_ready: (pn: string, n: number): string => `${pn} is knocking on the door at ${n}`,
    y_loanee: (pn: string, n: number, club: string): string => `${pn}: ${n} full games running at ${club}`,
    y_benched: (pn: string, club: string): string => `${pn} isn’t playing at ${club}`,
    y_full: (n: number, cap: string): string => `The academy has ${n} kids for ${cap} places`,
    y_ageout: (pn: string, n: number): string => `${pn} is ${n} and still in the academy`,
    ask_y_rush: (pn: string): string => `Rush ${pn} back?`,
    ask_y_rest: (pn: string): string => `Rest ${pn} for the next match?`,
    ask_y_loan: (pn: string, club: string): string => `Loan ${pn} to ${club}?`,
    ask_y_release: (pn: string): string => `Let ${pn} go from the academy?`,
  } as Record<string, (...a: any[]) => string>,
  advice: {
    y_risk_rest: (_pn: string, n: number, sub: string): string => `He can play. He can also pull something: about ${n}% today. ${sub ? `${sub} is fresh. ` : ''}I’d rest him.`,
    y_risk_rest_c: (pn: string, _n: number, sub: string): string => `Not with legs like that. ${pn} sits this one out${sub ? `, ${sub} goes in` : ''}.`,
    y_risk_play: (_pn: string, n: number): string => `He’s carrying a lot, but about ${n}% is a risk I’d take. Play him and take him off early.`,
    y_risk_play_b: (_pn: string, n: number): string => `${n}%? That’s football. Play him.`,
    y_risk_rr: (pn: string, n: number): string => `We pushed ${pn} back early. About ${n}% he breaks down again today. I’d keep him out of this one.`,
    y_rush_yes: (_pn: string, n: number): string => `He’s past halfway. Push him and he’s back sooner. There’s a ${n}% chance he breaks down in the next three games. I’d take it.`,
    y_rush_no: (_pn: string, n: number): string => `I can get him back sooner, but there’s a ${n}% chance he breaks down again, for longer. Let it heal.`,
    y_intake: (pn: string, pos: string, n: number): string => `They’re all here. Keep an eye on ${pn}: ${['a steady', 'a promising', 'an exciting', 'a special'][n] ?? 'a promising'} ${pos}. There’s room for all of them.`,
    y_intake_full: (pn: string, pos: string, n: number): string => `${pn} is the one: ${['a steady', 'a promising', 'an exciting', 'a special'][n] ?? 'a promising'} ${pos}. But we’re over capacity. Keep everyone and they all learn slower.`,
    y_ready: (pn: string, n: number): string => `${pn} is as good as our 18th man (${n}). Training with the first team will finish him off.`,
    y_ready_v: (pn: string): string => `${pn} is close. I’d rather he played men’s football somewhere first.`,
    y_loanee: (pn: string): string => `${pn} is playing every week. He hasn’t kicked on yet, but minutes like that are what grow a player.`,
    y_loanee_up: (pn: string, n: number, s: string): string => `${pn} has ${s} minutes and he’s up ${n} this season. Leave him there.`,
    y_benched: (pn: string, n: number): string => `${pn} has ${n} minutes. They promised us games. Bring him back and find him a club that plays him.`,
    y_full: (pn: string, n: number): string => `Too many kids, not enough coaching. ${pn} is the one I’d let go: ceiling around ${n}.`,
    y_ageout_keep: (pn: string, n: number): string => `${pn} still has something in him, maybe ${n}. Give him a squad number or a loan.`,
    y_ageout_go: (pn: string): string => `${pn} won’t make it here. Let him go and find a club.`,
    why_y_rush: (pn: string, n: number): string => `${pn} is past halfway. ${n}% risk, and we need him.`,
    why_y_rest: (pn: string, n: number): string => `${pn}’s legs are heavy. About ${n}% he pulls something.`,
    why_y_loan: (pn: string): string => `${pn} needs men’s football. They’ll start him.`,
    why_y_release: (pn: string): string => `We’re over capacity and ${pn} is the least likely to make it.`,
  } as Record<string, (...a: any[]) => string>,
  choices: {
    y_ch_rush: (n: number): string => `Push him back (${n} sooner)`,
    y_ch_heal: (): string => 'Let it heal',
    y_ch_spec: (v: string): string => `Specialist (${v})`,
    y_ch_keepAll: (): string => 'Keep them all',
    y_ch_trim: (n: number): string => `Let the weakest ${n === 1 ? 'one' : n} go`,
    y_ch_promote: (): string => 'Promote him',
    y_ch_loan: (club: string): string => `Loan him to ${club}`,
    y_ch_leave: (): string => 'Leave him there',
    y_ch_word: (): string => 'Tell him we’re watching',
    y_ch_recall: (): string => 'Bring him home',
    y_ch_release: (pn: string): string => `Let ${pn} go`,
  } as Record<string, (...a: any[]) => string>,
  fx: {
    y_fx_safe: (): string => 'No risk today',
    y_fx_risk: (n: number): string => `Injury risk ~${n}%`,
    y_fx_fragile: (n: number): string => `Fragile for ${n} more`,
    y_fx_sooner: (n: number): string => `Back ${n} sooner`,
    y_fx_relapse: (n: number): string => `${n}% relapse risk`,
    y_fx_heal: (n: number): string => `Out ${n} more`,
    y_fx_room: (n: number, cap: string): string => `${n} of ${cap} places`,
    y_fx_spread: (n: number, cap: string): string => `${n} for ${cap}: slower growth`,
    y_fx_letGo: (n: number): string => `${n} to the free-agent pool`,
    y_fx_squad: (): string => 'First-team squad',
    y_fx_proWage: (): string => 'A pro wage',
    y_fx_starter: (): string => 'He’d start there',
    y_fx_rotation: (): string => 'Rotation there',
    y_fx_academyPace: (): string => 'Academy pace',
    y_fx_growing: (n: number): string => (n > 0 ? `+${n} this season` : 'Minutes in the bank'),
    y_fx_morale: (): string => 'Morale up',
    y_fx_home: (): string => 'Loses his minutes',
    y_fx_reloan: (): string => 'Loan him again',
    y_fx_stall: (): string => 'His growth stalls',
    y_fx_focus: (): string => 'Better coaching for the rest',
    y_fx_free: (): string => 'Free agent',
  } as Record<string, (...a: any[]) => string>,

  // ---------- news, inbox, staff log ----------
  news: {
    y_preview: (club: string, pos: string, tier: string): [string, string] => [`${club}’s academy whispers about ${tier} ${pos.toLowerCase()}`, 'The Head of Youth has seen this year’s group. Intake Day is ten matchdays away.'],
    y_intake: (club: string, n: number, pn: string, pos: string): [string, string] => [`Intake Day at ${club}: ${num(n).toLowerCase()} new ${P(n, 'face', 'faces')}`, pn ? `The one everyone watched: ${pn}, ${pos.toLowerCase()}.` : 'A new group starts today.'],
    y_rivalGem: (club: string, pn: string, pos: string, tier: string): [string, string] => [`${club} unveil ${tier} ${pos.toLowerCase()}`, `${pn} joins their academy. Remember the name.`],
    y_breakthrough: (pn: string, club: string, n: string): [string, string] => [`${pn}, ${n}, is a regular at ${club}`, 'Ten league games this season for the academy graduate.'],
    y_loaned: (pn: string, club: string): [string, string] => [`${pn} joins ${club} on loan`, 'The academy prospect goes to get games.'],
  } as Record<string, (...a: any[]) => [string, string]>,
  msg: {
    y_preview: (pn: string, pos: string, tier: string): [string, string] => [`Head of Youth: ${tier} ${pos.toLowerCase()} in this year’s group`, `I’ve seen the new group. ${pn} is the one to watch. Intake Day is ten matchdays away.`],
    y_learned: (pn: string, pos: string): [string, string] => [`${pn} can now play ${pos}`, 'The extra work paid off. The XI picker will use him there.'],
    y_reinjured: (pn: string, n: number): [string, string] => [`${pn} has broken down again`, `We pushed him back early. He’s out for ${n} more.`],
    y_loanReport: (pn: string, n: number, s: string, club: string): [string, string] => [`Loan report: ${pn} at ${club}`, `${n} minutes this season, ${Number(s) > 0 ? `up ${s}` : Number(s) < 0 ? `down ${-Number(s)}` : 'level'} since the summer.`],
    y_devGone: (n: number): [string, string] => ['Development points are gone', `The ${n} points left over went into the squad’s mood (+5 morale). Players grow on the training pitch and with minutes now.`],
  } as Record<string, (...a: any[]) => [string, string]>,
  log: {
    'medical:y_rush': (pn: string, n: number): string => `Rushed ${pn} back (${n}% relapse risk)`,
    'medical:y_rest': (pn: string, n: number): string => `Rested ${pn}: ~${n}% injury risk`,
    'academy:y_loan': (pn: string, club: string): string => `Loaned ${pn} to ${club}`,
    'academy:y_release': (pn: string): string => `Released ${pn} from the academy`,
    'academy:promote': (pn: string): string => `Promoted ${pn} to the first team`,
  } as Record<string, (pn: string, a: any, b?: any) => string>,
  note: { rushed: 'He’s back in training.', promoted: 'He has a first-team shirt.' } as Record<string, string>,
  no: {
    congested: 'Two matches this week: no heavy training.', plans: 'Five plans is the limit.', notYet: 'Too early to push him.', retired: 'That’s gone: Intake Day replaced it.',
    young: 'Too young for that.', pos: 'Pick a position he doesn’t already play.', load: 'Pick Light, Normal or Heavy.', unknown: 'That no longer exists.',
  } as Record<string, string>,
};

export type YStrings = typeof Y_EN;
