// v0.12 text in French.
import type { NewStrings } from './lang-new';

const P = (n: number, one: string, many: string) => (n === 1 ? one : many);

export const NEW_FR: NewStrings = {
  tabs: ['Accueil', 'Effectif', 'Match', 'Transferts', 'Club'],
  hospitalT: 'Infirmerie',
  hospitalSub: (n: number) => (n ? `${n} ${P(n, 'blessé', 'blessés')}` : 'Tout le monde est apte'),
  settingsMore: 'Réglages et plus',
  settingsMoreSub: 'Langue, sauvegardes, éditeur, match rapide, confidentialité',

  today: (n: number) => (n ? `Aujourd’hui : ${n} ${P(n, 'chose vous attend', 'choses vous attendent')}` : 'Rien à signaler'),
  allClear: 'Rien ne vous attend avant le prochain match.',
  todayItems: {
    offers: (n: number) => `${n} ${P(n, 'offre', 'offres')} pour vos joueurs`,
    contracts: (n: number) => `${n} ${P(n, 'contrat se termine', 'contrats se terminent')} cette saison`,
    unavailable: (n: number) => `${n} ${P(n, 'titulaire blessé ou suspendu', 'titulaires blessés ou suspendus')}`,
    tired: (n: number) => `${n} ${P(n, 'titulaire est fatigué', 'titulaires sont fatigués')}`,
    windowOpen: (left: number) => `Mercato ouvert : encore ${left} ${P(left, 'journée', 'journées')}`,
    deadline: 'Dernier jour du mercato : il ferme après cette journée',
    sponsors: (n: number) => `${n} ${P(n, 'emplacement de sponsor libre', 'emplacements de sponsor libres')}`,
    red: 'Le club est dans le rouge',
    thin: (n: number) => `Seulement ${n} joueurs dans l’effectif`,
    jobs: (n: number) => `${n} ${P(n, 'club veut', 'clubs veulent')} vous parler`,
    dev: (n: number) => `${n} points de progression à dépenser`,
    staff: (n: number) => `Votre staff a fait ${n} ${P(n, 'chose', 'choses')} depuis le dernier match`,
    board: (n: number, d: number) => `Confiance de la direction ${n} : ${d === 1 ? 'une défaite de plus' : `${d} défaites de plus`} et vous êtes dehors`,
  },
  todayActions: { offers: 'Répondre', contracts: 'Prolonger', unavailable: 'Corriger le XI', tired: 'Faire tourner', windowOpen: 'Marché', deadline: 'Marché', sponsors: 'Signer', red: 'Finances', thin: 'Recruter', jobs: 'Voir les offres', dev: 'Entraîner', staff: 'Voir', board: 'Direction' },
  formT: 'Forme',
  formLetters: ['V', 'N', 'D'],
  nextMatchT: 'Prochain match',

  ev2: {
    goal: [
      (p: string, c: string) => `BUT ! ${p} marque pour ${c}.`,
      (p: string, c: string) => `BUT ! ${p} trouve la lucarne. ${c} exulte.`,
      (p: string, c: string) => `But pour ${c} ! ${p} ne tremble pas.`,
      (p: string, c: string) => `BUT ! ${p} la met au fond. Les supporters de ${c} explosent.`,
      (p: string, c: string) => `BUT ! Clinique de ${p}. ${c} frappe.`,
    ],
    miss: [
      (p: string) => `${p} tire à côté.`,
      (p: string) => `${p} frôle le poteau.`,
      (p: string) => `Au-dessus de la barre, signé ${p}.`,
      (p: string) => `${p} se précipite. À côté.`,
      (p: string) => `${p} tente de loin. Loin du cadre.`,
      (p: string) => `Demi-occasion pour ${p}, mais c’est à côté.`,
    ],
    save: [
      (p: string) => `Grosse parade de ${p}.`,
      (p: string) => `${p} se couche bien et repousse.`,
      (p: string) => `Du bout des doigts ! ${p} la sort en corner.`,
      (p: string) => `${p} reste debout et bloque.`,
      (p: string) => `Mains fermes de ${p}.`,
      (p: string) => `${p} lit la frappe et capte.`,
    ],
    yellow: [
      (p: string) => `Carton jaune pour ${p}.`,
      (p: string) => `${p} est averti.`,
      (p: string) => `${p} arrive en retard. Jaune.`,
      (p: string) => `${p} averti pour avoir retenu son adversaire.`,
    ],
    red: [
      (p: string) => `CARTON ROUGE ! ${p} est expulsé.`,
      (p: string) => `Rouge ! ${p} doit sortir. À dix.`,
      (p: string) => `Direction le vestiaire : rouge pour ${p}.`,
    ],
    injury: [
      (p: string) => `${p} est blessé et ne peut pas continuer.`,
      (p: string) => `${p} s’arrête. Le kiné demande le changement.`,
      (p: string) => `Mauvaise nouvelle : ${p} sort en boitant.`,
    ],
    sub: [
      (off: string, on: string) => `Changement : ${on} remplace ${off}.`,
      (off: string, on: string) => `Changement : ${off} sort, ${on} entre.`,
      (off: string, on: string) => `Du sang neuf : ${on} à la place de ${off}.`,
    ],
  },
  ratingT: 'Note',
  ratingsT: 'Notes',
  motm: 'Homme du match',
  motmN: (n: number) => `${n}× homme du match`,
  avgRatingT: 'Note moyenne',
  xgT: 'Buts attendus (xG)',
  ftTitle: { W: 'Victoire', D: 'Nul', L: 'Défaite' },
  ftSub: 'Ce que le résultat a changé',
  ftPos: 'Classement',
  ftBoard: 'Confiance de la direction',
  ftFans: 'Supporters',
  ftDev: 'Points de progression',
  ftOut: (name: string, n: number) => `${name} : absent ${n} ${P(n, 'journée', 'journées')}`,
  ftBan: (name: string) => `${name} : suspendu`,
  ftRecord: 'Nouveau record du club',
  ftMilestone: 'Objectif atteint',
  ftContinue: 'Continuer',

  windowNames: { summer: 'Mercato d’été', winter: 'Mercato d’hiver' },
  windowOpenT: (left: number) => `Ouvert : encore ${left} ${P(left, 'journée', 'journées')}`,
  windowShutT: (n: number) => `Mercato fermé : ouvre dans ${n} ${P(n, 'journée', 'journées')}`,
  deadlineT: 'Dernier jour du mercato',
  deadlineSub: 'Dernière chance : le mercato ferme après cette journée. Les clubs enchérissent davantage aujourd’hui.',
  windowClosedBid: 'Le mercato est fermé. Vous pouvez toujours signer des joueurs libres.',

  transfersT: 'Transferts',
  trTabs: ['Marché', 'Suivis', 'Offres', 'Prêts', 'Opérations'],
  shortlistAdd: 'Suivre',
  shortlistRemove: 'Ne plus suivre',
  shortlistEmpty: 'Aucun joueur suivi. Ceux que vous suivez apparaissent ici, et vos recruteurs précisent leur vrai niveau.',
  findPlayers: 'Chercher des joueurs',
  offersEmpty: 'Aucune offre pour vos joueurs pour l’instant. Elles arrivent pendant le mercato, plus souvent pour les joueurs listés.',
  answerBids: 'Répondre aux offres',
  dealsEmpty: 'Aucune opération pour l’instant. Achats, ventes et libres apparaîtront ici.',
  loansInT: 'Prêtés chez nous',
  loansOutT: 'Prêtés ailleurs',
  loansEmpty: 'Aucun prêt cette saison. Empruntez des joueurs hors du XI de leur club, ou prêtez vos jeunes pour qu’ils jouent.',
  loanHint: 'Les prêts durent la saison. Le club qui accueille paie le salaire. Les jeunes reviennent meilleurs.',
  loanInBtn: (fee: string) => `Prêt pour la saison · ${fee}`,
  loanOutBtn: 'Prêter',
  loanTo: 'Le prêter à',
  loanFrom: (club: string) => `Prêté par ${club}`,
  loanAt: (club: string) => `Prêté à ${club}`,
  loanReason: {
    window: 'Les prêts se font seulement pendant le mercato.', budget: 'Pas assez de budget pour les frais de prêt.', wageCap: 'Son salaire dépasserait la masse salariale.',
    squad: 'Effectif complet.', key: 'Titulaire là-bas : pas prêtable.', limit: 'Vous avez déjà 4 prêts dans ce sens.',
    free: 'Un joueur libre signe, il n’est pas prêté.', loaned: 'Déjà prêté.', injured: 'Un joueur blessé ne peut pas être prêté.',
    lenderThin: 'Ils ne prêtent pas : ils passeraient sous 16 joueurs.', club: 'Ce club ne peut pas le prendre.',
  },
  loanedIn: (name: string) => `${name} arrive en prêt.`,
  loanedOut: (name: string, club: string) => `${name} part en prêt à ${club}.`,
  noLoanClubs: 'Aucun club de son niveau ne le veut en prêt pour l’instant.',
  estimateT: 'Estimation des recruteurs',
  estHint: 'Suivez-le et vos recruteurs connaîtront son vrai niveau en 2 journées.',

  showT: 'Afficher',
  squadViews: ['Note', 'Condition', 'Contrat', 'Valeur', 'Forme'],

  matchTabs: ['Prochain', 'Classement', 'Résultats', 'Coupes', 'Stats'],
  leaderTabs: ['Buts', 'Passes D', 'Notes'],
  worldRankings: 'Classement mondial',

  boardT: 'Direction et objectifs',
  staffRoomT: 'Staff',
  staffRoomSub: (n: number, all: number) => (n ? `${n} tâches sur ${all} déléguées` : 'Vous gérez tout. Déléguez au choix.'),
  financesT: 'Finances',
  ticketsT: 'Billetterie',
  sponsorsT: 'Sponsors',
  facilitiesT: 'Infrastructures',
  hireStaffT: 'Recruter du staff',
  historyT: 'Histoire et records',
  historySub: 'Saisons, records, trophées, jeunes du centre',

  staffIntro: 'Confiez n’importe quelle tâche à votre staff. Il s’en charge à chaque journée, aussi bien que sa qualité le permet. Les matchs, c’est toujours vous.',
  staffYours: 'Votre staff',
  qualityT: 'Qualité',
  dutiesT: 'Tâches',
  dutyGroups: { matchday: 'Jour de match', squad: 'Effectif', transfers: 'Transferts', club: 'Club' },
  duties: {
    lineup: ['Composition et changements', 'Choisit le meilleur XI à chaque match.'],
    tactics: ['Tactique', 'Choisit le système et la mentalité selon l’adversaire.'],
    scouting: ['Rapports adverses', 'Achète un rapport avant les gros matchs et applique son plan.'],
    training: ['Entraînement', 'Règle la charge et dépense les points de progression.'],
    medical: ['Infirmerie', 'Paie la rééducation des blessures longues.'],
    morale: ['Moral', 'Parle au groupe quand le moral baisse.'],
    academy: ['Centre de formation', 'Repère des espoirs, promeut les prêts, vend le reste.'],
    contracts: ['Contrats', 'Prolonge ceux qui le méritent dès la journée 5.'],
    selling: ['Ventes', 'Répond aux offres et liste les joueurs en trop.'],
    signing: ['Recrutement', 'Recrute au poste le plus faible pendant le mercato.'],
    loans: ['Prêts', 'Prête les jeunes pour qu’ils jouent.'],
    sponsors: ['Sponsors', 'Signe la meilleure offre pour chaque emplacement libre.'],
    tickets: ['Prix des billets', 'Fixe le prix qui rapporte le plus sans vider les tribunes.'],
  },
  matchDuty: ['Jouer le match', 'Toujours vous.'],
  meT: 'Moi',
  staffT: 'Staff',
  delegateAll: 'Tout confier au staff',
  takeAll: 'Tout faire moi-même',
  needStaff: (role: string) => `Recrutez d’abord : ${role.toLowerCase()}`,
  staffLogT: 'Ce qu’a fait votre staff',
  staffLogEmpty: 'Rien pour l’instant. Déléguez une tâche et votre staff notera ici ce qu’il fait.',
  staffLog: {
    'training:load': (a) => `Charge d’entraînement : ${['récupération', 'équilibrée', 'intense'][a.n] ?? 'équilibrée'}.`,
    'training:dev': (a) => `Points de progression pour ${a.pn} (+1 de note).`,
    'medical:rehab': (a) => `A payé la rééducation de ${a.pn}.`,
    'morale:talk': (a) => `Discours au groupe : le moral était à ${a.n}.`,
    'academy:promote': (a) => `A promu ${a.pn} du centre de formation.`,
    'academy:sold': (a) => `A vendu les droits de ${a.pn} pour ${a.money(a.n)}.`,
    'academy:scouted': (a) => `A trouvé ${a.n} ${P(a.n, 'nouvel espoir', 'nouveaux espoirs')}.`,
    'selling:sold': (a) => `A vendu ${a.pn} à ${a.club} pour ${a.money(a.n)}.`,
    'selling:rejected': (a) => `A refusé ${a.money(a.n)} pour ${a.pn}.`,
    'selling:listed': (a) => `A placé ${a.pn} sur la liste des transferts.`,
    'contracts:renewed': (a) => `A prolongé ${a.pn} de ${a.n} ${P(a.n, 'saison', 'saisons')}.`,
    'contracts:capRaise': (a) => `A relevé le plafond salarial de ${a.money(a.n)} par mois pour garder ${a.pn}.`,
    'signing:signed': (a) => `A recruté ${a.pn} ${a.club ? `de ${a.club}` : 'libre'} pour ${a.n ? a.money(a.n) : '0'}.`,
    'loans:out': (a) => `A prêté ${a.pn} à ${a.club}.`,
    'sponsors:signed': (a) => `A signé ${a.pn} comme sponsor : ${a.money(a.n)} par mois.`,
    'tickets:price': (a) => `Prix du billet : ${a.s}.`,
    'tactics:formation': (a) => `Passage au ${a.s}.`,
    'scouting:report': (a) => `A acheté un rapport sur ${a.club}.`,
  },
  staffNames2: { director: 'Directeur sportif' },
  staffEffects2: { director: 'Contrats, offres, recrutement, prêts, sponsors et billetterie quand vous les déléguez' },
  ledgerKeys2: { loans: 'Frais de prêt' },

  wagesOfCap: 'Salaires, du plafond',
  newEnd: (y: number) => `Nouvelle fin : ${y}`,
  resumedFrom: (min: number) => `Reprise à la ${min}′`,
  playingT: (what: string) => `${what} en cours…`,
  saveRefused: (why: string) => `Sauvegarde impossible : ${why}`,
  tacticsTabs: ['Système', 'Style', 'Coups de pied arrêtés'],
  confirmSub: (off: string, on: string) => `Confirmer le changement : ${off} ↔ ${on}`,
  pickSubHint: 'Choisissez qui sort et qui entre.',
  detailsT: 'Détails',
  hideDetailsT: 'Masquer les détails',
  radarLocked: 'Observez l’adversaire pour voir son profil.',

  histTabs: ['Saisons', 'Records', 'Trophées', 'Formation'],
  seasonsEmpty: 'Votre première saison est en cours. Les saisons terminées sont gardées ici.',
  recordsEmpty: 'Les records apparaissent après quelques matchs.',
  trophiesEmpty: 'Pas encore de trophée. Gagnez un championnat ou une coupe pour remplir la vitrine.',
  gradsEmpty: 'Pas encore de jeune promu. Promouvez un espoir et suivez son histoire ici.',
  recordNames: {
    bigWin: 'Plus large victoire', mostPoints: 'Plus de points en championnat', mostGoals: 'Plus de buts en championnat', unbeaten: 'Plus longue série sans défaite',
    scorer: 'Meilleur buteur sur une saison', bestFinish: 'Meilleur classement', bestBuy: 'Achat record', bestSale: 'Vente record',
  },
  gamesN: (n: number) => `${n} ${P(n, 'match', 'matchs')}`,
  gradLine: (apps: number, goals: number) => `${apps} matchs · ${goals} buts cette saison`,
  trophyKinds: { league: 'Championnat', cup: 'Coupe', continental: 'Coupe continentale', promotion: 'Montée' },

  updWeb: (v: string) => `The Gaffer ${v} est prêt : correctifs et nouveautés.`,
  updWebBtn: 'Mettre à jour',
  updApk: (v: string) => `La version ${v} de l’app est sortie. Installez-la pour continuer à recevoir les mises à jour.`,
  updApkBtn: 'Télécharger',
  updLater: 'Plus tard',
  supportT: 'Soutenir The Gaffer',
  supportBody: 'Un pack Supporter en une fois : tous les styles de club, un badge Supporter sur votre carte et pas de pubs. Le jeu reste complet pour tout le monde.',
  supportBtn: 'Obtenir le pack Supporter',
  supportSoon: 'Le pack Supporter arrive bientôt.',
  supporterBadge: 'Supporter',
  supportThanks: 'Merci de soutenir The Gaffer. Tout est débloqué.',
  looksT: 'Style',
  looks: ['Sarcelle', 'Projecteurs', 'Pelouse', 'Rouge derby'],
  looksLocked: 'Pack Supporter',
  rewardedBtn: 'Regarder une courte pub : rapport gratuit',
  rewardedHint: 'Facultatif. Vous pouvez toujours payer le rapport avec l’argent du club.',
  adFailed: 'Pas de pub disponible. Réessayez plus tard.',
  sponsoredT: 'Sponsorisé',
  howToBody2: [
    ['Votre rôle', 'Choisissez un club et signez le contrat. La direction fixe des objectifs en championnat et en coupe. Atteignez-les et votre réputation grandit ; ratez-les et vous pouvez être limogé.'],
    ['Accueil', 'L’accueil liste ce qui vous attend aujourd’hui, chaque point avec un bouton. Réglez-les, puis jouez le prochain match.'],
    ['Journées', 'Touchez Jouer le match pour le vivre en direct, ou prenez un résultat rapide. Chaque match se termine par des notes, un homme du match et une carte de ce que le résultat a changé.'],
    ['Tactique', 'Choisissez système, XI, mentalité, pressing et jeu de passes. Les philosophies se battent comme pierre-feuille-ciseaux, et votre maîtrise progresse à chaque match. Espionnez l’adversaire avant les gros matchs.'],
    ['Votre staff', 'Club › Staff : confiez n’importe quelle tâche (composition, entraînement, contrats, recrutement et plus) ou faites-la vous-même. Les matchs, c’est toujours vous.'],
    ['Transferts', 'Achetez et vendez pendant le mercato (été et hiver, avec dernier jour). Les joueurs libres signent à tout moment. Suivez des joueurs pour connaître leur vrai niveau, et prêtez ou empruntez pour la saison.'],
    ['Argent', 'Billetterie, droits TV et sponsors rentrent ; salaires, staff et entretien sortent. Améliorez les infrastructures, recrutez du staff et finissez la saison dans le vert.'],
    ['Coupes', 'La coupe nationale est à élimination directe dès le départ. Les coupes continentales commencent par des groupes de quatre : les deux premiers passent.'],
    ['Votre carrière', 'Gagnez de l’XP et des licences, suivez des formations, cumulez objectifs et trophées, battez les records du club. Les grands clubs appelleront.'],
    ['Sauvegarde', 'La carrière s’enregistre après chaque match et est vérifiée au chargement. Exportez une sauvegarde depuis Club › Réglages et plus.'],
  ],
  privacyBody2: [
    ['Ce que nous gardons', 'Votre carrière, vos réglages et la photo d’entraîneur sont enregistrés uniquement sur cet appareil. La vérification des mises à jour demande à Semba Games le dernier numéro de version, sans envoyer de données de carrière.'],
    ['Fonctions en ligne', 'Les pubs et les achats, quand ils sont activés, sont clairement signalés. Les pubs web viennent de Google AdSense, qui peut utiliser des cookies pour les afficher et les mesurer. Les achats passent par Stripe ; nous ne voyons jamais votre carte.'],
    ['Sans compte', 'The Gaffer n’a pas de connexion. Votre carrière reste sur votre appareil, et vous pouvez l’exporter à tout moment depuis les réglages.'],
    ['Sauvegardes', 'Une sauvegarde exportée va où vous le choisissez. L’import ne lit que le fichier choisi.'],
    ['Photos', 'La photo de votre carte d’entraîneur reste sur cet appareil et ne sert qu’à dessiner la carte.'],
    ['Supprimer vos données', 'Recommencez depuis les réglages, ou effacez les données de l’app, et tout disparaît.'],
    ['Contact', 'Des questions ? sembagames.app'],
  ],

  philosophyHints: {
    balanced: 'Toutes les consignes au milieu. L’équipe la connaît par cœur.',
    possession: 'Passes courtes, rythme lent, latéraux intérieurs, faux 9. Fait mal aux équipes fatiguées ou basses ; il faut des passeurs.',
    counter: 'Reculer, partir aussitôt, jouer direct. Mortel contre les équipes qui montent.',
    gegenpress: 'Ligne haute, pressing haut, rythme rapide. Récupère près du but ; fatigant, et de bons passeurs le contournent.',
    bus: 'Tout le monde derrière, étroit, en contre. Le plus dur à battre, et le moins dangereux.',
    wings: 'Largeur, latéraux offensifs, les grands montent sur corner. Il faut des ailiers rapides contre des latéraux lents.',
    direct: 'Longs ballons vers un pivot, rythme rapide. Évite le pressing haut ; il faut un attaquant costaud.',
  },
  eng: {
    comma: ', ',
    ins: {
      mentality: { t: 'Mentalité', o: ['Bus garé', 'Défensive', 'Équilibrée', 'Offensive', 'Tout pour l’attaque'], h: [
        'Tout le monde derrière le ballon. Très dur à percer, mais vous menacerez à peine.',
        'Les latéraux restent et moins de joueurs montent. Plus sûr, moins dangereux.',
        'Autant de monde en attaque qu’en défense.',
        'Plus de joueurs dans la surface et plus de tirs, mais moins de monde derrière à la perte du ballon.',
        'Tout le monde devant. Des occasions des deux côtés : vous prendrez des contres.',
      ] },
      pressing: { t: 'Pressing', o: ['Bloc bas', 'Bloc médian', 'Pressing haut'], h: [
        'Laissez-leur le ballon dans leur moitié. Jambes fraîches, moins de fautes, mais ils relancent tranquillement.',
        'Pressez au milieu quand le moment s’y prête.',
        'Chassez le ballon dans leur tiers : récupérations près du but, mais fatigant, plus de fautes, et une équipe qui passe bien vous éliminera.',
      ] },
      line: { t: 'Ligne défensive', o: ['Basse', 'Normale', 'Haute'], h: [
        'Reculez : pas d’espace dans le dos, mais ils ont plus de temps au milieu.',
        'Une ligne normale.',
        'Réduisez le terrain et piégez-les au hors-jeu, mais les attaquants rapides iront dans votre dos.',
      ] },
      width: { t: 'Largeur', o: ['Étroite', 'Normale', 'Large'], h: [
        'Resserrez-vous : plus de combinaisons dans l’axe, moins de centres.',
        'Usage équilibré du terrain.',
        'Écartez le jeu : ailiers et latéraux en un-contre-un, plus de centres. Idéal avec des côtés rapides.',
      ] },
      tempo: { t: 'Rythme', o: ['Lent', 'Normal', 'Rapide'], h: [
        'Gardez le ballon et attendez l’ouverture : plus de possession, moins de pertes, moins d’occasions.',
        'Rythme normal.',
        'Jouez vite vers l’avant avant qu’ils se replacent : plus d’attaques et de contres, plus de pertes, plus de fatigue.',
      ] },
      passing: { t: 'Passes', o: ['Courtes', 'Mixtes', 'Directes'], h: [
        'Relancez court depuis l’arrière. Il faut de bons passeurs ; un pressing haut peut faire mal.',
        'Court quand on peut, long quand il faut.',
        'Long vers les attaquants : ça saute leur pressing, mais vous perdez plus de seconds ballons.',
      ] },
      fullback: { t: 'Latéraux', o: ['Classiques', 'Offensifs', 'Intérieurs'], h: [
        'Restent derrière : solide, mais pas d’homme en plus sur le côté.',
        'Montent sans cesse : deux contre un sur l’aile, mais un gros trou derrière sur les contres.',
        'Rentrent au milieu : un passeur de plus dans l’axe, moins de largeur.',
      ] },
      striker: { t: 'Attaquant', o: ['Avancé', 'Pivot', 'Faux 9', 'Presseur'], h: [
        'Joue sur le dernier défenseur.',
        'Point d’appui pour les centres et les ballons longs. Il faut un attaquant costaud.',
        'Décroche au milieu pour créer le surnombre, mais moins de monde dans la surface.',
        'Mène le pressing devant. Fatigant.',
      ] },
      trap: { t: 'Piège de pressing', o: ['Aucun', 'Côtés', 'Axe', 'Demi-espaces'], h: [
        'Pas de piège.',
        'Poussez-les sur le côté et étouffez-les le long de la ligne. L’axe se libère un peu.',
        'Éloignez-les de l’axe. Les côtés se libèrent un peu.',
        'Pressez un peu partout. Il faut que le pressing soit actif.',
      ] },
      routine: { t: 'Corners', o: ['Variés', 'Les grands montent', 'À deux'], h: [
        'Un peu de tout.',
        'Les centraux montent : plus de têtes, mais moins de défenseurs derrière si ça tourne mal.',
        'Joué à deux : on garde le ballon, moins de tirs sur le corner lui-même.',
      ] },
      counter: { t: 'Contre immédiat', h: 'Partez dès la récupération. Plus de contre-attaques ; le milieu joue un peu plus bas.' },
      waste: { t: 'Gagner du temps', h: 'Ralentissez chaque reprise quand vous menez. Moins d’occasions des deux côtés, et un carton de temps en temps.' },
      mark: { t: 'Marquage individuel', none: 'Personne', h: 'Collez une ombre à leur joueur clé : il gagne bien moins de duels, mais le marqueur laisse un trou.' },
      formation: 'Système',
      on: 'Oui', off: 'Non',
    },
    styleHint: 'Choisir une philosophie règle ces consignes ; ajustez-les ci-dessous.',
    assistantPick: 'Votre adjoint changerait',
    momentum: 'Temps forts',
    territory: 'Territoire',
    xgFrom: 'D’où sont venues les occasions',
    statsMore: ['Grosses occasions', 'Hors-jeu', 'Entrées dans le dernier tiers', 'Ballons récupérés haut'],
    themes: { centre: 'Par l’axe', wide: 'Par les côtés', behind: 'Dans le dos', counter: 'En contre', press: 'Récupération haute', setpiece: 'Coups de pied arrêtés', long: 'De loin', pen: 'Penalties' },
    themeIn: { centre: 'par l’axe', wide: 'par les côtés', behind: 'dans notre dos', counter: 'en contre', press: 'sur récupération haute', setpiece: 'sur coups de pied arrêtés', long: 'de loin', pen: 'sur penalty' },
    goalFlash: 'BUT !',
    soundOn: 'Son activé', soundOff: 'Son coupé',
    whyHT: 'Mi-temps : ce qui se passe',
    whyFT: 'Pourquoi ça s’est terminé ainsi',
    assistant: 'Votre adjoint',
    verdict: {
      deserved: 'On l’a mérité. {xa} xG contre {xb} : le score dit vrai.',
      smash: 'On prend, mais ils ont créé plus ({xb} xG contre {xa}). On a été efficaces au bon moment.',
      robbed: 'On était meilleurs, {xa} xG contre {xb}, et on repart sans rien. Continuez comme ça et les buts viendront.',
      beaten: 'Rien à dire : ils ont créé plus ({xb} xG contre {xa}). Il faut comprendre pourquoi.',
      clinical: 'Implacables : {ga} buts pour {xa} xG.',
      wasteful: 'On a eu les occasions ({xa} xG) sans les mettre.',
      level: 'Rien entre les deux équipes : {xa} xG contre {xb}.',
      even: 'Ils ont eu le dessus ({xb} xG contre {xa}). On ne peut pas se plaindre du score.',
    },
    point: {
      sourceMe: 'Nos meilleures actions sont venues {theme} : {x} xG sur {n} tirs.',
      sourceMe1: 'Nos meilleures actions sont venues {theme} : {x} xG sur un seul tir.',
      sourceThem1: 'L’essentiel de leur danger est venu {theme} : {x} xG sur un seul tir.',
      sourceThem: 'L’essentiel de leur danger est venu {theme} : {x} xG sur {n} tirs.',
      midfieldMe: 'Le milieu est à nous : {x} % de nos actions passent, {y} % des leurs.',
      midfieldThem: 'Ils gagnent le milieu : {y} % de leurs actions passent, seulement {x} % des nôtres.',
      pressed: 'Leur pressing nous fait mal : {n} ballons perdus dans notre tiers.',
      pressedXg: 'Leur pressing nous fait mal : {n} ballons perdus dans notre tiers, {x} xG directement sur nos erreurs.',
      pressing: 'Notre pressing marche : {n} ballons récupérés haut.',
      duelMeWin: '{a} martyrise {d} : {n} duels gagnés sur {of}.',
      duelMeLose: '{d} a {a} dans sa poche : {n} sur {of} pour le défenseur.',
      duelThemWin: '{a} prend le dessus sur {d} : {n} duels sur {of}.',
      duelThemLose: '{d} a éteint {a} : {n} sur {of} gagnés.',
      finishMeGood: 'Implacables : {n} buts pour {x} xG.',
      finishMeBad: 'On gâche : {n} pour {x} xG.',
      finishThemGood: 'Ils ont beaucoup gâché : {n} pour {x} xG. Ne comptez pas là-dessus deux fois.',
      finishThemBad: 'Ils nous punissent : {n} buts pour seulement {x} xG.',
      keeperMe: '{a} nous maintient en vie : {n} arrêts, {x} xG sauvés.',
      keeperThem: 'Leur gardien {a} est dans un grand jour : {n} arrêts.',
      tiredMe: 'Plus de jambes : {n} % de forme en fin de match, eux {y} %.',
      tiredThem: 'Leurs jambes ont lâché ({n} % de forme) et c’est là qu’on a frappé.',
      redMe: 'Le rouge de {a} à la {min}e a tout changé.',
      redThem: 'Leur carton rouge à la {min}e a ouvert le match.',
      changeGood: 'Le changement de la {min}e ({what}) a marché : notre xG est passé de {x} à {y} par 90.',
      changeBad: 'Le changement de la {min}e ({what}) n’a pas marché : xG {x} → {y} par 90.',
      theyChanged: 'Leur banc a réagi à la {min}e : {what}.',
    },
    tipsHT: 'Ce que je changerais',
    tipsFT: 'La prochaine fois contre eux',
    tipWhy: {
      centreMe: 'plus d’occasions dans l’axe', wideMe: 'plus de jeu sur les côtés', wideMeAD: '{a} peut déborder {d} sur son côté',
      behindMe: 'plus de ballons dans le dos', behindMeAD: '{a} peut partir dans le dos de {d}', counterMe: 'plus de contres', counterMeA: 'plus de contres pour {a}',
      pressMe: 'on récupère plus souvent haut', setpieceMe: 'plus de danger sur coups de pied arrêtés', longMe: 'plus de tirs de loin', penMe: 'plus de penalties obtenus',
      centreThem: 'moins d’occasions pour eux dans l’axe', wideThem: 'moins de centres contre nous', wideThemA: 'éteint {a} sur son côté',
      behindThem: 'personne dans notre dos', behindThemA: 'stoppe les appels de {a} dans notre dos', counterThem: 'coupe leurs contres', counterThemA: 'stoppe {a} en contre',
      pressThem: 'nous sort de leur pressing', setpieceThem: 'moins de coups de pied arrêtés contre nous', longThem: 'moins de tirs de loin contre nous', penThem: 'moins de penalties concédés',
    },
    winChance: 'Chances de victoire {w0} % → {w1} %',
    apply: 'Faire le changement',
    applied: 'Changement fait',
    noTips: 'Je ne toucherais à rien.',
    shape: (f: string) => `Système ${f}`,
    reason: { chase: 'pour revenir au score', protect: 'pour garder l’avance', red: 'après le rouge', tenmen: 'contre dix', tip: '', read: 'après lecture de la première période', prep: 'face à cet adversaire', wx3: 'à cause du vent', wx4: 'à cause de la chaleur' },
    changeLine: '{c} : {what}{why}.',
    talkLine: 'Causerie de {c} à la pause : « {what} ».',
    c: {
      box: ['{a} glisse le ballon à {s}', 'un une-deux à l’entrée de la surface libère {s}', '{s} trouve un demi-mètre dans une surface bondée', '{s} se retourne vite dans la surface', 'des passes rapides dans l’axe ouvrent la voie à {s}'],
      cutback: ['{s} reprend un centre en retrait', '{a} arrive au bout et remet en retrait pour {s}', '{a} élimine {d} et remet à {s}', 'un centre en retrait de {a} pour {s}'],
      header: ['{s} s’élève sur un centre', '{s} place une tête sur un centre venu du côté', '{a} envoie un centre et {s} s’élève', '{s} attaque le centre de {a}', 'long centre de {a}, reprise de {s}'],
      through: ['{a} transperce la défense et {s} est seul', '{s} casse la ligne sur la passe de {a}', 'un ballon par-dessus et {s} s’échappe'],
      counter: ['{s} part à toute vitesse après la récupération', 'un contre éclair se termine par {s}', 'trois passes et {s} fonce vers le but'],
      press: ['{s} intercepte une passe haute', 'le pressing provoque l’erreur et {s} s’infiltre', '{s} vole le dernier défenseur et file au but'],
      long: ['{s} tente sa chance de 25 mètres', '{s} frappe de loin', 'le ballon arrive à {s} hors de la surface'],
      corner: ['{s} s’élève plus haut que tout le monde sur le corner de {a}', 'corner de {a}, tête de {s}', '{s} dévie au premier poteau'],
      set: ['le coup franc de {a} est repris par {s}', '{s} est au rendez-vous sur le coup de pied arrêté'],
      fk: ['{s} enroule le coup franc au-dessus du mur', '{s} s’élance pour le coup franc'],
      pen: ['{s} s’avance pour le penalty', '{s} pose le ballon sur le point, face à {k}'],
      goal: ['et marque !', 'BUT ! Dans la lucarne.', 'et fusille le gardien !', 'et ça rentre !', 'poteau rentrant !', 'sans trembler. BUT !', 'et les filets tremblent !'],
      save: ['mais {k} arrête.', 'mais {k} se couche bien.', '{k} détourne en corner.', 'droit sur {k}.', '{k} reste debout et repousse.'],
      miss: ['mais c’est au-dessus.', 'juste à côté.', 'ça part de travers.', 'non cadré.', 'au-dessus de la barre.'],
      block: ['contré par {b} !', '{b} se jette et bloque.', 'repoussé.'],
      after: {
        lead: ['{c} prend l’avantage !', '{c} mène !'], equal: ['C’est l’égalisation !', 'Tout est à refaire !'], more: ['{c} creuse l’écart.', 'Ça devrait être plié.'],
        late: ['Un but au bout du bout !', 'Drame dans les dernières secondes !'], brace: ['Doublé pour {s}.'], hat: ['Triplé pour {s} !'], back: ['{c} réduit l’écart.', 'Le match est relancé !'],
      },
      yellow: ['{s} est averti.', 'Carton jaune pour {s}.', 'L’arbitre avertit {s}.'],
      yellowWaste: ['{s} est averti pour gain de temps.'],
      red: ['CARTON ROUGE ! {s} est expulsé.', '{s} dehors ! Réduits à dix.'],
      injury: ['{s} est au sol et ne peut pas continuer.', 'Mauvaise nouvelle : {s} est blessé.'],
      sub: ['Changement pour {c} : {a} entre, {s} sort.', '{a} remplace {s}.', 'Du sang neuf : {a} pour {s}.'],
      offside: ['{s} est signalé hors-jeu.', 'Le drapeau se lève contre {s}.'],
      corner2: ['Corner pour {c}.'],
      flow: {
        camp: ['{c} s’installe dans le dernier tiers.', '{c} les tient à la gorge.', 'Vague après vague de {c}.'],
        press: ['{c} chasse le ballon très haut.', 'Le pressing de {c} étouffe.'],
        calm: ['Période plus calme : les deux équipes s’observent.', 'Jeu patient au milieu.'],
      },
    },
  },
};
