// V2.6 Training & pathway, Arabic (Egyptian colloquial). Type-checked against lang-youth.ts.
import type { YStrings } from './lang-youth';

const TIERS = ['كويس', 'واعد', 'مبشّر جدًا', 'موهبة استثنائية'];

export const Y_AR: YStrings = {
  doors: { train: 'أسبوع التمرين', medical: 'العيادة', academy: 'الأكاديمية' },
  bands: ['قليل', 'عالي شوية', 'عالي'],
  intens: ['خفيف', 'عادي', 'تقيل'],
  tiers: ['كويس', 'واعد', 'مبشّر جدًا', 'موهبة استثنائية'],

  tw: {
    title: 'أسبوع التمرين',
    head: (i: number, focus: string, plans: number): string => `أسبوع ${['خفيف', 'عادي', 'تقيل'][i]}، والتركيز على ${focus}. ${plans === 1 ? 'لاعب واحد عنده شغل زيادة.' : plans ? `${plans} لاعيبة عندهم شغل زيادة.` : 'مفيش حد عنده شغل زيادة.'}`,
    intensity: 'شدة التمرين',
    intFx: ['التطور ×0.7. الرجلين بترتاح أسرع.', 'التطور ×1.0. أسبوع عادي.', 'التطور ×1.4. الحِمل +4 كل يوم، والإصابات الخفيفة واردة.'],
    congested: 'عندنا ماتشين الأسبوع ده: التمرين التقيل ممنوع.',
    dropped: 'لغينا التمرين التقيل الأسبوع اللي فات: كان عندنا ماتشين.',
    focus: 'تركيز الأسبوع',
    load: 'الحِمل',
    loadSub: 'مين يقدر يلعب تسعين دقيقة كمان',
    loadHidden: 'مدرب لياقة تقييمه 60 أو أكتر هيديك الأرقام بالظبط.',
    loadN: (n: number): string => `الحِمل ${n}`,
    fragile: (n: number): string => `لسه هش · ${n} ماتش`,
    riskX: (x: string): string => `خطر الإصابة ×${x}`,
    allFresh: 'الكل جاهز يلعب تاني.',
    plans: 'برامج فردية',
    plansN: (n: number, max: number): string => `${n} من ${max}`,
    plansNone: 'مفيش حد عنده شغل زيادة. ممكن لحد خمس لاعيبة.',
    plansFull: 'خمسة بس الحد الأقصى. شيل حد الأول.',
    add: 'زوّد برنامج',
    who: 'اللاعب',
    attr: 'يقوّي مهارة',
    pos: 'يتعلم مركز جديد',
    attrFx: 'التطور +10%، والنقطة الزيادة بتروح للمهارة دي، والحِمل +2 كل يوم.',
    posFx: 'حوالي 11 جولة شغل زيادة. التطور −10% في الفترة دي.',
    learning: (pos: string, pct: number): string => `بيتعلم ${pos} · ${pct}%`,
    sharpening: (a: string): string => `بيقوّي ${a}`,
    also: (pos: string): string => `بيلعب كمان ${pos}`,
    remove: 'شيله',
    save: 'ابدأ البرنامج',
    report: 'الأسبوع اللي فات',
    up: (n: number): string => (n ? `${n} لاعيبة اتطوروا` : 'محدش اتطور'),
    near: 'قربوا من الخطوة الجاية',
    knocks: (n: number): string => `${n} خدوا خبطة`,
    academyUp: (n: number): string => `${n} من الأكاديمية اتطوروا`,
    quiet: 'مفيش حاجة اتحركت الأسبوع ده. هتتحرك.',
  },

  md: {
    title: 'العيادة',
    head: (out: number, edge: number): string => (out || edge ? `${out} مصابين، و${edge} على الحافة.` : 'الكل سليم.'),
    out: 'غرفة العلاج',
    back: (lo: number, hi: number): string => (lo === hi ? `راجع بعد ${lo} جولة` : `راجع بعد ${lo}–${hi} جولات`),
    orig: (n: number): string => `كان هيغيب ${n} جولات وقت الإصابة`,
    fog: (who: string): string => `ده تقدير ${who}. دكتور أحسن يضيّق المدة.`,
    fogNone: 'مفيش دكتور في النادي: ده تخمين.',
    rush: 'رجّعه بدري',
    rushFx: (gain: number, risk: number): string => `أسرع بـ${gain} جولة · ${risk}% يتصاب تاني`,
    rushNotYet: (n: number): string => `ينفع ترجّعه بدري لما يفضل ${n} جولات`,
    edge: 'على الحافة',
    edgeSub: 'حِمل عالي أو لسه هش',
    thisMatch: (n: number): string => `~${n}% الماتش ده`,
    none: 'محدش على سرير العلاج.',
    noEdge: 'محدش شايل أكتر من طاقته. كمّل تدوير.',
    rest: 'ريّحه',
    unrest: 'نزّله تاني',
  },

  ac: {
    title: 'الأكاديمية والطريق للفريق الأول',
    head: (n: number, loans: number, grads: number): string => `${n} في الأكاديمية، ${loans} معارين، ${grads} في الفريق الأول.`,
    countdown: (n: number): string => `يوم الدفعة الجديدة بعد ${n} جولة`,
    countdownSub: 'مدير الناشئين لسه ما شافش دفعة السنة دي.',
    preview: (tier: string, pos: string): string => `${pos} ${tier} في دفعة السنة دي`,
    previewSub: (n: number): string => `يوم الدفعة الجديدة بعد ${n} جولة. مدير الناشئين شافهم.`,
    arrived: (n: number): string => `يوم الدفعة الجديدة. ${n} وشوش جديدة.`,
    classOf: (y: string): string => `دفعة ${y}`,
    reveal: 'اتعرّف عليهم',
    standout: 'الأبرز',
    nextYear: 'يوم الدفعة الجديدة الجاي الموسم الجاي.',
    cap: (n: number, cap: number): string => `${n} من ${cap} مكان`,
    over: 'الأكاديمية فوق طاقتها: كل عيل بيتطور أبطأ 15%.',
    squad: 'الأكاديمية',
    empty: 'الأكاديمية فاضية لحد يوم الدفعة الجديدة.',
    ready: 'جاهز',
    late: 'الوقت بيخلص',
    grown: (n: number): string => (n > 0 ? `+${n} الموسم ده` : n < 0 ? `${n} الموسم ده` : 'زي ما هو الموسم ده'),
    promote: 'صعّده',
    loan: 'إعارة',
    release: 'استغنى عنه',
    word: 'كلمة معاه',
    recall: 'رجّعه',
    loanTitle: (pn: string): string => `${pn} يلعب فين؟`,
    loanSub: 'نادي يلعّبه أساسي يديله دقايق بجد، والدقايق هي اللي بتكبّره.',
    roles: ['هيلعب أساسي', 'بالتبادل', 'غالبًا دكة'],
    windowShut: 'الميركاتو مقفول. الإعارات بتتعمل في الصيف ونص الموسم.',
    tooYoung: 'صغير على الإعارة (17 سنة وأكتر).',
    noSpots: 'مفيش نادي في مستواه عايزه لسه.',
    releaseQ: (pn: string): string => `تستغنى عن ${pn}؟ هيبقى لاعب حر وأي نادي يقدر يمضيله.`,
    loans: 'معارين',
    loansNone: 'مفيش حد معار. في الميركاتو ابعت اللي عليهم الدور لنادي يلعّبهم.',
    mins: (n: number): string => `${n} دقيقة الموسم ده`,
    run: (n: number): string => `${n} ماتشات كاملة ورا بعض`,
    grads: 'خريجين',
    gradsNone: 'مفيش ابن النادي في الفريق الأول لسه.',
    since: (from: number, now: number): string => `${from} ← ${now}`,
    apps: (n: number): string => `${n} ماتش`,
    path: ['الأكاديمية', 'معار', 'الفريق الأول'],
  },

  cv: {
    real: 'التاريخ الحقيقي',
    proj: 'رايح فين',
    avg: 'متوسط التشكيلة',
    starts: (s: string): string => `التاريخ من ${s}`,
    one: 'التاريخ بيبدأ من هنا: كل جولة من دلوقتي متسجلة.',
    academy: 'أكاديمية',
    homegrown: 'ابن النادي',
    load: 'الحِمل',
    minutes: (n: number): string => `${n} دقيقة الموسم ده`,
  },

  tag: { risk: 'طبي', rush: 'طبي', intake: 'يوم الدفعة الجديدة', ready: 'الأكاديمية', loanee: 'تقرير إعارة', benched: 'تقرير إعارة', full: 'الأكاديمية', ageout: 'الأكاديمية' },
  titles: {
    y_risk: (pn: string, n: number): string => `${pn} يقدر يلعب، بس حِمله ${n}`,
    y_fragile: (pn: string, n: number): string => `${pn} رجع بدري ولسه هش (${n} ماتشات كمان)`,
    y_rush: (pn: string, n: number): string => `${pn} ممكن يرجع بدري (فاضل ${n} جولات)`,
    y_intake: (n: number): string => `يوم الدفعة الجديدة: ${n} وشوش جديدة`,
    y_ready: (pn: string, n: number): string => `${pn} بيخبط على الباب بتقييم ${n}`,
    y_loanee: (pn: string, n: number, club: string): string => `${pn}: ${n} ماتشات كاملة ورا بعض مع ${club}`,
    y_benched: (pn: string, club: string): string => `${pn} مش بيلعب في ${club}`,
    y_full: (n: number, cap: string): string => `الأكاديمية فيها ${n} عيل لـ${cap} مكان`,
    y_ageout: (pn: string, n: number): string => `${pn} عنده ${n} سنة ولسه في الأكاديمية`,
    ask_y_rush: (pn: string): string => `نرجّع ${pn} بدري؟`,
    ask_y_rest: (pn: string): string => `نريّح ${pn} الماتش الجاي؟`,
    ask_y_loan: (pn: string, club: string): string => `نعير ${pn} لـ${club}؟`,
    ask_y_release: (pn: string): string => `نستغنى عن ${pn} من الأكاديمية؟`,
  },
  advice: {
    y_risk_rest: (_pn: string, n: number, sub: string): string => `يقدر يلعب، ويقدر برضه يشد عضلة: حوالي ${n}% النهارده. ${sub ? `${sub} فريش. ` : ''}أنا أريّحه.`,
    y_risk_rest_c: (pn: string, _n: number, sub: string): string => `مش برجلين زي دي. ${pn} يقعد الماتش ده${sub ? `، و${sub} ينزل` : ''}.`,
    y_risk_play: (_pn: string, n: number): string => `شايل كتير، بس ${n}% مخاطرة أقبلها. نزّله وطلّعه بدري.`,
    y_risk_play_b: (_pn: string, n: number): string => `${n}%؟ دي كورة. نزّله.`,
    y_risk_rr: (pn: string, n: number): string => `رجّعنا ${pn} بدري. حوالي ${n}% يتصاب تاني النهارده. أنا أبعده عن الماتش ده.`,
    y_rush_yes: (_pn: string, n: number): string => `عدّى نص المدة. لو ضغطنا يرجع أسرع. فيه ${n}% يتصاب تاني في التلات ماتشات الجايين. أنا موافق.`,
    y_rush_no: (_pn: string, n: number): string => `أقدر أرجّعه أسرع، بس فيه ${n}% يتصاب تاني ولمدة أطول. سيبه يخف.`,
    y_intake: (pn: string, pos: string, n: number): string => `كلهم وصلوا. خلّي عينك على ${pn}: ${pos} ${TIERS[n] ?? 'واعد'}. فيه مكان للكل.`,
    y_intake_full: (pn: string, pos: string, n: number): string => `${pn} هو اللي فيهم: ${pos} ${TIERS[n] ?? 'واعد'}. بس إحنا فوق الطاقة. لو خلّينا الكل، الكل هيتعلم أبطأ.`,
    y_ready: (pn: string, n: number): string => `${pn} بقى في مستوى اللاعب رقم 18 عندنا (${n}). التمرين مع الفريق الأول هيكمّله.`,
    y_ready_v: (pn: string): string => `${pn} قرّب. بس أنا أفضّل يلعب كورة رجالة في حتة الأول.`,
    y_loanee: (pn: string): string => `${pn} بيلعب كل أسبوع. لسه ما طلعش لفوق، بس الدقايق دي هي اللي بتكبّر اللاعب.`,
    y_loanee_up: (pn: string, n: number, s: string): string => `${pn} لعب ${s} دقيقة واتطور ${n} الموسم ده. سيبه هناك.`,
    y_benched: (pn: string, n: number): string => `${pn} لعب ${n} دقيقة بس. وعدونا يلعّبوه. رجّعه ودوّرله على نادي يلعّبه.`,
    y_full: (pn: string, n: number): string => `عيال كتير وتدريب مش مكفّي. ${pn} هو اللي أستغنى عنه: سقفه حوالي ${n}.`,
    y_ageout_keep: (pn: string, n: number): string => `${pn} لسه فيه حاجة، يمكن يوصل ${n}. اديله رقم في الفريق أو إعارة.`,
    y_ageout_go: (pn: string): string => `${pn} مش هينجح هنا. سيبه يدوّر على نادي.`,
    why_y_rush: (pn: string, n: number): string => `${pn} عدّى نص المدة. ${n}% مخاطرة، ومحتاجينه.`,
    why_y_rest: (pn: string, n: number): string => `رجلين ${pn} تقيلة. حوالي ${n}% يشد عضلة.`,
    why_y_loan: (pn: string): string => `${pn} محتاج يلعب كورة رجالة. هناك هيلعب أساسي.`,
    why_y_release: (pn: string): string => `إحنا فوق الطاقة و${pn} أقل واحد فرصته إنه ينجح.`,
  },
  choices: {
    y_ch_rush: (n: number): string => `رجّعه بدري (أسرع بـ${n})`,
    y_ch_heal: (): string => 'سيبه يخف',
    y_ch_spec: (v: string): string => `أخصائي (${v})`,
    y_ch_keepAll: (): string => 'خلّيهم كلهم',
    y_ch_trim: (n: number): string => (n === 1 ? 'استغنى عن الأضعف' : `استغنى عن أضعف ${n}`),
    y_ch_promote: (): string => 'صعّده',
    y_ch_loan: (club: string): string => `عيره لـ${club}`,
    y_ch_leave: (): string => 'سيبه هناك',
    y_ch_word: (): string => 'قوله إننا متابعينه',
    y_ch_recall: (): string => 'رجّعه',
    y_ch_release: (pn: string): string => `استغنى عن ${pn}`,
  },
  fx: {
    y_fx_safe: (): string => 'مفيش مخاطرة النهارده',
    y_fx_risk: (n: number): string => `خطر إصابة ~${n}%`,
    y_fx_fragile: (n: number): string => `هش لـ${n} ماتشات كمان`,
    y_fx_sooner: (n: number): string => `يرجع أسرع بـ${n}`,
    y_fx_relapse: (n: number): string => `${n}% يتصاب تاني`,
    y_fx_heal: (n: number): string => `غايب ${n} كمان`,
    y_fx_room: (n: number, cap: string): string => `${n} من ${cap} مكان`,
    y_fx_spread: (n: number, cap: string): string => `${n} لـ${cap}: تطور أبطأ`,
    y_fx_letGo: (n: number): string => `${n} للاعيبة الأحرار`,
    y_fx_squad: (): string => 'قايمة الفريق الأول',
    y_fx_proWage: (): string => 'مرتب محترف',
    y_fx_starter: (): string => 'هيلعب أساسي هناك',
    y_fx_rotation: (): string => 'بالتبادل هناك',
    y_fx_academyPace: (): string => 'بسرعة الأكاديمية',
    y_fx_growing: (n: number): string => (n > 0 ? `+${n} الموسم ده` : 'دقايق في الرصيد'),
    y_fx_morale: (): string => 'الروح المعنوية تعلى',
    y_fx_home: (): string => 'هيخسر دقايقه',
    y_fx_reloan: (): string => 'نعيره تاني',
    y_fx_stall: (): string => 'تطوره يقف',
    y_fx_focus: (): string => 'تدريب أحسن للباقيين',
    y_fx_free: (): string => 'لاعب حر',
  },

  news: {
    y_preview: (club: string, pos: string, tier: string): [string, string] => [`كلام في أكاديمية ${club} عن ${pos} ${tier}`, 'مدير الناشئين شاف دفعة السنة دي. يوم الدفعة الجديدة بعد عشر جولات.'],
    y_intake: (club: string, n: number, pn: string, pos: string): [string, string] => [`يوم الدفعة الجديدة في ${club}: ${n} وشوش جديدة`, pn ? `اللي الكل كان بيتفرج عليه: ${pn}، ${pos}.` : 'دفعة جديدة بتبدأ النهارده.'],
    y_rivalGem: (club: string, pn: string, pos: string, tier: string): [string, string] => [`${club} بيقدّم ${pos} ${tier}`, `${pn} انضم لأكاديميتهم. افتكر الاسم ده.`],
    y_breakthrough: (pn: string, club: string, n: string): [string, string] => [`${pn} (${n} سنة) بقى أساسي في ${club}`, 'عشر ماتشات في الدوري الموسم ده لخريج الأكاديمية.'],
    y_loaned: (pn: string, club: string): [string, string] => [`${pn} ينضم لـ${club} على سبيل الإعارة`, 'ابن الأكاديمية رايح يلعب.'],
  },
  msg: {
    y_preview: (pn: string, pos: string, tier: string): [string, string] => [`مدير الناشئين: ${pos} ${tier} في دفعة السنة دي`, `شفت الدفعة الجديدة. خلّي عينك على ${pn}. يوم الدفعة الجديدة بعد عشر جولات.`],
    y_learned: (pn: string, pos: string): [string, string] => [`${pn} بقى يلعب ${pos}`, 'الشغل الزيادة جاب نتيجة. اختيار التشكيلة هيستخدمه في المركز ده.'],
    y_reinjured: (pn: string, n: number): [string, string] => [`${pn} اتصاب تاني`, `رجّعناه بدري. هيغيب ${n} جولات كمان.`],
    y_loanReport: (pn: string, n: number, s: string, club: string): [string, string] => [`تقرير إعارة: ${pn} في ${club}`, `${n} دقيقة الموسم ده، ${Number(s) > 0 ? `اتطور ${s}` : Number(s) < 0 ? `نزل ${-Number(s)}` : 'زي ما هو'} من الصيف.`],
    y_devGone: (n: number): [string, string] => ['نقط التطوير اتلغت', `الـ${n} نقطة اللي كانت فاضلة راحت لمعنويات الفريق (+5). اللاعيبة بتتطور في التمرين وبالدقايق دلوقتي.`],
  },
  log: {
    'medical:y_rush': (pn: string, n: number): string => `رجّع ${pn} بدري (${n}% يتصاب تاني)`,
    'medical:y_rest': (pn: string, n: number): string => `ريّح ${pn}: ~${n}% خطر إصابة`,
    'academy:y_loan': (pn: string, club: string): string => `عار ${pn} لـ${club}`,
    'academy:y_release': (pn: string): string => `استغنى عن ${pn} من الأكاديمية`,
    'academy:promote': (pn: string): string => `صعّد ${pn} للفريق الأول`,
  },
  note: { rushed: 'رجع للتمرين.', promoted: 'خد تيشيرت الفريق الأول.' },
  no: {
    congested: 'عندنا ماتشين الأسبوع ده: مفيش تمرين تقيل.', plans: 'خمس برامج بس الحد الأقصى.', notYet: 'بدري قوي نضغط عليه.', retired: 'دي اتلغت: يوم الدفعة الجديدة بدالها.',
    young: 'صغير على كده.', pos: 'اختار مركز مش بيلعبه أصلًا.', load: 'اختار خفيف أو عادي أو تقيل.', unknown: 'دي مبقتش موجودة.',
  },
};
