// Copy for The Gaffer v2 (connected core). English is the reference; Arabic (Egyptian), Spanish and French are
// type-checked against it in lang-v2-*.ts. Voice: the dugout, not an app. No "Welcome back", no "Unlock", no "Oops",
// no exclamation marks. The answer goes in the headline, the evidence underneath.
import type { Bias, Dept, DeptLevel, PrepFocus } from './model/types';
import type { Philosophy } from './sim/tactics';

const P = (n: number, one: string, many: string) => (n === 1 ? one : many);
const WORDS = ['Nothing', 'One thing', 'Two things', 'Three things', 'Four things', 'Five things'];

export const X_EN = {
  // ---------- navigation ----------
  nav: { today: 'Today', squad: 'Squad', match: 'Match', transfers: 'Transfers', club: 'Club', career: 'Career', pass: 'Club Pass' },
  back: 'Back',
  close: 'Close',
  cont: 'Continue',
  open: (n: number): string => (n ? `· ${n} open` : '· all clear'),
  wk: (season: string, n: number): string => `${season} · Wk ${n}`,
  seasonLabel: (y: number): string => `${y}/${String((y + 1) % 100).padStart(2, '0')}`,
  place: (n: number): string => `${n}${n % 10 === 1 && n % 100 !== 11 ? 'st' : n % 10 === 2 && n % 100 !== 12 ? 'nd' : n % 10 === 3 && n % 100 !== 13 ? 'rd' : 'th'}`,
  wdl: ['W', 'D', 'L'] as [string, string, string],
  saved: 'Saved',
  notNowShort: 'Not now',

  // ---------- title and new career ----------
  title: {
    tag: 'Run the club. Own the dugout.',
    season: 'The 2026/27 season',
    lead: 'Every Premier League, La Liga, Serie A, Bundesliga and Ligue 1 squad as it stands after the summer window, plus the big six of Egypt and Saudi Arabia. Real names. Our own ratings.',
    newCareer: 'Start a 2026/27 career',
    newSub: 'Pick a club. The board will tell you what they expect.',
    slots: 'Your careers',
    slot: (n: number): string => `Slot ${n}`,
    empty: 'Empty slot',
    cont: 'Continue',
    oldWorld: 'Old world · fictional names',
    oldTitle: 'Your career from before the rebuild',
    oldBody: 'It was played in the old generated world, so it keeps its fictional names and clubs. Nothing is lost: carry on with it, or start a 2026/27 career in the other slot.',
    contOld: 'Continue old career',
    startNew: 'Start a new 2026/27 career',
    full: 'Both slots are taken. Pick one to replace.',
    replace: 'Replace this career',
    replaceAsk: (club: string): string => `Replace your ${club} career?`,
    replaceBody: 'That career is deleted from this device. Export it first from Settings if you might want it back.',
    cancel: 'Keep it',
    quick: 'Quick match',
    quickSub: 'Any two clubs, one game, nothing counts.',
    foot: 'Unofficial game. Real club and player names are used as facts only; crests and kits are our own drawings; ratings are The Gaffer\'s own judgement, not anyone else\'s. Not affiliated with any club, league or player.',
    badSave: 'A save on this device failed its check and was left alone. Your other slot is fine.',
    loading: 'Opening the office…',
    matchday: (n: number): string => `Matchday ${n}`,
  },
  pick: {
    league: 'Where do you want to work?',
    leagueSub: 'Seven leagues with real 2026/27 squads. The rest of the pyramid is there to play against.',
    covered: 'Real squads',
    generated: 'Generated squads',
    club: 'Pick your club',
    clubSub: 'Big clubs expect trophies. Small clubs give you time.',
    search: 'Find a club',
    strength: 'Squad',
    budget: 'Budget',
    expects: 'The board expects',
    job: 'The job',
    you: 'You',
    name: 'Your name',
    nameDefault: 'The Gaffer',
    age: 'Age',
    ageRule: 'Between 20 and 80.',
    nation: 'Nationality',
    sign: 'Sign the contract',
    signSub: (club: string): string => `${club} is waiting.`,
    slotNote: (n: number): string => `Saves to slot ${n}.`,
    tiers: ['Top flight', 'Second tier'],
    stars: 'Best players',
    clubs: (n: number): string => `${n} clubs`,
  },

  // ---------- Today ----------
  today: {
    eyebrow: (md: string, opp: string, days: string): string => `${md} · ${opp} ${days}`,
    inDays: (n: number): string => (n <= 0 ? 'today' : n === 1 ? 'tomorrow' : `in ${n} days`),
    head: (n: number, day: string) => (n === 0 ? ['Nothing on your desk.', ` ${day}’s all that matters.`, ''] : [`${WORDS[Math.min(5, n)]} `, P(n, 'needs you', 'need you'), ` before ${day}.`]) as [string, string, string],
    headCup: (n: number) => (n === 0 ? ['Cup night.', ' Nothing else needs you.', ''] : [`${WORDS[Math.min(5, n)]} `, P(n, 'needs you', 'need you'), ' before the cup tie.']) as [string, string, string],
    seasonDone: ['Season’s done.', ' Time to see how it ends.', ''] as [string, string, string],
    sacked: ['The board has let you go.', ' The phone is still ringing.', ''] as [string, string, string],
    week: 'The weeks ahead',
    more: (n: number): string => `+${n} more on the desk`,
    fewer: 'Show fewer',
    nothing: 'Nothing else needs you. Staff have the rest.',
    nothingSub: (list: string): string => (list ? `${list} run themselves` : 'Every department waits for you'),
    review: 'Review',
    staffDid: (n: number): string => (n ? `Staff made ${n} ${P(n, 'call', 'calls')} since the last match` : 'Staff made no calls since the last match'),
    fit: (day: string): string => `Fit for ${day}`,
    fitOf: (a: number, b: number): string => `${a} of ${b}`,
    allFit: 'Everyone’s available. Pick from the whole squad.',
    doubt: 'Doubt', banned: 'Banned', injured: (n: number): string => `Out ${n} ${P(n, 'wk', 'wks')}`, tired: (n: number): string => `${n}% fit`,
    pulse: 'Club pulse', office: 'Office',
    board: 'Board', fans: 'Fans', room: 'Dressing room',
    mood: (v: number): string => (v >= 75 ? 'Delighted' : v >= 60 ? 'Confident' : v >= 45 ? 'Watching' : v >= 30 ? 'Restless' : 'Losing patience'),
    fansMood: (v: number): string => (v >= 80 ? 'Buzzing' : v >= 60 ? 'Behind you' : v >= 40 ? 'Muttering' : 'Turning'),
    roomMood: (v: number): string => (v >= 75 ? 'Flying' : v >= 62 ? 'Settled' : v >= 50 ? 'Restless' : 'Flat'),
    boardWhy: (obj: string, pos: string): string => `${pos} now. They want ${obj}.`,
    fansWhy: (res: string): string => res,
    roomWhy: (low: string | null): string => (low ? `${low} is the one to watch` : 'Nobody sulking this week'),
    table: 'The table', after: (n: number): string => `After ${n}`, next: 'Next',
    headlines: 'Headlines', allNews: 'All news',
    lastResult: 'Last time out',
    home: 'Home', away: 'Away', at: (v: string): string => v,
    ourGround: 'Our ground', theirGround: 'Away day',
  },
  fixture: {
    comp: (c: string, md: string): string => `${c} · ${md}`,
    win: 'Win', draw: 'Draw', loss: 'Loss',
    pick: 'Pick the XI', report: 'Report', getReport: 'Get the report',
    assistant: 'Assistant', analyst: 'Analyst',
    advice: {
      scoutFirst: 'We haven’t watched them yet. Give me the week on the tape and I’ll tell you where to hurt them.',
      mismatch: (ph: string): string => `They’re set up to beat how we play. Switch to ${ph} and we’re the ones asking questions.`,
      edge: 'We’ve got the right plan for them. Keep it, and keep the legs fresh.',
      lowMastery: (n: number): string => `The lads only know this plan at ${n}%. Another week on the training ground or something they know.`,
      tired: (n: number): string => `${n} starters are running on fumes. Rotate or we’ll be chasing shadows by the hour.`,
      outOfPos: (n: number): string => `${n} ${P(n, 'player is', 'players are')} out of position in the XI. It’ll cost us.`,
      underdog: 'They’re better than us on paper. Sit a little deeper and make them come onto us.',
      trap: 'Set the press to trap them where they like to play. The report says it hurts them.',
      fine: 'Nothing jumps out. Same again, and make sure we start fast.',
    },
  },
  dec: {
    due: { kickoff: 'Before kick-off', days: (n: number): string => (n <= 1 ? 'Today' : `${n} days left`), week: 'This week', season: 'Before summer', window: 'Window shuts tonight' } as Record<string, string | ((n: number) => string)>,
    tag: { welcome: 'First day', offer: 'Transfer bid', condition: 'Fitness', contract: 'Contract', staff: 'Staff call', job: 'Job offer', tape: 'Analysis', focus: 'Training week', deadline: 'Deadline day' } as Record<string, string>,
    staffPick: 'Staff pick',
    yourCall: 'Your call. Nobody else’s.',
    done: (label: string): string => `Done: ${label}`,
    undo: 'Undo',
    swipe: 'Swipe right to take the staff pick',
    open: 'Open',
    titles: {
      offer: (club: string, fee: string, pn: string): string => `${club} bid ${fee} for ${pn}`,
      tired: (pn: string, n: number): string => `${pn} is running on ${n}%`,
      expiring: (pn: string, y: number): string => `${pn}’s deal ends in ${y}`,
      job: (club: string): string => `${club} want to talk to you`,
      tape: (club: string): string => `${club} are on the tape`,
      focus: (): string => 'Change this week’s training focus?',
      deadline: (g: string): string => `Deadline day and we’re short at ${g}`,
      ask_signed: (pn: string, fee: string): string => `Sign ${pn} for ${fee}?`,
      ask_renewed: (pn: string, years: number): string => `Give ${pn} ${years} more ${P(years, 'year', 'years')}?`,
      ask_listed: (pn: string): string => `Put ${pn} on the transfer list?`,
      ask_out: (pn: string, club: string): string => `Loan ${pn} to ${club}?`,
      ask_sold: (pn: string): string => `Sell ${pn}’s academy rights?`,
      ask_rejected: (pn: string): string => `Turn down the bid for ${pn}?`,
      ask_load: (load: string): string => `Training to ${load} this week?`,
      ask_focus: (f: string): string => `Make it a ${f} week?`,
      ask_rehab: (pn: string): string => `Pay for ${pn}’s rehab?`,
      ask_talk: (): string => 'Call the squad together for a talk?',
      ask_promote: (pn: string): string => `Promote ${pn} from the academy?`,
      ask_scouted: (): string => 'Run an academy trial day?',
      ask_plan: (ph: string): string => `Switch to ${ph} for the next match?`,
      ask_formation: (f: string): string => `Change the shape to ${f}?`,
      ask_mentality: (): string => 'Change our approach for the next match?',
      ask_price: (s: string): string => `Move ticket prices to ${s}?`,
      ask_report: (): string => 'The analyst has a report ready',
      welcome: (): string => 'How do you want to run this place?',
    } as Record<string, (...a: any[]) => string>,
    advice: {
      offer_accept: (pn: string, v: string): string => `That’s over what he’s worth to us. ${pn}’s valued at ${v}. Take it.`,
      offer_counter: (_pn: string, v: string): string => `Close, but not there. He’s worth ${v}. Push them and see if they blink.`,
      offer_reject: (pn: string, v: string): string => `Not even close for a player like ${pn}. He’s worth ${v}. Tell them no.`,
      offer_accept_money: (pn: string): string => `Money like that doesn’t come round often. I’d cash in on ${pn}.`,
      offer_counter_money: (): string => 'I’d sell, but squeeze them first.',
      offer_reject_money: (): string => 'Even I wouldn’t sell at that price.',
      offer_accept_loyal: (pn: string): string => `I hate losing ${pn}, but that’s a proper offer.`,
      offer_counter_loyal: (pn: string): string => `${pn}’s part of this place. If they want him, make them pay.`,
      offer_reject_loyal: (pn: string): string => `${pn} isn’t for sale. Tell them no.`,
      rest: (_pn: string, n: number, sub: string): string => `He’d give us ${n}% of himself. ${sub} is fresh. Rest him and he’s right for next week.`,
      rest_cautious: (pn: string, _n: number, sub: string): string => `I’m not risking ${pn} on tired legs. ${sub} can do a job.`,
      rest_bold: (_pn: string, _n: number, sub: string): string => `Even I’d sit him down this time. ${sub} is ready.`,
      play: (_pn: string, n: number): string => `He’s at ${n}% and still better than what’s on the bench. Play him and manage his minutes.`,
      renew_yes: (_pn: string, age: number, years: string): string => `He’s ${age}. ${years} years and he signs this week. Leave it and his agent starts taking calls.`,
      renew_no: (_pn: string, age: number): string => `At ${age} I wouldn’t commit. Let it run and we’ll get something younger in.`,
      renew_cap: (): string => 'We can’t fit his new wage under the cap as it stands. Raise the cap or let it run.',
      tape: (club: string): string => `Give me the week with ${club} on the laptop and I’ll show you where they leak.`,
      focus_recovery: (): string => 'The legs are heavy. A recovery week puts four points of fitness back in everyone.',
      focus_tactical: (): string => 'Drill the plan. The better they know it, the better we play it.',
      focus_opposition: (): string => 'We’ve got their tape. A week on them is worth half a point of quality on the day.',
      focus_development: (): string => 'The kids learn faster when the week is about them. Nobody’s tired.',
      deadline: (g: string): string => `We’re thin at ${g}. One more body before midnight or we’re praying nobody gets hurt.`,
      why_signed: (pn: string, fee: string): string => `${pn} fills our thinnest spot and he’s worth ${fee}. His agent will sign today.`,
      why_renewed: (pn: string): string => `${pn}’s worth keeping and the wage fits.`,
      why_listed: (pn: string): string => `The squad is too big. ${pn} is the one we’d miss least.`,
      why_out: (pn: string): string => `${pn} needs games, not a seat in the stand.`,
      why_sold: (pn: string): string => `${pn} won’t make it here. His rights still fetch something.`,
      why_rejected: (pn: string): string => `The bid for ${pn} is short. I’d tell them no.`,
      why_load: (): string => 'The squad’s condition says so.',
      why_focus: (): string => 'It’s what this week needs.',
      why_rehab: (pn: string): string => `${pn} is out a while. Rehab gets him back sooner.`,
      why_talk: (): string => 'The room’s gone flat. A word from you lifts it.',
      why_promote: (pn: string): string => `${pn} is ready. Training with the first team will finish the job.`,
      why_scouted: (): string => 'The academy is thin. A trial day turns up two or three.',
      why_plan: (ph: string): string => `The report says ${ph} is the way to hurt them.`,
      why_formation: (f: string): string => `Our best XI fits ${f} better.`,
      why_mentality: (): string => 'The odds say we should change our approach.',
      why_price: (): string => 'More money through the gate without emptying the stands.',
      why_report: (): string => 'It’s on your desk.',
      welcome: (): string => 'Tell us how close you want to be. We’ll pick up whatever you leave, and you can change it any time in the staff room.',
    } as Record<string, (...a: any[]) => string>,
    choices: {
      accept: (fee: string): string => `Accept ${fee}`, counter: (fee: string): string => `Ask for ${fee}`, reject: (): string => 'Turn it down',
      restHim: (pn: string): string => `Rest him · ${pn} starts`, playHim: (): string => 'Play him',
      renewYears: (n: number): string => `Open talks · ${n} ${P(n, 'yr', 'yrs')}`, wait: (): string => 'Let it run',
      takeJob: (): string => 'Take the job', stay: (): string => 'Stay where I am',
      watchTape: (): string => 'Watch the tape', skipTape: (): string => 'Not this week',
      focus_recovery: (): string => 'Recovery', focus_tactical: (): string => 'Tactical', focus_opposition: (): string => 'Opposition', focus_development: (): string => 'Development',
      findCover: (): string => 'Find cover', standPat: (): string => 'Stand pat',
      approve: (): string => 'Yes, do it', notNow: (): string => 'Not now',
      runUsual: (): string => 'The usual split', handsOn: (): string => 'Hands on: I pick the team', leaveIt: (): string => 'Leave it to the staff',
    } as Record<string, (...a: any[]) => string>,
    fx: {
      cash: (v: string): string => `+${v}`, loseStarter: (): string => 'Lose a starter', loseSquad: (): string => 'Squad −1', mayWalk: (): string => 'They may walk', stays: (): string => 'He stays',
      freshNext: (n: number): string => `${n}% next week`, slotLevel: (n: number): string => (n >= 0 ? `Level +${n}` : `Level ${n}`), playsAt: (n: number): string => `Plays at ${n}%`, legs: (): string => 'Legs go late',
      wagesYear: (v: string): string => `Wages ${v}/yr`, moraleUp: (): string => 'Morale ↑', rivalsCall: (): string => 'Rivals may call',
      newClub: (): string => 'New club, new board', loyalty: (): string => 'Board notices loyalty',
      knowThem: (): string => 'Their plan, threats and a counter', noPrep: (): string => 'We go in blind',
      signingsAsk: (): string => 'Signings wait for you', moreCalls: (): string => 'More calls on your desk', fewestCalls: (): string => 'Fewest calls', staffSign: (): string => 'Staff can sign players',
      focusFx_recovery: (): string => 'Fitness +4', focusFx_tactical: (): string => 'Familiarity +2', focusFx_opposition: (): string => 'Edge v them', focusFx_development: (): string => 'Growth ×1.25',
      toMarket: (): string => 'Opens the market', thin: (): string => 'One injury from trouble',
      fee: (v: string): string => `Fee ${v}`, listed: (): string => 'Listed', minutes: (): string => 'Real minutes', monthly: (v: string): string => `+${v}/mo`, backSooner: (): string => 'Back sooner', plan: (): string => 'New plan',
      nothingChanges: (): string => 'Nothing changes',
    } as Record<string, (...a: any[]) => string>,
    groups: ['keeper', 'the back', 'midfield', 'up front'],
  },
  desk: {
    title: (n: number): string => (n ? `${n} ${P(n, 'call', 'calls')} still on your desk` : 'Desk clear'),
    body: 'Continue now and your staff take their own advice on anything open. Nothing you haven’t seen gets signed.',
    take: 'Take the staff calls and go',
    leave: 'Leave them as they are',
    stay: 'Let me look first',
  },

  // ---------- matchday ----------
  pre: {
    crowd: (n: string, club: string): string => `${n} · ${club} in full voice`,
    crowdAway: (n: string): string => `${n} · the away end is packed`,
    stakesUp: (club: string, pos: string): string => `Win and you go ${pos}. ${club} are the ones in the way.`,
    stakesCup: (round: string): string => `${round}. Lose and you’re out.`,
    stakesPlain: 'Three points. Nothing else counts on a Saturday.',
    sheets: 'Team sheets', confirmed: 'Confirmed',
    talk: 'Last word in the dressing room',
    talks: [
      ['“Go and take it off them.”', 'Big-game players lift. The young ones might freeze.'],
      ['“Stick to the plan.”', 'Steady. Nobody gets carried away.'],
      ['“No pressure. Enjoy it.”', 'The young ones settle. The ones who want more go quiet.'],
    ] as [string, string][],
    winChance: 'Win chance', ourXg: 'Our xG forecast', theirXg: 'Theirs',
    walk: 'Walk out', result: 'Just give me the result', sim: 'Sim to the next decision', simSub: 'Quick results until something needs you',
    resume: (m: number): string => `Back out for the ${m}′`,
    report: 'Analyst’s report',
    threats: 'Watch these', weak: 'Where they leak', counter: 'The counter plan', apply: 'Use it', using: 'We’re on it',
    weakWhy: { slow: 'Slow on the turn', tired: 'Out on his feet', weak: 'The weak link' } as Record<string, string>,
    accuracy: (n: number): string => `${n}% sure`,
  },
  live: {
    ht: 'Half-time', ft: 'Full-time', min: (n: number): string => `${n}′`,
    moments: 'Key moments', numbers: 'The numbers', touchline: 'From the touchline', takes: 'Takes effect now',
    where: 'Where the ball has lived', whereSub: 'Last 10 min',
    views: ['Pitch', 'Territory', 'Our shots', 'Theirs'],
    momentum: 'Momentum', momentumKey: (a: string, b: string): string => `${a} above · ${b} below`,
    xg: 'Expected goals', attack: (club: string): string => `${club} attack →`,
    stats: ['Possession', 'Shots', 'On target', 'Corners', 'Fouls', 'Yellow cards'],
    changes: 'Changes', pause: 'Pause', play: 'Play', key: 'Key', speed: 'Speed',
    shouts: [['Keep going', 'mentality', 0], ['Get it wide', 'width', 2], ['Calm it down', 'tempo', 0], ['Press them', 'pressing', 2], ['Drop off', 'line', 0], ['Go for it', 'mentality', 2]] as [string, string, number][],
    assistant: 'Assistant',
    planB: 'Switch to Plan B', planBOn: 'Plan B is on',
    subsLeft: (n: number): string => `${n} ${P(n, 'sub', 'subs')} left`,
    off: 'Off', on: 'On', makeSub: 'Make the change', pickTwo: 'Pick who comes off, then who goes on.',
    confirm: (a: string, b: string): string => `${b} on for ${a}`,
    skip: 'Skip to full-time',
    goal: 'GOAL', sound: 'Sound',
    ev: {
      goal: (p: string): string => `GOAL · ${p}`, pen: (p: string): string => `Penalty · ${p}`, chance: (p: string): string => `Big chance · ${p}`, save: (p: string): string => `Saved · ${p}`,
      red: (p: string): string => `Sent off · ${p}`, injury: (p: string): string => `Injury · ${p}`,
      goalSub: (xg: string): string => `xG ${xg}`, chanceSub: (xg: string): string => `xG ${xg}, and it didn’t go in`, redSub: 'Down to ten', injurySub: 'He can’t carry on',
    },
    noMoments: 'Nothing worth writing home about yet.',
    resumed: (m: number): string => `Picked up where you left it: ${m}′`,
  },
  ht: {
    eyebrow: 'Why it happened · from the analysts',
    change: 'What we’d change', tapApply: 'Tap to apply',
    win: (a: number, b: number): string => `${a}% → ${b}%`, winLine: (n: number): string => `Win chance with ${n} ${P(n, 'change', 'changes')}`,
    yourChange: 'Your change', second: 'Second half', teamTalk: 'Team talk',
    noTips: 'Nothing the engine rates better than what we’re doing. Keep going.',
    applied: 'Done. They’ll know at the restart.',
    cause: {
      source: ['This is where we hurt them', 'This is where they hurt us'], setpiece: ['Set pieces are our weapon', 'Set pieces are killing us'],
      midfield: ['We own the middle', 'They own the middle'], pressed: ['Their press isn’t biting', 'Their press is biting'], pressing: ['Our press is biting', 'Our press isn’t biting'],
      duel: ['We’re winning the one-on-one', 'We’re losing the one-on-one'], finish: ['The finishing is on our side', 'The finishing is costing us'],
      keeper: ['A keeper is keeping us in it', 'Their keeper is having a day'], tired: ['They’ve run out of legs', 'We’ve run out of legs'],
      red: ['They’re down to ten', 'We’re down to ten'], change: ['The change is working', 'The change hasn’t worked'], theyChanged: ['They changed, it hasn’t helped', 'They’ve changed something'],
    } as Record<string, [string, string]>,
    evid: { shots: (n: number): string => `${n} ${P(n, 'shot', 'shots')}`, xg: 'xG', of: (a: number, b: number): string => `${a} of ${b}`, pct: (n: number): string => `${n}%`, won: 'won high up', saves: 'saves', fit: 'fitness late on', min: (n: number): string => `${n}′`, through: 'of moves get through' },
    subIdea: (a: string, b: string): string => `${b} on for ${a}`, subWhy: (a: string, n: number): string => `${a} is down to ${n}%. The bench is fresh.`,
    heads: {
      deserved: 'We’ve earned this.', robbed: 'We’re doing enough. The scoreline disagrees.', smash: 'We’re ahead, but we’ve ridden our luck.',
      beaten: 'They’ve been better. Simple as that.', even: 'Nothing in it.', clinical: 'We’ve taken our chances.', wasteful: 'We should be further ahead.', level: 'Level, and it feels about right.',
    } as Record<string, string>,
  },
  ft: {
    eyebrow: (ground: string): string => `Full-time · ${ground}`,
    xg90: 'Expected goals · 90 min',
    changed: 'What it changed',
    league: 'League', board: 'Board', fans: 'Fans', room: 'Dressing room',
    ratings: 'Ratings', all: (n: number): string => `All ${n}`, motm: 'Player of the match',
    heads: {
      W: (club: string, opp: string) => [`${club} beat ${opp}.`, `A proper result.`, `Three points in the bag.`],
      D: (club: string, opp: string) => [`${club} and ${opp} share it.`, `A point apiece.`, `Honours even.`],
      L: (club: string, opp: string) => [`${opp} beat ${club}.`, `One to forget.`, `Back to work on Monday.`],
    } as Record<'W' | 'D' | 'L', (a: string, b: string) => string[]>,
    tail: { up: (p: string): string => ` Up to ${p}.`, down: (p: string): string => ` Down to ${p}.`, same: (p: string): string => ` Still ${p}.` },
    boardQuote: (d: number): string => (d >= 2 ? '“A statement result.”' : d >= 0 ? '“As expected.”' : d > -2 ? '“We expected more.”' : '“That can’t happen again.”'),
    fansQuote: (d: number): string => (d >= 2 ? 'They were singing your name' : d >= 0 ? 'They went home happy enough' : 'Some boos at the whistle'),
    roomQuote: (d: number): string => (d >= 2 ? 'Buzzing in there' : d >= 0 ? 'Quiet and settled' : 'Heads down'),
    out: (n: number): string => `Out: ${n}`,
    injuredFor: (pn: string, n: number): string => `${pn} is out for ${n} ${P(n, 'week', 'weeks')}`,
    bannedFor: (pn: string, n: number): string => `${pn} is banned for ${n}`,
    record: 'New club record',
    press: 'Share the report', done: 'Continue',
    note: 'Assistant',
  },
  digest: {
    title: 'While you were away',
    sub: (a: string, b: string): string => `${a} to ${b}`,
    results: 'Results', staff: (n: number): string => `${n} staff ${P(n, 'call', 'calls')}`,
    stopped: { decision: 'Stopped: something needs you.', season: 'Stopped: the season is over.', max: 'Stopped: eight matchdays is enough in one go.', big: 'Stopped: a big match is next.', window: 'Stopped: the window opened.' } as Record<string, string>,
    back: 'Back to Today',
  },

  // ---------- squad ----------
  squad: {
    title: 'The squad',
    sub: (n: number): string => `First team · ${n} players`,
    facts: { age: 'avg age', wages: 'wages a month', unhappy: 'unhappy', holes: (n: number): string => P(n, 'hole to fill', 'holes to fill') },
    lens: { all: 'Everyone', starters: 'Starters', ending: 'Deals ending', unhappy: 'Unhappy', injured: 'Injured', loans: 'On loan', listed: 'Listed' },
    depth: 'Depth', depthSub: 'First choice · cover',
    covered: 'Covered', thin: 'Thin', hole: 'One injury from trouble',
    noCover: (pn: string): string => `No cover for ${pn}`, noCoverSub: 'Recruitment is on it when you are.', shortlist: 'Shortlist',
    thenNobody: 'then nobody fit',
    player: 'Player', fit: 'Fit', mood: 'Mood', yrs: 'Yrs',
    desk: 'On the desk', deskSub: 'Contracts and moves',
    ending: (n: number): string => `${n} ${P(n, 'deal ends', 'deals end')} this season`, endingNone: 'No deal ends this season.',
    loansOut: (n: number): string => `${n} out on loan`, listedN: (n: number): string => `${n} on the transfer list`,
    training: 'Training week', medical: 'Medical', academy: 'Academy',
    find: 'Find',
    form: (v: string): string => `${v} form`,
    sub2: { captain: 'captain', inj: (n: number): string => `out ${n} wks`, ban: 'banned', loan: 'on loan', listed: 'listed', talks: 'wants talks', young: 'academy' },
  },
  player: {
    back: 'Squad',
    ability: 'Ability', ceiling: 'Ceiling', form: 'Form', value: 'Value', apps: (n: number): string => `${n} apps`,
    dev: 'Development', devHead: (age: number, peak: number, up: boolean): string => (age >= 31 ? 'Still doing it. The years are catching up.' : !up ? 'At his level. What you see is what you get.' : peak <= age + 1 ? 'Nearly there. One more push.' : `Still climbing. Peak around ${peak}.`),
    known: 'Known', own: 'Own player', scouted: (k: number): string => `Scouts ${k}% sure`,
    good: 'What he’s good at', groups: ['With the ball', 'Without it', 'Mind and body'],
    attrs: ['Pace', 'Shooting', 'Passing', 'Dribbling', 'Defending', 'Physical', 'Goalkeeping'],
    fits: 'Where he fits',
    man: 'The man', captain: 'Captain', morale: (v: string): string => `Morale: ${v}`, moods: ['low', 'flat', 'fine', 'good', 'flying'],
    contract: 'Contract', expires: 'Expires June', perMonth: 'A month', secure: 'Secure', ending: 'Ending', release: 'Release clause', none: 'None', rank: 'Earner rank',
    renew: 'Offer a new deal', list: 'Put on the list', unlist: 'Take off the list', talk: 'Talk to him', rest: 'Rest him next match', unrest: 'Available again',
    bid: 'Make an offer', shortlist: 'Shortlist', unshortlist: 'Off the shortlist', loanIn: 'Loan him', loanOut: 'Loan him out',
    rename: 'Rename',
    season: 'This season', seasonStats: (a: number, g: number, as: number): string => `${a} apps · ${g} goals · ${as} assists`,
    ageNat: (age: number): string => `${age}`,
    free: 'Free agent',
    onLoan: (club: string): string => `On loan at ${club}`,
    ability2: 'Projection', abilityLine: 'Ability', projLine: 'Coaches’ projection', avgLine: 'Squad average',
  },
  train: {
    title: 'Training week', sub: 'Intensity and focus',
    load: 'Intensity', loads: ['Light', 'Normal', 'Heavy'], loadFx: ['Legs recover. Learning slows.', 'The usual week.', 'Faster learning, heavier legs, the odd knock.'],
    focus: 'This week’s focus', focusNames: { recovery: 'Recovery', tactical: 'Tactical', opposition: 'Opposition', development: 'Development' } as Record<PrepFocus, string>,
    focusFx: { recovery: 'Everyone +4 fitness by Saturday.', tactical: 'The plan sticks: +2 familiarity after the match.', opposition: 'With the analyst’s report: a small edge on the day.', development: 'Players learn 25% faster this week.' } as Record<PrepFocus, string>,
    report: 'Last week', improved: (n: number): string => `${n} improved`, hurt: (n: number): string => `${n} picked up a knock`,
    individual: 'Individual work', choose: 'Pick a player', attr: 'Extra work on',
    none: 'Nothing extra',
    medical: 'Medical room', injuredN: (n: number): string => (n ? `${n} injured` : 'Everyone fit'), rehab: 'Rehab', specialist: 'Specialist', out: (n: number): string => `Out ${n} wks`,
    academy: 'Academy', prospects: (n: number): string => `${n} prospects`, trial: (cost: string): string => `Trial day · ${cost}`, promote: 'Promote', release: 'Release', sellRights: (v: string): string => `Sell rights · ${v}`,
    trialsLeft: (n: number): string => `${n} trial ${P(n, 'day', 'days')} left this season`,
  },

  // ---------- tactics ----------
  tac: {
    title: (opp: string): string => `Tactics · v ${opp}`, titleFree: 'Tactics',
    styles: { balanced: 'Balanced', possession: 'Keep the ball', counter: 'Sit and break', gegenpress: 'Press, then run in behind', bus: 'Park it', wings: 'Go down the wings', direct: 'Get it forward' } as Record<Philosophy, string>,
    forecast: 'Forecast',
    how: 'How we play', changes: (n: number): string => `${n} ${P(n, 'change', 'changes')}`, changed: 'Changed',
    style: 'Style', shape: 'Shape',
    ins: {
      press: ['Press', ['Sit off', 'Mid-block', 'Hunt high']],
      line: ['Defensive line', ['Deep', 'Standard', 'High']],
      width: ['Where we attack', ['Narrow', 'Balanced', 'Wide']],
      tempo: ['Tempo', ['Patient', 'Normal', 'Quick']],
      passing: ['Passing', ['Short', 'Mixed', 'Direct']],
      mentality: ['Approach', ['Park it', 'Careful', 'Balanced', 'Positive', 'All out']],
    } as Record<string, [string, string[]]>,
    gain: 'Gain', risk: 'Risk',
    trade: {
      press: [['Deep and compact: fresh legs at 80′.', 'They have the ball and time to pick a pass.'], ['Hard to play through, cheap on the legs.', 'Neither here nor there.'], ['Win it near their box.', 'Legs go around 70′, and they get runs at us.']],
      line: [['Nothing in behind for their runners.', 'They camp on our box.'], ['Our centre-backs are comfortable here.', 'A gap between the lines when we press.'], ['The pitch shrinks for them.', 'One ball over the top and we’re in a race.']],
      width: [['Numbers through the middle.', 'Easy to crowd.'], ['Nothing obvious to stop.', 'Nothing obvious to fear.'], ['Stretches them; our wingers get one-on-ones.', 'Thin in the middle if we lose it.']],
      tempo: [['We keep the ball and our shape.', 'They get set before we arrive.'], ['Balanced.', 'Balanced.'], ['We catch them before they’re set.', 'We give it away more.']],
      passing: [['Short and safe: we keep it.', 'Slow to hurt anyone.'], ['A bit of both.', 'A bit of both.'], ['Straight at their back line.', 'Coin flips in midfield.']],
    } as Record<string, [string, string][]>,
    mentality: ['Park the bus', 'Careful', 'Balanced', 'Positive', 'All-out attack'],
    board: 'Tactics board. Tap a player, then tap a spot or another player to swap.',
    hint: 'Tap to pick · tap again to swap',
    theirPress: (club: string): string => `${club}’s shape`,
    bench: 'Bench', lock: 'Lock it in', locked: 'Plan locked in', undo: 'Undo', reset: 'Best XI for me',
    role: (pos: string): string => `Role · ${pos}`, fitFor: 'How he fits each spot',
    opp: (f: string, st: string): string => `Opponent · ${f} · ${st}`, oppHow: (club: string): string => `How ${club} play`,
    ours: 'Ours', theirs: 'Theirs', even: 'Even',
    lanes: ['Our left', 'Centre', 'Our right'],
    danger: 'danger man', engine: 'the engine', oppManager: (n: string): string => `${n} picks their team`,
    noReport: 'No report yet. The analyst needs the week on them.',
    familiar: 'Familiarity', familiarSub: (n: number): string => (n >= 80 ? 'They know it in their sleep' : n >= 55 ? 'Getting there' : 'Still learning it'),
    planB: 'Plan B', planBSet: 'Save this as Plan B', planBNone: 'No Plan B yet. Set a second plan you can switch to in a match.', planBClear: 'Clear Plan B', useB: 'Use Plan B now',
    setPieces: 'Set pieces', captain: 'Captain', penalties: 'Penalties', freeKicks: 'Free kicks', corners: 'Corners', auto: 'Best available',
    swapped: (a: string, b: string): string => `${a} and ${b} swapped`,
    outOfPos: (n: number): string => `Plays at ${n}`,
    philosophy: 'Philosophy',
  },
  table: {
    tabs: ['Next match', 'Fixtures', 'Table', 'Cups'],
    pos: '#', club: 'Club', p: 'P', gd: 'GD', pts: 'Pts', w: 'W', d: 'D', l: 'L',
    scorers: 'Top scorers', assists: 'Top assists', zones: { up: 'Promotion', down: 'Relegation', top: 'Continental places' },
    round: (n: number): string => `Matchday ${n}`, noCups: 'No cup ties this season.', group: (g: string): string => `Group ${g}`,
    bye: 'Bye', tbd: 'To be drawn', winnerGoes: 'Winner goes through',
    finished: 'Played', upcoming: 'Coming up', you: 'You',
  },

  // ---------- transfers ----------
  tr: {
    title: 'Transfers', window: (open: boolean, left: number): string => (open ? `Window open · ${left} ${P(left, 'matchday', 'matchdays')} left` : `Window shut · opens in ${left} ${P(left, 'matchday', 'matchdays')}`),
    deadline: 'Deadline day',
    hero: { need: (pos: string): string => `Find a ${pos}`, none: 'Nobody to find. Yet.' },
    budget: 'Transfer budget', wageRoom: 'Wage room / mo', onList: 'On the list',
    why: 'Why this search exists', needHead: (pos: string): string => `We’re thin at ${pos}.`, noNeed: 'Every spot has cover. Shop for quality, not bodies.',
    chief: 'Chief scout',
    scoutLine: (pn: string, k: number): string => `${pn} is the one. We know him ${k}% of the way.`,
    scoutNone: 'Put a few names on the shortlist and I’ll get eyes on them.',
    fog: 'What we know · ability', fogHead: 'The wider the bar, the less we know.', fogKey: 'Scouted range', ref: (pn: string, n: number): string => `${pn} today (${n})`,
    tabs: ['Shortlist', 'Search', 'Bids', 'Deals', 'Loans'],
    known: 'known', likely: 'Likely fee', wants: 'Wants / mo', interest: 'Interest',
    interestL: ['Keen', 'Open', 'Cool', 'Unknown'],
    ability: 'Ability', ceiling: 'Ceiling', fit: 'Fit',
    bid: 'Make an offer', inTalks: 'In talks', report: 'Report', ask: 'Ask the price',
    empty: 'The shortlist is empty. Search the market and star who you like: the scouts start watching straight away.',
    search: 'Search players', filters: { pos: 'Position', league: 'League', age: 'Age', value: 'Max fee' }, any: 'Any', results: (n: number): string => `${n} players`,
    sort: ['Scouts’ rating', 'Fee', 'Age', 'Wage'],
    bids: 'Bids for your players', noBids: 'Nobody’s asking. That can change fast in a window.',
    deals: 'This season’s deals', noDeals: 'No deals yet.', inOut: { in: 'In', out: 'Out', free: 'Free', released: 'Released' } as Record<string, string>,
    loans: 'Loans', noLoans: 'Nobody on loan.', loanedIn: 'Loaned in', loanedOut: 'Loaned out',
    closed: 'The window is shut. Free agents only until it opens.',
  },
  bid: {
    title: (pn: string): string => `Offer for ${pn}`, fee: 'Fee', wage: 'Wage a month', years: 'Years', role: 'Role',
    roles: { star: 'Star', regular: 'Starter', rotation: 'Rotation', prospect: 'Prospect' } as Record<string, string>,
    ask: (v: string): string => `They want ${v}`, demand: (v: string): string => `He wants ${v}`, send: 'Send the offer',
    afford: 'After the deal', budgetLeft: 'Budget left', wageLeft: 'Wage room left',
    no: {
      budget: 'We can’t afford that fee.', wageCap: 'That wage breaks the cap.', squadFull: 'The squad is full (32).', fee: 'They want more.', wage: 'He wants more.',
      ambition: 'He won’t drop down to us.', role: 'He’s too old to be a prospect.', injured: 'He’s injured.', sellerThin: 'They can’t spare him: their squad is too thin.',
      gone: 'He’s not available.', window: 'The window is shut.', limit: 'Loan limit reached.', loaned: 'Already on loan.', squad: 'Our squad is too thin.', key: 'He’s a key player for them.',
      club: 'Pick a club.', free: 'He isn’t ours to loan.', lenderThin: 'They can’t spare him.', unhappy: 'He won’t talk while he’s this unhappy.', years: 'Too many years for his age.',
      terms: 'Those terms don’t work.', counter: 'They want more.', wait: 'Too soon for another talk.', fee2: 'That’s no raise.',
    } as Record<string, string>,
    counter: (v: string): string => `They’d take ${v}`,
    renewTitle: (pn: string): string => `New deal for ${pn}`, renewSend: 'Offer it',
    offersTitle: 'Bids for your players', accept: 'Accept', reject: 'Reject', counterBtn: (v: string): string => `Ask ${v}`,
  },
  note: {
    signed: (pn: string): string => `${pn} signs.`, sold: (pn: string): string => `${pn} is sold.`, renewed: (pn: string): string => `${pn} commits his future.`,
    loanedIn: (pn: string): string => `${pn} joins on loan.`, loanedOut: (pn: string): string => `${pn} goes out on loan.`, counterOk: 'They met your price.', counterNo: 'They walked away.',
    haggleOk: 'They went up 10%.', haggleNo: 'They pulled the offer.', rightsSold: (v: string): string => `Rights sold for ${v}.`, scoutFound: (n: number): string => `${n} ${P(n, 'prospect', 'prospects')} turned up.`,
    tactics: 'Plan locked in.', done: 'Done.', refused: 'Not possible:',
  },

  // ---------- club office ----------
  office: {
    title: 'Club office', hero: 'The money, the board, the bricks.',
    tabs: ['Money', 'Board', 'Facilities', 'Staff', 'Commercial'],
    runway: (to: string): string => `Cash runway · to ${to}`,
    runwayHead: (ok: boolean, low: string): string => (ok ? `Healthy all season. ${low} is the low point.` : `We go into the red around ${low}. Something has to give.`),
    cash: 'Cash today', wageUse: 'Wages / cap', transfer: 'Transfer budget',
    projected: 'Projected cash', floor: 'Zero line',
    income: 'Income a month', spend: 'Spending a month',
    lines: { gate: 'Matchday', tv: 'Broadcast', sponsors: 'Commercial', wages: 'Wages', staff: 'Staff', upkeep: 'Upkeep' } as Record<string, string>,
    ledger: 'This season so far',
    capT: 'Wage cap', capMove: 'Move the cap', capUp: (v: string): string => `Costs ${v} now`, capDown: (v: string): string => `Gives back ${v}`,
    board: 'What the board wants', trust: 'Board trust', trustWhy: (n: number): string => (n < 30 ? 'Below 30 and they start looking.' : n < 50 ? 'They’re watching.' : 'They’re behind you.'),
    obj: { league: 'League', cup: 'Cup', youth: 'Youth', finance: 'Finance' },
    onTrack: 'On track', close: 'Close', behind: 'Behind',
    youthLine: (n: number, of: number): string => `${n} of ${of} league apps for the under-21s`,
    financeLine: (ok: boolean): string => (ok ? 'In the black' : 'In the red'),
    facilities: 'Facilities', level: (n: number): string => `Level ${n}`, upgrade: (v: string): string => `Build · ${v}`, maxed: 'The best there is',
    fac: { stadium: 'Stadium', medical: 'Medical centre', training: 'Training ground', academy: 'Academy', scouting: 'Scouting network' } as Record<string, string>,
    facFx: { stadium: 'More seats, more gate money', medical: 'Injuries heal faster', training: 'Players improve faster', academy: 'Better prospects', scouting: 'More academy trial days' } as Record<string, string>,
    staff: 'The staff room', staffSub: 'Who does what, and how much you let them',
    levels: { me: 'Me', ask: 'Ask me', staff: 'Staff' } as Record<DeptLevel, string>,
    levelHelp: { me: 'Nothing happens without you.', ask: 'They prepare it and wait for your yes.', staff: 'They get on with it and tell you after.' } as Record<DeptLevel, string>,
    depts: { matchprep: 'Match prep', opposition: 'Opposition', fitness: 'Fitness & medical', development: 'Development', recruitment: 'Recruitment', contracts: 'Contracts & sales', commercial: 'Commercial' } as Record<Dept, string>,
    deptSub: { matchprep: 'XI and plan', opposition: 'Reports and the counter plan', fitness: 'Training load, focus, rehab', development: 'Academy and morale', recruitment: 'Signings and loans out', contracts: 'Renewals and bids', commercial: 'Sponsors and tickets' } as Record<Dept, string>,
    roles: { assistant: 'Assistant manager', director: 'Director of football', fitness: 'Fitness coach', doctor: 'Club doctor', psychologist: 'Psychologist', scout: 'Chief scout' } as Record<string, string>,
    bias: { cautious: 'Cautious', bold: 'Bold', youth: 'Youth-minded', veteran: 'Trusts experience', money: 'Money-first', loyal: 'Loyalist' } as Record<Bias, string>,
    biasWhy: { cautious: 'Plays it safe: rests early, bids low, can lose targets.', bold: 'Goes for it: pushes the legs, pays over the odds.', youth: 'Backs the young ones.', veteran: 'Wants proven players.', money: 'Sells when the price is right, and sometimes before.', loyal: 'Keeps his players, renews nearly everyone.' } as Record<Bias, string>,
    quality: (n: number): string => `Quality ${n}`, hire: 'Hire', candidates: 'Candidates', wage: (v: string): string => `${v}/mo`,
    all: 'Set every department', log: 'What the staff did', logEmpty: 'Nothing yet.',
    sponsors: 'Sponsors', offers: 'Offers', sign: 'Sign', haggle: 'Ask for 10% more', extend: 'Extend', end: 'End early',
    slots: { shirt: 'Shirt', kit: 'Kit supplier', stadium: 'Stadium name', sleeve: 'Sleeve', commercial: 'Commercial partner' } as Record<string, string>,
    months: (n: number): string => `${n} months`,
    tickets: 'Tickets', price: 'Ticket price', attendance: (n: string, c: string): string => `${n} of ${c} seats`, setPrice: 'Set the price',
    settings: 'Settings and saves',
  },

  // ---------- career ----------
  career: {
    title: 'Your career', hero: (n: number): string => (n ? `${n} ${P(n, 'trophy', 'trophies')} and counting.` : 'The first trophy is the hardest.'),
    totals: { matches: 'Matches', wins: 'Wins', trophies: 'Trophies', rep: 'Reputation' },
    tier: (r: number): string => (r < 30 ? 'Unknown' : r < 50 ? 'Regional' : r < 70 ? 'National' : r < 85 ? 'Continental' : 'World-class'),
    badge: 'Coaching badge', badgeNext: (b: string, n: number): string => `${b} after ${n} matches managed`, badgeTop: 'The top badge',
    seasons: 'Season by season', now: 'Now', noSeasons: 'Your first season is still being written.',
    records: 'Records', recs: { bigWin: 'Biggest win', mostPoints: 'Most points', mostGoals: 'Most goals', unbeaten: 'Longest unbeaten', scorer: 'Top scorer in a season', bestFinish: 'Best finish', bestBuy: 'Record signing', bestSale: 'Record sale' } as Record<string, string>,
    jobs: 'Clubs asking about you', noJobs: 'Nobody’s calling. Win things and they will.', take: 'Take the job', decline: 'Not interested',
    courses: 'Courses', courseBuy: (v: string): string => `Enrol · ${v}`, done: 'Done',
    wallet: 'Your own money',
    lift: (season: string, club: string): string => `${season} · ${club}`,
    trophyKinds: { league: 'League title', cup: 'Cup', continental: 'Continental cup', promotion: 'Promotion' } as Record<string, string>,
    milestones: 'Milestones',
    sacked: 'Sacked', objMet: 'Objective met', objMissed: 'Objective missed',
  },

  // ---------- Club Pass (concept on the web) ----------
  pass: {
    concept: 'Concept · nothing is sold here',
    title: 'The Semba Club Pass', lead: 'For people who want to back the studio. It never buys results, players or form.',
    price: '$4.99', per: 'a month, for The Gaffer and Tier One',
    perks: [['No ads in either game', 'Rewarded ads disappear too'], ['400 Semba Credits a month', 'For kits, badges and looks'], ['A monthly look, yours to keep', 'Even if you stop'], ['The pass badge', 'On your coach card']] as [string, string][],
    cta: 'Coming soon',
    note: 'On the web the Pass and Credits are a preview. Purchases will only open once they can be verified.',
    credits: 'Semba Credits', balance: (n: number): string => `${n} cr`, creditsSub: 'Stored on this device only. Shared with Tier One on the same browser.',
    earn: 'Watch an ad · +25 cr', earned: '+25 credits.', adsOff: 'Ads aren’t switched on in this build.', daily: (n: number): string => `${n} of 4 today`,
    never: 'What money never buys', nevers: ['Better players or ratings', 'Results or form', 'Faster development', 'Anything in the Daily or a ranking'],
    looks: 'Looks', lookNames: ['Claret night', 'Harbour blue', 'Desert gold'], lookPrice: '250 cr · concept',
    items: 'Also planned', itemList: [['Kit and badge designer', '400 cr'], ['Extra save slot', '300 cr'], ['Scenario pack: three rescue jobs', '500 cr']] as [string, string][],
  },

  // ---------- settings ----------
  set: {
    title: 'Settings', lang: 'Language', names: 'Player and club names', namesReal: 'Real names', namesFictional: 'Fictional names',
    namesHelp: 'Fictional keeps every rating, number and colour and swaps the names. You can switch back.',
    namesLocked: 'This career was made in the old fictional world; it stays fictional.',
    sim: 'Sim to the next decision stops for', stopAll: 'Any decision', stopImportant: 'Important ones', stopBig: 'Big matches too',
    match: 'Match', speed: 'Default speed', speeds: ['1×', '2×', '4×'], sound: 'Crowd and whistle',
    balance: 'Difficulty', saves: 'Saves', export: 'Export this career', import: 'Import a career', exportSub: 'A .gaffer file you keep', importSub: 'From a .gaffer file',
    reset: 'Delete this career', resetAsk: 'Delete this career from this device?', resetBody: 'It can’t be undone. Export it first if you might want it.', del: 'Delete it', keep: 'Keep it',
    about: 'About', howTo: 'How to play', privacy: 'Privacy', version: (v: string, b: number): string => `The Gaffer ${v} · build ${b}`,
    motion: 'Motion follows your device’s reduced-motion setting.',
    world: 'World editor', worldSub: 'Rename clubs, move leagues', quick: 'Quick match',
    menu: 'Title screen', importOk: 'Career imported.', importBad: 'That file didn’t pass its check.',
  },
  log: {
    'training:focus': (f: string): string => `Made it a ${f.toLowerCase()} week.`,
    'tactics:plan': (ph: string): string => `Switched us to ${ph} for the next match.`,
    'tactics:mentality': (): string => 'Changed our approach for the next match.',
    'tactics:formation': (f: string): string => `Changed the shape to ${f}.`,
    'scouting:report': (club: string): string => `Watched ${club} on tape and wrote the report.`,
    'morale:talk': (n: number): string => `Talked to the squad: the room was at ${n}.`,
  } as Record<string, (...a: any[]) => string>,
  news: { title: 'News and inbox', inbox: 'Inbox', news: 'News', empty: 'Quiet day.', read: 'Mark all read' },
  season: {
    title: (y: string): string => `${y} is done`, finish: (p: string, obj: string): string => `Finished ${p}. The board wanted ${obj}.`,
    met: 'Job done.', missed: 'Not good enough.', up: 'Promoted', down: 'Relegated', stay: 'Staying put',
    next: (y: string): string => `Start ${y}`, finishRest: 'Play out the other leagues', left: 'Left the club', kids: 'Up from the academy', retired: (n: number): string => `${n} players retired around the world.`,
  },
  common: {
    free: 'Free', perMonth: '/mo', yrs: (n: number): string => `${n} ${P(n, 'yr', 'yrs')}`, matchday: (n: number): string => `Matchday ${n}`,
    pos: { GK: 'GK', CB: 'CB', LB: 'LB', RB: 'RB', CDM: 'DM', CM: 'CM', CAM: 'AM', LW: 'LW', RW: 'RW', ST: 'ST' } as Record<string, string>,
    posLong: { GK: 'Goalkeeper', CB: 'Centre-back', LB: 'Left-back', RB: 'Right-back', CDM: 'Holding midfielder', CM: 'Central midfielder', CAM: 'Attacking midfielder', LW: 'Left winger', RW: 'Right winger', ST: 'Striker' } as Record<string, string>,
    group: ['Keepers', 'Defenders', 'Midfielders', 'Forwards'],
    none: 'None', yes: 'Yes', no: 'No', cancel: 'Cancel', save: 'Save', done: 'Done',
  },
};

export type XStrings = typeof X_EN;
