// V2.6 Training & pathway, Spanish. Type-checked against lang-youth.ts.
import type { YStrings } from './lang-youth';

const P = (n: number, one: string, many: string) => (n === 1 ? one : many);
const TIERS = ['un', 'un prometedor', 'un ilusionante', 'un especial'];

export const Y_ES: YStrings = {
  doors: { train: 'Semana de entrenamiento', medical: 'Servicio médico', academy: 'Cantera' },
  bands: ['Bajo', 'Elevado', 'Alto'],
  intens: ['Suave', 'Normal', 'Intenso'],
  tiers: ['un', 'un prometedor', 'un ilusionante', 'un especial'],

  tw: {
    title: 'Semana de entrenamiento',
    head: (i: number, focus: string, plans: number): string => `Semana ${['suave', 'normal', 'intensa'][i]}, foco en ${focus.toLowerCase()}. ${plans ? `${plans} con trabajo extra.` : 'Nadie con trabajo extra.'}`,
    intensity: 'Intensidad',
    intFx: ['Progreso ×0,7. Las piernas se recuperan antes.', 'Progreso ×1,0. La semana de siempre.', 'Progreso ×1,4. Carga +4 al día, y caen golpes.'],
    congested: 'Dos partidos esta semana: nada de intensidad alta.',
    dropped: 'La semana pasada se quitó el trabajo intenso: hubo dos partidos.',
    focus: 'El foco de la semana',
    load: 'Carga',
    loadSub: 'Quién aguanta otros noventa',
    loadHidden: 'Un preparador físico de 60+ te da los números exactos.',
    loadN: (n: number): string => `Carga ${n}`,
    fragile: (n: number): string => `Frágil · ${n} ${P(n, 'partido', 'partidos')}`,
    riskX: (x: string): string => `Riesgo de lesión ×${x}`,
    allFresh: 'Todos pueden volver a jugar.',
    plans: 'Planes individuales',
    plansN: (n: number, max: number): string => `${n} de ${max}`,
    plansNone: 'Nadie con trabajo extra. Caben hasta cinco jugadores.',
    plansFull: 'Cinco es el límite. Quita a alguien antes.',
    add: 'Añadir un plan',
    who: 'Jugador',
    attr: 'Pulir un atributo',
    pos: 'Aprender otra posición',
    attrFx: 'Progreso +10 %, el punto extra va a este atributo, carga +2 al día.',
    posFx: 'Unas once jornadas de trabajo extra. Progreso −10 % mientras tanto.',
    learning: (pos: string, pct: number): string => `Aprendiendo ${pos} · ${pct} %`,
    sharpening: (a: string): string => `Puliendo ${a}`,
    also: (pos: string): string => `También juega de ${pos}`,
    remove: 'Quitar',
    save: 'Empezar el plan',
    report: 'La semana pasada',
    up: (n: number): string => (n ? `${n} ${P(n, 'dio', 'dieron')} un paso adelante` : 'Nadie dio un paso adelante'),
    near: 'A punto de dar el siguiente paso',
    knocks: (n: number): string => `${n} con un golpe`,
    academyUp: (n: number): string => `${n} de la cantera ${P(n, 'mejoró', 'mejoraron')}`,
    quiet: 'Esta semana no se movió nada. Se moverá.',
  },

  md: {
    title: 'Servicio médico',
    head: (out: number, edge: number): string => (out || edge ? `${out} ${P(out, 'lesionado', 'lesionados')}, ${edge} al límite.` : 'Todos sanos.'),
    out: 'Sala de tratamiento',
    back: (lo: number, hi: number): string => (lo === hi ? `Vuelve en ${lo} ${P(lo, 'jornada', 'jornadas')}` : `Vuelve en ${lo}–${hi} jornadas`),
    orig: (n: number): string => `Baja de ${n} al lesionarse`,
    fog: (who: string): string => `Estimación de ${who}. Un médico mejor la afina.`,
    fogNone: 'Sin médico en el club: esto es una suposición.',
    rush: 'Forzar la vuelta',
    rushFx: (gain: number, risk: number): string => `${gain} ${P(gain, 'jornada', 'jornadas')} antes · ${risk} % de recaída`,
    rushNotYet: (n: number): string => `Se puede forzar cuando le queden ${n} ${P(n, 'jornada', 'jornadas')}`,
    edge: 'Al límite',
    edgeSub: 'Cargados o frágiles',
    thisMatch: (n: number): string => `~${n} % este partido`,
    none: 'Nadie en la camilla.',
    noEdge: 'Nadie va sobrecargado. Sigue rotando.',
    rest: 'Que descanse',
    unrest: 'Volver a contar con él',
  },

  ac: {
    title: 'Cantera y camino',
    head: (n: number, loans: number, grads: number): string => `${n} en la cantera, ${loans} ${P(loans, 'cedido', 'cedidos')}, ${grads} en el primer equipo.`,
    countdown: (n: number): string => `Día de la nueva hornada en ${n} ${P(n, 'jornada', 'jornadas')}`,
    countdownSub: 'El director de cantera aún no ha visto al grupo de este año.',
    preview: (tier: string, pos: string): string => `${tier.charAt(0).toUpperCase()}${tier.slice(1)} ${pos.toLowerCase()} en la hornada de este año`,
    previewSub: (n: number): string => `Llegan en ${n} ${P(n, 'jornada', 'jornadas')}. El director de cantera ya los ha visto.`,
    arrived: (n: number): string => `Día de la nueva hornada. ${n} ${P(n, 'cara nueva', 'caras nuevas')}.`,
    classOf: (y: string): string => `La hornada de ${y}`,
    reveal: 'Conócelos',
    standout: 'El que destaca',
    nextYear: 'La próxima hornada llega la temporada que viene.',
    cap: (n: number, cap: number): string => `${n} de ${cap} plazas`,
    over: 'Por encima de su capacidad: cada chaval progresa un 15 % más lento.',
    squad: 'La cantera',
    empty: 'La cantera está vacía hasta el día de la nueva hornada.',
    ready: 'Listo',
    late: 'Se le acaba el tiempo',
    grown: (n: number): string => (n > 0 ? `+${n} esta temporada` : n < 0 ? `${n} esta temporada` : 'Igual esta temporada'),
    promote: 'Subir',
    pmTitle: (pn: string) => `¿Subir a ${pn}?`,
    pmSquad: (n: number, max: number) => `Primer equipo: ${n} de ${max}`,
    pmDeal: (wage: string, until: number) => `Contrato del primer equipo hasta ${until}, ${wage} al mes`,
    pmPromise: (apps: number, md: number) => `La promesa que lleva: ${apps} partidos en las próximas ${md} jornadas de liga, o una cesión. Si no la cumples, dejará de confiar en ti.`,
    pmAlt: '¿No sabes si tendrá minutos? Déjalo en la cantera o cédelo.',
    pmYes: 'Subirlo',
    loan: 'Ceder',
    release: 'Dejar ir',
    word: 'Unas palabras',
    recall: 'Repescarlo',
    loanTitle: (pn: string): string => `¿Dónde debería jugar ${pn}?`,
    loanSub: 'Un club donde sea titular le da minutos de verdad, y los minutos son lo que le hace crecer.',
    roles: ['Sería titular', 'Rotación', 'Sobre todo banquillo'],
    windowShut: 'El mercado está cerrado. Las cesiones se hacen en verano y a mitad de temporada.',
    tooYoung: 'Demasiado joven para salir cedido (17+).',
    noSpots: 'Todavía no lo quiere ningún club de su nivel.',
    releaseQ: (pn: string): string => `¿Dejar ir a ${pn}? Quedará libre y cualquiera podrá ficharlo.`,
    loans: 'Cedidos',
    loansNone: 'Nadie cedido. Con el mercado abierto, manda a los siguientes donde jueguen.',
    mins: (n: number): string => `${n} min esta temporada`,
    run: (n: number): string => `${n} ${P(n, 'partido completo', 'partidos completos')} seguidos`,
    grads: 'Canteranos',
    gradsNone: 'Todavía no hay canteranos en el primer equipo.',
    since: (from: number, now: number): string => `${from} → ${now}`,
    apps: (n: number): string => `${n} ${P(n, 'partido', 'partidos')}`,
    path: ['Cantera', 'Cedido', 'Primer equipo'],
  },

  cv: {
    real: 'Historia real',
    proj: 'Hacia dónde va',
    avg: 'Media de nuestro once',
    starts: (s: string): string => `Historia desde ${s}`,
    one: 'La historia empieza aquí: cada jornada desde ahora queda registrada.',
    academy: 'Cantera',
    homegrown: 'Canterano',
    load: 'Carga',
    minutes: (n: number): string => `${n} min esta temporada`,
  },

  tag: { risk: 'Médico', rush: 'Médico', intake: 'Nueva hornada', ready: 'Cantera', loanee: 'Informe de cesión', benched: 'Informe de cesión', full: 'Cantera', ageout: 'Cantera' },
  titles: {
    y_risk: (pn: string, n: number): string => `${pn} puede jugar, pero su carga es ${n}`,
    y_fragile: (pn: string, n: number): string => `${pn} volvió antes de tiempo y sigue frágil (${n} ${P(n, 'partido', 'partidos')} más)`,
    y_rush: (pn: string, n: number): string => `${pn} podría volver antes (le ${P(n, 'queda', 'quedan')} ${n} ${P(n, 'jornada', 'jornadas')})`,
    y_intake: (n: number): string => `Nueva hornada: ${n} ${P(n, 'cara nueva', 'caras nuevas')}`,
    y_ready: (pn: string, n: number): string => `${pn} llama a la puerta con ${n}`,
    y_loanee: (pn: string, n: number, club: string): string => `${pn}: ${n} partidos completos seguidos en el ${club}`,
    y_benched: (pn: string, club: string): string => `${pn} no juega en el ${club}`,
    y_full: (n: number, cap: string): string => `La cantera tiene ${n} chavales para ${cap} plazas`,
    y_ageout: (pn: string, n: number): string => `${pn} tiene ${n} años y sigue en la cantera`,
    ask_y_rush: (pn: string): string => `¿Forzamos la vuelta de ${pn}?`,
    ask_y_rest: (pn: string): string => `¿Que descanse ${pn} el próximo partido?`,
    ask_y_loan: (pn: string, club: string): string => `¿Ceder a ${pn} al ${club}?`,
    ask_y_release: (pn: string): string => `¿Dejar ir a ${pn} de la cantera?`,
  },
  advice: {
    y_risk_rest: (_pn: string, n: number, sub: string): string => `Puede jugar. También puede romperse: un ${n} % hoy. ${sub ? `${sub} está fresco. ` : ''}Yo lo dejaría descansar.`,
    y_risk_rest_c: (pn: string, _n: number, sub: string): string => `Con esas piernas, no. ${pn} se queda fuera${sub ? ` y entra ${sub}` : ''}.`,
    y_risk_play: (_pn: string, n: number): string => `Va muy cargado, pero un ${n} % es un riesgo que asumiría. Que juegue y lo cambiamos pronto.`,
    y_risk_play_b: (_pn: string, n: number): string => `¿Un ${n} %? Esto es fútbol. Que juegue.`,
    y_risk_rr: (pn: string, n: number): string => `Forzamos la vuelta de ${pn}. Hay un ${n} % de que recaiga hoy. Yo lo dejaría fuera.`,
    y_rush_yes: (_pn: string, n: number): string => `Ya pasó la mitad. Si apretamos, vuelve antes. Hay un ${n} % de recaída en los tres próximos partidos. Yo lo haría.`,
    y_rush_no: (_pn: string, n: number): string => `Puedo acelerarlo, pero hay un ${n} % de que recaiga, y para más tiempo. Que se cure.`,
    y_intake: (pn: string, pos: string, n: number): string => `Ya están todos. Ojo con ${pn}: ${TIERS[n] ?? 'un prometedor'} ${pos}. Hay sitio para todos.`,
    y_intake_full: (pn: string, pos: string, n: number): string => `${pn} es el bueno: ${TIERS[n] ?? 'un prometedor'} ${pos}. Pero vamos por encima de la capacidad. Si nos quedamos con todos, todos aprenden más lento.`,
    y_ready: (pn: string, n: number): string => `${pn} ya está al nivel de nuestro jugador 18 (${n}). Entrenar con el primer equipo lo terminará de hacer.`,
    y_ready_v: (pn: string): string => `${pn} está cerca. Prefiero que antes juegue fútbol de mayores en otro sitio.`,
    y_loanee: (pn: string): string => `${pn} juega cada semana. Aún no ha dado el salto, pero esos minutos son los que hacen crecer a un jugador.`,
    y_loanee_up: (pn: string, n: number, s: string): string => `${pn} lleva ${s} minutos y ha subido ${n} esta temporada. Que siga allí.`,
    y_benched: (pn: string, n: number): string => `${pn} lleva ${n} minutos. Nos prometieron partidos. Repéscalo y búscale un club que lo ponga.`,
    y_full: (pn: string, n: number): string => `Demasiados chavales y poco entrenador. ${pn} es al que dejaría ir: techo en torno a ${n}.`,
    y_ageout_keep: (pn: string, n: number): string => `A ${pn} aún le queda algo, quizá ${n}. Dale un dorsal o una cesión.`,
    y_ageout_go: (pn: string): string => `${pn} no va a llegar aquí. Que se busque un club.`,
    why_y_rush: (pn: string, n: number): string => `${pn} ya pasó la mitad. ${n} % de riesgo, y lo necesitamos.`,
    why_y_rest: (pn: string, n: number): string => `${pn} tiene las piernas cargadas. Un ${n} % de que se rompa.`,
    why_y_loan: (pn: string): string => `${pn} necesita fútbol de mayores. Allí será titular.`,
    why_y_release: (pn: string): string => `Vamos por encima de la capacidad y ${pn} es el que menos opciones tiene.`,
  },
  choices: {
    y_ch_rush: (n: number): string => `Forzar la vuelta (${n} antes)`,
    y_ch_heal: (): string => 'Que se cure',
    y_ch_spec: (v: string): string => `Especialista (${v})`,
    y_ch_keepAll: (): string => 'Quedarse con todos',
    y_ch_trim: (n: number): string => (n === 1 ? 'Dejar ir al más flojo' : `Dejar ir a los ${n} más flojos`),
    y_ch_promote: (): string => 'Subirlo',
    y_ch_loan: (club: string): string => `Cederlo al ${club}`,
    y_ch_leave: (): string => 'Que siga allí',
    y_ch_word: (): string => 'Decirle que lo seguimos',
    y_ch_recall: (): string => 'Repescarlo',
    y_ch_release: (pn: string): string => `Dejar ir a ${pn}`,
  },
  fx: {
    y_fx_safe: (): string => 'Sin riesgo hoy',
    y_fx_risk: (n: number): string => `Riesgo de lesión ~${n} %`,
    y_fx_fragile: (n: number): string => `Frágil ${n} más`,
    y_fx_sooner: (n: number): string => `Vuelve ${n} antes`,
    y_fx_relapse: (n: number): string => `${n} % de recaída`,
    y_fx_heal: (n: number): string => `${n} más de baja`,
    y_fx_room: (n: number, cap: string): string => `${n} de ${cap} plazas`,
    y_fx_spread: (n: number, cap: string): string => `${n} para ${cap}: progreso más lento`,
    y_fx_letGo: (n: number): string => `${n} a la lista de libres`,
    y_fx_squad: (): string => 'Plantilla del primer equipo',
    y_fx_pledge: (): string => 'Promesa: 10 partidos en 20 jornadas, o cesión',
    y_fx_proWage: (): string => 'Sueldo de profesional',
    y_fx_starter: (): string => 'Allí sería titular',
    y_fx_rotation: (): string => 'Allí, rotación',
    y_fx_academyPace: (): string => 'Ritmo de cantera',
    y_fx_growing: (n: number): string => (n > 0 ? `+${n} esta temporada` : 'Minutos en el bolsillo'),
    y_fx_morale: (): string => 'Sube la moral',
    y_fx_home: (): string => 'Pierde sus minutos',
    y_fx_reloan: (): string => 'Cederlo de nuevo',
    y_fx_stall: (): string => 'Su progreso se frena',
    y_fx_focus: (): string => 'Mejor trabajo para el resto',
    y_fx_free: (): string => 'Agente libre',
  },

  news: {
    y_preview: (club: string, pos: string, tier: string): [string, string] => [`En la cantera del ${club} se habla de ${tier} ${pos.toLowerCase()}`, 'El director de cantera ya ha visto a la hornada. Llegan en diez jornadas.'],
    y_intake: (club: string, n: number, pn: string, pos: string): [string, string] => [`Nueva hornada en el ${club}: ${n} ${P(n, 'cara nueva', 'caras nuevas')}`, pn ? `El que todos miraban: ${pn}, ${pos.toLowerCase()}.` : 'Un grupo nuevo empieza hoy.'],
    y_rivalGem: (club: string, pn: string, pos: string, tier: string): [string, string] => [`El ${club} presenta a ${tier} ${pos.toLowerCase()}`, `${pn} llega a su cantera. Recuerda el nombre.`],
    y_breakthrough: (pn: string, club: string, n: string): [string, string] => [`${pn}, ${n} años, ya es fijo en el ${club}`, 'Diez partidos de liga esta temporada para el canterano.'],
    y_loaned: (pn: string, club: string): [string, string] => [`${pn} se marcha cedido al ${club}`, 'El canterano sale a buscar minutos.'],
  },
  msg: {
    y_preview: (pn: string, pos: string, tier: string): [string, string] => [`Director de cantera: ${tier} ${pos.toLowerCase()} en la hornada`, `He visto al nuevo grupo. Ojo con ${pn}. Llegan en diez jornadas.`],
    y_learned: (pn: string, pos: string): [string, string] => [`${pn} ya puede jugar de ${pos}`, 'El trabajo extra ha dado fruto. La alineación contará con él ahí.'],
    y_reinjured: (pn: string, n: number): [string, string] => [`${pn} ha recaído`, `Forzamos su vuelta. Estará ${n} jornadas más de baja.`],
    y_loanReport: (pn: string, n: number, s: string, club: string): [string, string] => [`Informe de cesión: ${pn} en el ${club}`, `${n} minutos esta temporada, ${Number(s) > 0 ? `ha subido ${s}` : Number(s) < 0 ? `ha bajado ${-Number(s)}` : 'igual'} desde el verano.`],
    y_devGone: (n: number): [string, string] => ['Adiós a los puntos de desarrollo', `Los ${n} puntos que quedaban se convirtieron en moral para la plantilla (+5). Ahora los jugadores crecen entrenando y jugando.`],
  },
  log: {
    'medical:y_rush': (pn: string, n: number): string => `Forzó la vuelta de ${pn} (${n} % de recaída)`,
    'medical:y_rest': (pn: string, n: number): string => `Dio descanso a ${pn}: ~${n} % de riesgo`,
    'academy:y_loan': (pn: string, club: string): string => `Cedió a ${pn} al ${club}`,
    'academy:y_release': (pn: string): string => `Dejó ir a ${pn} de la cantera`,
    'academy:promote': (pn: string): string => `Subió a ${pn} al primer equipo`,
  },
  note: { rushed: 'Ya entrena con el grupo.', promoted: 'Ya tiene dorsal del primer equipo.' },
  no: {
    congested: 'Dos partidos esta semana: sin trabajo intenso.', plans: 'El límite son cinco planes.', notYet: 'Demasiado pronto para forzarlo.', retired: 'Eso ya no existe: lo sustituyó la nueva hornada.',
    young: 'Demasiado joven para eso.', pos: 'Elige una posición que no juegue ya.', load: 'Elige suave, normal o intenso.', unknown: 'Eso ya no existe.',
  },
};
