// Tactics v3 copy, French (checked against lang-tac.ts).
import type { TxStrings } from './lang-tac';

export const TX_FR: TxStrings = {
  phase: { ip: 'Avec le ballon', oop: 'Sans le ballon' },
  phaseLong: { ip: 'En possession', oop: 'Hors possession' },
  shapeIp: 'Système avec ballon',
  shapeOop: 'Système sans ballon',
  same: 'Le même',
  roles: {
    keeper: ['Gardien', 'G', 'Reste dans ses buts et joue court vers ses défenseurs.'],
    distributor: ['Gardien relanceur', 'REL', 'Participe à la relance comme passeur en plus. Il faut un bon pied : un relanceur nerveux se fait prendre.'],
    defender: ['Défenseur central', 'DC', 'Défend d’abord et joue la passe simple.'],
    ball_player: ['Central relanceur', 'CR', 'Monte balle au pied jusqu’au milieu et cherche la passe vers l’avant. Il faut de la passe.'],
    fullback: ['Latéral', 'LAT', 'Soutient derrière l’action et reste disponible derrière.'],
    wingback: ['Piston', 'PIS', 'Monte jusqu’à la ligne : un homme de plus sur le côté, un trou dans son dos. Épuisant.'],
    inverted_fullback: ['Latéral inversé', 'LI', 'Rentre au milieu : un passeur de plus dans l’axe, moins de largeur.'],
    holder: ['Sentinelle', 'SEN', 'Se place devant la défense et recycle le ballon.'],
    playmaker: ['Meneur de jeu', 'MJ', 'Tout passe par lui : plus d’occasions pour les autres, moins de tirs pour lui. Il faut de la passe.'],
    midfielder: ['Milieu central', 'MC', 'Relie la défense et l’attaque.'],
    box_to_box: ['Box-to-box', 'B2B', 'Arrive lancé dans la surface : plus de tirs du milieu. Il faut du coffre, il se fatigue plus vite.'],
    attacking_mid: ['Milieu offensif', 'MO', 'Joue entre les lignes et alimente les attaquants.'],
    shadow_striker: ['Second attaquant', 'SA', 'Plonge derrière l’avant-centre dans la surface : plus de tirs, moins de passes.'],
    winger: ['Ailier', 'AIL', 'Reste large, élimine son vis-à-vis et centre.'],
    inside_forward: ['Ailier inversé', 'AI', 'Repique dans l’axe : tirs et centres en retrait plutôt que centres.'],
    advanced_forward: ['Avant-centre', 'AC', 'Joue sur le dernier défenseur et attaque la surface.'],
    target_man: ['Point d’appui', 'PA', 'La référence : ballons longs et centres pour sa tête. Il faut de la puissance.'],
    false_nine: ['Faux 9', 'F9', 'Décroche au milieu pour combiner : plus d’occasions pour les autres, moins de monde dans la surface.'],
    line_keeper: ['Gardien', 'G', 'Reste sur sa ligne.'],
    sweeper_keeper: ['Gardien libéro', 'LIB', 'Sort pour les ballons dans le dos. Une frappe lointaine peut le surprendre.'],
    hold_line: ['Tenir la ligne', 'LIG', 'Garde sa place dans la ligne défensive.'],
    step_out: ['Sortir au pressing', 'SOR', 'Va chercher son joueur tôt : récupère plus haut, fait plus de fautes, laisse de l’espace derrière.'],
    screen: ['Écran', 'ECR', 'Se replie devant la défense et ferme l’axe. Ne presse pas haut.'],
    ball_winner: ['Récupérateur', 'REC', 'Chasse le ballon au milieu : le récupère, fait plus de fautes, laisse un trou. Épuisant.'],
    hold_shape: ['Garder la forme', 'FOR', 'Garde sa place dans le bloc.'],
    track_back: ['Replier', 'REP', 'Suit le joueur qui monte de son côté.'],
    press_forward: ['Mener le pressing', 'PRE', 'Harcèle leurs défenseurs et le gardien : récupérations hautes, plus de fautes. Très épuisant.'],
    libero: ['Libéro', 'LIB', 'Sort de la ligne vers le milieu avec le ballon : un passeur de plus, un risque s’il le perd.'],
    half_back: ['Demi-défenseur', 'DD', 'Descend entre les centraux pour lancer le jeu : relance plus propre, un de moins au milieu.'],
    mezzala: ['Mezzala', 'MEZ', 'Glisse dans le demi-espace et arrive dans la surface : tirs et occasions excentrés. Fatigant.'],
    wide_playmaker: ['Meneur excentré', 'ME', 'Rentre du côté pour animer : plus d’occasions pour les autres, moins de centres.'],
    deep_forward: ['Attaquant en retrait', 'AR', 'Décroche pour garder et relier le jeu, puis rejoint l’attaque.'],
    poacher: ['Renard des surfaces', 'RS', 'Vit sur le dernier défenseur et dans la surface : plus de tirs, presque absent de la relance.'],
    cover: ['Couverture', 'COU', 'Reste en retrait pour couper les ballons dans le dos : moins d’appels qui passent, plus d’espace devant lui.'],
    press_fullback: ['Presser le latéral', 'PL', 'Attaque leur latéral dès qu’il reçoit : récupère plus haut sur son côté. Fatigant.'],
    tuck_in: ['Rentrer', 'RE', 'Se resserre au milieu sans ballon : ferme l’axe, laisse leur latéral libre.'],
    outlet: ['Rester devant', 'DEV', 'Ne défend pas : attend la contre. Contres plus rapides, un de moins dans le bloc.'],
  },
  roleFor: (phase: string) => `Rôle · ${phase}`,
  fit: ['Naturel', 'Adapté', 'Peut le faire', 'Inadapté'],
  suggest: 'Suggérer des rôles', suggested: 'Rôles réglés selon les joueurs',
  ins: {
    build: ['Relance', ['Courte', 'Mixte', 'Longue']],
    cpress: ['À la perte', ['Se replier', 'Équilibré', 'Contre-pressing']],
    counter: ['À la récupération', ['Garder', 'Contre immédiate']],
    trap: ['Piège de pressing', ['Aucun', 'Côtés', 'Axe', 'Demi-espaces']],
    routine: ['Corners', ['Variés', 'Les grands montent', 'À deux']],
    marking: ['Marquage', ['Zone', 'Mixte', 'Individuel']],
    setMark: ['Marquage sur coups de pied arrêtés', ['Zone', 'Mixte', 'Individuel']],
  },
  trade: {
    build: [['Gardien et centraux relancent au sol : plus de ballon.', 'Un bon pressing récupère près de notre but.'], ['Court quand c’est possible, long sinon.', 'Ni chaud ni froid.'], ['On saute leur pressing.', 'Plus de ballons disputés ; on le rend plus souvent.']],
    cpress: [['Tout le monde se replie : leurs contres se tarissent.', 'Ils gardent le ballon une fois qu’ils l’ont.'], ['Certains pressent, d’autres se replient.', 'Rien de spécial.'], ['On le récupère tout de suite, haut.', 'Épuisant ; plus de fautes tactiques ; s’ils passent, ils filent.']],
    counter: [['On le garde et on reconstruit.', 'Moins d’occasions rapides.'], ['On part dès qu’on le récupère.', 'Les milieux jouent plus bas pour lancer.']],
    trap: [['Pas de piège.', 'Pas de piège.'], ['On les pousse sur le côté et on les enferme.', 'L’axe est un peu plus ouvert.'], ['On les éloigne de l’axe.', 'Les côtés sont un peu plus ouverts.'], ['Un peu de pression partout.', 'Rien n’est vraiment fermé.']],
    routine: [['Des centres variés.', 'Rien de spécial.'], ['Les centraux montent : plus de têtes.', 'Moins de monde derrière si ça tourne mal.'], ['À deux pour garder le ballon.', 'Moins de tirs sur le corner lui-même.']],
    marking: [['Chacun tient sa zone : peu d’espace entre les lignes ; moins de fautes.', 'Les appels venus du côté et dans la surface trouvent de l’espace.'], ['Des zones, et le plus proche prend l’appel.', 'Rien de spécial.'], ['Chacun son joueur : serré sur les côtés et dans les airs.', 'Les marqueurs sont aspirés : plus d’espace au milieu ; plus de fautes.']],
    setMark: [['Des zones dans la surface : premier contact au premier poteau.', 'Ceux qui attaquent le ballon lancés gagnent plus de têtes.'], ['Quelques-uns en zone, les autres à l’homme.', 'Rien de spécial.'], ['Chacun un joueur dans la surface : moins de têtes libres.', 'Le second ballon à l’entrée de la surface reste libre.']],
  },
  trapOff: 'Un piège a besoin de pressing : réglez le pressing sur bloc médian ou plus.',
  advMore: (n: number) => (n ? `Plus de consignes · ${n} réglées` : 'Plus de consignes'), advLess: 'Moins de consignes', advWhy: 'L’essentiel est au-dessus. Ceci affine : bloc sans ballon, largeur, tempo, passes, transitions, coups de pied arrêtés, marquage.',
  mark: 'Marquage individuel', markNone: 'Personne', markHint: 'Il gagne beaucoup moins de duels ; son marqueur laisse un trou.',
  preview: {
    title: 'Ce que voit le moteur',
    sub: 'Joueurs dans chaque zone, les nôtres contre les leurs, avec les chiffres mêmes du match',
    rest: (n: string) => `${n} restent derrière quand on attaque`,
    line: (n: number) => `Ligne défensive à ${n} % du terrain`,
    press: (n: string) => `${n} pressent leur relance`,
    box: (n: string) => `${n} attaquent la surface`,
    zones: { build: 'Relance', mid: 'Milieu', final: 'Dernier tiers', box: 'Surface', press: 'Leur relance', screen: 'Milieu', defend: 'Notre tiers' },
  },
  warn: {
    title: 'Risques',
    none: 'Rien d’évident. Le moteur valide le plan.',
    fit: (p: string, role: string) => `${p} est inadapté comme ${role} : le rôle tourne à moitié et il joue sous son niveau.`,
    rest: (n: string) => `Seulement ${n} restent derrière quand on attaque. À la perte, on s’expose à la contre.`,
    pressAlone: (p: string, role: string) => `${p} doit ${role.toLowerCase()} alors que l’équipe attend : il presse seul et se fait éliminer.`,
    trapOff: 'Le piège de pressing ne sert à rien sans pressing.',
    slowLine: (p: string) => `${p} manque de vitesse pour une ligne haute : les ballons dans le dos feront mal.`,
    noBox: 'Des centres et des ballons longs, mais presque personne dans la surface.',
    outlets: (n: number) => `${n} joueurs restent devant sans ballon : le bloc manque de monde.`,
  },
  why: {
    won: (a: string, role: string, n: number) => `${a} a récupéré le ballon ${n} fois comme ${role}.`,
    shots: (a: string, role: string, n: number, x: string) => `${a} a tiré ${n} fois comme ${role} (${x} xG).`,
    made: (a: string, role: string, n: number, x: string) => `${a} a créé ${n} occasions comme ${role} (${x} xG).`,
    themWon: (a: string, role: string, n: number) => `Leur ${role.toLowerCase()} ${a} a récupéré le ballon ${n} fois.`,
    themShots: (a: string, role: string, n: number, x: string) => `Leur ${role.toLowerCase()} ${a} a tiré ${n} fois (${x} xG).`,
    themMade: (a: string, role: string, n: number, x: string) => `Leur ${role.toLowerCase()} ${a} a créé ${n} occasions (${x} xG).`,
    head: ['Le rôle qui a marché', 'Leur rôle qui nous a fait mal'],
  },
  change: (p: string, role: string) => `${p} : ${role}`,
  live: { roles: 'Rôles', rolesSub: 'Les changements comptent dès la minute suivante.' },
};
