// Text for the v0.12 features (navigation, manager hub, matchday, transfers, staff room, history, support).
// English is the reference; Arabic (Egyptian), Spanish and French are type-checked against it in lang-new-*.ts.
import type { Duty } from './model/types';

export interface LogArgs { pn: string; n: number; s: string; club: string; money: (v: number) => string }
type LogFn = (a: LogArgs) => string;

const P = (n: number, one: string, many: string) => (n === 1 ? one : many);

export const NEW_EN = {
  // Navigation
  tabs: ['Home', 'Squad', 'Match', 'Transfers', 'Club'],
  hospitalT: 'Medical',
  hospitalSub: (n: number) => (n ? `${n} injured` : 'Everyone fit'),
  settingsMore: 'Settings and more',
  settingsMoreSub: 'Language, saves, world editor, quick match, privacy',

  // Manager hub
  today: (n: number) => (n ? `Today: ${n} ${P(n, 'thing needs', 'things need')} you` : 'All clear'),
  allClear: 'Nothing needs you before the next match.',
  todayItems: {
    offers: (n: number) => `${n} ${P(n, 'bid', 'bids')} for your players`,
    contracts: (n: number) => `${n} ${P(n, 'contract ends', 'contracts end')} this season`,
    unavailable: (n: number) => `${n} ${P(n, 'starter is', 'starters are')} injured or banned`,
    tired: (n: number) => `${n} ${P(n, 'starter is', 'starters are')} tired`,
    windowOpen: (left: number) => `Transfer window open: ${left} ${P(left, 'matchday', 'matchdays')} left`,
    deadline: 'Deadline day: the window shuts after this matchday',
    sponsors: (n: number) => `${n} sponsor ${P(n, 'slot is', 'slots are')} empty`,
    red: 'The club is in the red',
    thin: (n: number) => `Only ${n} players in the squad`,
    jobs: (n: number) => `${n} ${P(n, 'club wants', 'clubs want')} to talk to you`,
    dev: (n: number) => `${n} development points to spend`,
    staff: (n: number) => `Your staff did ${n} ${P(n, 'thing', 'things')} since the last match`,
    board: (n: number, d: number) => `Board confidence ${n}: ${d === 1 ? 'one more defeat' : `${d} more defeats`} and you’re out`,
  },
  todayActions: { offers: 'Answer', contracts: 'Renew', unavailable: 'Fix XI', tired: 'Rotate', windowOpen: 'Market', deadline: 'Market', sponsors: 'Sign', red: 'Finances', thin: 'Sign players', jobs: 'See offers', dev: 'Train', staff: 'See log', board: 'Board' },
  formT: 'Form',
  formLetters: ['W', 'D', 'L'] as [string, string, string],
  nextMatchT: 'Next match',

  // Matchday
  ev2: {
    goal: [
      (p: string, c: string) => `GOAL! ${p} scores for ${c}.`,
      (p: string, c: string) => `GOAL! ${p} finds the corner. ${c} celebrate.`,
      (p: string, c: string) => `GOAL for ${c}! ${p} makes no mistake.`,
      (p: string, c: string) => `GOAL! ${p} buries it. The ${c} fans are up.`,
      (p: string, c: string) => `GOAL! Clinical from ${p}. ${c} strike.`,
    ],
    miss: [
      (p: string) => `${p} fires wide.`,
      (p: string) => `${p} drags it past the post.`,
      (p: string) => `Over the bar from ${p}.`,
      (p: string) => `${p} snatches at it. Wide.`,
      (p: string) => `${p} goes for goal from distance. Nowhere near.`,
      (p: string) => `Half-chance for ${p}, but it's wide.`,
    ],
    save: [
      (p: string) => `Big save from ${p}.`,
      (p: string) => `${p} gets down well to keep it out.`,
      (p: string) => `Fingertips! ${p} tips it round the post.`,
      (p: string) => `${p} stands tall and blocks it.`,
      (p: string) => `Strong hands from ${p}.`,
      (p: string) => `${p} reads it and gathers.`,
    ],
    yellow: [
      (p: string) => `Yellow card for ${p}.`,
      (p: string) => `${p} goes into the book.`,
      (p: string) => `Late from ${p}. Yellow.`,
      (p: string) => `${p} is booked for pulling back his man.`,
    ],
    red: [
      (p: string) => `RED CARD! ${p} is sent off.`,
      (p: string) => `RED! ${p} has to go. Down to ten.`,
      (p: string) => `Off he goes: ${p} sees red.`,
    ],
    injury: [
      (p: string) => `${p} is hurt and can’t go on.`,
      (p: string) => `${p} pulls up. The physio waves for a change.`,
      (p: string) => `Bad news: ${p} limps off.`,
    ],
    sub: [
      (off: string, on: string) => `Sub: ${on} comes on for ${off}.`,
      (off: string, on: string) => `Change: ${off} off, ${on} on.`,
      (off: string, on: string) => `Fresh legs: ${on} replaces ${off}.`,
    ],
  },
  ratingT: 'Rating',
  ratingsT: 'Ratings',
  motm: 'Man of the match',
  motmN: (n: number) => `${n}× man of the match`,
  avgRatingT: 'Avg rating',
  xgT: 'Expected goals (xG)',
  ftTitle: { W: 'Win', D: 'Draw', L: 'Defeat' } as Record<'W' | 'D' | 'L', string>,
  ftSub: 'What the result changed',
  ftPos: 'League position',
  ftBoard: 'Board confidence',
  ftFans: 'Fans',
  ftDev: 'Development points',
  ftOut: (name: string, n: number) => `${name}: out for ${n} ${P(n, 'matchday', 'matchdays')}`,
  ftBan: (name: string) => `${name}: suspended`,
  ftRecord: 'New club record',
  ftMilestone: 'Milestone reached',
  ftContinue: 'Continue',

  // Transfer windows
  windowNames: { summer: 'Summer window', winter: 'Winter window' } as Record<'summer' | 'winter', string>,
  windowOpenT: (left: number) => `Open: ${left} ${P(left, 'matchday', 'matchdays')} left`,
  windowShutT: (n: number) => `Window shut: opens in ${n} ${P(n, 'matchday', 'matchdays')}`,
  deadlineT: 'Deadline day',
  deadlineSub: 'Last chance: the window shuts after this matchday. Clubs bid more today.',
  windowClosedBid: 'The transfer window is shut. You can still sign free agents.',

  // Transfers hub
  transfersT: 'Transfers',
  trTabs: ['Market', 'Shortlist', 'Bids', 'Loans', 'Deals'],
  shortlistAdd: 'Shortlist',
  shortlistRemove: 'Remove from shortlist',
  shortlistEmpty: 'No players shortlisted. Players you shortlist appear here, and your scouts pin down their real level.',
  findPlayers: 'Find players',
  offersEmpty: 'No bids for your players right now. Bids arrive while a window is open, more often for listed players.',
  answerBids: 'Answer bids',
  dealsEmpty: 'No deals yet. Signings, sales and free transfers are listed here.',
  loansInT: 'On loan here',
  loansOutT: 'Out on loan',
  loansEmpty: 'No loans this season. Borrow players outside other clubs’ best XI, or send young players out to get games.',
  loanHint: 'Loans last the season. The borrowing club pays the wage. Young players come back better.',
  loanInBtn: (fee: string) => `Loan for the season · ${fee}`,
  loanOutBtn: 'Loan out',
  loanTo: 'Loan him to',
  loanFrom: (club: string) => `On loan from ${club}`,
  loanAt: (club: string) => `On loan at ${club}`,
  loanReason: {
    window: 'Loans only happen while a window is open.', budget: 'Not enough budget for the loan fee.', wageCap: 'His wage would break the wage cap.',
    squad: 'Squad size limit reached.', key: 'A first-team regular there: not for loan.', limit: 'You already have 4 loans that way.',
    free: 'Free agents sign, they don’t loan.', loaned: 'Already on loan.', injured: 'Injured players can’t move on loan.',
    lenderThin: 'They won’t lend: it would leave them under 16 players.', club: 'That club can’t take him.',
  } as Record<string, string>,
  loanedIn: (name: string) => `${name} joins on loan.`,
  loanedOut: (name: string, club: string) => `${name} joins ${club} on loan.`,
  noLoanClubs: 'No club at his level wants him on loan right now.',
  estimateT: 'Scout estimate',
  estHint: 'Shortlist him and your scouts pin down his real level within 2 matchdays.',

  // Squad
  showT: 'Show',
  squadViews: ['Rating', 'Fitness', 'Contract', 'Value', 'Form'],

  // Match hub
  matchTabs: ['Next', 'Table', 'Results', 'Cups', 'Stats'],
  leaderTabs: ['Goals', 'Assists', 'Ratings'],
  worldRankings: 'World rankings',

  // Club hub
  boardT: 'Board and objectives',
  staffRoomT: 'Staff room',
  staffRoomSub: (n: number, all: number) => (n ? `${n} of ${all} duties delegated` : 'You run everything. Delegate what you like.'),
  financesT: 'Finances',
  ticketsT: 'Tickets',
  sponsorsT: 'Sponsors',
  facilitiesT: 'Facilities',
  hireStaffT: 'Hire staff',
  historyT: 'History and records',
  historySub: 'Seasons, records, trophies, academy graduates',

  // Staff room
  staffIntro: 'Hand any job to your staff. They do it every matchday, as well as their quality allows. You always play the matches.',
  staffYours: 'Your staff',
  qualityT: 'Quality',
  dutiesT: 'Duties',
  dutyGroups: { matchday: 'Matchday', squad: 'Squad', transfers: 'Transfers', club: 'Club' } as Record<string, string>,
  duties: {
    lineup: ['Line-up and subs', 'Picks the best XI for every match.'],
    tactics: ['Tactics', 'Chooses the shape and mentality for each opponent.'],
    scouting: ['Opponent reports', 'Buys a report before tough matches and uses its counter plan.'],
    training: ['Training', 'Sets the training load and spends development points.'],
    medical: ['Medical', 'Pays for rehab on longer injuries.'],
    morale: ['Morale', 'Gives a team talk when morale drops.'],
    academy: ['Academy', 'Scouts prospects, promotes the ready ones, sells the rest.'],
    contracts: ['Contracts', 'Renews players worth keeping from matchday 5.'],
    selling: ['Selling', 'Answers bids and lists surplus players.'],
    signing: ['Signings', 'Signs a player for the thinnest position while a window is open.'],
    loans: ['Loans', 'Sends young players out on loan to get games.'],
    sponsors: ['Sponsors', 'Signs the best offer for every empty slot.'],
    tickets: ['Ticket prices', 'Sets the price that earns most without emptying the stands.'],
  } as Record<Duty, [string, string]>,
  matchDuty: ['Play the match', 'Always you.'] as [string, string],
  meT: 'Me',
  staffT: 'Staff',
  delegateAll: 'Hand everything to staff',
  takeAll: 'Do it all myself',
  needStaff: (role: string) => `Hire a ${role.toLowerCase()} first`,
  staffLogT: 'What your staff did',
  staffLogEmpty: 'Nothing yet. Delegate a duty and your staff log what they do here.',
  staffLog: {
    'training:load': (a) => `Training load set to ${['recovery', 'balanced', 'hard'][a.n] ?? 'balanced'}.`,
    'training:dev': (a) => `Spent development points on ${a.pn} (+1 rating).`,
    'medical:rehab': (a) => `Paid for rehab: ${a.pn}.`,
    'morale:talk': (a) => `Team talk: morale was ${a.n}.`,
    'academy:promote': (a) => `Promoted ${a.pn} from the academy.`,
    'academy:sold': (a) => `Sold the rights to ${a.pn} for ${a.money(a.n)}.`,
    'academy:scouted': (a) => `Found ${a.n} new ${P(a.n, 'prospect', 'prospects')}.`,
    'selling:sold': (a) => `Sold ${a.pn} to ${a.club} for ${a.money(a.n)}.`,
    'selling:rejected': (a) => `Turned down ${a.money(a.n)} for ${a.pn}.`,
    'selling:listed': (a) => `Put ${a.pn} on the transfer list.`,
    'contracts:renewed': (a) => `Renewed ${a.pn} for ${a.n} more ${P(a.n, 'season', 'seasons')}.`,
    'contracts:capRaise': (a) => `Raised the wage cap by ${a.money(a.n)} a month to keep ${a.pn}.`,
    'signing:signed': (a) => `Signed ${a.pn} from ${a.club || 'free agency'} for ${a.n ? a.money(a.n) : 'free'}.`,
    'loans:out': (a) => `Loaned ${a.pn} to ${a.club}.`,
    'sponsors:signed': (a) => `Signed ${a.pn} as a sponsor: ${a.money(a.n)} a month.`,
    'tickets:price': (a) => `Ticket price set to ${a.s}.`,
    'tactics:formation': (a) => `Switched to ${a.s}.`,
    'scouting:report': (a) => `Bought a report on ${a.club}.`,
  } as Record<string, LogFn>,
  staffNames2: { director: 'Sporting director' } as Record<string, string>,
  staffEffects2: { director: 'Contracts, bids, signings, loans, sponsors and tickets when you delegate them' } as Record<string, string>,
  ledgerKeys2: { loans: 'Loan fees' } as Record<string, string>,

  // G1 (integrity and UX fixes)
  wagesOfCap: 'Wages, of cap',
  newEnd: (y: number) => `New end: ${y}`,
  resumedFrom: (min: number) => `Resumed from ${min}′`,
  playingT: (what: string) => `Playing ${what}…`,
  saveRefused: (why: string) => `Couldn’t save: ${why}`,
  tacticsTabs: ['Shape', 'Style', 'Set pieces'] as [string, string, string],
  confirmSub: (off: string, on: string) => `Confirm sub: ${off} ↔ ${on}`,
  pickSubHint: 'Pick who goes off and who comes on.',
  detailsT: 'Details',
  hideDetailsT: 'Hide details',
  radarLocked: 'Scout the opponent to see their profile.',

  // History
  histTabs: ['Seasons', 'Records', 'Trophies', 'Academy'],
  seasonsEmpty: 'Your first season is still going. Finished seasons are kept here.',
  recordsEmpty: 'Records appear once you’ve played some games.',
  trophiesEmpty: 'No trophies yet. Win a league or a cup and it goes in the cabinet.',
  gradsEmpty: 'No academy graduates yet. Promote a prospect and follow his story here.',
  recordNames: {
    bigWin: 'Biggest win', mostPoints: 'Most league points', mostGoals: 'Most league goals', unbeaten: 'Longest unbeaten run',
    scorer: 'Top scorer in a season', bestFinish: 'Best league finish', bestBuy: 'Record signing', bestSale: 'Record sale',
  } as Record<string, string>,
  gamesN: (n: number) => `${n} ${P(n, 'game', 'games')}`,
  gradLine: (apps: number, goals: number) => `${apps} apps · ${goals} goals this season`,
  trophyKinds: { league: 'League title', cup: 'Cup', continental: 'Continental cup', promotion: 'Promotion' } as Record<string, string>,

  updWeb: (v: string) => `The Gaffer ${v} is ready: new fixes and features.`,
  updWebBtn: 'Update now',
  updApk: (v: string) => `App update ${v} is out. Install it to keep getting updates.`,
  updApkBtn: 'Download',
  updLater: 'Later',
  // Support and looks
  supportT: 'Support The Gaffer',
  supportBody: 'A one-off Supporter pack: every club look, a Supporter badge on your coach card, and no ads. The game itself stays complete for everyone.',
  supportBtn: 'Get the Supporter pack',
  supportSoon: 'The Supporter pack opens soon.',
  supporterBadge: 'Supporter',
  supportThanks: 'Thanks for backing The Gaffer. Everything is unlocked.',
  looksT: 'Look',
  looks: ['Teal', 'Floodlight', 'Pitch', 'Derby red'],
  looksLocked: 'Supporter pack',
  rewardedBtn: 'Watch a short ad: free report',
  rewardedHint: 'Optional. You can always buy the report with club money.',
  adFailed: 'No ad right now. Try again later.',
  sponsoredT: 'Sponsored',
  howToBody2: [
    ['Your job', 'Pick a club and sign the contract. The board sets objectives for the league and the cup. Meet them and your reputation grows; miss them and you can be sacked.'],
    ['Home', 'Home lists what needs you today, each with one button. Clear it, then play the next match.'],
    ['Matchdays', 'Tap Play the match to watch it live, or take a quick result. Every match ends with ratings, a man of the match and a card showing what the result changed.'],
    ['Tactics', 'Pick a formation, the XI, mentality, pressing and passing. Philosophies beat each other like rock, paper, scissors, and your mastery of one grows every game. Scout the opponent before the big ones.'],
    ['Your staff', 'Club › Staff room: hand any duty to your staff (line-up, training, contracts, signings and more) or do it yourself. You always play the matches.'],
    ['Transfers', 'Buy and sell while a window is open (summer and winter, deadline day last). Free agents sign any time. Shortlist players so your scouts learn their real level, and loan players in or out for the season.'],
    ['Money', 'Tickets, TV and sponsors come in; wages, staff and upkeep go out. Build facilities, hire staff, and end the season in the black.'],
    ['Cups', 'Your national cup is knockout from the start. Continental cups start with groups of four: the top two go through.'],
    ['Your career', 'Earn XP and licences, take courses, collect milestones and trophies, and set club records. Bigger clubs will call.'],
    ['Saving', 'The career saves itself after every match and is checked when it loads. Export a save file from Club › Settings and more.'],
  ] as [string, string][],
  privacyBody2: [
    ['What we keep', 'Your career, settings and coach photo are saved on this device only. Update checks ask Semba Games for the latest version number and send no career data.'],
    ['Online features', 'Ads and purchases, when switched on, are clearly labelled. Web ads come from Google AdSense, which may use cookies to show and measure ads. Purchases are handled by Stripe; we never see your card.'],
    ['No account', 'The Gaffer has no sign-in. Your career lives on your device, and you can export it any time from Settings.'],
    ['Save files', 'A save you export goes where you choose. Importing only reads the file you pick.'],
    ['Photos', 'A photo you add to your coach card stays on this device and is only used to draw the card.'],
    ['Deleting your data', 'Start over from Settings, or clear the app’s data, and everything is gone.'],
    ['Contact', 'Questions? sembagames.app'],
  ] as [string, string][],

  // Match engine v2: instructions (each option's effect and its price), live match, the assistant's "Why", commentary.
  // Placeholders in {braces} are filled in by the UI: {s} shooter, {a} assist or attacker, {d} defender, {k} keeper,
  // {b} blocker, {c} club, {n} {of} {x} {y} numbers, {min} minute, {what} a change, {theme} a kind of chance.
  philosophyHints: {
    balanced: 'Every instruction in the middle. The side knows it by heart.',
    possession: 'Short passing, slow tempo, inverted full-backs, a false 9. Hurts tired or deep sides; needs passers.',
    counter: 'Sit deeper, break at once, go direct. Deadly against sides that push up.',
    gegenpress: 'High line, high press, fast tempo. Wins it near goal; tiring, and good passers can play through it.',
    bus: 'Everyone behind the ball, narrow, counters. Hardest to score against; hardest to score with.',
    wings: 'Wide, overlapping full-backs, big men up at corners. Needs quick wingers against slow full-backs.',
    direct: 'Long balls to a target man, fast tempo. Skips a high press; needs a strong striker.',
  } as Record<string, string>,
  eng: {
    comma: ', ',
    ins: {
      mentality: { t: 'Mentality', o: ['Park the bus', 'Defensive', 'Balanced', 'Attacking', 'All-out attack'], h: [
        'Everyone behind the ball. Very hard to break down, but you will barely threaten.',
        'Full-backs stay home and fewer runners join attacks. Safer, less dangerous.',
        'Even numbers in attack and at the back.',
        'More bodies in the box and more shots, but fewer players left behind when you lose it.',
        'Throw everyone forward. Chances galore both ways: you will be caught on the break.',
      ] },
      pressing: { t: 'Pressing', o: ['Low block', 'Mid block', 'High press'], h: [
        'Let them have it in their half. Fresher legs, fewer fouls, but they build up in peace.',
        'Press in midfield when the trigger is right.',
        'Hunt the ball in their third: turnovers near goal, but tiring, more fouls, and a good passing side can play through you.',
      ] },
      line: { t: 'Defensive line', o: ['Deep', 'Normal', 'High'], h: [
        'Drop off: no space in behind, but they get more time on the ball in midfield.',
        'A normal line.',
        'Squeeze the pitch and catch them offside, but quick forwards will run in behind you.',
      ] },
      width: { t: 'Width', o: ['Narrow', 'Normal', 'Wide'], h: [
        'Crowd the middle: more combinations centrally, fewer crosses.',
        'Balanced use of the pitch.',
        'Stretch them: wingers and full-backs go one-on-one, more crosses. Best with quick wide players.',
      ] },
      tempo: { t: 'Tempo', o: ['Slow', 'Normal', 'Fast'], h: [
        'Keep the ball and wait for a gap: more possession, fewer turnovers, fewer chances.',
        'Normal tempo.',
        'Play forward quickly before they set: more attacks and counters, more balls lost, more tiring.',
      ] },
      passing: { t: 'Passing', o: ['Short', 'Mixed', 'Direct'], h: [
        'Play out from the back. Needs good passers; a high press can hurt you.',
        'Short when you can, long when you must.',
        'Go long to the forwards: skips their press, but you lose more second balls.',
      ] },
      fullback: { t: 'Full-backs', o: ['Classic', 'Overlapping', 'Inverted'], h: [
        'Stay home: solid, but no extra man on the wing.',
        'Bomb on: two against one on the flanks, but a big gap behind them on the break.',
        'Step into midfield: an extra passer in the middle, less width.',
      ] },
      striker: { t: 'Striker', o: ['Advanced', 'Target man', 'False 9', 'Pressing'], h: [
        'Plays on the last defender.',
        'A focal point for crosses and long balls. Needs a strong forward.',
        'Drops into midfield to overload it, but fewer bodies in the box.',
        'Leads the press from the front. Tiring.',
      ] },
      trap: { t: 'Pressing trap', o: ['None', 'Wings', 'Centre', 'Half-spaces'], h: [
        'No trap.',
        'Show them wide and swarm the touchline. Leaves the middle a bit looser.',
        'Force them away from the middle. Leaves the flanks a bit looser.',
        'Press every lane a little. Needs pressing to be on.',
      ] },
      routine: { t: 'Corners', o: ['Mixed', 'Big men up', 'Short'], h: [
        'A mix of deliveries.',
        'Centre-backs go up: more headers, but fewer defenders back if it breaks down.',
        'Work it short: keeps the ball, fewer shots from the corner itself.',
      ] },
      counter: { t: 'Counter at once', h: 'Break the moment you win it. More counter-attacks; your midfield sits a little deeper.' },
      waste: { t: 'Run the clock', h: 'Slow every restart when you lead. Fewer chances both ways, and a booking now and then.' },
      mark: { t: 'Man-mark', none: 'Nobody', h: 'Put a shadow on their danger man: he wins far fewer duels, but the marker leaves a hole.' },
      formation: 'Shape',
      on: 'On', off: 'Off',
    },
    styleHint: 'Choosing a philosophy sets these instructions; fine-tune them below.',
    assistantPick: 'Your assistant would change',
    // live match
    momentum: 'Momentum',
    territory: 'Territory',
    xgFrom: 'Where the chances came from',
    statsMore: ['Big chances', 'Offsides', 'Final-third entries', 'Balls won high'] as string[],
    themes: { centre: 'Through the middle', wide: 'Down the flanks', behind: 'In behind', counter: 'On the break', press: 'Winning it high', setpiece: 'Set pieces', long: 'From distance', pen: 'Penalties' } as Record<string, string>,
    themeIn: { centre: 'through the middle', wide: 'down the flanks', behind: 'in behind us', counter: 'on the break', press: 'from winning it high', setpiece: 'from set pieces', long: 'from distance', pen: 'from the spot' } as Record<string, string>,
    goalFlash: 'GOAL!',
    soundOn: 'Sound on', soundOff: 'Sound off',
    // the assistant's "Why" card
    whyHT: 'Half-time: what’s going on',
    whyFT: 'Why it finished like that',
    assistant: 'Your assistant',
    verdict: {
      deserved: 'We earned that. {xa} xG to {xb}: the score tells the truth.',
      smash: 'We’ll take it, but they made more ({xb} xG to our {xa}). We were ruthless when it mattered.',
      robbed: 'We were the better side, {xa} xG to {xb}, and we’ve nothing to show for it. Keep doing that and the goals come.',
      beaten: 'No complaints: they created more ({xb} xG to {xa}). We need to look at why.',
      clinical: 'Ruthless: {ga} goals from {xa} xG.',
      wasteful: 'We made the chances ({xa} xG) and didn’t put them away.',
      level: 'Nothing in it: {xa} xG to {xb}.',
      even: 'They’ve had the better of it ({xb} xG to {xa}). We can’t complain about the score.',
    } as Record<string, string>,
    point: {
      sourceMe: 'Our best stuff came {theme}: {x} xG from {n} shots.',
      sourceMe1: 'Our best stuff came {theme}: {x} xG from a single shot.',
      sourceThem1: 'Most of their danger came {theme}: {x} xG from a single shot.',
      sourceThem: 'Most of their danger came {theme}: {x} xG from {n} shots.',
      midfieldMe: 'We own the midfield: {x}% of our moves get through, they manage {y}%.',
      midfieldThem: 'They’re winning the midfield: {y}% of their moves get through, only {x}% of ours.',
      pressed: 'Their press is hurting us: {n} balls lost in our own third.',
      pressedXg: 'Their press is hurting us: {n} balls lost in our own third, {x} xG straight from our mistakes.',
      pressing: 'Our press is working: {n} balls won high up the pitch.',
      duelMeWin: '{a} is tearing {d} apart: {n} of {of} duels won.',
      duelMeLose: '{d} has {a} in his pocket: {n} of {of} won by the defender.',
      duelThemWin: '{a} is getting the better of {d}: {n} of {of} duels.',
      duelThemLose: '{d} has shut {a} out: {n} of {of} won.',
      finishMeGood: 'Clinical: {n} goals from {x} xG.',
      finishMeBad: 'We’re wasteful: {n} from {x} xG.',
      finishThemGood: 'They’ve been wasteful: {n} from {x} xG. Don’t count on that twice.',
      finishThemBad: 'They’re punishing us: {n} goals from only {x} xG.',
      keeperMe: '{a} is keeping us in it: {n} saves, {x} xG kept out.',
      keeperThem: 'Their keeper {a} is having a day: {n} saves.',
      tiredMe: 'We ran out of legs: {n}% fitness late on, they had {y}%.',
      tiredThem: 'Their legs went ({n}% fitness) and that’s when we struck.',
      redMe: '{a}’s red card on {min}′ changed everything.',
      redThem: 'Their red card on {min}′ opened it up.',
      changeGood: 'The switch on {min}′ ({what}) worked: our xG rate went from {x} to {y} per 90.',
      changeBad: 'The switch on {min}′ ({what}) hasn’t worked: our xG rate {x} → {y} per 90.',
      theyChanged: 'Their bench reacted at {min}′: {what}.',
    },
    tipsHT: 'What I’d change',
    tipsFT: 'Next time against them',
    tipWhy: {
      centreMe: 'more chances through the middle', wideMe: 'more joy down the flanks', wideMeAD: '{a} can get at {d} down the flank',
      behindMe: 'more balls in behind', behindMeAD: '{a} can run in behind {d}', counterMe: 'more counter-attacks', counterMeA: 'more counters for {a}',
      pressMe: 'we win it high more often', setpieceMe: 'more from set pieces', longMe: 'more shots from distance', penMe: 'more penalties won',
      centreThem: 'fewer chances for them through the middle', wideThem: 'fewer crosses and cutbacks against us', wideThemA: 'shuts {a} down on the flank',
      behindThem: 'nobody gets in behind us', behindThemA: 'stops {a} running in behind', counterThem: 'cuts out their counters', counterThemA: 'cuts out {a} on the break',
      pressThem: 'gets us out of their press', setpieceThem: 'fewer set pieces against us', longThem: 'fewer shots from distance against us', penThem: 'fewer penalties conceded',
    } as Record<string, string>,
    winChance: 'Win chance {w0}% → {w1}%',
    apply: 'Make the change',
    applied: 'Change made',
    noTips: 'I wouldn’t change a thing.',
    shape: (f: string) => `Shape ${f}`,
    // tactic changes in the commentary
    reason: { chase: 'chasing the game', protect: 'protecting the lead', red: 'after the red card', tenmen: 'against ten men', tip: '', read: 'reading the first half', prep: 'set up for this opponent', wx3: 'in the wind', wx4: 'in the heat' } as Record<string, string>,
    changeLine: '{c}: {what}{why}.',
    talkLine: '{c} have their half-time talk: “{what}”.',
    // commentary pools: a chance is a build-up clause and a finish; lines never repeat within a match
    c: {
      box: ['{a} threads it into {s}', 'a one-two on the edge of the box frees {s}', '{s} finds half a yard in a crowded box', '{s} spins sharply in the area', 'quick passing through the middle opens it up for {s}', '{s} drives at the heart of the defence'],
      cutback: ['{s} meets a cutback from the byline', '{a} reaches the byline and cuts it back for {s}', '{a} skips past {d} and pulls it back to {s}', 'a low cutback from {a} finds {s}', '{a} goes outside {d}, looks up, and {s} is arriving'],
      header: ['{s} rises to meet the cross', '{s} gets his head to a cross from the flank', '{a} whips in a cross and {s} rises', '{s} attacks {a}’s delivery', 'a deep cross from {a} is met by {s}', '{s} gets across his man to {a}’s cross'],
      through: ['{a} splits the defence and {s} is clean through', '{s} beats the line onto {a}’s pass', 'one ball over the top and {s} is away', '{s} runs off the shoulder and he’s through'],
      counter: ['{s} breaks at speed after the turnover', 'a lightning counter ends with {s}', 'three passes and {s} is bearing down on goal', '{c} break two-on-one and {s} has the ball'],
      press: ['{s} pounces on a loose pass high up the pitch', 'the press forces an error and {s} is in', '{s} robs the last man and goes for goal', 'hunted down in their own third, and {s} takes aim'],
      long: ['{s} lets fly from 25 yards', '{s} tries his luck from distance', 'the ball sits up for {s} outside the box', '{s} shapes to shoot from range'],
      corner: ['{s} climbs highest from {a}’s corner', 'from {a}’s corner, {s} gets the header in', '{s} flicks on at the near post', 'a big leap from {s} at the corner'],
      set: ['{a}’s free-kick is met by {s}', '{s} gets on the end of the set piece', 'the free-kick is swung in and {s} attacks it'],
      fk: ['{s} curls the free-kick over the wall', '{s} steps up to the free-kick', '{s} goes for goal from the dead ball'],
      pen: ['{s} steps up from the spot', '{s} places the ball on the spot, eyes on {k}'],
      goal: ['and scores!', 'GOAL! Right into the corner.', 'and buries it!', 'and it’s in!', 'in off the post!', 'no mistake. GOAL!', 'and the net bulges!', 'past {k}. GOAL!'],
      save: ['but {k} saves.', 'but {k} gets down to it.', '{k} tips it round the post.', 'straight at {k}.', '{k} stands tall and blocks.', 'a strong hand from {k}.'],
      miss: ['but it flies over.', 'just wide.', 'skews it wide.', 'off target.', 'over the bar.', 'wide of the far post.'],
      block: ['blocked by {b}!', '{b} throws himself in the way.', 'charged down.', 'deflected away by {b}.'],
      after: {
        lead: ['{c} lead!', '{c} in front!'], equal: ['That’s the equaliser!', 'All square!'], more: ['{c} extend the lead.', 'That should settle it.'],
        late: ['A late, late goal!', 'Drama at the death!'], brace: ['That’s two for {s}.'], hat: ['Hat-trick for {s}!'], back: ['{c} pull one back.', 'Game on!'],
      },
      yellow: ['{s} goes into the book.', 'Yellow card for {s}.', 'The referee books {s}.', '{s} sees yellow for that challenge.'],
      yellowWaste: ['{s} is booked for time-wasting.'],
      red: ['RED CARD! {s} is sent off.', '{s} is off! Down to ten.'],
      injury: ['{s} is down and can’t continue.', 'Bad news: {s} is injured.'],
      sub: ['{c} change: {a} on, {s} off.', '{a} comes on for {s}.', 'Fresh legs: {a} replaces {s}.'],
      offside: ['{s} is flagged offside.', 'The flag goes up against {s}.'],
      corner2: ['Corner to {c}.'],
      flow: {
        camp: ['{c} are camped in the final third.', '{c} have them pinned back.', 'Wave after wave from {c}.'],
        press: ['{c} are hunting the ball high up the pitch.', 'The {c} press is suffocating.'],
        calm: ['A quieter spell: both sides feeling their way.', 'Patient stuff in midfield.'],
      },
    },
  },
};

export type NewStrings = typeof NEW_EN;
