// Text for the v0.12 features (navigation, manager hub, matchday, transfers, staff room, history, support).
// English is the reference; Arabic (Egyptian), Spanish and French are type-checked against it in lang-new-*.ts.
import type { Duty } from './model/types';

export interface LogArgs { pn: string; n: number; s: string; club: string; money: (v: number) => string }
type LogFn = (a: LogArgs) => string;

const P = (n: number, one: string, many: string) => (n === 1 ? one : many);

export const NEW_EN = {
  // Navigation
  tabs: ['Home', 'Squad', 'Match', 'Transfers', 'Club'],
  hospitalT: 'Medical',
  hospitalSub: (n: number) => (n ? `${n} injured` : 'Everyone fit'),
  settingsMore: 'Settings and more',
  settingsMoreSub: 'Language, saves, world editor, quick match, privacy',

  // Manager hub
  today: (n: number) => (n ? `Today: ${n} ${P(n, 'thing needs', 'things need')} you` : 'All clear'),
  allClear: 'Nothing needs you before the next match.',
  todayItems: {
    offers: (n: number) => `${n} ${P(n, 'bid', 'bids')} for your players`,
    contracts: (n: number) => `${n} ${P(n, 'contract ends', 'contracts end')} this season`,
    unavailable: (n: number) => `${n} ${P(n, 'starter is', 'starters are')} injured or banned`,
    tired: (n: number) => `${n} ${P(n, 'starter is', 'starters are')} tired`,
    windowOpen: (left: number) => `Transfer window open: ${left} ${P(left, 'matchday', 'matchdays')} left`,
    deadline: 'Deadline day: the window shuts after this matchday',
    sponsors: (n: number) => `${n} sponsor ${P(n, 'slot is', 'slots are')} empty`,
    red: 'The club is in the red',
    thin: (n: number) => `Only ${n} players in the squad`,
    jobs: (n: number) => `${n} ${P(n, 'club wants', 'clubs want')} to talk to you`,
    dev: (n: number) => `${n} development points to spend`,
    staff: (n: number) => `Your staff did ${n} ${P(n, 'thing', 'things')} since the last match`,
    board: (n: number, d: number) => `Board confidence ${n}: ${d === 1 ? 'one more defeat' : `${d} more defeats`} and you’re out`,
  },
  todayActions: { offers: 'Answer', contracts: 'Renew', unavailable: 'Fix XI', tired: 'Rotate', windowOpen: 'Market', deadline: 'Market', sponsors: 'Sign', red: 'Finances', thin: 'Sign players', jobs: 'See offers', dev: 'Train', staff: 'See log', board: 'Board' },
  formT: 'Form',
  formLetters: ['W', 'D', 'L'] as [string, string, string],
  nextMatchT: 'Next match',

  // Matchday
  ev2: {
    goal: [
      (p: string, c: string) => `GOAL! ${p} scores for ${c}.`,
      (p: string, c: string) => `GOAL! ${p} finds the corner. ${c} celebrate.`,
      (p: string, c: string) => `GOAL for ${c}! ${p} makes no mistake.`,
      (p: string, c: string) => `GOAL! ${p} buries it. The ${c} fans are up.`,
      (p: string, c: string) => `GOAL! Clinical from ${p}. ${c} strike.`,
    ],
    miss: [
      (p: string) => `${p} fires wide.`,
      (p: string) => `${p} drags it past the post.`,
      (p: string) => `Over the bar from ${p}.`,
      (p: string) => `${p} snatches at it. Wide.`,
      (p: string) => `${p} goes for goal from distance. Nowhere near.`,
      (p: string) => `Half-chance for ${p}, but it's wide.`,
    ],
    save: [
      (p: string) => `Big save from ${p}.`,
      (p: string) => `${p} gets down well to keep it out.`,
      (p: string) => `Fingertips! ${p} tips it round the post.`,
      (p: string) => `${p} stands tall and blocks it.`,
      (p: string) => `Strong hands from ${p}.`,
      (p: string) => `${p} reads it and gathers.`,
    ],
    yellow: [
      (p: string) => `Yellow card for ${p}.`,
      (p: string) => `${p} goes into the book.`,
      (p: string) => `Late from ${p}. Yellow.`,
      (p: string) => `${p} is booked for pulling back his man.`,
    ],
    red: [
      (p: string) => `RED CARD! ${p} is sent off.`,
      (p: string) => `RED! ${p} has to go. Down to ten.`,
      (p: string) => `Off he goes: ${p} sees red.`,
    ],
    injury: [
      (p: string) => `${p} is hurt and can’t go on.`,
      (p: string) => `${p} pulls up. The physio waves for a change.`,
      (p: string) => `Bad news: ${p} limps off.`,
    ],
    sub: [
      (off: string, on: string) => `Sub: ${on} comes on for ${off}.`,
      (off: string, on: string) => `Change: ${off} off, ${on} on.`,
      (off: string, on: string) => `Fresh legs: ${on} replaces ${off}.`,
    ],
  },
  ratingT: 'Rating',
  ratingsT: 'Ratings',
  motm: 'Man of the match',
  motmN: (n: number) => `${n}× man of the match`,
  avgRatingT: 'Avg rating',
  xgT: 'Expected goals (xG)',
  ftTitle: { W: 'Win', D: 'Draw', L: 'Defeat' } as Record<'W' | 'D' | 'L', string>,
  ftSub: 'What the result changed',
  ftPos: 'League position',
  ftBoard: 'Board confidence',
  ftFans: 'Fans',
  ftDev: 'Development points',
  ftOut: (name: string, n: number) => `${name}: out for ${n} ${P(n, 'matchday', 'matchdays')}`,
  ftBan: (name: string) => `${name}: suspended`,
  ftRecord: 'New club record',
  ftMilestone: 'Milestone reached',
  ftContinue: 'Continue',

  // Transfer windows
  windowNames: { summer: 'Summer window', winter: 'Winter window' } as Record<'summer' | 'winter', string>,
  windowOpenT: (left: number) => `Open: ${left} ${P(left, 'matchday', 'matchdays')} left`,
  windowShutT: (n: number) => `Window shut: opens in ${n} ${P(n, 'matchday', 'matchdays')}`,
  deadlineT: 'Deadline day',
  deadlineSub: 'Last chance: the window shuts after this matchday. Clubs bid more today.',
  windowClosedBid: 'The transfer window is shut. You can still sign free agents.',

  // Transfers hub
  transfersT: 'Transfers',
  trTabs: ['Market', 'Shortlist', 'Bids', 'Loans', 'Deals'],
  shortlistAdd: 'Shortlist',
  shortlistRemove: 'Remove from shortlist',
  shortlistEmpty: 'No players shortlisted. Players you shortlist appear here, and your scouts pin down their real level.',
  findPlayers: 'Find players',
  offersEmpty: 'No bids for your players right now. Bids arrive while a window is open, more often for listed players.',
  answerBids: 'Answer bids',
  dealsEmpty: 'No deals yet. Signings, sales and free transfers are listed here.',
  loansInT: 'On loan here',
  loansOutT: 'Out on loan',
  loansEmpty: 'No loans this season. Borrow players outside other clubs’ best XI, or send young players out to get games.',
  loanHint: 'Loans last the season. The borrowing club pays the wage. Young players come back better.',
  loanInBtn: (fee: string) => `Loan for the season · ${fee}`,
  loanOutBtn: 'Loan out',
  loanTo: 'Loan him to',
  loanFrom: (club: string) => `On loan from ${club}`,
  loanAt: (club: string) => `On loan at ${club}`,
  loanReason: {
    window: 'Loans only happen while a window is open.', budget: 'Not enough budget for the loan fee.', wageCap: 'His wage would break the wage cap.',
    squad: 'Squad size limit reached.', key: 'A first-team regular there: not for loan.', limit: 'You already have 4 loans that way.',
    free: 'Free agents sign, they don’t loan.', loaned: 'Already on loan.', injured: 'Injured players can’t move on loan.',
    lenderThin: 'They won’t lend: it would leave them under 16 players.', club: 'That club can’t take him.',
  } as Record<string, string>,
  loanedIn: (name: string) => `${name} joins on loan.`,
  loanedOut: (name: string, club: string) => `${name} joins ${club} on loan.`,
  noLoanClubs: 'No club at his level wants him on loan right now.',
  estimateT: 'Scout estimate',
  estHint: 'Shortlist him and your scouts pin down his real level within 2 matchdays.',

  // Squad
  showT: 'Show',
  squadViews: ['Rating', 'Fitness', 'Contract', 'Value', 'Form'],

  // Match hub
  matchTabs: ['Next', 'Table', 'Results', 'Cups', 'Stats'],
  leaderTabs: ['Goals', 'Assists', 'Ratings'],
  worldRankings: 'World rankings',

  // Club hub
  boardT: 'Board and objectives',
  staffRoomT: 'Staff room',
  staffRoomSub: (n: number, all: number) => (n ? `${n} of ${all} duties delegated` : 'You run everything. Delegate what you like.'),
  financesT: 'Finances',
  ticketsT: 'Tickets',
  sponsorsT: 'Sponsors',
  facilitiesT: 'Facilities',
  hireStaffT: 'Hire staff',
  historyT: 'History and records',
  historySub: 'Seasons, records, trophies, academy graduates',

  // Staff room
  staffIntro: 'Hand any job to your staff. They do it every matchday, as well as their quality allows. You always play the matches.',
  staffYours: 'Your staff',
  qualityT: 'Quality',
  dutiesT: 'Duties',
  dutyGroups: { matchday: 'Matchday', squad: 'Squad', transfers: 'Transfers', club: 'Club' } as Record<string, string>,
  duties: {
    lineup: ['Line-up and subs', 'Picks the best XI for every match.'],
    tactics: ['Tactics', 'Chooses the shape and mentality for each opponent.'],
    scouting: ['Opponent reports', 'Buys a report before tough matches and uses its counter plan.'],
    training: ['Training', 'Sets the training load and spends development points.'],
    medical: ['Medical', 'Pays for rehab on longer injuries.'],
    morale: ['Morale', 'Gives a team talk when morale drops.'],
    academy: ['Academy', 'Scouts prospects, promotes the ready ones, sells the rest.'],
    contracts: ['Contracts', 'Renews players worth keeping from matchday 5.'],
    selling: ['Selling', 'Answers bids and lists surplus players.'],
    signing: ['Signings', 'Signs a player for the thinnest position while a window is open.'],
    loans: ['Loans', 'Sends young players out on loan to get games.'],
    sponsors: ['Sponsors', 'Signs the best offer for every empty slot.'],
    tickets: ['Ticket prices', 'Sets the price that earns most without emptying the stands.'],
  } as Record<Duty, [string, string]>,
  matchDuty: ['Play the match', 'Always you.'] as [string, string],
  meT: 'Me',
  staffT: 'Staff',
  delegateAll: 'Hand everything to staff',
  takeAll: 'Do it all myself',
  needStaff: (role: string) => `Hire a ${role.toLowerCase()} first`,
  staffLogT: 'What your staff did',
  staffLogEmpty: 'Nothing yet. Delegate a duty and your staff log what they do here.',
  staffLog: {
    'training:load': (a) => `Training load set to ${['recovery', 'balanced', 'hard'][a.n] ?? 'balanced'}.`,
    'training:dev': (a) => `Spent development points on ${a.pn} (+1 rating).`,
    'medical:rehab': (a) => `Paid for rehab: ${a.pn}.`,
    'morale:talk': (a) => `Team talk: morale was ${a.n}.`,
    'academy:promote': (a) => `Promoted ${a.pn} from the academy.`,
    'academy:sold': (a) => `Sold the rights to ${a.pn} for ${a.money(a.n)}.`,
    'academy:scouted': (a) => `Found ${a.n} new ${P(a.n, 'prospect', 'prospects')}.`,
    'selling:sold': (a) => `Sold ${a.pn} to ${a.club} for ${a.money(a.n)}.`,
    'selling:rejected': (a) => `Turned down ${a.money(a.n)} for ${a.pn}.`,
    'selling:listed': (a) => `Put ${a.pn} on the transfer list.`,
    'contracts:renewed': (a) => `Renewed ${a.pn} for ${a.n} more ${P(a.n, 'season', 'seasons')}.`,
    'signing:signed': (a) => `Signed ${a.pn} from ${a.club || 'free agency'} for ${a.n ? a.money(a.n) : 'free'}.`,
    'loans:out': (a) => `Loaned ${a.pn} to ${a.club}.`,
    'sponsors:signed': (a) => `Signed ${a.pn} as a sponsor: ${a.money(a.n)} a month.`,
    'tickets:price': (a) => `Ticket price set to ${a.s}.`,
    'tactics:formation': (a) => `Switched to ${a.s}.`,
    'scouting:report': (a) => `Bought a report on ${a.club}.`,
  } as Record<string, LogFn>,
  staffNames2: { director: 'Sporting director' } as Record<string, string>,
  staffEffects2: { director: 'Contracts, bids, signings, loans, sponsors and tickets when you delegate them' } as Record<string, string>,
  ledgerKeys2: { loans: 'Loan fees' } as Record<string, string>,

  // G1 (integrity and UX fixes)
  wagesOfCap: 'Wages, of cap',
  newEnd: (y: number) => `New end: ${y}`,
  resumedFrom: (min: number) => `Resumed from ${min}′`,
  playingT: (what: string) => `Playing ${what}…`,
  saveRefused: (why: string) => `Couldn’t save: ${why}`,
  tacticsTabs: ['Shape', 'Style', 'Set pieces'] as [string, string, string],
  confirmSub: (off: string, on: string) => `Confirm sub: ${off} ↔ ${on}`,
  pickSubHint: 'Pick who goes off and who comes on.',
  detailsT: 'Details',
  hideDetailsT: 'Hide details',
  radarLocked: 'Scout the opponent to see their profile.',

  // History
  histTabs: ['Seasons', 'Records', 'Trophies', 'Academy'],
  seasonsEmpty: 'Your first season is still going. Finished seasons are kept here.',
  recordsEmpty: 'Records appear once you’ve played some games.',
  trophiesEmpty: 'No trophies yet. Win a league or a cup and it goes in the cabinet.',
  gradsEmpty: 'No academy graduates yet. Promote a prospect and follow his story here.',
  recordNames: {
    bigWin: 'Biggest win', mostPoints: 'Most league points', mostGoals: 'Most league goals', unbeaten: 'Longest unbeaten run',
    scorer: 'Top scorer in a season', bestFinish: 'Best league finish', bestBuy: 'Record signing', bestSale: 'Record sale',
  } as Record<string, string>,
  gamesN: (n: number) => `${n} ${P(n, 'game', 'games')}`,
  gradLine: (apps: number, goals: number) => `${apps} apps · ${goals} goals this season`,
  trophyKinds: { league: 'League title', cup: 'Cup', continental: 'Continental cup', promotion: 'Promotion' } as Record<string, string>,

  updWeb: (v: string) => `The Gaffer ${v} is ready: new fixes and features.`,
  updWebBtn: 'Update now',
  updApk: (v: string) => `App update ${v} is out. Install it to keep getting updates.`,
  updApkBtn: 'Download',
  updLater: 'Later',
  // Support and looks
  supportT: 'Support The Gaffer',
  supportBody: 'A one-off Supporter pack: every club look, a Supporter badge on your coach card, and no ads. The game itself stays complete for everyone.',
  supportBtn: 'Get the Supporter pack',
  supportSoon: 'The Supporter pack opens soon.',
  supporterBadge: 'Supporter',
  supportThanks: 'Thanks for backing The Gaffer. Everything is unlocked.',
  looksT: 'Look',
  looks: ['Violet', 'Floodlight', 'Pitch', 'Derby red'],
  looksLocked: 'Supporter pack',
  rewardedBtn: 'Watch a short ad: free report',
  rewardedHint: 'Optional. You can always buy the report with club money.',
  adFailed: 'No ad right now. Try again later.',
  sponsoredT: 'Sponsored',
  howToBody2: [
    ['Your job', 'Pick a club and sign the contract. The board sets objectives for the league and the cup. Meet them and your reputation grows; miss them and you can be sacked.'],
    ['Home', 'Home lists what needs you today, each with one button. Clear it, then play the next match.'],
    ['Matchdays', 'Tap Play the match to watch it live, or take a quick result. Every match ends with ratings, a man of the match and a card showing what the result changed.'],
    ['Tactics', 'Pick a formation, the XI, mentality, pressing and passing. Philosophies beat each other like rock, paper, scissors, and your mastery of one grows every game. Scout the opponent before the big ones.'],
    ['Your staff', 'Club › Staff room: hand any duty to your staff (line-up, training, contracts, signings and more) or do it yourself. You always play the matches.'],
    ['Transfers', 'Buy and sell while a window is open (summer and winter, deadline day last). Free agents sign any time. Shortlist players so your scouts learn their real level, and loan players in or out for the season.'],
    ['Money', 'Tickets, TV and sponsors come in; wages, staff and upkeep go out. Build facilities, hire staff, and end the season in the black.'],
    ['Cups', 'Your national cup is knockout from the start. Continental cups start with groups of four: the top two go through.'],
    ['Your career', 'Earn XP and licences, take courses, collect milestones and trophies, and set club records. Bigger clubs will call.'],
    ['Saving', 'The career saves itself after every match and is checked when it loads. Export a save file from Club › Settings and more.'],
  ] as [string, string][],
  privacyBody2: [
    ['What we keep', 'Your career, settings and coach photo are saved on this device only. Update checks ask Semba Games for the latest version number and send no career data.'],
    ['Online features', 'Ads and purchases, when switched on, are clearly labelled. Web ads come from Google AdSense, which may use cookies to show and measure ads. Purchases are handled by Stripe; we never see your card.'],
    ['No account', 'The Gaffer has no sign-in. Your career lives on your device, and you can export it any time from Settings.'],
    ['Save files', 'A save you export goes where you choose. Importing only reads the file you pick.'],
    ['Photos', 'A photo you add to your coach card stays on this device and is only used to draw the card.'],
    ['Deleting your data', 'Start over from Settings, or clear the app’s data, and everything is gone.'],
    ['Contact', 'Questions? sembagames.app'],
  ] as [string, string][],
};

export type NewStrings = typeof NEW_EN;
