// Tactics v3 copy, Spanish (checked against lang-tac.ts).
import type { TxStrings } from './lang-tac';

export const TX_ES: TxStrings = {
  phase: { ip: 'Con balón', oop: 'Sin balón' },
  phaseLong: { ip: 'En posesión', oop: 'Sin posesión' },
  shapeIp: 'Dibujo con balón',
  shapeOop: 'Dibujo sin balón',
  same: 'El mismo',
  roles: {
    keeper: ['Portero', 'POR', 'Se queda en portería y la juega corta a sus defensas.'],
    distributor: ['Portero distribuidor', 'DIS', 'Se suma a la salida como un pasador más. Necesita buen pie: si se pone nervioso, se la roban.'],
    defender: ['Central', 'DFC', 'Primero defiende y juega el pase fácil.'],
    ball_player: ['Central con salida', 'CSB', 'Conduce hasta el medio y busca el pase hacia delante. Necesita pase.'],
    fullback: ['Lateral', 'LAT', 'Acompaña por detrás de la jugada y se queda disponible atrás.'],
    wingback: ['Carrilero', 'CAR', 'Sube hasta la línea: un hombre más en banda, un hueco a su espalda. Agotador.'],
    inverted_fullback: ['Lateral invertido', 'LI', 'Se mete al medio: un pasador más por dentro, menos amplitud.'],
    holder: ['Pivote', 'PIV', 'Se planta delante de la defensa y recicla el balón.'],
    playmaker: ['Organizador', 'ORG', 'Todo pasa por él: más ocasiones para otros, menos tiros propios. Necesita pase.'],
    midfielder: ['Mediocentro', 'MC', 'Une la defensa y el ataque.'],
    box_to_box: ['Box-to-box', 'B2B', 'Llega tarde al área: más tiros desde el medio. Necesita piernas y se cansa antes.'],
    attacking_mid: ['Mediapunta', 'MP', 'Juega entre líneas y alimenta a los delanteros.'],
    shadow_striker: ['Segundo delantero', 'SD', 'Rompe por detrás del 9 hacia el área: más tiros, menos pases.'],
    winger: ['Extremo', 'EXT', 'Se queda abierto, encara y centra.'],
    inside_forward: ['Extremo a pierna cambiada', 'EPC', 'Se mete hacia dentro: tiros y pases atrás en vez de centros.'],
    advanced_forward: ['Delantero', 'DC', 'Juega al hombro del último defensa y ataca el área.'],
    target_man: ['Delantero de referencia', 'REF', 'El punto de apoyo: balones largos y centros a su cabeza. Necesita fuerza.'],
    false_nine: ['Falso 9', 'F9', 'Baja al medio para asociarse: más ocasiones para otros, menos gente en el área.'],
    line_keeper: ['Portero', 'POR', 'Se queda en su línea.'],
    sweeper_keeper: ['Portero líbero', 'LIB', 'Sale a por los balones a la espalda. Un tiro lejano le puede pillar.'],
    hold_line: ['Mantener la línea', 'LIN', 'Guarda su sitio en la línea defensiva.'],
    step_out: ['Salir al cruce', 'SAL', 'Sale pronto a por su hombre: roba más arriba, comete más faltas, deja espacio detrás.'],
    screen: ['Escudo', 'ESC', 'Se hunde delante de la defensa y cierra el centro. No presiona arriba.'],
    ball_winner: ['Recuperador', 'REC', 'Caza el balón en el medio: recupera, comete más faltas, deja un hueco. Agotador.'],
    hold_shape: ['Mantener la forma', 'FOR', 'Guarda su sitio en el bloque.'],
    track_back: ['Replegar', 'REP', 'Persigue hacia atrás al que llega por su lado.'],
    press_forward: ['Liderar la presión', 'PRE', 'Persigue a sus defensas y al portero: robos arriba, más faltas. Muy agotador.'],
    outlet: ['Quedarse arriba', 'ARR', 'No defiende: espera la contra. Contras más rápidas, uno menos en el bloque.'],
  },
  roleFor: (phase: string) => `Rol · ${phase}`,
  fit: ['Natural', 'Encaja', 'Puede hacerlo', 'No encaja'],
  suggest: 'Sugerir roles', suggested: 'Roles ajustados a los jugadores',
  ins: {
    build: ['Salida', ['Desde atrás', 'Mixta', 'En largo']],
    cpress: ['Al perderla', ['Replegar', 'Equilibrado', 'Presión tras pérdida']],
    counter: ['Al recuperarla', ['Tenerla', 'Contra al momento']],
    trap: ['Trampa de presión', ['Ninguna', 'Bandas', 'Centro', 'Carriles interiores']],
    routine: ['Córners', ['Variados', 'Los altos arriba', 'En corto']],
    marking: ['Marcaje', ['Zonal', 'Mixto', 'Individual']],
    setMark: ['Marcaje a balón parado', ['Zonal', 'Mixto', 'Individual']],
  },
  trade: {
    build: [['Portero y centrales la sacan jugada: más balón.', 'Una buena presión roba cerca de nuestra portería.'], ['Corto cuando se puede, largo cuando no.', 'Ni fu ni fa.'], ['Nos saltamos su presión.', 'Más balones divididos; la devolvemos más.']],
    cpress: [['Todos atrás: sus contras se secan.', 'Se quedan el balón cuando lo tienen.'], ['Unos presionan, otros repliegan.', 'Nada especial.'], ['La recuperamos arriba al momento.', 'Agotador; más faltas tácticas; si la superan, se escapan.']],
    counter: [['La tenemos y volvemos a construir.', 'Menos ocasiones rápidas.'], ['Salimos en cuanto la robamos.', 'Los medios juegan más atrás para lanzarla.']],
    trap: [['Sin trampa.', 'Sin trampa.'], ['Los mandamos a la banda y los encerramos.', 'El centro queda algo más suelto.'], ['Los alejamos del centro.', 'Las bandas quedan algo más sueltas.'], ['Presión un poco en cada carril.', 'Nada queda cerrado del todo.']],
    routine: [['Envíos variados.', 'Nada especial.'], ['Suben los centrales: más cabezazos.', 'Menos gente atrás si sale mal.'], ['En corto para conservarla.', 'Menos tiros del propio córner.']],
    marking: [['Cada uno guarda su zona: poco espacio entre líneas; menos faltas.', 'Los que llegan desde fuera y al área encuentran hueco.'], ['Zonas, y el más cercano coge al que llega.', 'Nada especial.'], ['Cada uno con su hombre: pegados en las bandas y por arriba.', 'Los marcadores se salen de su sitio: más espacio por dentro; más faltas.']],
    setMark: [['Zonas en el área: primer contacto en el primer palo.', 'Los que atacan el balón en carrera ganan más cabezazos.'], ['Unos en zona y el resto al hombre.', 'Nada especial.'], ['Cada uno con un hombre en el área: menos cabezazos libres.', 'El rechace en la frontal queda libre.']],
  },
  trapOff: 'Una trampa necesita presión: pon la presión en bloque medio o más.',
  mark: 'Marcaje individual', markNone: 'Nadie', markHint: 'Gana muchos menos duelos; su marcador deja un hueco.',
  preview: {
    title: 'Lo que ve el motor',
    sub: 'Jugadores en cada zona, nuestros contra suyos, con los mismos números del partido',
    rest: (n: string) => `${n} se quedan atrás cuando atacamos`,
    line: (n: number) => `Línea defensiva al ${n}% del campo`,
    press: (n: string) => `${n} presionan su salida`,
    box: (n: string) => `${n} atacan el área`,
    zones: { build: 'Salida', mid: 'Medio', final: 'Último tercio', box: 'Área', press: 'Su salida', screen: 'Medio', defend: 'Nuestro tercio' },
  },
  warn: {
    title: 'Riesgos',
    none: 'Nada evidente. El motor está de acuerdo con el plan.',
    fit: (p: string, role: string) => `${p} no encaja como ${role}: el rol rinde a medias y él juega por debajo de su nivel.`,
    rest: (n: string) => `Solo ${n} se quedan atrás cuando atacamos. Si la perdemos, nos pillan a la contra.`,
    pressAlone: (p: string, role: string) => `${p} tiene que ${role.toLowerCase()} mientras el equipo espera: presiona solo y lo superan.`,
    trapOff: 'La trampa de presión no hace nada sin presión.',
    slowLine: (p: string) => `A ${p} le falta velocidad para una línea alta: los balones a la espalda dolerán.`,
    noBox: 'Centros y balones largos, pero casi nadie en el área para rematarlos.',
    outlets: (n: number) => `${n} jugadores se quedan arriba sin balón: al bloque le faltan piernas.`,
  },
  why: {
    won: (a: string, role: string, n: number) => `${a} recuperó el balón ${n} veces como ${role}.`,
    shots: (a: string, role: string, n: number, x: string) => `${a} disparó ${n} veces como ${role} (${x} xG).`,
    made: (a: string, role: string, n: number, x: string) => `${a} generó ${n} ocasiones como ${role} (${x} xG).`,
    themWon: (a: string, role: string, n: number) => `Su ${role.toLowerCase()} ${a} recuperó el balón ${n} veces.`,
    themShots: (a: string, role: string, n: number, x: string) => `Su ${role.toLowerCase()} ${a} disparó ${n} veces (${x} xG).`,
    themMade: (a: string, role: string, n: number, x: string) => `Su ${role.toLowerCase()} ${a} generó ${n} ocasiones (${x} xG).`,
    head: ['El rol que funcionó', 'Su rol que nos hizo daño'],
  },
  change: (p: string, role: string) => `${p}: ${role}`,
  live: { roles: 'Roles', rolesSub: 'Los cambios cuentan desde el minuto siguiente.' },
};
