// Vestiaire (V2.4) en français : la voix du banc. Vérifié contre l'anglais (lang-dressing.ts).
import type { DStrings } from './lang-dressing';

type Pair = [string, string];
const P = (n: number, one: string, many: string) => (n <= 1 ? one : many);

export const D_FR: DStrings = {
  title: 'Vestiaire',
  eyebrow: (club: string) => `${club} · le vestiaire`,
  mood: {
    together: ['Le vestiaire est ', 'avec vous', '.'], settled: ['Le vestiaire est ', 'calme', '.'],
    restless: ['Le vestiaire est ', 'agité', '.'], split: ['Le vestiaire est ', 'divisé', '.'],
  },
  moodSub: {
    together: 'Les mêmes visages, de bons résultats, et ils croient ce que vous leur dites.',
    settled: 'Rien ne cloche là-dedans. Rien de spécial non plus.',
    restless: 'Quelques-uns attendent de voir ce que vous allez faire.',
    split: 'Trop d’entre eux n’écoutent plus. Réglez ça avant de le payer sur le terrain.',
  },
  facts: { coh: 'cohésion', morale: 'moral', trust: 'confiance', open: (n: number) => P(n, 'promesse en cours', 'promesses en cours') },
  coh: {
    title: 'Cohésion', causes: 'Ce qui l’a fait bouger', none: 'Rien ne l’a encore fait bouger.',
    worth: (v: string) => `Vaut ${v} le jour du match face à une équipe normale`,
    scale: ['En miettes', 'Normal', 'Soudé'],
    how: 'Elle monte quand vous gardez le même onze et que vous gagnez. Les recrues la dérèglent six journées. Décevoir un cadre fait le plus mal.',
  },
  cause: {
    settled: () => 'Même onze', win: () => 'Une victoire', loss: () => 'Une défaite', drift: () => 'Retour au calme',
    bedIn: () => 'Les nouveaux s’intègrent', arrival: (pn: string) => `Arrivée de ${pn}`,
    leaderBroken: (pn: string) => `Votre parole à ${pn}`, leaderRequest: (pn: string) => `${pn} a demandé à partir`,
    leaderSold: (pn: string) => `${pn} est parti`, armLeader: (pn: string) => `${pn} prend le brassard`, armFringe: (pn: string) => `${pn} prend le brassard`,
  },
  tiers: { leader: 'Cadres', core: 'Noyau', fringe: 'Remplaçants' },
  tierSub: { leader: 'Leur humeur devient celle de tous.', core: 'La colonne vertébrale.', fringe: 'Ils attendent leur chance.' },
  leadersSub: 'Le vestiaire les écoute. Leur moral entraîne celui des autres.',
  captain: 'Capitaine', armband: 'Brassard', noCaptain: 'Personne ne porte le brassard.',
  pickCaptain: 'Qui porte le brassard ?', pickCaptainSub: 'Un cadre élève le vestiaire. Un remplaçant lui coûte.',
  give: 'Lui donner le brassard',
  word: 'Votre parole', noWord: 'Aucune promesse en cours. Personne ne vous tient à rien.',
  status: { open: 'En bonne voie', slip: 'Ça glisse', lost: 'Perdue', kept: 'Tenue', broken: 'Rompue' },
  groups: ['gardien', 'défenseur', 'milieu', 'attaquant'],
  pledge: (key: string, group: string) => ({
    'role.star': 'être la star', 'role.starter': 'être titulaire', 'role.rotation': 'du temps de jeu en rotation', 'role.prospect': 'un chemin vers l’équipe première',
    contract: 'un nouveau contrat', keep: 'ne pas être vendu ce mercato', sign: `un nouveau ${group}`,
  } as Record<string, string>)[key.startsWith('sign') ? 'sign' : key] ?? key,
  progress: {
    role: (st: number, el: number, need: number, left: number) => `${st} ${P(st, 'titularisation', 'titularisations')} sur ${el}. Le rôle demande ${need} % ; ${left} ${P(left, 'journée', 'journées')} à jouer.`,
    prospect: (apps: number, left: number) => `${apps} matchs sur 10. ${left} ${P(left, 'journée', 'journées')} de championnat, ou un prêt.`,
    contract: (left: number) => `Un nouveau contrat d’ici ${left} ${P(left, 'journée', 'journées')}.`,
    sign: () => 'Avant la fin du mercato.',
    keep: () => 'Jusqu’à la fin du mercato.',
    kept: 'Il l’a remarqué.', broken: 'Il ne l’oubliera pas.',
  },
  waiting: 'Veut vous parler', unsettled: 'Veut partir', talkBtn: 'Parler',
  role: { star: 'Star', starter: 'Titulaire', rotation: 'Rotation', prospect: 'Espoir' },
  roleSub: { star: 'Titulaire 7 fois sur 10', starter: 'Titulaire un match sur deux', rotation: 'Titulaire 1 fois sur 4', prospect: '10 matchs ou un prêt' },
  arch: { driven: 'Ambitieux', steady: 'Posé', volatile: 'Lunatique', loyal: 'Fidèle', mercenary: 'Mercenaire', leader: 'Meneur né' },
  archSub: {
    driven: 'Un coup de pression marche mieux qu’une tape dans le dos.', steady: 'Dur à ébranler, dur à relancer.', volatile: 'Les éloges le portent, les critiques l’abattent.',
    loyal: 'Pardonne plus que les autres.', mercenary: 'Les mots comptent moins que l’argent.', leader: 'Le vestiaire suit son humeur.',
  },
  trust: 'Confiance', morale: 'Moral',
  cause2: {
    'kept.role': 'promesse tenue', 'kept.contract': 'promesse tenue', 'kept.keep': 'promesse tenue', 'kept.sign': 'promesse tenue',
    'broken.role': 'promesse rompue', 'broken.contract': 'promesse rompue', 'broken.keep': 'promesse rompue', 'broken.sign': 'promesse rompue',
    minutes: 'ne joue pas assez', ignored: 'vous l’avez laissé attendre', 'talk.reassure': 'votre soutien', 'talk.challenge': 'votre défi',
    'talk.promise': 'votre promesse', armband: 'le brassard', armLost: 'a perdu le brassard', listed: 'transférable, comme demandé', refused: 'demande refusée',
    stayed: 'est resté', renewed: 'nouveau contrat', win: 'la victoire', loss: 'la défaite', draw: 'le nul', drift: 'retour au calme', leaderBroken: 'un cadre déçu',
  },
  talk: {
    btn: 'Lui parler', title: (pn: string) => `Un mot avec ${pn}`,
    why: {
      asked: 'Il a demandé à vous voir.', request: 'Il a demandé à partir.', broken: 'Vous avez manqué à votre parole.', minutes: 'Il joue moins que ce que dit son rôle.',
      role: 'Il joue au-dessus du rôle de son contrat.', contract: 'Son contrat arrive à terme.', unhappy: 'Il est au fond.', doubts: 'Il ne vous croit plus.',
      new: 'Il vient d’arriver. La première impression compte.', form: 'Il a été le meilleur sur le terrain.',
    },
    none: 'Rien à dire. Il sait où il en est.',
    wait: 'Vous lui avez parlé cette semaine. Laissez passer quelques jours.',
    tones: { reassure: ['Le rassurer', 'Une main sur l’épaule'], challenge: ['Le défier', 'Dites-lui ce que vous attendez'], promise: ['Donner votre parole', 'Une promesse qu’il vous rappellera'] },
    staff: 'Avis du staff',
    choose: 'Que lui promettez-vous ?',
    types: { role: 'Son rôle', sign: 'Une recrue', keep: 'Pas à vendre', contract: 'Un nouveau contrat' },
    bind: {
      'role.star': 'Titulaire 7 fois sur les 10 prochains matchs de championnat où il est apte. Sinon : confiance −20.',
      'role.starter': 'Titulaire la moitié des 10 prochains matchs de championnat où il est apte. Sinon : confiance −20.',
      'role.rotation': 'Titulaire 1 fois sur 4 lors des 10 prochains matchs de championnat. Sinon : confiance −20.',
      'role.prospect': '10 matchs sur les 20 prochaines journées, ou un prêt. Sinon : confiance −20.',
      contract: 'Un nouveau contrat sur la table d’ici 8 journées. Sinon : confiance −20.',
      keep: 'Il n’est pas vendu avant la fin du mercato. Vendez-le et tout le vestiaire le verra.',
      sign: 'Une recrue à ce poste avant la fin du mercato. Sinon : confiance −20.',
    },
    signPos: 'Quel poste ?',
    giveBtn: 'Donner votre parole', back: 'Retour', done: 'Terminé',
    delta: (label: string, d: number) => `${label} ${d > 0 ? '+' : d < 0 ? '−' : '±'}${Math.abs(d)}`,
    withdrew: 'Il retire sa demande de transfert.',
    reply: {
      'reassure.driven': 'D’accord. Je veux juste jouer.', 'reassure.steady': 'Compris, coach.', 'reassure.volatile': 'Ça compte beaucoup. Vraiment.',
      'reassure.loyal': 'Je sais que vous me couvrez.', 'reassure.mercenary': 'Jolis mots.', 'reassure.leader': 'Bien. Je le dirai aux gars.',
      'challenge.driven': 'Vous allez voir. Regardez-moi.', 'challenge.steady': 'Reçu.', 'challenge.volatile': 'C’est ce que vous pensez de moi ?',
      'challenge.loyal': 'Je ne vous décevrai pas.', 'challenge.mercenary': 'On verra qui a besoin de qui.', 'challenge.leader': 'Juste. Je donnerai l’exemple.',
      'promise.steady': 'Alors c’est entendu.', 'promise.driven': 'Je vous le rappellerai.', 'promise.mercenary': 'La prochaine fois, par écrit.',
      'promise.cold': 'J’ai déjà entendu des promesses.', 'reassure.heard': 'Vous avez dit ça la dernière fois.', 'challenge.cold': 'Venant de vous ? Elle est bonne.',
      'praise.volatile': 'Je me ferai tuer pour vous.', 'praise.steady': 'Merci, coach. Et la semaine prochaine aussi.',
    },
  },
  no: {
    'dr.nothing': 'Rien à dire. Il sait où il en est.', 'dr.pledged': 'Vous lui avez déjà donné votre parole sur quelque chose.',
    'dr.window': 'Seulement pendant le mercato.', 'dr.role': 'Il est trop âgé pour être un espoir.', 'dr.long': 'Il lui reste des années de contrat.',
    'dr.group': 'Choisissez un poste.', 'dr.already': 'Il le porte déjà.', 'dr.noRequest': 'Il n’a pas demandé à partir.',
    wait: 'Vous lui avez parlé cette semaine. Laissez passer quelques jours.', gone: 'Il n’est plus chez nous.', trust: 'Il ne vous fait pas assez confiance pour signer.',
    loaned: 'Il est prêté.', terms: 'Ces conditions ne vont pas.', role: 'Il est trop âgé pour être un espoir.',
  },
  tag: { talk: 'Un mot', request: 'Veut partir', promise: 'Votre parole', armband: 'Brassard', clause: 'Clause libératoire' },
  titles: {
    'ask.asked': (pn: string) => `${pn} veut vous parler`, 'ask.broken': (pn: string) => `${pn} veut parler de votre promesse`,
    'ask.minutes': (pn: string) => `${pn} veut savoir pourquoi il ne joue pas`, 'ask.role': (pn: string) => `${pn} veut un plus grand rôle`,
    'ask.contract': (pn: string) => `${pn} veut parler de son avenir`, 'ask.unhappy': (pn: string) => `${pn} veut vous parler`,
    'ask.doubts': (pn: string) => `${pn} a des doutes`, 'ask.request': (pn: string) => `${pn} veut partir`,
    'ask.new': (pn: string) => `${pn} veut vous parler`, 'ask.form': (pn: string) => `${pn} veut vous parler`,
    request: (pn: string) => `${pn} a demandé à partir`,
    clause: (pn: string, fee: string, club: string) => `${club} paie la clause de ${pn} : ${fee}`,
    'due.role.star': (pn: string) => `Votre parole à ${pn} : être la star`, 'due.role.starter': (pn: string) => `Votre parole à ${pn} : être titulaire`,
    'due.role.rotation': (pn: string) => `Votre parole à ${pn} : du temps de jeu`, 'due.contract': (pn: string) => `Votre parole à ${pn} : un nouveau contrat`,
    'due.sign': (pn: string, g: string) => `Votre parole à ${pn} : un nouveau ${g}`,
    'arm.none': () => 'Personne ne porte le brassard', 'arm.lost': (pn: string) => `Le vestiaire ne suit plus ${pn}`,
  },
  advice: {
    reassure: (pn: string, a: string) => `${pn} est ${a.toLowerCase()}. Mettez-lui une main sur l’épaule ; c’est ce qu’il lui faut.`,
    challenge: (pn: string, a: string) => `${pn} est ${a.toLowerCase()}. Défiez-le. Il y répond.`,
    'promise.role': () => 'Donnez-lui votre parole sur son rôle. On peut la tenir, et il sait que c’est sérieux.',
    'promise.contract': () => 'Promettez-lui un nouveau contrat. Il veut savoir qu’il a un avenir ici.',
    'promise.sign': () => 'Promettez-lui la recrue. Il veut voir de l’ambition.',
    'promise.keep': () => 'Dites-lui qu’il n’est pas à vendre.',
    'req.list': (pn: string) => `Laissez partir ${pn}. Un joueur qui veut partir joue comme tel.`,
    'req.refuse': (_pn: string, n: string) => `C’est notre numéro ${n}. Refusez, et laissez-le se calmer.`,
    'req.promise': () => 'Donnez-lui un vrai rôle et il restera peut-être. Ne le dites pas si vous ne le ferez pas.',
    'clause.stay': (_pn: string, n: string) => `Il vous fait confiance (${n}). Demandez-lui de rester ; je pense qu’il le fera.`,
    'clause.go': (_pn: string, n: string) => `Confiance à ${n}. Il partira quoi qu’on dise. Prenez l’argent avec classe.`,
    'due.start': (pn: string) => `Titularisez ${pn} samedi. Ça ne nous coûte presque rien et vous tenez parole.`,
    'due.cost': (pn: string, n: string) => `Titulariser ${pn} nous coûte ${n} à ce poste. Votre parole, votre choix.`,
    'due.none': () => 'Il n’est pas en état d’être titulaire. Il faudra peut-être laisser filer.',
    'due.contract': (_pn: string, n: string) => `Mettez le contrat sur la table : il signerait à ${n} par mois.`,
    'due.sign': (_pn: string, g: string) => `On lui doit encore un ${g}. Le mercato se ferme.`,
    arm: (pn: string) => `${pn}. Le vestiaire le suit déjà.`,
    'arm.home': (pn: string, n: string) => `${pn}. ${n} ans, formé ici, et le vestiaire le suit déjà.`,
  },
  choices: {
    reassure: 'Le rassurer', challenge: 'Le défier', list: 'Le rendre transférable', refuse: 'Refuser', stay: 'Lui demander de rester', go: 'Le laisser partir',
    start: (pn: string) => `Titulariser ${pn}`, letgo: 'Laisser filer', armband: (pn: string) => `Brassard à ${pn}`, later: 'Pas maintenant',
    promise: (what: string) => `Promettre : ${what}`,
  },
  fx: {
    morale: (s: string) => `Moral ${s}`, trust: (s: string) => `Confiance ${s}`, coh: (s: string) => `Cohésion ${s}`, shrug: 'Change peu',
    bind: 'Il vous le rappellera', bids: 'Des offres vont venir', stillWants: 'Veut toujours partir', withdraw: 'Retire sa demande',
    likelyStays: (s: string) => `Confiance ${s} : il écoutera`, likelyGoes: (s: string) => `Confiance ${s} : il part`,
    noChange: 'Rien ne change', onTrack: 'Vous tenez parole', kept: 'Vous tenez parole', keepWord: 'Vous avez promis de le garder',
  },
  news: {
    'dr.broken': (pn: string, what: string): Pair => [`${pn} déçu`, `L’entraîneur lui avait promis ${what}. Ça ne s’est pas fait, et le vestiaire l’a vu.`],
    'dr.request': (pn: string): Pair => [`${pn} demande à partir`, 'Une demande de transfert est sur le bureau de l’entraîneur. Les clubs l’ont su.'],
    'dr.settled': (pn: string): Pair => [`${pn} se calme`, 'La demande de transfert est mise de côté. Pour l’instant.'],
    'dr.withdrawn': (pn: string): Pair => [`${pn} retire sa demande`, 'Une promesse de l’entraîneur l’a fait changer d’avis.'],
    'dr.refused': (pn: string): Pair => ['Demande refusée', `${pn} ne bougera pas, dit le club. Le joueur n’est pas content.`],
    'dr.exit': (pn: string, club: string): Pair => [`${pn} s’en va`, `Il rejoint ${club}. Le vestiaire perd une voix.`],
    'dr.leftFree': (pn: string): Pair => [`${pn} part pour rien`, 'Son contrat a expiré et il est parti. Pas un centime pour le club.'],
    'dr.returns': (pn: string, club: string, n: string, s: string): Pair => [`${pn} retrouve son ancien club`, `${club}, ${s}. Sa note : ${n}.`],
    'dr.clauseMet': (pn: string, club: string, n: string): Pair => [`${club} lève la clause de ${pn}`, `${n}, payés comptant. La clause a fait le reste.`],
    'dr.stays': (pn: string, club: string): Pair => [`${pn} dit non à ${club}`, 'Ils ont payé sa clause. Il veut rester.'],
    'dr.core': (pn: string, _c: string, n: string): Pair => [`${pn} gagne le vestiaire`, `${n} ans et formé au club. Les anciens l’écoutent maintenant.`],
    'dr.leader': (pn: string, _c: string, n: string): Pair => [`${pn}, cadre à ${n} ans`, 'Du centre de formation au cœur du vestiaire.'],
    'dr.armband': (pn: string): Pair => [`${pn} nouveau capitaine`, 'L’entraîneur lui confie le brassard.'],
    'dr.armbandHome': (pn: string, _c: string, n: string): Pair => ['Du centre de formation au brassard', `${pn}, ${n} ans, capitaine du club où il a grandi.`],
  },
  msg: {
    'dr.kept': (pn: string, what: string): Pair => [`Promesse tenue : ${pn}`, `Vous lui aviez promis ${what}. Il l’a remarqué.`],
    'dr.broken': (pn: string, what: string): Pair => [`Promesse rompue : ${pn}`, `Vous lui aviez promis ${what}. Confiance −20, et il veut vous parler.`],
    'dr.request': (pn: string): Pair => [`${pn} a demandé à partir`, 'Il ne vous croit plus. Rendez-le transférable, refusez, ou donnez-lui une raison de rester.'],
    'dr.interest': (pn: string, club: string, fee: string): Pair => [`${club} fait une offre pour ${pn}`, `${fee}. Ils savent qu’il est agité.`],
    'dr.clause': (pn: string, club: string, fee: string): Pair => [`${club} paie la clause de ${pn}`, `${fee}. C’est contraignant, sauf s’il veut rester.`],
  },
  log: { 'dr.talk.reassure': (pn: string) => `A parlé à ${pn} (l’a rassuré)`, 'dr.talk.challenge': (pn: string) => `A parlé à ${pn} (l’a défié)` },
  whyHead: ['Le vestiaire nous a portés', 'Le vestiaire nous a lâchés'],
  whyGood: (n: number, x: string) => `Cohésion ${n} : une équipe soudée vaut ${x} par joueur sur le terrain.`,
  whyBad: (n: number, x: string) => `Cohésion ${n} : une équipe désunie nous a coûté ${x} par joueur sur le terrain.`,
  ftCoh: 'Cohésion', ftCohQuote: (lv: string) => `Joué à ${lv} face à une équipe normale.`,
  player: {
    room: 'Au vestiaire', release: 'Clause libératoire', none: 'Aucune', role: 'Rôle', wantsOut: 'Veut partir', refused: 'Demande refusée', wantsWord: 'Veut vous parler',
    word: (what: string) => `Votre parole : ${what}`, kept: (what: string) => `Promesse tenue : ${what}`, broken: (what: string) => `Promesse rompue : ${what}`,
    last: (why: string) => `dernier : ${why}`,
  },
  renew: { role: 'Rôle dans le nouveau contrat', release: 'Clause libératoire', releaseOn: (v: string) => `${v}, salaire −10 %`, off: 'Sans clause', promiseNote: 'Un nouveau rôle est une promesse qu’il vous rappellera.' },
  squad: { door: 'Vestiaire', req: 'veut partir', ask: 'veut vous parler', word: 'votre parole' },
  today: { roomWhy: (coh: number) => `Cohésion ${coh}` },
  note: { talk: 'C’est dit.', stays: (pn: string) => `${pn} reste.`, clauseGo: (pn: string) => `${pn} est parti.` },
};
