// Post-match analysis copy (ui2/Analysis.tsx), all four languages; Arabic in the game's Egyptian voice.
import type { UiLang } from './i18n';

const EN = {
  open: 'Match analysis',
  title: 'Match analysis',
  tabs: ['Chances', 'Territory', 'Players'] as [string, string, string],
  us: 'Us', them: 'Them',
  shots: (n: number) => `${n} shot${n === 1 ? '' : 's'}`,
  onTarget: (n: number) => `${n} on target`,
  big: (n: number) => `${n} big chance${n === 1 ? '' : 's'}`,
  xg: 'xG',
  res: { g: 'Goal', v: 'Saved', b: 'Blocked', m: 'Off target' } as Record<'g' | 'v' | 'b' | 'm', string>,
  mapNote: 'Each circle is a shot where it was taken; the bigger it is, the better the chance. Filled: a goal.',
  sources: 'Where the chances came from',
  open_: 'Open play', set: 'Set pieces',
  how: { box: 'In the box', cutback: 'Cut-backs', header: 'Headers', through: 'Through balls', counter: 'Counters', press: 'Won high', long: 'From distance', corner: 'Corners', set: 'From free-kick crosses', fk: 'Free kicks', pen: 'Penalties' } as Record<string, string>,
  none: 'No shots.',
  where: 'Where the ball was',
  whereNote: 'Time on the ball along the pitch, both sides together. We attack left to right.',
  poss: 'Possession',
  entries: 'Into the final third',
  lanes: ['Left', 'Centre', 'Right'] as [string, string, string],
  build: 'Building out past their press',
  prog: 'Through midfield',
  high: 'Won the ball high up',
  counters: 'Counter-attacks',
  of: (a: number, b: number) => `${a} of ${b}`,
  pick: 'Player',
  heat: 'Where he was involved: his contests, shots and fouls.',
  duels: 'Contests won', saves: 'Saves', fouls: 'Fouls', goals: 'Goals', assists: 'Assists', rating: 'Rating',
  noPass: 'The match engine plays contests between players, not single passes, so there is no pass map.',
};
export type AnaStrings = typeof EN;

const AR: AnaStrings = {
  open: 'تحليل الماتش',
  title: 'تحليل الماتش',
  tabs: ['الفرص', 'السيطرة', 'اللعيبة'],
  us: 'إحنا', them: 'هما',
  // Egyptian Arabic counts: 3 to 10 take the plural, everything else the singular.
  shots: (n) => `${n} ${n >= 3 && n <= 10 ? 'تسديدات' : 'تسديدة'}`,
  onTarget: (n) => `${n} على المرمى`,
  big: (n) => `${n} ${n >= 3 && n <= 10 ? 'فرص كبيرة' : 'فرصة كبيرة'}`,
  xg: 'xG',
  res: { g: 'جول', v: 'اتصدّت', b: 'اتصدّ قدامها', m: 'برّه' },
  mapNote: 'كل دايرة تسديدة في المكان اللي اتشاطت منه؛ كل ما كانت أكبر كانت الفرصة أخطر. المليانة: جول.',
  sources: 'الفرص جت منين',
  open_: 'لعب مفتوح', set: 'كور ثابتة',
  how: { box: 'من جوه الصندوق', cutback: 'كورة راجعة', header: 'رأسيات', through: 'بينيات', counter: 'هجمات مرتدة', press: 'خطفناها فوق', long: 'من بعيد', corner: 'كورنرات', set: 'من عرضيات الفاولات', fk: 'فاولات مباشرة', pen: 'ضربات جزاء' },
  none: 'مفيش تسديد.',
  where: 'الكورة كانت فين',
  whereNote: 'وقت الكورة على طول الملعب، الفريقين مع بعض. إحنا بنهاجم من الشمال لليمين.',
  poss: 'الاستحواذ',
  entries: 'دخول التلت الأخير',
  lanes: ['شمال', 'نص', 'يمين'],
  build: 'الخروج بالكورة من ضغطهم',
  prog: 'عدّينا من الوسط',
  high: 'خطفنا الكورة فوق',
  counters: 'هجمات مرتدة',
  of: (a, b) => `${a} من ${b}`,
  pick: 'اللعيب',
  heat: 'الأماكن اللي شارك فيها: التحامات وتسديدات وفاولات.',
  duels: 'التحامات كسبها', saves: 'تصديات', fouls: 'فاولات', goals: 'أجوان', assists: 'أسيست', rating: 'التقييم',
  noPass: 'محرك الماتش بيلعب التحامات بين اللعيبة مش باصات منفصلة، عشان كده مفيش خريطة باصات.',
};

const ES: AnaStrings = {
  open: 'Análisis del partido',
  title: 'Análisis del partido',
  tabs: ['Ocasiones', 'Territorio', 'Jugadores'],
  us: 'Nosotros', them: 'Ellos',
  shots: (n) => `${n} tiro${n === 1 ? '' : 's'}`,
  onTarget: (n) => `${n} a puerta`,
  big: (n) => `${n} ocasión${n === 1 ? '' : 'es'} clara${n === 1 ? '' : 's'}`,
  xg: 'xG',
  res: { g: 'Gol', v: 'Parada', b: 'Bloqueado', m: 'Fuera' },
  mapNote: 'Cada círculo es un tiro donde se hizo; cuanto más grande, mejor la ocasión. Relleno: gol.',
  sources: 'De dónde vinieron las ocasiones',
  open_: 'Juego abierto', set: 'Balón parado',
  how: { box: 'Dentro del área', cutback: 'Pases atrás', header: 'Cabezazos', through: 'Pases al hueco', counter: 'Contras', press: 'Robos arriba', long: 'De lejos', corner: 'Córners', set: 'Centros de falta', fk: 'Faltas directas', pen: 'Penaltis' },
  none: 'Sin tiros.',
  where: 'Dónde estuvo el balón',
  whereNote: 'Tiempo con el balón a lo largo del campo, los dos equipos juntos. Atacamos de izquierda a derecha.',
  poss: 'Posesión',
  entries: 'Llegadas al último tercio',
  lanes: ['Izquierda', 'Centro', 'Derecha'],
  build: 'Salida de balón ante su presión',
  prog: 'Por el centro del campo',
  high: 'Recuperaciones arriba',
  counters: 'Contragolpes',
  of: (a, b) => `${a} de ${b}`,
  pick: 'Jugador',
  heat: 'Dónde participó: sus duelos, tiros y faltas.',
  duels: 'Duelos ganados', saves: 'Paradas', fouls: 'Faltas', goals: 'Goles', assists: 'Asistencias', rating: 'Nota',
  noPass: 'El motor juega duelos entre jugadores, no pases sueltos, así que no hay mapa de pases.',
};

const FR: AnaStrings = {
  open: 'Analyse du match',
  title: 'Analyse du match',
  tabs: ['Occasions', 'Territoire', 'Joueurs'],
  us: 'Nous', them: 'Eux',
  shots: (n) => `${n} tir${n === 1 ? '' : 's'}`,
  onTarget: (n) => `${n} cadré${n === 1 ? '' : 's'}`,
  big: (n) => `${n} grosse${n === 1 ? '' : 's'} occasion${n === 1 ? '' : 's'}`,
  xg: 'xG',
  res: { g: 'But', v: 'Arrêté', b: 'Contré', m: 'Non cadré' },
  mapNote: 'Chaque cercle est un tir, là où il a été pris ; plus il est grand, plus l’occasion était bonne. Plein : un but.',
  sources: 'D’où sont venues les occasions',
  open_: 'Jeu ouvert', set: 'Coups de pied arrêtés',
  how: { box: 'Dans la surface', cutback: 'Centres en retrait', header: 'Têtes', through: 'Passes en profondeur', counter: 'Contres', press: 'Ballons récupérés haut', long: 'De loin', corner: 'Corners', set: 'Centres sur coup franc', fk: 'Coups francs directs', pen: 'Penalties' },
  none: 'Aucun tir.',
  where: 'Où était le ballon',
  whereNote: 'Temps avec le ballon sur la longueur du terrain, les deux équipes ensemble. Nous attaquons de gauche à droite.',
  poss: 'Possession',
  entries: 'Entrées dans le dernier tiers',
  lanes: ['Gauche', 'Centre', 'Droite'],
  build: 'Relance face à leur pressing',
  prog: 'Au milieu de terrain',
  high: 'Ballons récupérés haut',
  counters: 'Contre-attaques',
  of: (a, b) => `${a} sur ${b}`,
  pick: 'Joueur',
  heat: 'Là où il a pesé : ses duels, tirs et fautes.',
  duels: 'Duels gagnés', saves: 'Arrêts', fouls: 'Fautes', goals: 'Buts', assists: 'Passes décisives', rating: 'Note',
  noPass: 'Le moteur joue des duels entre joueurs, pas des passes une à une : il n’y a donc pas de carte des passes.',
};

export const AN: Record<UiLang, AnaStrings> = { en: EN, ar: AR, es: ES, fr: FR };
