// V2.4 dressing room copy. English is the reference; Arabic (Egyptian), Spanish and French are type-checked against it
// in lang-dressing-*.ts. Voice: the dugout. The answer in the headline, the evidence underneath, no exclamation marks.
import type { Archetype, SquadRole, TalkWhy, Tier } from './model/types';

const P = (n: number, one: string, many: string) => (n === 1 ? one : many);
type Pair = [string, string];

export const D_EN = {
  title: 'Dressing room',
  eyebrow: (club: string): string => `${club} · the room`,
  // Headline by mood: [before, emphasis, after]
  mood: {
    together: ['The room is ', 'with you', '.'], settled: ['The room is ', 'settled', '.'],
    restless: ['The room is ', 'restless', '.'], split: ['The room is ', 'split', '.'],
  } as Record<string, [string, string, string]>,
  moodSub: {
    together: 'Same faces, good results, and they believe what you tell them.',
    settled: 'Nothing wrong in there. Nothing special either.',
    restless: 'A few of them are watching what you do next.',
    split: 'Too many of them have stopped listening. Fix it before it costs you on the pitch.',
  } as Record<string, string>,
  facts: { coh: 'cohesion', morale: 'morale', trust: 'trust', open: (n: number): string => P(n, 'promise open', 'promises open') },
  coh: {
    title: 'Cohesion', causes: 'What moved it', none: 'Nothing has moved it yet.',
    worth: (v: string): string => `Worth ${v} on matchday against a normal side`,
    scale: ['In pieces', 'Normal', 'Together'] as [string, string, string],
    how: 'Grows when you keep the same XI and win. New arrivals unsettle it for six matchdays. A leader let down hits it hardest.',
  },
  cause: {
    settled: (): string => 'Same XI again', win: (): string => 'A win', loss: (): string => 'A defeat', drift: (): string => 'Settling back',
    bedIn: (): string => 'New faces bedding in', arrival: (pn: string): string => `${pn} arrived`,
    leaderBroken: (pn: string): string => `Your word to ${pn}`, leaderRequest: (pn: string): string => `${pn} asked to leave`,
    leaderSold: (pn: string): string => `${pn} is gone`, armLeader: (pn: string): string => `${pn} took the armband`, armFringe: (pn: string): string => `${pn} took the armband`,
  } as Record<string, (_pn: string) => string>,
  tiers: { leader: 'Leaders', core: 'Core', fringe: 'Fringe' } as Record<Tier, string>,
  tierSub: {
    leader: 'Their mood becomes everyone’s mood.', core: 'The spine of the squad.', fringe: 'Waiting for a chance.',
  } as Record<Tier, string>,
  leadersSub: 'The room listens to them. Their morale pulls the rest.',
  captain: 'Captain', armband: 'Armband', noCaptain: 'Nobody wears the armband.',
  pickCaptain: 'Who wears the armband?', pickCaptainSub: 'A leader gives the room a lift. A fringe player costs it.',
  give: 'Give him the armband',
  word: 'Your word', noWord: 'No promises open. Nobody is holding you to anything.',
  status: { open: 'On track', slip: 'Slipping', lost: 'Gone', kept: 'Kept', broken: 'Broken' } as Record<string, string>,
  groups: ['goalkeeper', 'defender', 'midfielder', 'forward'] as [string, string, string, string],
  pledge: (key: string, group: string): string => ({
    'role.star': 'star billing', 'role.starter': 'regular starts', 'role.rotation': 'rotation minutes', 'role.prospect': 'a pathway',
    contract: 'a new contract', keep: 'not sold this window', sign: `a new ${group}`,
  } as Record<string, string>)[key.startsWith('sign') ? 'sign' : key] ?? key,
  progress: {
    role: (st: number, el: number, need: number, left: number): string => `${st} ${P(st, 'start', 'starts')} from ${el}. The role needs ${need}%; ${left} ${P(left, 'matchday', 'matchdays')} to go.`,
    prospect: (apps: number, left: number): string => `${apps} of 10 games. ${left} league ${P(left, 'matchday', 'matchdays')} to go, or a loan.`,
    contract: (left: number): string => `A new deal within ${left} ${P(left, 'matchday', 'matchdays')}.`,
    sign: (): string => 'Before the window shuts.',
    keep: (): string => 'Until the window shuts.',
    kept: 'He noticed.', broken: 'He won’t forget it.',
  },
  waiting: 'Wants a word', unsettled: 'Wants out', talkBtn: 'Talk',
  role: { star: 'Star', starter: 'Starter', rotation: 'Rotation', prospect: 'Prospect' } as Record<SquadRole, string>,
  roleSub: { star: 'Starts 7 in 10', starter: 'Starts half the games', rotation: 'Starts 1 in 4', prospect: '10 games, or a loan' } as Record<SquadRole, string>,
  arch: { driven: 'Driven', steady: 'Steady', volatile: 'Volatile', loyal: 'Loyal', mercenary: 'Mercenary', leader: 'Natural leader' } as Record<Archetype, string>,
  archSub: {
    driven: 'A push works better than an arm round him.', steady: 'Hard to rattle, hard to lift.', volatile: 'Praise lifts him, criticism floors him.',
    loyal: 'Forgives more than most.', mercenary: 'Words matter less than money.', leader: 'The room follows his mood.',
  } as Record<Archetype, string>,
  trust: 'Trust', morale: 'Morale',
  cause2: {
    'kept.role': 'promise kept', 'kept.contract': 'promise kept', 'kept.keep': 'promise kept', 'kept.sign': 'promise kept',
    'broken.role': 'promise broken', 'broken.contract': 'promise broken', 'broken.keep': 'promise broken', 'broken.sign': 'promise broken',
    minutes: 'not playing enough', ignored: 'you never gave him that word', 'talk.reassure': 'your arm round him', 'talk.challenge': 'your challenge',
    'talk.promise': 'your promise', armband: 'the armband', armLost: 'lost the armband', listed: 'listed, as he asked', refused: 'request refused',
    stayed: 'stayed on', renewed: 'new deal', win: 'the win', loss: 'the defeat', draw: 'the draw', drift: 'settling', leaderBroken: 'a leader let down',
  } as Record<string, string>,
  talk: {
    btn: 'Talk to him', title: (pn: string): string => `A word with ${pn}`,
    why: {
      asked: 'He asked to see you.', request: 'He has asked to leave.', broken: 'You broke your word to him.', minutes: 'He isn’t playing as much as his role says.',
      role: 'He’s playing above the role in his contract.', contract: 'His deal is running down.', unhappy: 'He’s low.', doubts: 'He doesn’t believe you any more.',
      new: 'He’s new here. First impressions count.', form: 'He was the best man on the pitch.',
    } as Record<TalkWhy, string>,
    none: 'Nothing to talk about. He knows where he stands.',
    wait: 'You spoke to him this week. Give it a few days.',
    tones: { reassure: ['Reassure', 'An arm round the shoulder'], challenge: ['Challenge', 'Tell him what you expect'], promise: ['Give your word', 'A promise he’ll hold you to'] } as Record<string, Pair>,
    staff: 'Staff read',
    choose: 'What do you promise him?',
    types: { role: 'His role', sign: 'Sign a player', keep: 'Not for sale', contract: 'A new contract' } as Record<string, string>,
    bind: {
      'role.star': 'He starts 7 of the next 10 league games he’s fit for. Miss it: trust −20.',
      'role.starter': 'He starts half of the next 10 league games he’s fit for. Miss it: trust −20.',
      'role.rotation': 'He starts 1 in 4 of the next 10 league games. Miss it: trust −20.',
      'role.prospect': '10 games in the next 20 matchdays, or a loan. Miss it: trust −20.',
      contract: 'A new deal on the table within 8 matchdays. Miss it: trust −20.',
      keep: 'He isn’t sold before the window shuts. Sell him and the whole room sees it.',
      sign: 'A new signing in that position before the window shuts. Miss it: trust −20.',
    } as Record<string, string>,
    signPos: 'Which position?',
    giveBtn: 'Give your word', back: 'Back', done: 'Done',
    delta: (label: string, d: number): string => `${label} ${d > 0 ? '+' : d < 0 ? '−' : '±'}${Math.abs(d)}`,
    withdrew: 'He takes back his transfer request.',
    reply: {
      'reassure.driven': 'Fine. I just want to play.', 'reassure.steady': 'Understood, boss.', 'reassure.volatile': 'That means a lot. Honestly.',
      'reassure.loyal': 'I know you’ve got my back.', 'reassure.mercenary': 'Words are nice.', 'reassure.leader': 'Good. I’ll tell the lads.',
      'challenge.driven': 'You’ll get it. Watch me.', 'challenge.steady': 'Heard.', 'challenge.volatile': 'That’s what you think of me?',
      'challenge.loyal': 'I won’t let you down.', 'challenge.mercenary': 'We’ll see who needs who.', 'challenge.leader': 'Fair. I’ll set the standard.',
      'promise.steady': 'Then we have a deal.', 'promise.driven': 'I’ll hold you to that.', 'promise.mercenary': 'Put it in writing next time.',
      'promise.cold': 'I’ve heard promises before.', 'reassure.heard': 'You said that last time.', 'challenge.cold': 'From you? That’s rich.',
      'praise.volatile': 'I’ll run through a wall for you.', 'praise.steady': 'Thanks, boss. Next week too.',
    } as Record<string, string>,
  },
  no: {
    'dr.nothing': 'Nothing to talk about. He knows where he stands.', 'dr.pledged': 'You already gave him your word on something.',
    'dr.window': 'Only while the window is open.', 'dr.role': 'He’s too old to be a prospect.', 'dr.long': 'His deal has years left.',
    'dr.group': 'Pick a position.', 'dr.already': 'He already wears it.', 'dr.noRequest': 'He hasn’t asked to leave.',
    wait: 'You spoke to him this week. Give it a few days.', gone: 'He isn’t ours any more.', trust: 'He doesn’t trust you enough to sign.',
    loaned: 'He’s on loan.', terms: 'Those terms don’t work.', role: 'He’s too old to be a prospect.',
  } as Record<string, string>,
  // ---------- Today cards ----------
  tag: { talk: 'A word', request: 'Wants out', promise: 'Your word', armband: 'Armband', clause: 'Release clause' } as Record<string, string>,
  titles: {
    'ask.asked': (pn: string): string => `${pn} wants a word`, 'ask.broken': (pn: string): string => `${pn} wants a word about your promise`,
    'ask.minutes': (pn: string): string => `${pn} wants to know why he isn’t playing`, 'ask.role': (pn: string): string => `${pn} wants a bigger role`,
    'ask.contract': (pn: string): string => `${pn} wants to talk about his future`, 'ask.unhappy': (pn: string): string => `${pn} wants a word`,
    'ask.doubts': (pn: string): string => `${pn} has doubts`, 'ask.request': (pn: string): string => `${pn} wants out`,
    'ask.new': (pn: string): string => `${pn} wants a word`, 'ask.form': (pn: string): string => `${pn} wants a word`,
    request: (pn: string): string => `${pn} has asked to leave`,
    clause: (pn: string, fee: string, club: string): string => `${club} have met ${pn}’s ${fee} release clause`,
    'due.role.star': (pn: string): string => `Your word to ${pn}: star billing`, 'due.role.starter': (pn: string): string => `Your word to ${pn}: regular starts`,
    'due.role.rotation': (pn: string): string => `Your word to ${pn}: rotation minutes`, 'due.contract': (pn: string): string => `Your word to ${pn}: a new contract`,
    'due.sign': (pn: string, g: string): string => `Your word to ${pn}: a new ${g}`,
    'arm.none': (): string => 'Nobody wears the armband', 'arm.lost': (pn: string): string => `The room has stopped following ${pn}`,
  } as Record<string, (...a: string[]) => string>,
  advice: {
    reassure: (pn: string, a: string): string => `${pn} is ${a.toLowerCase()}. Put an arm round him; that’s what he needs right now.`,
    challenge: (pn: string, a: string): string => `${pn} is ${a.toLowerCase()}. Challenge him. He responds to it.`,
    'promise.role': (_pn: string): string => `Give him your word on his role. We can keep it, and he knows it’s real.`,
    'promise.contract': (_pn: string): string => `Promise him a new deal. He wants to know he has a future here.`,
    'promise.sign': (): string => 'Promise him the signing. He wants to see ambition.',
    'promise.keep': (): string => 'Tell him he isn’t for sale.',
    'req.list': (pn: string): string => `Let ${pn} go. A player who wants out plays like one.`,
    'req.refuse': (_pn: string, n: string): string => `He’s our number ${n}. Refuse, and let him cool down.`,
    'req.promise': (_pn: string): string => `Give him a real role and he might stay. Don’t say it if you won’t do it.`,
    'clause.stay': (_pn: string, n: string): string => `He trusts you (${n}). Ask him to stay; I think he will.`,
    'clause.go': (_pn: string, n: string): string => `Trust is ${n}. He’ll go whatever we say. Take the money gracefully.`,
    'due.start': (pn: string): string => `Start ${pn} on Saturday. It costs us almost nothing and keeps your word.`,
    'due.cost': (pn: string, n: string): string => `Starting ${pn} costs us ${n} in that slot. Your word, your call.`,
    'due.none': (_pn: string): string => `He isn’t fit to start. We may have to let this one go.`,
    'due.contract': (_pn: string, n: string): string => `Put the deal on the table: he’d sign at ${n} a month.`,
    'due.sign': (_pn: string, g: string): string => `We still owe him a ${g}. The window is closing.`,
    arm: (pn: string): string => `${pn}. The room already follows him.`,
    'arm.home': (pn: string, n: string): string => `${pn}. ${n} years old, one of our own, and the room already follows him.`,
  } as Record<string, (...a: string[]) => string>,
  choices: {
    reassure: 'Reassure him', challenge: 'Challenge him', list: 'List him', refuse: 'Refuse', stay: 'Ask him to stay', go: 'Let him go',
    start: (pn: string): string => `Start ${pn}`, letgo: 'Let it go', armband: (pn: string): string => `Armband to ${pn}`, later: 'Not now',
    promise: (what: string): string => `Promise ${what}`,
  } as Record<string, string | ((s: string) => string)>,
  fx: {
    morale: (s: string): string => `Morale ${s}`, trust: (s: string): string => `Trust ${s}`, coh: (s: string): string => `Cohesion ${s}`, shrug: 'Changes little',
    bind: 'You’ll be held to it', bids: 'Bids will come', stillWants: 'Still wants out', withdraw: 'Takes the request back',
    likelyStays: (s: string): string => `Trust ${s}: he’ll listen`, likelyGoes: (s: string): string => `Trust ${s}: he’s going`,
    noChange: 'Nothing changes', onTrack: 'Keeps your word', kept: 'Keeps your word', keepWord: 'You promised to keep him',
  } as Record<string, string | ((s: string) => string)>,
  // ---------- news and inbox ----------
  news: {
    'dr.broken': (pn: string, what: string): Pair => [`${pn} let down`, `The manager promised ${what}. It didn’t happen, and the dressing room noticed.`],
    'dr.request': (pn: string): Pair => [`${pn} asks to leave`, 'A transfer request is on the manager’s desk. Clubs will have heard.'],
    'dr.settled': (pn: string): Pair => [`${pn} settles`, 'The transfer request is off the table. For now.'],
    'dr.withdrawn': (pn: string): Pair => [`${pn} withdraws request`, 'A promise from the manager changed his mind.'],
    'dr.refused': (pn: string): Pair => [`Request refused`, `${pn} is going nowhere, says the club. The player is not happy.`],
    'dr.exit': (pn: string, club: string): Pair => [`${pn} leaves`, `He joins ${club}. The room loses a voice.`],
    'dr.leftFree': (pn: string): Pair => [`${pn} leaves for nothing`, 'His contract ran out and he walked. Not a penny for the club.'],
    'dr.returns': (pn: string, club: string, n: string, s: string): Pair => [`${pn} returns to face his old club`, `${club}, ${s}. His rating: ${n}.`],
    'dr.clauseMet': (pn: string, club: string, n: string): Pair => [`${club} trigger ${pn}’s clause`, `${n}, paid in full. The release clause did the rest.`],
    'dr.stays': (pn: string, club: string): Pair => [`${pn} turns down ${club}`, 'They met his release clause. He wants to stay.'],
    'dr.core': (pn: string, _c: string, n: string): Pair => [`${pn} earns the room`, `${n} and one of our own. The senior players listen to him now.`],
    'dr.leader': (pn: string, _c: string, n: string): Pair => [`${pn}, a leader at ${n}`, 'From the academy to the heart of the dressing room.'],
    'dr.armband': (pn: string): Pair => [`${pn} is the new captain`, 'The manager hands him the armband.'],
    'dr.armbandHome': (pn: string, _c: string, n: string): Pair => [`From the academy to the armband`, `${pn}, ${n}, captains the club he grew up at.`],
  } as Record<string, (...a: string[]) => Pair>,
  msg: {
    'dr.kept': (pn: string, what: string): Pair => [`Promise kept: ${pn}`, `You promised ${what}. He noticed.`],
    'dr.broken': (pn: string, what: string): Pair => [`Promise broken: ${pn}`, `You promised ${what}. Trust −20, and he wants a word.`],
    'dr.request': (pn: string): Pair => [`${pn} has asked to leave`, 'He has stopped believing you. List him, refuse, or give him a reason to stay.'],
    'dr.interest': (pn: string, club: string, fee: string): Pair => [`${club} bid for ${pn}`, `${fee}. They know he’s unsettled.`],
    'dr.clause': (pn: string, club: string, fee: string): Pair => [`${club} meet ${pn}’s release clause`, `${fee}. It’s binding, unless he wants to stay.`],
  } as Record<string, (...a: string[]) => Pair>,
  log: { 'dr.talk.reassure': (pn: string): string => `Had a word with ${pn} (reassured him)`, 'dr.talk.challenge': (pn: string): string => `Had a word with ${pn} (challenged him)` } as Record<string, (pn: string) => string>,
  // ---------- Why, full time ----------
  whyHead: ['The room carried us', 'The room let us down'] as Pair,
  whyGood: (n: number, x: string): string => `Cohesion ${n}: a settled side is worth ${x} a player across the pitch.`,
  whyBad: (n: number, x: string): string => `Cohesion ${n}: an unsettled side cost us ${x} a player across the pitch.`,
  ftCoh: 'Cohesion', ftCohQuote: (lv: string): string => `Played at ${lv} against a normal side.`,
  // ---------- player profile, renewal, squad, Today ----------
  player: {
    room: 'In the room', release: 'Release clause', none: 'None', role: 'Role', wantsOut: 'Wants out', refused: 'Request refused', wantsWord: 'Wants a word',
    word: (what: string): string => `Your word: ${what}`, kept: (what: string): string => `Promise kept: ${what}`, broken: (what: string): string => `Promise broken: ${what}`,
    last: (why: string): string => `last: ${why}`,
  },
  renew: { role: 'Role in the new deal', release: 'Release clause', releaseOn: (v: string): string => `${v}, 10% off his wage`, off: 'No clause', promiseNote: 'A new role is a promise he’ll hold you to.' },
  squad: { door: 'Dressing room', req: 'wants out', ask: 'wants a word', word: 'your word' },
  today: { roomWhy: (coh: number): string => `Cohesion ${coh}` },
  note: { talk: 'Said.', stays: (pn: string): string => `${pn} stays.`, clauseGo: (pn: string): string => `${pn} is gone.` },
};

export type DStrings = typeof D_EN;
