// v0.12 text in Spanish.
import type { NewStrings } from './lang-new';

const P = (n: number, one: string, many: string) => (n === 1 ? one : many);

export const NEW_ES: NewStrings = {
  tabs: ['Inicio', 'Plantilla', 'Partido', 'Fichajes', 'Club'],
  hospitalT: 'Servicio médico',
  hospitalSub: (n: number) => (n ? `${n} ${P(n, 'lesionado', 'lesionados')}` : 'Todos en forma'),
  settingsMore: 'Ajustes y más',
  settingsMoreSub: 'Idioma, partidas, editor, partido rápido, privacidad',

  today: (n: number) => (n ? `Hoy: ${n} ${P(n, 'cosa te necesita', 'cosas te necesitan')}` : 'Todo en orden'),
  allClear: 'Nada te necesita antes del próximo partido.',
  todayItems: {
    offers: (n: number) => `${n} ${P(n, 'oferta', 'ofertas')} por tus jugadores`,
    contracts: (n: number) => `${n} ${P(n, 'contrato acaba', 'contratos acaban')} esta temporada`,
    unavailable: (n: number) => `${n} ${P(n, 'titular lesionado o sancionado', 'titulares lesionados o sancionados')}`,
    tired: (n: number) => `${n} ${P(n, 'titular está cansado', 'titulares están cansados')}`,
    windowOpen: (left: number) => `Mercado abierto: ${P(left, 'queda', 'quedan')} ${left} ${P(left, 'jornada', 'jornadas')}`,
    deadline: 'Último día de mercado: cierra tras esta jornada',
    sponsors: (n: number) => `${n} ${P(n, 'hueco de patrocinio libre', 'huecos de patrocinio libres')}`,
    red: 'El club está en números rojos',
    thin: (n: number) => `Solo ${n} jugadores en la plantilla`,
    jobs: (n: number) => `${n} ${P(n, 'club quiere', 'clubes quieren')} hablar contigo`,
    dev: (n: number) => `${n} puntos de desarrollo por gastar`,
    staff: (n: number) => `Tu cuerpo técnico hizo ${n} ${P(n, 'cosa', 'cosas')} desde el último partido`,
    board: (n: number, d: number) => `Confianza de la directiva ${n}: ${d === 1 ? 'una derrota más' : `${d} derrotas más`} y estás fuera`,
  },
  todayActions: { offers: 'Responder', contracts: 'Renovar', unavailable: 'Arreglar XI', tired: 'Rotar', windowOpen: 'Mercado', deadline: 'Mercado', sponsors: 'Firmar', red: 'Finanzas', thin: 'Fichar', jobs: 'Ver ofertas', dev: 'Entrenar', staff: 'Ver', board: 'Directiva' },
  formT: 'Forma',
  formLetters: ['G', 'E', 'P'],
  nextMatchT: 'Próximo partido',

  ev2: {
    goal: [
      (p: string, c: string) => `¡GOL! ${p} marca para el ${c}.`,
      (p: string, c: string) => `¡GOL! ${p} la pone en la escuadra. El ${c} lo celebra.`,
      (p: string, c: string) => `¡Gol del ${c}! ${p} no perdona.`,
      (p: string, c: string) => `¡GOL! ${p} la manda al fondo. La afición del ${c} ruge.`,
      (p: string, c: string) => `¡GOL! Frialdad total de ${p}. Golpea el ${c}.`,
    ],
    miss: [
      (p: string) => `${p} dispara fuera.`,
      (p: string) => `${p} la manda junto al palo.`,
      (p: string) => `Por encima del larguero, de ${p}.`,
      (p: string) => `${p} se precipita. Fuera.`,
      (p: string) => `${p} prueba desde lejos. Ni cerca.`,
      (p: string) => `Media ocasión para ${p}, pero fuera.`,
    ],
    save: [
      (p: string) => `¡Paradón de ${p}!`,
      (p: string) => `${p} se estira bien y la saca.`,
      (p: string) => `¡Con la yema de los dedos! ${p} la manda a córner.`,
      (p: string) => `${p} aguanta y tapa el disparo.`,
      (p: string) => `Manos firmes de ${p}.`,
      (p: string) => `${p} la lee y la atrapa.`,
    ],
    yellow: [
      (p: string) => `Amarilla para ${p}.`,
      (p: string) => `${p} ve la tarjeta.`,
      (p: string) => `Llega tarde ${p}. Amarilla.`,
      (p: string) => `Amonestado ${p} por agarrar a su rival.`,
    ],
    red: [
      (p: string) => `¡ROJA! ${p} se va a la calle.`,
      (p: string) => `¡Roja! ${p} tiene que irse. Se quedan con diez.`,
      (p: string) => `A la ducha: roja para ${p}.`,
    ],
    injury: [
      (p: string) => `${p} está lesionado y no puede seguir.`,
      (p: string) => `${p} se para. El fisio pide el cambio.`,
      (p: string) => `Mala noticia: ${p} se retira cojeando.`,
    ],
    sub: [
      (off: string, on: string) => `Cambio: entra ${on} por ${off}.`,
      (off: string, on: string) => `Cambio: sale ${off}, entra ${on}.`,
      (off: string, on: string) => `Piernas frescas: ${on} sustituye a ${off}.`,
    ],
  },
  ratingT: 'Nota',
  ratingsT: 'Notas',
  motm: 'Jugador del partido',
  motmN: (n: number) => `${n}× jugador del partido`,
  avgRatingT: 'Nota media',
  xgT: 'Goles esperados (xG)',
  ftTitle: { W: 'Victoria', D: 'Empate', L: 'Derrota' },
  ftSub: 'Lo que cambió el resultado',
  ftPos: 'Posición en liga',
  ftBoard: 'Confianza de la directiva',
  ftFans: 'Afición',
  ftDev: 'Puntos de desarrollo',
  ftOut: (name: string, n: number) => `${name}: baja ${n} ${P(n, 'jornada', 'jornadas')}`,
  ftBan: (name: string) => `${name}: sancionado`,
  ftRecord: 'Nuevo récord del club',
  ftMilestone: 'Hito conseguido',
  ftContinue: 'Continuar',

  windowNames: { summer: 'Mercado de verano', winter: 'Mercado de invierno' },
  windowOpenT: (left: number) => `Abierto: ${P(left, 'queda', 'quedan')} ${left} ${P(left, 'jornada', 'jornadas')}`,
  windowShutT: (n: number) => `Mercado cerrado: abre en ${n} ${P(n, 'jornada', 'jornadas')}`,
  deadlineT: 'Último día de mercado',
  deadlineSub: 'Última oportunidad: el mercado cierra tras esta jornada. Hoy los clubes pujan más.',
  windowClosedBid: 'El mercado está cerrado. Aún puedes fichar agentes libres.',

  transfersT: 'Fichajes',
  trTabs: ['Mercado', 'Seguidos', 'Ofertas', 'Cesiones', 'Operaciones'],
  shortlistAdd: 'Seguir',
  shortlistRemove: 'Dejar de seguir',
  shortlistEmpty: 'No sigues a ningún jugador. Los que sigas aparecen aquí y tus ojeadores afinan su nivel real.',
  findPlayers: 'Buscar jugadores',
  offersEmpty: 'Ahora no hay ofertas por tus jugadores. Llegan con el mercado abierto, más a menudo por los transferibles.',
  answerBids: 'Responder ofertas',
  dealsEmpty: 'Aún no hay operaciones. Fichajes, ventas y libres aparecerán aquí.',
  loansInT: 'Cedidos aquí',
  loansOutT: 'Cedidos fuera',
  loansEmpty: 'Sin cesiones esta temporada. Pide jugadores que no sean titulares en su club o manda a los jóvenes a jugar.',
  loanHint: 'Las cesiones duran la temporada. Paga el sueldo el club que lo recibe. Los jóvenes vuelven mejores.',
  loanInBtn: (fee: string) => `Cesión por la temporada · ${fee}`,
  loanOutBtn: 'Ceder',
  loanTo: 'Cederlo a',
  loanFrom: (club: string) => `Cedido por el ${club}`,
  loanAt: (club: string) => `Cedido al ${club}`,
  loanReason: {
    window: 'Las cesiones solo con el mercado abierto.', budget: 'No hay presupuesto para la tasa de cesión.', wageCap: 'Su sueldo rompería el tope salarial.',
    squad: 'Plantilla completa.', key: 'Es titular allí: no se cede.', limit: 'Ya tienes 4 cesiones en ese sentido.',
    free: 'Los libres se fichan, no se ceden.', loaned: 'Ya está cedido.', injured: 'Un lesionado no puede salir cedido.',
    lenderThin: 'No lo ceden: se quedarían con menos de 16 jugadores.', club: 'Ese club no puede acogerlo.',
  },
  loanedIn: (name: string) => `${name} llega cedido.`,
  loanedOut: (name: string, club: string) => `${name} se va cedido al ${club}.`,
  noLoanClubs: 'Ningún club de su nivel lo quiere cedido ahora.',
  estimateT: 'Estimación de los ojeadores',
  estHint: 'Síguelo y tus ojeadores sabrán su nivel real en 2 jornadas.',

  showT: 'Ver',
  squadViews: ['Media', 'Forma física', 'Contrato', 'Valor', 'Notas'],

  matchTabs: ['Próximo', 'Clasificación', 'Resultados', 'Copas', 'Datos'],
  leaderTabs: ['Goles', 'Asistencias', 'Notas'],
  worldRankings: 'Ranking mundial',

  boardT: 'Directiva y objetivos',
  staffRoomT: 'Cuerpo técnico',
  staffRoomSub: (n: number, all: number) => (n ? `${n} de ${all} tareas delegadas` : 'Lo llevas todo tú. Delega lo que quieras.'),
  financesT: 'Finanzas',
  ticketsT: 'Entradas',
  sponsorsT: 'Patrocinadores',
  facilitiesT: 'Instalaciones',
  hireStaffT: 'Contratar personal',
  historyT: 'Historia y récords',
  historySub: 'Temporadas, récords, títulos, canteranos',

  staffIntro: 'Pasa cualquier tarea a tu cuerpo técnico. La harán cada jornada, tan bien como les permita su calidad. Los partidos siempre los juegas tú.',
  staffYours: 'Tu cuerpo técnico',
  qualityT: 'Calidad',
  dutiesT: 'Tareas',
  dutyGroups: { matchday: 'Día de partido', squad: 'Plantilla', transfers: 'Fichajes', club: 'Club' },
  duties: {
    lineup: ['Alineación y cambios', 'Elige el mejor XI para cada partido.'],
    tactics: ['Táctica', 'Elige sistema y mentalidad para cada rival.'],
    scouting: ['Informes del rival', 'Compra un informe antes de los partidos duros y usa su plan.'],
    training: ['Entrenamiento', 'Fija la carga y gasta los puntos de desarrollo.'],
    medical: ['Servicio médico', 'Paga rehabilitación en las lesiones largas.'],
    morale: ['Moral', 'Habla al vestuario cuando la moral cae.'],
    academy: ['Cantera', 'Busca promesas, sube a las listas y vende el resto.'],
    contracts: ['Contratos', 'Renueva a quien merece la pena desde la jornada 5.'],
    selling: ['Ventas', 'Responde ofertas y pone en venta a los que sobran.'],
    signing: ['Fichajes', 'Ficha para la posición más corta con el mercado abierto.'],
    loans: ['Cesiones', 'Cede a los jóvenes para que jueguen.'],
    sponsors: ['Patrocinadores', 'Firma la mejor oferta para cada hueco libre.'],
    tickets: ['Precio de entradas', 'Pone el precio que más recauda sin vaciar la grada.'],
  },
  matchDuty: ['Jugar el partido', 'Siempre tú.'],
  meT: 'Yo',
  staffT: 'Staff',
  delegateAll: 'Dejarlo todo al staff',
  takeAll: 'Hacerlo todo yo',
  needStaff: (role: string) => `Primero contrata: ${role.toLowerCase()}`,
  staffLogT: 'Lo que hizo tu cuerpo técnico',
  staffLogEmpty: 'Nada todavía. Delega una tarea y tu personal anotará aquí lo que hace.',
  staffLog: {
    'training:load': (a) => `Carga de entrenamiento: ${['recuperación', 'equilibrada', 'dura'][a.n] ?? 'equilibrada'}.`,
    'training:dev': (a) => `Puntos de desarrollo para ${a.pn} (+1 de media).`,
    'medical:rehab': (a) => `Pagó la rehabilitación de ${a.pn}.`,
    'morale:talk': (a) => `Charla al vestuario: la moral estaba en ${a.n}.`,
    'academy:promote': (a) => `Subió a ${a.pn} desde la cantera.`,
    'academy:sold': (a) => `Vendió los derechos de ${a.pn} por ${a.money(a.n)}.`,
    'academy:scouted': (a) => `Encontró ${a.n} ${P(a.n, 'promesa nueva', 'promesas nuevas')}.`,
    'selling:sold': (a) => `Vendió a ${a.pn} al ${a.club} por ${a.money(a.n)}.`,
    'selling:rejected': (a) => `Rechazó ${a.money(a.n)} por ${a.pn}.`,
    'selling:listed': (a) => `Puso a ${a.pn} en la lista de transferibles.`,
    'contracts:renewed': (a) => `Renovó a ${a.pn} ${a.n} ${P(a.n, 'temporada', 'temporadas')} más.`,
    'contracts:capRaise': (a) => `Subió el tope salarial ${a.money(a.n)} al mes para retener a ${a.pn}.`,
    'signing:signed': (a) => `Fichó a ${a.pn} ${a.club ? `del ${a.club}` : 'libre'} por ${a.n ? a.money(a.n) : '0'}.`,
    'loans:out': (a) => `Cedió a ${a.pn} al ${a.club}.`,
    'sponsors:signed': (a) => `Firmó con ${a.pn}: ${a.money(a.n)} al mes.`,
    'tickets:price': (a) => `Precio de la entrada: ${a.s}.`,
    'tactics:formation': (a) => `Cambió al ${a.s}.`,
    'scouting:report': (a) => `Compró un informe del ${a.club}.`,
  },
  staffNames2: { director: 'Director deportivo' },
  staffEffects2: { director: 'Contratos, ofertas, fichajes, cesiones, patrocinios y entradas cuando se los delegas' },
  ledgerKeys2: { loans: 'Tasas de cesión' },

  wagesOfCap: 'Sueldos, del tope',
  newEnd: (y: number) => `Nuevo final: ${y}`,
  resumedFrom: (min: number) => `Reanudado desde el ${min}′`,
  playingT: (what: string) => `Jugando ${what}…`,
  saveRefused: (why: string) => `No se pudo guardar: ${why}`,
  tacticsTabs: ['Sistema', 'Estilo', 'Balón parado'],
  confirmSub: (off: string, on: string) => `Confirmar cambio: ${off} ↔ ${on}`,
  pickSubHint: 'Elige quién sale y quién entra.',
  detailsT: 'Detalles',
  hideDetailsT: 'Ocultar detalles',
  radarLocked: 'Ojea al rival para ver su perfil.',

  histTabs: ['Temporadas', 'Récords', 'Títulos', 'Cantera'],
  seasonsEmpty: 'Tu primera temporada sigue en marcha. Las terminadas se guardan aquí.',
  recordsEmpty: 'Los récords aparecen tras jugar algunos partidos.',
  trophiesEmpty: 'Aún no hay títulos. Gana una liga o una copa y entra en la vitrina.',
  gradsEmpty: 'Aún no hay canteranos. Sube una promesa y sigue su historia aquí.',
  recordNames: {
    bigWin: 'Mayor victoria', mostPoints: 'Más puntos en liga', mostGoals: 'Más goles en liga', unbeaten: 'Racha más larga sin perder',
    scorer: 'Máximo goleador en una temporada', bestFinish: 'Mejor puesto en liga', bestBuy: 'Fichaje récord', bestSale: 'Venta récord',
  },
  gamesN: (n: number) => `${n} ${P(n, 'partido', 'partidos')}`,
  gradLine: (apps: number, goals: number) => `${apps} PJ · ${goals} goles esta temporada`,
  trophyKinds: { league: 'Liga', cup: 'Copa', continental: 'Copa continental', promotion: 'Ascenso' },

  updWeb: (v: string) => `The Gaffer ${v} está listo: arreglos y novedades.`,
  updWebBtn: 'Actualizar',
  updApk: (v: string) => `Ya está la versión ${v} de la app. Instálala para seguir recibiendo novedades.`,
  updApkBtn: 'Descargar',
  updLater: 'Luego',
  supportT: 'Apoya a The Gaffer',
  supportBody: 'Un pack de Socio de pago único: todos los estilos de club, insignia de Socio en tu tarjeta y sin anuncios. El juego sigue completo para todos.',
  supportBtn: 'Conseguir el pack de Socio',
  supportSoon: 'El pack de Socio llega pronto.',
  supporterBadge: 'Socio',
  supportThanks: 'Gracias por apoyar a The Gaffer. Todo desbloqueado.',
  looksT: 'Estilo',
  looks: ['Verde azulado', 'Focos', 'Césped', 'Rojo derbi'],
  looksLocked: 'Pack de Socio',
  rewardedBtn: 'Ver un anuncio corto: informe gratis',
  rewardedHint: 'Opcional. Siempre puedes pagar el informe con dinero del club.',
  adFailed: 'Ahora no hay anuncios. Prueba más tarde.',
  sponsoredT: 'Patrocinado',
  howToBody2: [
    ['Tu trabajo', 'Elige un club y firma el contrato. La directiva fija objetivos de liga y copa. Cúmplelos y tu reputación crece; fállalos y te pueden echar.'],
    ['Inicio', 'Inicio muestra lo que te necesita hoy, cada cosa con un botón. Despéjalo y juega el próximo partido.'],
    ['Jornadas', 'Pulsa Jugar el partido para verlo en directo, o elige resultado rápido. Cada partido acaba con notas, jugador del partido y una tarjeta con lo que cambió el resultado.'],
    ['Táctica', 'Elige sistema, XI, mentalidad, presión y pase. Las filosofías se ganan entre sí como piedra, papel o tijera, y tu dominio crece cada partido. Espía al rival antes de los grandes.'],
    ['Tu cuerpo técnico', 'Club › Cuerpo técnico: delega cualquier tarea (alineación, entrenamiento, contratos, fichajes y más) o hazla tú. Los partidos siempre los juegas tú.'],
    ['Fichajes', 'Compra y vende con el mercado abierto (verano e invierno, con último día). Los libres se fichan cuando quieras. Sigue jugadores para que tus ojeadores sepan su nivel real, y cede o pide cedidos por la temporada.'],
    ['Dinero', 'Entran taquilla, TV y patrocinio; salen sueldos, personal y mantenimiento. Mejora instalaciones, contrata personal y acaba la temporada en positivo.'],
    ['Copas', 'La copa nacional es eliminatoria desde el inicio. Las continentales empiezan con grupos de cuatro: pasan los dos primeros.'],
    ['Tu carrera', 'Gana XP y licencias, haz cursos, suma hitos y títulos y bate récords del club. Te llamarán clubes más grandes.'],
    ['Guardado', 'La carrera se guarda sola tras cada partido y se comprueba al cargar. Exporta una partida desde Club › Ajustes y más.'],
  ],
  privacyBody2: [
    ['Qué guardamos', 'Tu carrera, ajustes y foto de entrenador se guardan solo en este dispositivo. La comprobación de versiones pide a Semba Games el último número de versión y no envía datos de tu carrera.'],
    ['Funciones en línea', 'Anuncios y compras, cuando estén activos, van claramente marcados. Los anuncios web son de Google AdSense, que puede usar cookies para mostrarlos y medirlos. Las compras las gestiona Stripe; nunca vemos tu tarjeta.'],
    ['Sin cuenta', 'The Gaffer no tiene inicio de sesión. Tu carrera vive en tu dispositivo y puedes exportarla cuando quieras desde Ajustes.'],
    ['Partidas', 'Una partida exportada va donde tú elijas. Importar solo lee el archivo que eliges.'],
    ['Fotos', 'La foto de tu tarjeta de entrenador se queda en este dispositivo y solo sirve para dibujar la tarjeta.'],
    ['Borrar tus datos', 'Empieza de nuevo desde Ajustes o borra los datos de la app, y todo desaparece.'],
    ['Contacto', '¿Dudas? sembagames.app'],
  ],

  philosophyHints: {
    balanced: 'Todas las instrucciones en el medio. El equipo se lo sabe de memoria.',
    possession: 'Pase corto, ritmo lento, laterales por dentro y falso 9. Castiga a equipos cansados o hundidos; necesita pasadores.',
    counter: 'Replegarse, salir al instante y jugar directo. Letal contra equipos que se adelantan.',
    gegenpress: 'Línea alta, presión alta, ritmo rápido. Roba cerca del gol; cansa, y un buen equipo de toque la supera.',
    bus: 'Todos atrás, estrechos, a la contra. Lo más difícil de batir, y lo que menos marca.',
    wings: 'Amplitud, laterales profundos y los altos arriba en córners. Necesita extremos rápidos contra laterales lentos.',
    direct: 'Balones largos al pívot, ritmo rápido. Se salta la presión alta; necesita un delantero fuerte.',
  },
  eng: {
    comma: ', ',
    ins: {
      mentality: { t: 'Mentalidad', o: ['Autobús', 'Defensiva', 'Equilibrada', 'Ofensiva', 'Ataque total'], h: [
        'Todos detrás del balón. Muy difícil de romper, pero apenas amenazarás.',
        'Los laterales se quedan y suben menos jugadores. Más seguro, menos peligro.',
        'Mismo número de jugadores en ataque y en defensa.',
        'Más gente en el área y más tiros, pero menos jugadores atrás si la pierdes.',
        'Todos arriba. Ocasiones para los dos: te van a pillar a la contra.',
      ] },
      pressing: { t: 'Presión', o: ['Bloque bajo', 'Bloque medio', 'Presión alta'], h: [
        'Déjales el balón en su campo. Piernas frescas y menos faltas, pero salen jugando tranquilos.',
        'Presión en el medio cuando toca.',
        'Caza el balón en su tercio: robos cerca de la portería, pero cansa, hace más faltas y un equipo que toca bien te supera.',
      ] },
      line: { t: 'Línea defensiva', o: ['Baja', 'Normal', 'Alta'], h: [
        'Repliégate: sin espacio a la espalda, pero tienen más tiempo en el medio.',
        'Una línea normal.',
        'Achica el campo y déjalos en fuera de juego, pero los delanteros rápidos correrán a tu espalda.',
      ] },
      width: { t: 'Amplitud', o: ['Estrecha', 'Normal', 'Amplia'], h: [
        'Juntos por dentro: más combinaciones por el centro, menos centros.',
        'Uso equilibrado del campo.',
        'Abre el campo: extremos y laterales en uno contra uno, más centros. Ideal con bandas rápidas.',
      ] },
      tempo: { t: 'Ritmo', o: ['Lento', 'Normal', 'Rápido'], h: [
        'Guarda el balón y espera el hueco: más posesión, menos pérdidas, menos ocasiones.',
        'Ritmo normal.',
        'Juega vertical antes de que se ordenen: más ataques y contras, más pérdidas, más cansancio.',
      ] },
      passing: { t: 'Pase', o: ['Corto', 'Mixto', 'Directo'], h: [
        'Sal jugando desde atrás. Necesita buenos pasadores; la presión alta te puede hacer daño.',
        'Corto cuando se pueda, largo cuando haga falta.',
        'Balones largos a los delanteros: te saltas su presión, pero pierdes más segundas jugadas.',
      ] },
      fullback: { t: 'Laterales', o: ['Clásicos', 'Profundos', 'Por dentro'], h: [
        'Se quedan atrás: sólido, pero sin un hombre de más en banda.',
        'Suben siempre: dos contra uno en banda, pero dejan un agujero a la contra.',
        'Se meten al medio: un pasador más por dentro, menos amplitud.',
      ] },
      striker: { t: 'Delantero', o: ['Referencia', 'Pívot', 'Falso 9', 'Presionante'], h: [
        'Juega al límite del fuera de juego.',
        'Referencia para centros y balones largos. Necesita un delantero fuerte.',
        'Baja al medio para sumar gente, pero hay menos jugadores en el área.',
        'Lidera la presión desde arriba. Cansa.',
      ] },
      trap: { t: 'Trampa de presión', o: ['Ninguna', 'Bandas', 'Centro', 'Carriles interiores'], h: [
        'Sin trampa.',
        'Llévalos a la banda y ahógalos. El centro queda algo más libre.',
        'Aléjalos del centro. Las bandas quedan algo más libres.',
        'Presiona un poco todos los carriles. Necesita la presión activada.',
      ] },
      routine: { t: 'Córners', o: ['Variados', 'Arriba los altos', 'En corto'], h: [
        'Un poco de todo.',
        'Suben los centrales: más remates de cabeza, pero menos defensas atrás si falla.',
        'Jugada en corto: conservas el balón, menos remates del córner en sí.',
      ] },
      counter: { t: 'Contra inmediata', h: 'Sal en cuanto la recuperes. Más contraataques; tu medio campo se queda un poco más atrás.' },
      waste: { t: 'Perder tiempo', h: 'Frena cada reanudación cuando ganas. Menos ocasiones para ambos y alguna amarilla.' },
      mark: { t: 'Marcaje individual', none: 'Nadie', h: 'Ponle una sombra a su jugador clave: gana muchos menos duelos, pero el marcador deja un hueco.' },
      formation: 'Sistema',
      on: 'Sí', off: 'No',
    },
    styleHint: 'Elegir una filosofía fija estas instrucciones; ajústalas abajo.',
    assistantPick: 'Tu asistente cambiaría',
    momentum: 'Dominio',
    territory: 'Territorio',
    xgFrom: 'De dónde llegaron las ocasiones',
    statsMore: ['Ocasiones claras', 'Fueras de juego', 'Llegadas al último tercio', 'Balones robados arriba'],
    themes: { centre: 'Por el centro', wide: 'Por las bandas', behind: 'A la espalda', counter: 'A la contra', press: 'Robando arriba', setpiece: 'Balón parado', long: 'De lejos', pen: 'Penaltis' },
    themeIn: { centre: 'por el centro', wide: 'por las bandas', behind: 'a nuestra espalda', counter: 'a la contra', press: 'robando arriba', setpiece: 'a balón parado', long: 'de lejos', pen: 'de penalti' },
    goalFlash: '¡GOL!',
    soundOn: 'Sonido activado', soundOff: 'Sonido desactivado',
    whyHT: 'Descanso: qué está pasando',
    whyFT: 'Por qué acabó así',
    assistant: 'Tu asistente',
    verdict: {
      deserved: 'Nos lo ganamos. {xa} xG contra {xb}: el marcador dice la verdad.',
      smash: 'Lo aceptamos, pero ellos generaron más ({xb} xG contra {xa}). Fuimos letales cuando tocaba.',
      robbed: 'Fuimos mejores, {xa} xG contra {xb}, y no nos llevamos nada. Si seguimos así, los goles llegarán.',
      beaten: 'Sin excusas: generaron más ({xb} xG contra {xa}). Hay que ver por qué.',
      clinical: 'Letales: {ga} goles con {xa} xG.',
      wasteful: 'Creamos las ocasiones ({xa} xG) y no las metimos.',
      level: 'Nada entre los dos: {xa} xG contra {xb}.',
      even: 'Ellos fueron mejores ({xb} xG contra {xa}). No podemos quejarnos del resultado.',
    },
    point: {
      sourceMe: 'Lo mejor nuestro llegó {theme}: {x} xG en {n} tiros.',
      sourceMe1: 'Lo mejor nuestro llegó {theme}: {x} xG en un solo tiro.',
      sourceThem1: 'Casi todo su peligro llegó {theme}: {x} xG en un solo tiro.',
      sourceThem: 'Casi todo su peligro llegó {theme}: {x} xG en {n} tiros.',
      midfieldMe: 'El medio es nuestro: pasa el {x}% de nuestras jugadas, ellos el {y}%.',
      midfieldThem: 'Nos ganan el medio: pasa el {y}% de sus jugadas y solo el {x}% de las nuestras.',
      pressed: 'Su presión nos hace daño: {n} balones perdidos en nuestro tercio.',
      pressedXg: 'Su presión nos hace daño: {n} balones perdidos en nuestro tercio y {x} xG salidos de nuestros errores.',
      pressing: 'Nuestra presión funciona: {n} balones robados arriba.',
      duelMeWin: '{a} está destrozando a {d}: {n} de {of} duelos ganados.',
      duelMeLose: '{d} tiene a {a} en el bolsillo: {n} de {of} para el defensa.',
      duelThemWin: '{a} le está ganando a {d}: {n} de {of} duelos.',
      duelThemLose: '{d} ha anulado a {a}: {n} de {of} ganados.',
      finishMeGood: 'Letales: {n} goles con {x} xG.',
      finishMeBad: 'Estamos fallando: {n} con {x} xG.',
      finishThemGood: 'Ellos han fallado mucho: {n} con {x} xG. No cuentes con que se repita.',
      finishThemBad: 'Nos castigan: {n} goles con solo {x} xG.',
      keeperMe: '{a} nos mantiene vivos: {n} paradas, {x} xG evitados.',
      keeperThem: 'Su portero {a} está en un día enorme: {n} paradas.',
      tiredMe: 'Nos quedamos sin piernas: {n}% de forma al final, ellos {y}%.',
      tiredThem: 'Se les acabaron las piernas ({n}% de forma) y ahí golpeamos.',
      redMe: 'La roja a {a} en el {min}′ lo cambió todo.',
      redThem: 'Su roja en el {min}′ abrió el partido.',
      changeGood: 'El cambio del {min}′ ({what}) funcionó: nuestro xG pasó de {x} a {y} por 90.',
      changeBad: 'El cambio del {min}′ ({what}) no ha funcionado: xG {x} → {y} por 90.',
      theyChanged: 'Su banquillo reaccionó en el {min}′: {what}.',
    },
    tipsHT: 'Lo que yo cambiaría',
    tipsFT: 'La próxima vez contra ellos',
    tipWhy: {
      centreMe: 'más ocasiones por el centro', wideMe: 'más juego por las bandas', wideMeAD: '{a} puede superar a {d} por banda',
      behindMe: 'más balones a la espalda', behindMeAD: '{a} puede correr a la espalda de {d}', counterMe: 'más contraataques', counterMeA: 'más contras para {a}',
      pressMe: 'robamos arriba más a menudo', setpieceMe: 'más peligro a balón parado', longMe: 'más tiros de lejos', penMe: 'más penaltis a favor',
      centreThem: 'menos ocasiones suyas por el centro', wideThem: 'menos centros contra nosotros', wideThemA: 'anula a {a} en la banda',
      behindThem: 'nadie se nos mete a la espalda', behindThemA: 'frena las carreras de {a} a la espalda', counterThem: 'corta sus contras', counterThemA: 'frena a {a} a la contra',
      pressThem: 'nos saca de su presión', setpieceThem: 'menos balón parado en contra', longThem: 'menos tiros de lejos en contra', penThem: 'menos penaltis en contra',
    },
    winChance: 'Opciones de ganar {w0}% → {w1}%',
    apply: 'Hacer el cambio',
    applied: 'Cambio hecho',
    noTips: 'Yo no tocaría nada.',
    shape: (f: string) => `Sistema ${f}`,
    reason: { chase: 'buscando el resultado', protect: 'defendiendo la ventaja', red: 'tras la roja', tenmen: 'contra diez', tip: '', read: 'tras leer la primera parte', prep: 'pensando en el rival', wx3: 'por el viento', wx4: 'por el calor', conceded: 'tras encajar', pinned: 'por estar encerrados atrás' },
    changeLine: '{c}: {what}{why}.',
    talkLine: 'Charla de {c} en el descanso: «{what}».',
    c: {
      box: ['{a} se la filtra a {s}', 'una pared en la frontal deja solo a {s}', '{s} encuentra medio metro en un área llena', '{s} se gira rápido en el área', 'toque rápido por el centro y se abre para {s}'],
      cutback: ['{s} remata un pase atrás desde la línea de fondo', '{a} llega a línea de fondo y la pone atrás para {s}', '{a} se va de {d} y se la pasa atrás a {s}', 'pase atrás raso de {a} para {s}'],
      header: ['{s} se eleva a por el centro', '{s} cabecea un centro desde la banda', '{a} saca el centro y {s} se eleva', '{s} ataca el centro de {a}', 'centro largo de {a} y remate de {s}'],
      through: ['{a} parte la defensa y {s} se queda solo', '{s} rompe la línea con el pase de {a}', 'un balón por encima y {s} se escapa'],
      counter: ['{s} sale disparado tras el robo', 'una contra relámpago termina en {s}', 'tres pases y {s} encara la portería'],
      press: ['{s} caza un pase suelto arriba', 'la presión provoca el error y {s} entra', '{s} le roba al último defensa y va a puerta'],
      long: ['{s} lo intenta desde 25 metros', '{s} prueba suerte desde lejos', 'el balón le queda a {s} fuera del área'],
      corner: ['{s} salta más que nadie en el córner de {a}', 'córner de {a} y cabezazo de {s}', '{s} la peina en el primer palo'],
      set: ['la falta de {a} la remata {s}', '{s} llega al balón parado'],
      fk: ['{s} la roza por encima de la barrera', '{s} se prepara para lanzar la falta'],
      pen: ['{s} se planta ante el penalti', '{s} coloca el balón en el punto, mirando a {k}'],
      goal: ['¡y marca!', '¡GOL! A la escuadra.', '¡y la clava!', '¡y entra!', '¡al palo y dentro!', 'sin fallo. ¡GOL!', '¡la red se mueve!'],
      save: ['pero {k} la para.', 'pero {k} se estira.', '{k} la manda a córner.', 'directo a {k}.', '{k} aguanta y tapa.'],
      miss: ['pero se va por encima.', 'por poco fuera.', 'se le va desviado.', 'fuera.', 'por encima del larguero.'],
      block: ['¡bloqueado por {b}!', '{b} se tira al suelo y la tapa.', 'rechazado.'],
      after: {
        lead: ['¡{c} se adelanta!', '¡{c} manda!'], equal: ['¡Es el empate!', '¡Igualados!'], more: ['{c} amplía la ventaja.', 'Eso debería sentenciarlo.'],
        late: ['¡Gol en el último suspiro!', '¡Drama al final!'], brace: ['Doblete de {s}.'], hat: ['¡Triplete de {s}!'], back: ['{c} recorta.', '¡Hay partido!'],
      },
      yellow: ['{s} ve la amarilla.', 'Amarilla para {s}.', 'El árbitro amonesta a {s}.'],
      yellowWaste: ['{s} ve la amarilla por perder tiempo.'],
      red: ['¡ROJA! {s} a la calle.', '¡{s} expulsado! Se quedan con diez.'],
      injury: ['{s} está en el suelo y no puede seguir.', 'Malas noticias: {s} se lesiona.'],
      sub: ['Cambio en {c}: entra {a}, sale {s}.', '{a} entra por {s}.', 'Piernas frescas: {a} por {s}.'],
      offside: ['{s} está en fuera de juego.', 'Sube la bandera contra {s}.'],
      corner2: ['Córner para {c}.'],
      flow: {
        camp: ['{c} está instalado en el último tercio.', '{c} los tiene encerrados.', 'Oleada tras oleada de {c}.'],
        press: ['{c} caza el balón muy arriba.', 'La presión de {c} asfixia.'],
        calm: ['Fase tranquila: los dos se estudian.', 'Juego paciente en el medio.'],
      },
    },
  },
};
