// Vestuario (V2.4) en español: la voz del banquillo. Comprobado contra el inglés (lang-dressing.ts).
import type { DStrings } from './lang-dressing';

type Pair = [string, string];
const P = (n: number, one: string, many: string) => (n === 1 ? one : many);

export const D_ES: DStrings = {
  title: 'Vestuario',
  eyebrow: (club: string) => `${club} · el vestuario`,
  mood: {
    together: ['El vestuario está ', 'contigo', '.'], settled: ['El vestuario está ', 'tranquilo', '.'],
    restless: ['El vestuario está ', 'inquieto', '.'], split: ['El vestuario está ', 'partido', '.'],
  },
  moodSub: {
    together: 'Las mismas caras, buenos resultados, y se creen lo que les dices.',
    settled: 'Nada va mal ahí dentro. Nada especial tampoco.',
    restless: 'Unos cuantos están esperando a ver qué haces ahora.',
    split: 'Demasiados han dejado de escuchar. Arréglalo antes de que lo pagues en el campo.',
  },
  facts: { coh: 'cohesión', morale: 'moral', trust: 'confianza', open: (n: number) => P(n, 'promesa abierta', 'promesas abiertas') },
  coh: {
    title: 'Cohesión', causes: 'Qué la movió', none: 'Nada la ha movido aún.',
    worth: (v: string) => `Vale ${v} en el partido contra un rival normal`,
    scale: ['Rota', 'Normal', 'Una piña'],
    how: 'Sube si repites once y ganas. Los fichajes la desordenan seis jornadas. Fallarle a un líder es lo que más duele.',
  },
  cause: {
    settled: () => 'Mismo once', win: () => 'Una victoria', loss: () => 'Una derrota', drift: () => 'Volviendo a su sitio',
    bedIn: () => 'Los nuevos se adaptan', arrival: (pn: string) => `Llega ${pn}`,
    leaderBroken: (pn: string) => `Tu palabra a ${pn}`, leaderRequest: (pn: string) => `${pn} pidió salir`,
    leaderSold: (pn: string) => `${pn} se fue`, armLeader: (pn: string) => `${pn} lleva el brazalete`, armFringe: (pn: string) => `${pn} lleva el brazalete`,
  },
  tiers: { leader: 'Líderes', core: 'Núcleo', fringe: 'Secundarios' },
  tierSub: { leader: 'Su humor es el humor de todos.', core: 'La columna del equipo.', fringe: 'Esperando su oportunidad.' },
  leadersSub: 'El vestuario les escucha. Su moral tira de la del resto.',
  captain: 'Capitán', armband: 'Brazalete', noCaptain: 'Nadie lleva el brazalete.',
  pickCaptain: '¿Quién lleva el brazalete?', pickCaptainSub: 'Un líder levanta al vestuario. Un secundario le cuesta.',
  give: 'Dale el brazalete',
  word: 'Tu palabra', noWord: 'No hay promesas abiertas. Nadie te reclama nada.',
  status: { open: 'En camino', slip: 'Se escapa', lost: 'Perdida', kept: 'Cumplida', broken: 'Rota' },
  groups: ['portero', 'defensa', 'centrocampista', 'delantero'],
  pledge: (key: string, group: string) => ({
    'role.star': 'ser la estrella', 'role.starter': 'jugar de titular', 'role.rotation': 'minutos de rotación', 'role.prospect': 'un camino al primer equipo',
    contract: 'un contrato nuevo', keep: 'no venderle en este mercado', sign: `un ${group} nuevo`,
  } as Record<string, string>)[key.startsWith('sign') ? 'sign' : key] ?? key,
  progress: {
    role: (st: number, el: number, need: number, left: number) => `${st} ${P(st, 'titularidad', 'titularidades')} de ${el}. El rol pide un ${need}%; quedan ${left} ${P(left, 'jornada', 'jornadas')}.`,
    prospect: (apps: number, left: number) => `${apps} de 10 partidos. Quedan ${left} ${P(left, 'jornada', 'jornadas')} de liga, o una cesión.`,
    contract: (left: number) => `Un contrato nuevo en ${left} ${P(left, 'jornada', 'jornadas')}.`,
    sign: () => 'Antes de que cierre el mercado.',
    keep: () => 'Hasta que cierre el mercado.',
    kept: 'Lo ha notado.', broken: 'No lo va a olvidar.',
  },
  waiting: 'Quiere hablar', unsettled: 'Quiere irse', talkBtn: 'Hablar',
  role: { star: 'Estrella', starter: 'Titular', rotation: 'Rotación', prospect: 'Promesa' },
  roleSub: { star: 'Titular 7 de 10', starter: 'Titular la mitad', rotation: 'Titular 1 de 4', prospect: '10 partidos o una cesión' },
  arch: { driven: 'Ambicioso', steady: 'Sereno', volatile: 'Temperamental', loyal: 'Leal', mercenary: 'Mercenario', leader: 'Líder nato' },
  archSub: {
    driven: 'Le funciona más un empujón que una palmada.', steady: 'Difícil de alterar, difícil de levantar.', volatile: 'Los elogios le elevan, las críticas le hunden.',
    loyal: 'Perdona más que la mayoría.', mercenary: 'Las palabras le importan menos que el dinero.', leader: 'El vestuario sigue su estado de ánimo.',
  },
  trust: 'Confianza', morale: 'Moral',
  cause2: {
    press: 'lo que dijiste a la prensa',
    'kept.role': 'promesa cumplida', 'kept.contract': 'promesa cumplida', 'kept.keep': 'promesa cumplida', 'kept.sign': 'promesa cumplida',
    'broken.role': 'promesa rota', 'broken.contract': 'promesa rota', 'broken.keep': 'promesa rota', 'broken.sign': 'promesa rota',
    minutes: 'no juega lo suficiente', ignored: 'le dejaste esperando', 'talk.reassure': 'tu apoyo', 'talk.challenge': 'tu reto',
    'talk.promise': 'tu promesa', armband: 'el brazalete', armLost: 'perdió el brazalete', listed: 'transferible, como pidió', refused: 'petición rechazada',
    stayed: 'se quedó', renewed: 'contrato nuevo', win: 'la victoria', loss: 'la derrota', draw: 'el empate', drift: 'asentándose', leaderBroken: 'un líder defraudado',
  },
  talk: {
    btn: 'Hablar con él', title: (pn: string) => `Una charla con ${pn}`,
    why: {
      asked: 'Ha pedido verte.', request: 'Ha pedido salir.', broken: 'Rompiste tu palabra con él.', minutes: 'No juega lo que dice su rol.',
      role: 'Juega por encima del rol de su contrato.', contract: 'Su contrato se acaba.', unhappy: 'Está hundido.', doubts: 'Ya no te cree.',
      new: 'Es nuevo aquí. La primera impresión cuenta.', form: 'Fue el mejor del partido.',
    },
    none: 'No hay nada que hablar. Sabe dónde está.',
    wait: 'Ya hablaste con él esta semana. Dale unos días.',
    tones: { reassure: ['Tranquilizarle', 'Una mano en el hombro'], challenge: ['Retarle', 'Dile lo que esperas de él'], promise: ['Darle tu palabra', 'Una promesa que te reclamará'] },
    staff: 'Lectura del cuerpo técnico',
    choose: '¿Qué le prometes?',
    types: { role: 'Su rol', sign: 'Un fichaje', keep: 'No se vende', contract: 'Contrato nuevo' },
    bind: {
      'role.star': 'Titular en 7 de los próximos 10 partidos de liga en que esté disponible. Si no: confianza −20.',
      'role.starter': 'Titular en la mitad de los próximos 10 partidos de liga en que esté disponible. Si no: confianza −20.',
      'role.rotation': 'Titular 1 de cada 4 en los próximos 10 partidos de liga. Si no: confianza −20.',
      'role.prospect': '10 partidos en las próximas 20 jornadas, o una cesión. Si no: confianza −20.',
      contract: 'Un contrato nuevo sobre la mesa en 8 jornadas. Si no: confianza −20.',
      keep: 'No se le vende antes de que cierre el mercado. Si le vendes, todo el vestuario lo verá.',
      sign: 'Un fichaje en esa posición antes de que cierre el mercado. Si no: confianza −20.',
    },
    signPos: '¿Qué posición?',
    giveBtn: 'Dar tu palabra', back: 'Atrás', done: 'Hecho',
    delta: (label: string, d: number) => `${label} ${d > 0 ? '+' : d < 0 ? '−' : '±'}${Math.abs(d)}`,
    withdrew: 'Retira su petición de traspaso.',
    reply: {
      'reassure.driven': 'Vale. Solo quiero jugar.', 'reassure.steady': 'Entendido, míster.', 'reassure.volatile': 'Eso significa mucho. De verdad.',
      'reassure.loyal': 'Sé que me cubres.', 'reassure.mercenary': 'Bonitas palabras.', 'reassure.leader': 'Bien. Se lo diré a los chicos.',
      'challenge.driven': 'Lo tendrás. Mírame.', 'challenge.steady': 'Recibido.', 'challenge.volatile': '¿Eso es lo que piensas de mí?',
      'challenge.loyal': 'No te fallaré.', 'challenge.mercenary': 'Ya veremos quién necesita a quién.', 'challenge.leader': 'Justo. Yo marcaré el nivel.',
      'promise.steady': 'Entonces trato hecho.', 'promise.driven': 'Te lo voy a recordar.', 'promise.mercenary': 'La próxima vez, por escrito.',
      'promise.cold': 'Ya he oído promesas antes.', 'reassure.heard': 'Eso dijiste la última vez.', 'challenge.cold': '¿Tú me dices eso?',
      'praise.volatile': 'Me dejo la vida por ti.', 'praise.steady': 'Gracias, míster. La semana que viene también.',
    },
  },
  no: {
    'dr.nothing': 'No hay nada que hablar. Sabe dónde está.', 'dr.pledged': 'Ya le diste tu palabra en algo.',
    'dr.window': 'Solo con el mercado abierto.', 'dr.role': 'Es demasiado mayor para ser promesa.', 'dr.long': 'Le quedan años de contrato.',
    'dr.group': 'Elige una posición.', 'dr.already': 'Ya lo lleva.', 'dr.noRequest': 'No ha pedido salir.',
    wait: 'Ya hablaste con él esta semana. Dale unos días.', gone: 'Ya no es nuestro.', trust: 'No se fía de ti lo bastante para firmar.',
    loaned: 'Está cedido.', terms: 'Esas condiciones no valen.', role: 'Es demasiado mayor para ser promesa.',
  },
  tag: { talk: 'Una charla', request: 'Quiere irse', promise: 'Tu palabra', armband: 'Brazalete', clause: 'Cláusula' },
  titles: {
    'ask.asked': (pn: string) => `${pn} quiere hablar`, 'ask.broken': (pn: string) => `${pn} quiere hablar de tu promesa`,
    'ask.minutes': (pn: string) => `${pn} quiere saber por qué no juega`, 'ask.role': (pn: string) => `${pn} quiere un rol mayor`,
    'ask.contract': (pn: string) => `${pn} quiere hablar de su futuro`, 'ask.unhappy': (pn: string) => `${pn} quiere hablar`,
    'ask.doubts': (pn: string) => `${pn} tiene dudas`, 'ask.request': (pn: string) => `${pn} quiere irse`,
    'ask.new': (pn: string) => `${pn} quiere hablar`, 'ask.form': (pn: string) => `${pn} quiere hablar`,
    request: (pn: string) => `${pn} ha pedido salir`,
    clause: (pn: string, fee: string, club: string) => `El ${club} paga la cláusula de ${pn}: ${fee}`,
    'due.role.star': (pn: string) => `Tu palabra a ${pn}: ser la estrella`, 'due.role.starter': (pn: string) => `Tu palabra a ${pn}: jugar de titular`,
    'due.role.rotation': (pn: string) => `Tu palabra a ${pn}: minutos de rotación`, 'due.contract': (pn: string) => `Tu palabra a ${pn}: un contrato nuevo`,
    'due.sign': (pn: string, g: string) => `Tu palabra a ${pn}: un ${g} nuevo`,
    'arm.none': () => 'Nadie lleva el brazalete', 'arm.lost': (pn: string) => `El vestuario ya no sigue a ${pn}`,
  },
  advice: {
    reassure: (pn: string, a: string) => `${pn} es ${a.toLowerCase()}. Pásale el brazo por el hombro; es lo que necesita ahora.`,
    challenge: (pn: string, a: string) => `${pn} es ${a.toLowerCase()}. Rétale. Responde a eso.`,
    'promise.role': () => 'Dale tu palabra sobre su rol. Podemos cumplirla y él sabe que va en serio.',
    'promise.contract': () => 'Prométele un contrato nuevo. Quiere saber que tiene futuro aquí.',
    'promise.sign': () => 'Prométele el fichaje. Quiere ver ambición.',
    'promise.keep': () => 'Dile que no está en venta.',
    'req.list': (pn: string) => `Deja ir a ${pn}. Un jugador que quiere irse juega como tal.`,
    'req.refuse': (_pn: string, n: string) => `Es nuestro número ${n}. Recházalo y deja que se enfríe.`,
    'req.promise': () => 'Dale un rol de verdad y quizá se quede. No lo digas si no lo vas a cumplir.',
    'clause.stay': (_pn: string, n: string) => `Confía en ti (${n}). Pídele que se quede; creo que lo hará.`,
    'clause.go': (_pn: string, n: string) => `La confianza está en ${n}. Se irá digamos lo que digamos. Acepta el dinero con elegancia.`,
    'due.start': (pn: string) => `Pon a ${pn} de titular el sábado. Casi no nos cuesta nada y cumples tu palabra.`,
    'due.cost': (pn: string, n: string) => `Poner a ${pn} de titular nos cuesta ${n} en ese puesto. Tu palabra, tu decisión.`,
    'due.none': () => 'No está para ser titular. Puede que tengamos que dejarlo pasar.',
    'due.contract': (_pn: string, n: string) => `Pon el contrato sobre la mesa: firmaría por ${n} al mes.`,
    'due.sign': (_pn: string, g: string) => `Aún le debemos un ${g}. El mercado se cierra.`,
    arm: (pn: string) => `${pn}. El vestuario ya le sigue.`,
    'arm.home': (pn: string, n: string) => `${pn}. ${n} años, de la casa, y el vestuario ya le sigue.`,
  },
  choices: {
    reassure: 'Tranquilizarle', challenge: 'Retarle', list: 'Declararle transferible', refuse: 'Rechazar', stay: 'Pedirle que se quede', go: 'Dejarle ir',
    start: (pn: string) => `Titular: ${pn}`, letgo: 'Dejarlo pasar', armband: (pn: string) => `Brazalete para ${pn}`, later: 'Ahora no',
    promise: (what: string) => `Prometer ${what}`,
  },
  fx: {
    morale: (s: string) => `Moral ${s}`, trust: (s: string) => `Confianza ${s}`, coh: (s: string) => `Cohesión ${s}`, shrug: 'Cambia poco',
    bind: 'Te lo reclamará', bids: 'Llegarán ofertas', stillWants: 'Sigue queriendo irse', withdraw: 'Retira la petición',
    likelyStays: (s: string) => `Confianza ${s}: escuchará`, likelyGoes: (s: string) => `Confianza ${s}: se va`,
    noChange: 'No cambia nada', onTrack: 'Cumples tu palabra', kept: 'Cumples tu palabra', keepWord: 'Prometiste no venderle',
  },
  news: {
    'dr.broken': (pn: string, what: string): Pair => [`${pn}, defraudado`, `El entrenador le prometió ${what}. No pasó, y el vestuario lo notó.`],
    'dr.request': (pn: string): Pair => [`${pn} pide salir`, 'Hay una petición de traspaso en la mesa del entrenador. Los clubes se habrán enterado.'],
    'dr.settled': (pn: string): Pair => [`${pn} se calma`, 'La petición de traspaso queda aparcada. Por ahora.'],
    'dr.withdrawn': (pn: string): Pair => [`${pn} retira su petición`, 'Una promesa del entrenador le hizo cambiar de idea.'],
    'dr.refused': (pn: string): Pair => ['Petición rechazada', `${pn} no se mueve, dice el club. El jugador no está contento.`],
    'dr.exit': (pn: string, club: string): Pair => [`${pn} se va`, `Ficha por el ${club}. El vestuario pierde una voz.`],
    'dr.leftFree': (pn: string): Pair => [`${pn} se va gratis`, 'Se le acabó el contrato y se marchó. Ni un euro para el club.'],
    'dr.returns': (pn: string, club: string, n: string, s: string): Pair => [`${pn} vuelve contra su exequipo`, `${club}, ${s}. Su nota: ${n}.`],
    'dr.clauseMet': (pn: string, club: string, n: string): Pair => [`El ${club} paga la cláusula de ${pn}`, `${n}, al contado. La cláusula hizo el resto.`],
    'dr.stays': (pn: string, club: string): Pair => [`${pn} rechaza al ${club}`, 'Pagaron su cláusula. Él quiere quedarse.'],
    'dr.core': (pn: string, _c: string, n: string): Pair => [`${pn} se gana el vestuario`, `${n} años y de la casa. Los veteranos ya le escuchan.`],
    'dr.leader': (pn: string, _c: string, n: string): Pair => [`${pn}, líder con ${n} años`, 'De la cantera al corazón del vestuario.'],
    'dr.armband': (pn: string): Pair => [`${pn}, nuevo capitán`, 'El entrenador le da el brazalete.'],
    'dr.armbandHome': (pn: string, _c: string, n: string): Pair => ['De la cantera al brazalete', `${pn}, ${n} años, capitán del club en el que creció.`],
  },
  msg: {
    'dr.kept': (pn: string, what: string): Pair => [`Promesa cumplida: ${pn}`, `Le prometiste ${what}. Lo ha notado.`],
    'dr.broken': (pn: string, what: string): Pair => [`Promesa rota: ${pn}`, `Le prometiste ${what}. Confianza −20, y quiere hablar.`],
    'dr.request': (pn: string): Pair => [`${pn} ha pedido salir`, 'Ya no te cree. Hazle transferible, recházalo o dale un motivo para quedarse.'],
    'dr.interest': (pn: string, club: string, fee: string): Pair => [`El ${club} puja por ${pn}`, `${fee}. Saben que está inquieto.`],
    'dr.clause': (pn: string, club: string, fee: string): Pair => [`El ${club} paga la cláusula de ${pn}`, `${fee}. Es vinculante, salvo que él quiera quedarse.`],
  },
  log: { 'dr.talk.reassure': (pn: string) => `Charla con ${pn} (le tranquilizó)`, 'dr.talk.challenge': (pn: string) => `Charla con ${pn} (le retó)` },
  whyHead: ['El vestuario nos llevó', 'El vestuario nos falló'],
  whyGood: (n: number, x: string) => `Cohesión ${n}: un equipo asentado vale ${x} por jugador en el campo.`,
  whyBad: (n: number, x: string) => `Cohesión ${n}: un equipo desordenado nos costó ${x} por jugador en el campo.`,
  ftCoh: 'Cohesión', ftCohQuote: (lv: string) => `Jugamos con ${lv} frente a un rival normal.`,
  player: {
    room: 'En el vestuario', release: 'Cláusula de rescisión', none: 'Ninguna', role: 'Rol', wantsOut: 'Quiere irse', refused: 'Petición rechazada', wantsWord: 'Quiere hablar',
    word: (what: string) => `Tu palabra: ${what}`, kept: (what: string) => `Promesa cumplida: ${what}`, broken: (what: string) => `Promesa rota: ${what}`,
    last: (why: string) => `último: ${why}`,
  },
  renew: { role: 'Rol en el nuevo contrato', release: 'Cláusula de rescisión', releaseOn: (v: string) => `${v}, un 10% menos de sueldo`, off: 'Sin cláusula', promiseNote: 'Un rol nuevo es una promesa que te reclamará.' },
  squad: { door: 'Vestuario', req: 'quiere irse', ask: 'quiere hablar', word: 'tu palabra' },
  today: { roomWhy: (coh: number) => `Cohesión ${coh}` },
  note: { talk: 'Dicho.', stays: (pn: string) => `${pn} se queda.`, clauseGo: (pn: string) => `${pn} se ha ido.` },
};
