// French interface. Names of clubs, players and leagues stay in their English form (the data has EN and AR names).
import type { MsgP, Strings } from './i18n';

const ord = (n: number) => (n === 1 ? '1er' : `${n}e`);

export const fr: Strings = {
  live: 'Présaison',
  lang: 'FR',
  tagline: ['Dirige le club.', 'Règne sur le banc.'],
  heroOver: 'Ta carrière',
  heroTitle: 'Prends le poste',
  heroBody: 'Choisis un club des cinq grands championnats européens ou des ligues arabes. Gagne la direction, les supporters et le vestiaire.',
  newCareer: 'Nouvelle carrière',
  newCareerSub: 'Choisis un pays, un championnat, un club',
  moreWays: 'Autres façons de jouer',
  continue: 'Continuer',
  continueSub: 'Aucune carrière sauvegardée',
  friends: 'Amis',
  friendsSub: 'Salons privés. Bientôt.',
  quick: 'Match rapide',
  quickSub: 'Un match. Rien ne compte.',
  foot: 'Jeu de fans non officiel. Les noms de clubs, de championnats et de joueurs sont fictifs ou modifiés. Aucun lien avec un club, un championnat ou un joueur.',
  tabs: ['Accueil', 'Effectif', 'Match', 'Championnat', 'Plus'],
  chooseCountry: 'Choisis un pays',
  mainLeagues: 'Les cinq grands',
  arabLeagues: 'Ligues arabes',
  main: 'Principal',
  leagues: (n: number) => (n === 1 ? '1 championnat' : `${n} championnats`),
  chooseLeague: 'Choisis un championnat',
  clubs: (n: number) => `${n} clubs`,
  tier: (n: number) => (n === 1 ? 'Première division' : `Division ${n}`),
  nextClub: 'Ensuite : choisis ton club',
  back: 'Retour',
  soon: 'Touche un championnat pour voir ses clubs.',
  chooseClub: 'Choisis ton club',
  pickClubHint: 'Les grands clubs veulent des titres. Les petits te laissent du temps.',
  takeJob: 'Prendre le poste',
  signContract: 'Signer le contrat',
  replaceWarn: 'Cela remplace ta carrière sauvegardée.',
  managerName: 'Ton nom',
  managerDefault: 'The Gaffer',
  strength: 'Niveau',
  budget: 'Budget',
  wageBill: 'Masse salariale',
  perMonth: '/mois',
  boardWants: 'La direction veut',
  squadSize: 'Effectif',
  objective: {
    title: 'Gagner le championnat',
    europe: 'Finir dans les cinq premiers',
    topHalf: 'Finir dans la première moitié',
    survive: 'Se maintenir',
    promotion: 'Monter',
    playoffs: 'Atteindre les barrages',
    midTable: 'Finir en milieu de tableau',
  },
  season: (y: number) => `Saison ${y}/${String(y + 1).slice(2)}`,
  welcome: (name: string) => `Bienvenue, ${name}.`,
  nextUp: 'Prochain match',
  nextUpBody: 'Ton prochain match.',
  keyPlayers: 'Joueurs clés',
  seeSquad: 'Voir l’effectif',
  squad: 'Effectif',
  all: 'Tous',
  groups: ['GB', 'DEF', 'MIL', 'ATT'],
  table: 'Championnat',
  powerRanking: 'Classement de présaison',
  powerHint: 'Aucun match joué. Classé selon le meilleur onze.',
  you: 'Toi',
  player: {
    position: 'Poste', age: 'Âge', nation: 'Nationalité', rating: 'Note', potential: 'Potentiel',
    value: 'Valeur', wage: 'Salaire', contract: 'Contrat jusqu’en', shirt: 'Numéro',
  },
  pos: { GK: 'Gardien', CB: 'Défenseur central', LB: 'Latéral gauche', RB: 'Latéral droit', CDM: 'Milieu défensif', CM: 'Milieu', CAM: 'Meneur de jeu', LW: 'Ailier gauche', RW: 'Ailier droit', ST: 'Attaquant' },
  close: 'Fermer',
  continueOn: (club: string) => club,
  badSave: 'Ta carrière sauvegardée n’a pas passé la vérification et n’a pas été chargée.',
  startOver: 'Recommencer',
  startOverSub: 'Supprimer cette carrière',
  startOverAsk: 'Supprimer ta carrière ?',
  startOverBody: 'Ton club, ton effectif et ta progression sont effacés. Impossible d’annuler.',
  delete: 'Supprimer',
  cancel: 'Annuler',
  soonTag: 'Bientôt',
  noCareer: 'Commence une carrière pour débloquer ceci.',
  matchday: (n: number) => `Journée ${n}`,
  match: 'Match',
  vs: 'vs',
  home: 'Domicile',
  away: 'Extérieur',
  yourXI: 'Ton onze',
  autoXI: 'Meilleur onze choisi pour toi (4-3-3). La tactique arrive plus tard.',
  watch: 'Jouer le match',
  quickResult: 'Résultat rapide',
  skip: 'Aller à la fin',
  done: 'Continuer',
  leagueOver: 'Ta saison de championnat est terminée.',
  finishSeason: 'Terminer la saison',
  seasonOver: 'Fin de saison',
  finished: (pos: string) => `Tu as fini ${pos}.`,
  ordinal: ord,
  met: 'Direction satisfaite : objectif atteint',
  missed: 'Direction mécontente : objectif manqué',
  champion: 'Champions',
  topScorer: 'Meilleur buteur',
  nextSeason: (y: number) => `Lancer ${y}/${String(y + 1).slice(2)}`,
  promotedTo: (l: string) => `Promus ! La saison prochaine : ${l}.`,
  relegatedTo: (l: string) => `Relégués. La saison prochaine : ${l}.`,
  stayIn: (l: string) => `La saison prochaine : ${l}.`,
  retiredN: (n: number) => `${n} joueurs ont pris leur retraite dans le monde ; les jeunes du centre de formation ont pris leur place.`,
  moves: 'Montées et descentes',
  up: 'Montent',
  down: 'Descendent',
  lastResult: 'Dernier résultat',
  position: 'Position',
  points: 'pts',
  tableTab: 'Classement',
  resultsTab: 'Résultats',
  scorersTab: 'Buteurs',
  cols: ['J', 'G', 'N', 'P', '±', 'Pts'],
  noGames: 'Aucun match joué.',
  goals: 'Buts',
  history: 'Historique',
  fullTime: 'Fin',
  halfTime: 'Mi-temps',
  ev: {
    kickoff: 'Coup d’envoi.',
    half: 'Mi-temps.',
    full: 'Fin du match.',
    goal: (p: string, c: string) => `BUT ! ${p} marque pour ${c}.`,
    miss: (p: string) => `${p} tire à côté.`,
    save: (p: string) => `Superbe arrêt de ${p}.`,
    yellow: (p: string) => `Carton jaune pour ${p}.`,
    red: (p: string) => `CARTON ROUGE ! ${p} est expulsé.`,
    injury: (p: string) => `${p} est blessé et ne peut pas continuer.`,
    assist: (p: string) => `Passe décisive : ${p}.`,
    sub: (off: string, on: string) => `Changement : ${on} remplace ${off}.`,
    how: { pen: '(sur penalty)', fk: '(sur coup franc)', corner: '(sur corner)' },
  },
  win: 'Victoire', draw: 'Nul', loss: 'Défaite',
  sorts: ['Poste', 'Note', 'Valeur', 'Salaire', 'Âge', 'Forme'],
  avgRating: 'Note moyenne',
  avgAge: 'Âge moyen',
  wageCap: 'Plafond salarial',
  market: 'Marché des transferts',
  marketSub: 'Achète des joueurs, signe des joueurs libres',
  freeAgents: 'Joueurs libres',
  affordable: 'Dans le budget',
  allLeagues: 'Tous les championnats',
  showingTop: (n: number) => `Les ${n} premiers.`,
  free: 'Libre',
  askPrice: 'Prix demandé',
  makeOffer: 'Faire une offre',
  fee: 'Indemnité',
  years: 'Contrat',
  yearsN: (n: number) => (n === 1 ? '1 saison' : `${n} saisons`),
  role: 'Rôle dans l’effectif',
  roles: { star: 'Star', regular: 'Titulaire', rotation: 'Rotation', prospect: 'Espoir' },
  send: 'Envoyer l’offre',
  bidReason: {
    budget: 'Pas assez de budget pour cette indemnité.',
    wageCap: 'Ce salaire dépasse ton plafond salarial.',
    squadFull: 'Ton effectif est complet (32 joueurs).',
    fee: (m: string) => `Ils veulent au moins ${m}.`,
    wage: (m: string) => `Il veut ${m} par mois.`,
    ambition: 'Il ne rejoindra pas un club de ton niveau.',
    role: 'Seuls les joueurs de 21 ans ou moins peuvent être des espoirs.',
    injured: 'Il est blessé.',
  },
  signed: (n: string) => `${n} a signé !`,
  listForSale: 'Mettre en vente',
  unlist: 'Retirer de la vente',
  listed: 'En vente',
  renewTitle: 'Prolonger le contrat',
  extraYears: 'Saisons en plus',
  renewed: (n: string) => `${n} a prolongé.`,
  renewReason: {
    wage: (m: string) => `Il veut ${m} par mois.`,
    years: (n: number) => `À son âge : ${n === 1 ? '1 saison' : `${n} saisons`} au plus.`,
    wageCap: 'Ce salaire dépasse ton plafond salarial.',
    unhappy: 'Il est mécontent et refuse de parler.',
  },
  expiringN: (n: number) => (n === 1 ? '1 contrat se termine cette saison' : `${n} contrats se terminent cette saison`),
  expiringHint: 'Prolonge-les ou ils partiront libres.',
  offersN: (n: number) => (n === 1 ? '1 offre pour tes joueurs' : `${n} offres pour tes joueurs`),
  offers: 'Offres',
  accept: 'Accepter',
  reject: 'Refuser',
  counter: 'Demander +20 %',
  sold: (n: string, c: string) => `${n} vendu à ${c}.`,
  counterOk: 'Ils ont accepté le nouveau prix.',
  counterNo: 'Ils se sont retirés.',
  sellReason: { squadMin: 'Il te faut au moins 16 joueurs.', buyerBudget: 'Ils n’en ont plus les moyens.' },
  thinSquad: (n: number) => `Seulement ${n} joueurs. Recrute pour couvrir blessures et suspensions.`,
  injuredN: (n: number) => `${n} blessés`,
  bannedN: (n: number) => `${n} suspendus`,
  statusInj: (n: number) => `Blessé · ${n} j.`,
  statusBan: (n: number) => `Suspendu · ${n} j.`,
  fitness: 'Forme',
  morale: 'Moral',
  attrs: ['Vitesse', 'Tir', 'Passe', 'Dribble', 'Défense', 'Physique', 'Gardien'],
  seasonStats: 'Cette saison',
  statCols: ['MJ', 'Buts', 'Passes D', 'Jaunes', 'Rouges'],
  assistsTab: 'Passes D',
  leftClub: 'Contrats terminés',
  academyUp: 'Jeunes promus',
  deals: 'Tes transferts',
  dealKind: { in: 'Acheté', out: 'Vendu', free: 'Libre', released: 'Libéré' },
  exportSave: 'Exporter la sauvegarde',
  exportSub: 'Télécharge un fichier .gaffer ou copie-le',
  download: 'Télécharger le fichier',
  copy: 'Copier',
  copied: 'Copié.',
  importSave: 'Importer une sauvegarde',
  importSub: 'Charge un fichier .gaffer ou colle-le',
  pasteHere: 'Colle une sauvegarde ici',
  load: 'Charger',
  chooseFile: 'Choisir un fichier',
  importBad: {
    format: 'Ce n’est pas une sauvegarde The Gaffer.',
    checksum: 'Cette sauvegarde a été modifiée ou abîmée, elle a été refusée.',
    world: 'Cette sauvegarde n’a pas passé la vérification du monde.',
    none: 'Rien à charger.',
  },
  importOk: 'Sauvegarde chargée.',
  kit: 'Tenue',
  shirt: 'Maillot',
  tactics: 'Tactique',
  formation: 'Système',
  mentality: 'Mentalité',
  mentalities: ['Bus garé', 'Défensive', 'Équilibrée', 'Offensive', 'Tout pour l’attaque'],
  pressing: 'Pressing',
  pressings: ['Bas', 'Moyen', 'Haut'],
  passing: 'Passes',
  passings: ['Courtes', 'Mixtes', 'Directes'],
  bestXI: 'Meilleur onze',
  saveTactics: 'Enregistrer la tactique',
  tacticsSaved: 'Tactique enregistrée.',
  pickFor: (pos: string) => `Choisis un joueur pour ${pos}`,
  outOfPos: 'Hors de son poste',
  setPiecesT: 'Coups de pied arrêtés',
  captain: 'Capitaine',
  penaltiesT: 'Penaltys',
  freeKicksT: 'Coups francs',
  cornersT: 'Corners',
  prediction: 'Pronostic',
  replacedN: (names: string) => `Remplacés automatiquement (indisponibles) : ${names}.`,
  unsaved: 'Modifications non enregistrées',
  pause: 'Pause',
  resume: 'Reprendre',
  changes: 'Changements',
  subsLeft: (n: number) => (n === 1 ? '1 changement restant' : `${n} changements restants`),
  makeSub: 'Faire le changement',
  subOut: 'Sort',
  subIn: 'Entre',
  feed: 'Commentaires',
  statsT: 'Stats',
  lineups: 'Compositions',
  statNames: ['Possession', 'Tirs', 'Cadrés', 'Corners', 'Fautes', 'Cartons jaunes', 'Cartons rouges'],
  halfTimeTalk: 'Causerie de la mi-temps',
  talks: ['Ne rien dire', 'Les motiver', 'Les calmer', 'Rester concentrés'],
  talkHints: ['', 'Plus d’attaque, un peu plus ouverts derrière.', 'Moins de fautes et de cartons.', 'Plus solides derrière, un peu moins devant.'],
  secondHalf: 'Seconde période',
  resumeMatch: 'Reprendre le match',
  bench: 'Banc',
  coachAge: 'Ton âge',
  ageRule: 'Entre 20 et 80 ans.',
  coachNation: 'Nationalité',
  searchClub: 'Chercher un club',
  saveFailed: 'Sauvegarde impossible : le stockage du navigateur est plein ou bloqué. Exporte ta sauvegarde depuis Plus.',
  inbox: 'Messages',
  markAllRead: 'Tout marquer comme lu',
  clearAll: 'Tout effacer',
  noMsgs: 'Aucun message.',
  inboxKinds: { all: 'Tous', board: 'Direction', fans: 'Supporters', club: 'Club', contract: 'Contrats', offer: 'Offres', cup: 'Coupes', coach: 'Entraîneur', job: 'Postes', scout: 'Recruteurs' },
  msg: {
    welcome: (p: MsgP) => [`Bienvenue à ${p.club}`, 'La direction, les joueurs et les supporters sont prêts. Bonne chance, coach.'],
    bigWin: (p: MsgP) => ['Supporters : quelle victoire !', `${p.s} contre ${p.club}. Les tribunes chantent ton nom.`],
    badLoss: (p: MsgP) => ['Direction : pas assez bien', `${p.s} contre ${p.club}. Nous attendons une réaction.`],
    giantKill: (p: MsgP) => ['Tombeurs de géants !', `Battre ${p.club} fait les gros titres.`],
    boardWorried: () => ['Direction : nous sommes inquiets', 'Les résultats doivent vite s’améliorer.'],
    boardAngry: () => ['Direction : dernier avertissement', 'Encore une mauvaise série et tu es dehors.'],
    boardHappy: () => ['Direction : excellent travail', 'La direction est totalement derrière toi.'],
    fansAngry: () => ['Les supporters sont en colère', 'Des banderoles réclament du changement.'],
    fansLove: () => ['Les supporters t’adorent', 'Ton nom est sur tous les maillots de la ville.'],
    sacked: (p: MsgP) => ['Tu es limogé', `${p.club} a mis fin à ton contrat. Choisis ton prochain poste.`],
    seasonGood: (p: MsgP) => ['Direction : bilan de la saison', `Fini ${ord(p.n)}. Objectif atteint. Bravo.`],
    seasonBad: (p: MsgP) => ['Direction : bilan de la saison', `Fini ${ord(p.n)}. Objectif manqué.`],
    contractsEnding: (p: MsgP) => ['Contrats en fin', `${p.n} contrats se terminent cette saison. Prolonge-les ou ils partiront libres.`],
    offerIn: (p: MsgP) => ['Nouvelle offre', `${p.club} a fait une offre pour ${p.player}.`],
    cupThrough: (p: MsgP) => [`${p.s} : qualifiés !`, `Nous avons éliminé ${p.club}.`],
    cupOut: (p: MsgP) => [`${p.s} : éliminés`, `${p.club} nous a éliminés.`],
    cupWon: (p: MsgP) => [`${p.s} : CHAMPIONS !`, `Nous avons battu ${p.club} en finale.`],
    groupThrough: (p: MsgP) => [`${p.s} : qualifiés pour la phase finale`, `Nous avons fini ${p.n === 1 ? 'premiers' : 'deuxièmes'} du groupe.`],
    groupOut: (p: MsgP) => [`${p.s} : éliminés en phase de groupes`, `Nous avons fini ${p.n === 3 ? 'troisièmes' : 'derniers'} du groupe.`],
    milestone: (p: MsgP) => ['Palier atteint', p.s],
    licence: (p: MsgP) => ['Licence obtenue', `Tu as maintenant la licence ${p.s}.`],
    course: (p: MsgP) => ['Formation terminée', p.s],
    jobOffer: (p: MsgP) => ['Offre de poste', `${p.club} te veut comme entraîneur.`],
  } as Record<string, (p: MsgP) => string[]>,
  career: 'Ta carrière',
  careerSub: 'Niveau, licence, formations, paliers',
  level: 'Niveau',
  reputation: 'Réputation',
  licence: 'Licence',
  wallet: 'Ton argent',
  record: 'Bilan',
  trophies: 'Trophées',
  noTrophies: 'Pas encore de trophée.',
  trophyKind: { league: 'Championnat', cup: 'Coupe', continental: 'Continental', promotion: 'Montée' },
  nextLicence: (l: string) => `Suivante : licence ${l}`,
  licenceCap: (n: number) => `Clubs jusqu’à réputation ${n}`,
  examNeeds: {
    level: (n: number) => `Niveau ${n} requis`, matches: (n: number) => `${n} matchs requis`, fee: (m: string) => `Frais d’examen ${m}`,
    wait: (n: number) => `Prochain examen dans ${n} journées`, trophy: () => 'Un trophée requis', max: () => 'Licence maximale atteinte',
  },
  takeExam: 'Passer l’examen',
  examTitle: (l: string) => `Examen de licence ${l}`,
  examPassed: 'Réussi ! Nouvelle licence.',
  examFailed: 'Pas cette fois. Révise et réessaie.',
  submit: 'Valider',
  coursesT: 'Formations',
  courseNames: { conditioning: 'Préparation physique moderne', psychology: 'Psychologie du sport', gegenpress: 'Atelier pressing', fellowship: 'Bourse d’académie européenne' } as Record<string, string>,
  courseEffects: { conditioning: 'Ton équipe se fatigue 15 % moins vite en match.', psychology: 'Les défaites pèsent moins sur le moral ; le moral se stabilise plus haut.', gegenpress: 'Le pressing haut fait plus mal.', fellowship: 'Tes jeunes progressent plus vite.' } as Record<string, string>,
  takeCourse: (m: string) => `La suivre · ${m}`,
  doneTag: 'Fait',
  notEnough: 'Pas assez d’argent.',
  milestonesT: 'Paliers',
  msCats: { short: 'Court terme', mid: 'Moyen terme', long: 'Long terme' },
  msNames: {
    firstWin: 'Première victoire', streak3: '3 victoires de suite', streak5: '5 victoires de suite', unbeaten10: '10 matchs sans défaite', giantSlayer: 'Tombeur de géants',
    cupGlory: 'Gloire en coupe', promotion: 'On monte', leagueTitle: 'Champions', topFlightTitle: 'Champions de première division', continental: 'Rois du continent',
    matches100: '100 matchs', winRate55: '55 % de victoires après 50 matchs', twoClubs: 'Titres avec deux clubs', licenceA: 'Licence A', licencePro: 'Licence PRO', worldNo1: 'Numéro un mondial',
  } as Record<string, string>,
  jobsT: 'Offres de poste',
  takeJobQ: (c: string) => `Partir pour ${c} ?`,
  takeJobBody: 'Ton nouveau club repart d’où il en est : son effectif, son calendrier, sa direction.',
  sackedTitle: 'Tu es limogé',
  sackedBody: 'Choisis ton prochain club pour continuer.',
  boardFans: 'Direction et supporters',
  confidence: 'Direction',
  fansT: 'Supporters',
  objectivesT: 'Objectifs',
  cupAim: { win: 'Gagner la coupe', semi: 'Atteindre les demi-finales de coupe', round2: 'Passer un tour de coupe' },
  youthAim: (n: number, have: number) => `Faire jouer ${n} matchs aux moins de 21 ans (${have} pour l’instant)`,
  cupsTab: 'Coupes',
  roundName: (k: number, total: number) => (k < 0 ? 'Phase de groupes' : ['Finale', 'Demi-finales', 'Quarts de finale', 'Huitièmes de finale', 'Seizièmes de finale'][total - k - 1] ?? `Tour de ${2 ** (total - k)}`),
  pens: (a: number, b: number) => `${a}–${b} tab`,
  bye: 'exempt',
  shootout: 'Séance de tirs au but',
  kick: (p: string, ok: boolean) => `${p} ${ok ? 'marque' : 'rate'}`,
  cupOut: (r: string) => `Éliminé en ${r.toLowerCase()}`,
  cupWonT: 'Vainqueur',
  groupDay: (n: number) => `Phase de groupes · match ${n} sur 6`,
  groupT: (g: number) => `Groupe ${'ABCDEFGH'[g]}`,
  groupStage: 'Phase de groupes',
  knockouts: 'Phase finale',
  editName: 'Modifier le nom',
  nameEn: 'Nom en anglais',
  nameAr: 'Nom en arabe',
  save: 'Enregistrer',
  lockedBy: (l: string) => `Licence ${l} requise`,
  clubT: 'Club',
  topPlayers: 'Meilleurs joueurs',
  acceptJobShort: 'Offre',
  clubScreen: 'Club',
  clubSub: 'Argent, billetterie, sponsors, installations, staff',
  trainingT: 'Entraînement',
  trainingSub: 'Charge, axe de travail, points de progression',
  hospitalT: 'Infirmerie',
  hospitalSub: (n: number) => (n ? `${n} blessés` : 'Aucun blessé'),
  academyT: 'Centre de formation',
  academySub: (n: number) => `${n} espoirs`,
  finTabs: ['Argent', 'Billetterie', 'Sponsors', 'Installations', 'Staff'],
  ledgerKeys: {
    tickets: 'Billetterie', tv: 'Droits TV', sponsors: 'Sponsors', prizes: 'Primes de compétition', sales: 'Ventes de jeunes', donations: 'Dons', bonusSponsor: 'Primes des sponsors',
    milestones: 'Récompenses de paliers', transfersOut: 'Joueurs vendus', transfersIn: 'Joueurs achetés', wages: 'Salaires des joueurs', staff: 'Salaires du staff',
    upkeep: 'Entretien', facilities: 'Travaux', bonuses: 'Primes', medical: 'Médical', scouting: 'Recrutement', wageCap: 'Plafond salarial',
  } as Record<string, string>,
  perMonthT: 'Par mois',
  thisSeason: 'Cette saison',
  lastSeason: 'Saison dernière',
  net: 'Solde',
  inTheRed: 'Le club est dans le rouge. La direction perd patience chaque semaine.',
  capacity: 'Capacité',
  ticketPrice: 'Prix du billet',
  expected: 'Affluence prévue',
  revenue: 'Recette par match à domicile',
  lastGate: (a: number, m: string) => `Dernier match à domicile : ${a} spectateurs, ${m}`,
  setPrice: 'Fixer le prix',
  usual: 'Prix habituel ici',
  slotNames: { shirt: 'Maillot', kit: 'Équipementier', stadium: 'Nom du stade', sleeve: 'Manche', commercial: 'Partenaire commercial' } as Record<string, string>,
  monthsLeft: (n: number) => `${n} mois restants`,
  months: (n: number) => `${n} mois`,
  bonusLeague: 'Prime titre de champion',
  bonusCup: 'Prime coupe',
  sign: 'Signer',
  askMore: 'Demander +10 %',
  extend: 'Prolonger de 12 mois',
  endDeal: 'Rompre le contrat',
  endDealCost: (m: string) => `Rompre plus tôt coûte ${m}`,
  haggleOk: 'Ils acceptent 10 % de plus.',
  haggleNo: 'Ils se sont retirés.',
  emptySlots: (n: number) => `${n} emplacements de sponsor libres`,
  emptySlotsHint: 'Des offres t’attendent dans Club › Sponsors.',
  facilityNames: { stadium: 'Stade', medical: 'Centre médical', training: 'Centre d’entraînement', academy: 'Centre de formation', scouting: 'Réseau de recruteurs' } as Record<string, string>,
  facilityEffects: { stadium: '+15 % de places par niveau', medical: 'Blessures plus courtes, soins moins chers', training: 'Les joueurs progressent plus vite', academy: 'De meilleurs espoirs', scouting: 'Plus d’espoirs par détection' } as Record<string, string>,
  upgrade: (m: string) => `Améliorer · ${m}`,
  maxLevel: 'Niveau max',
  upkeepT: 'Entretien',
  staffNames: { assistant: 'Entraîneur adjoint', fitness: 'Préparateur physique', doctor: 'Médecin du club', psychologist: 'Psychologue', scout: 'Chef recruteur' } as Record<string, string>,
  staffEffects: { assistant: 'Niveau en match et à l’entraînement', fitness: 'Moins de fatigue, moins de pépins à l’entraînement', doctor: 'Blessures plus courtes, soins moins chers', psychologist: 'Moral plus haut et plus stable', scout: 'Un espoir de plus s’il est bon' } as Record<string, string>,
  quality: 'Qualité',
  hire: 'Engager',
  candidates: 'Candidats',
  staffTotal: (m: string) => `Salaires du staff : ${m} par mois`,
  bonusT: 'Primes',
  teamBonus: 'Prime d’équipe',
  playerBonus: 'Un joueur',
  perPlayer: 'Par joueur',
  fromClub: 'Du club',
  fromWallet: 'De ton argent',
  pay: 'Payer',
  bonusPaid: 'Prime versée. Le moral monte.',
  donateT: 'Faire un don au club',
  donateHint: 'De ton propre argent. La direction et les supporters le remarquent, d’autant plus que le don est gros.',
  donate: 'Donner',
  donated: 'Merci, coach.',
  wageCapT: 'Plafond salarial',
  wageCapHint: 'Chaque +1 par mois coûte 12 sur le budget (et inversement).',
  raise: 'Augmenter',
  lower: 'Baisser',
  loadT: 'Charge d’entraînement',
  loads: ['Récupération', 'Normale', 'Intense'],
  loadHints: ['Les joueurs récupèrent plus, progressent lentement.', 'Forme et progression normales.', 'Progression plus rapide, moins de forme, un petit risque de blessure.'],
  focusT: 'Axe individuel',
  focusNone: 'Général',
  reportT: 'La semaine dernière',
  reportNone: 'Personne n’a progressé cette semaine.',
  improvedN: (n: number) => `${n} joueurs ont progressé (+1)`,
  hurtIn: (p: string) => `${p} s’est fait une petite blessure à l’entraînement.`,
  ceiling: 'À son plafond : l’entraînement le garde affûté mais il ne progressera plus.',
  devT: 'Points de progression',
  devHint: 'Gagnés avec les victoires, les trophées et les objectifs.',
  devUses: { rating: '+1 de note', potential: '+2 de potentiel', fitness: '+15 de forme', morale: 'Causerie : +10 de moral pour tous' } as Record<string, string>,
  devWhy: { points: 'Pas assez de points.', ceiling: 'Il est à son plafond.', age: 'Seulement pour les joueurs de 26 ans ou moins.', full: 'Il est déjà en pleine forme.' } as Record<string, string>,
  choosePlayer: 'Choisis un joueur',
  use: 'Utiliser',
  treatments: { rehab: 'Rééducation (−1 journée)', specialist: 'Spécialiste (−2 journées)', instant: 'Guérison immédiate' } as Record<string, string>,
  noInjuries: 'Personne n’est blessé.',
  treated: 'Soins terminés.',
  scoutExam: (m: string) => `Détection · ${m}`,
  scoutFound: (n: number) => `${n} espoirs trouvés.`,
  academyFull: 'Le centre de formation est plein (8).',
  promoteT: 'Promouvoir',
  releaseT: 'Libérer',
  sellRightsT: (m: string) => `Vendre les droits · ${m}`,
  promoted: 'Promu en équipe première.',
  noProspects: 'Pas encore d’espoir. Lance une détection.',
  nicknameT: 'Surnom',
  financeAim: 'Finir la saison à l’équilibre',
  playerSavings: 'Primes reçues',
  philosophyT: 'Philosophie',
  philosophies: { balanced: 'Équilibrée', possession: 'Possession', counter: 'Contre-attaque', gegenpress: 'Gegenpress', bus: 'Bus garé', wings: 'Jeu sur les ailes', direct: 'Jeu direct' } as Record<string, string>,
  philosophyHints: {
    balanced: 'Ni point fort ni point faible.', possession: 'Garder le ballon ; bat le bus garé et le jeu direct.', counter: 'Frapper en contre ; idéal en outsider. Bat la possession et le gegenpress.',
    gegenpress: 'Récupérer haut ; fatigant. Bat la possession et le jeu sur les ailes.', bus: 'Défendre bas : moins de buts des deux côtés. Bat les ailes et la contre-attaque.',
    wings: 'Il faut des ailiers rapides. Bat le jeu direct et le bus garé.', direct: 'Il faut un attaquant costaud ou rapide. Bat le gegenpress et la contre-attaque.',
  } as Record<string, string>,
  mastery: 'Maîtrise',
  rolesT: 'Rôles',
  fullbackT: 'Latéraux',
  fullbacks: ['Classiques', 'Débordants', 'Rentrants'],
  strikerT: 'Attaquant',
  strikers: ['Renard', 'Pivot', 'Faux 9', 'Presseur'],
  trapT: 'Piège de pressing',
  traps: ['Aucun', 'Côtés', 'Axe', 'Demi-espaces'],
  adviceT: 'Conseils de l’adjoint',
  tips: {
    scoutFirst: () => 'Observe-les d’abord pour voir comment ils jouent.',
    mismatch: (a: string, b: string) => `Leur ${a.toLowerCase()} bat notre plan. Essaie ${b.toLowerCase()}.`,
    edge: (a: string) => `Notre philosophie bat leur ${a.toLowerCase()}. Garde-la.`,
    lowMastery: (n: number) => `L’effectif ne maîtrise cette philosophie qu’à ${n} %. Elle rapporte plus avec les matchs.`,
    tired: (n: number) => `${n} titulaires sont fatigués. Fais tourner ou baisse le pressing.`,
    outOfPos: (n: number) => `${n} joueurs hors de leur poste.`,
    underdog: () => 'Nous sommes outsiders : une mentalité plus défensive ou la contre-attaque peut aider.',
    trap: (s: string) => `Tends-leur un piège de pressing : ${s.toLowerCase()}.`,
  },
  scoutT: 'Rapport d’observation',
  scoutBtn: (m: string) => `Observer l’adversaire · ${m}`,
  predictedShape: 'Système attendu',
  keyThreats: 'Dangers',
  weakSpots: 'Points faibles',
  weakWhy: { slow: 'lent', tired: 'fatigué', weak: 'défenseur le plus faible' } as Record<string, string>,
  counterPlan: 'Plan de riposte',
  applyPlan: 'Appliquer le plan',
  planApplied: 'Plan appliqué.',
  accuracyT: (n: number) => `Fiabilité du recruteur ${n} %`,
  pitchT: 'Terrain',
  speed: 'Vitesse',
  rankingsT: 'Classement mondial',
  rankingsSub: (n: number) => `Tu es n° ${n} mondial`,
  coachesT: 'Entraîneurs',
  clubsT: 'Clubs',
  regions: { world: 'Monde', country: 'Ton pays', europe: 'Europe', africa: 'Afrique', asia: 'Asie et Golfe' } as Record<string, string>,
  pointsT: 'Points',
  newsT: 'Journal',
  newsSub: 'Résultats, transferts, entraîneurs, jeunes, records',
  newsCats: { all: 'Tout', results: 'Résultats', transfers: 'Transferts', managers: 'Entraîneurs', youth: 'Jeunes', records: 'Records', crisis: 'Crises' } as Record<string, string>,
  noNews: 'Pas encore de nouvelles.',
  news: {
    thrash: (a: string, b: string, s: string) => [`${a} écrase ${b} ${s}`, `Une démonstration. ${b} n’a rien pu faire.`],
    newLeader: (a: string) => [`${a} prend la tête`, 'Un nouveau leader en haut du classement.'],
    goals: (p: string, a: string, n: string) => [`${p} atteint ${n} buts en championnat`, `Le buteur de ${a} ne s’arrête plus.`],
    crisis: (a: string) => [`Crise à ${a}`, 'Cinq défaites de suite. La pression monte.'],
    debut: (p: string, a: string) => [`Premiers pas pour ${p}`, `Un jeune du centre joue son premier match de championnat avec ${a}.`],
    promoted: (p: string, a: string) => [`${p} rejoint l’équipe première`, `${a} promeut un talent du centre de formation.`],
    cupFinal: (a: string, b: string, s: string) => [`${a} remporte la ${s}`, `Victoire contre ${b} en finale.`],
    rumour: (p: string, a: string, b: string, n: string) => [`${a} veut ${p}`, `Le joueur de ${b} est sur sa liste. Chances : ${n} %.`],
    aiTransfer: (p: string, a: string, b: string, s: string) => [`${p} file à ${b}`, `${a} accepte ${s}.`],
    userSign: (p: string, a: string, b: string, s: string) => [`${p} signe à ${a}`, `L’accord avec ${b} est conclu : ${s}.`],
    userSell: (p: string, a: string, b: string, s: string) => [`${p} part à ${a}`, `${b} encaisse ${s}.`],
    appointed: (a: string, s: string) => [`${s} prend les rênes de ${a}`, 'Nouvel entraîneur, nouveau départ.'],
    sacked: (a: string, s: string) => [`${a} limoge ${s}`, 'La direction a perdu patience.'],
  } as Record<string, (...x: string[]) => string[]>,
  rumoursT: 'Rumeurs',
  hijack: 'Doubler',
  chance: (n: number) => `${n} % de chances`,
  searchT: 'Chercher',
  more: 'Plus',
  followSemba: 'Semba Games',
  followSembaSub: 'Nos jeux, nos news et nos mises à jour',
  settings: 'Réglages',
  coachCardT: 'Carte d’entraîneur',
  ageT: (n: number) => `${n} ans`,
  trophiesT: 'Trophées',
  worldRankT: 'Rang mondial',
  addPhoto: 'Ajouter une photo',
  changePhoto: 'Changer la photo',
  removePhoto: 'Retirer la photo',
  photoTooBig: 'La photo est sur la carte, mais le téléphone n’avait pas la place de la garder',
  photoBad: 'Ce fichier n’est pas une photo lisible',
  shareT: 'Partager',
  downloadPng: 'Télécharger le PNG',
  savedAs: (f: string) => `Enregistré sous ${f}`,
  shareReport: 'Partager le résumé',
  editorT: 'Éditeur du monde',
  editorSub: 'Modifie n’importe quel club ou joueur. Rien n’est enregistré tant que le monde ne passe pas la vérification.',
  editorMoreSub: 'Clubs, joueurs, fichiers du monde',
  worldVersion: (n: number) => (n ? `Monde v${n}` : 'Monde d’origine'),
  leagueT: 'Championnat',
  shortNameT: 'Nom court',
  colorsT: 'Couleurs',
  addPlayer: 'Ajouter un joueur',
  editPlayer: 'Modifier le joueur',
  moveToClub: 'Club',
  newPlayer: { en: 'New Player', ar: 'لعيب جديد' },
  discard: 'Annuler',
  saveChanges: 'Enregistrer',
  worldSaved: (n: number) => `Monde v${n} enregistré`,
  worldIssues: (n: number) => (n === 1 ? '1 problème à corriger avant d’enregistrer' : `${n} problèmes à corriger avant d’enregistrer`),
  editorMySquad: 'Ton club doit avoir au moins 11 joueurs',
  worldFile: 'Fichier du monde',
  exportWorld: 'Exporter le monde',
  exportWorldSub: 'Un fichier .json à modifier ou partager',
  importWorld: 'Importer un monde',
  importWorldSub: 'Mêmes championnats et clubs ; les joueurs peuvent changer',
  importWorldBad: { format: 'Ce n’est pas un fichier de monde The Gaffer', mismatch: 'Ce monde a d’autres clubs ou championnats', invalid: 'Ce monde n’a pas passé la vérification' } as Record<string, string>,
  goalWord: 'BUT !',
  issueShirt: (p: string, n: number, c: string) => `${p} : le numéro ${n} est déjà pris à ${c}`,
  issueFew: (c: string, n: number) => `${c} n’a que ${n} joueurs (il en faut 11)`,
  quickPick: (s: string) => `Choisis l’équipe (${s.toLowerCase()}) dans n’importe quel championnat.`,
  kickOffT: 'Coup d’envoi',
  coachNation2: 'Seconde nationalité',
  noneT: 'Aucune',
  editorTabs: ['Clubs', 'Championnats', 'Pays'],
  leaguesHint: 'Renomme un championnat, ou échange des clubs entre championnats du même pays à partir de la saison prochaine.',
  editLeague: 'Modifier le championnat',
  editCountry: 'Modifier le pays',
  swapT: 'Échanger des clubs entre championnats',
  swapHint: 'Appliqué à la fin de la saison, après les montées et descentes.',
  swapBtn: 'Échanger la saison prochaine',
  queuedSwaps: 'Échanges de la saison prochaine',
  swapWhen: 'À la fin de cette saison',
  removeT: 'Retirer',
  issueName: (id: string) => `${id} : un nom est vide`,
  cameraT: 'Caméra du terrain',
  radarT: 'Radar de la composition',
  languageT: 'Langue',
  matchPrefs: 'Match',
  defaultSpeed: 'Vitesse du match',
  openOn: 'Le match en direct s’ouvre sur',
  balanceT: 'Réalisme',
  balanceSub: 'Enregistré avec cette carrière. Modifiable à tout moment.',
  balanceRows: { income: 'Revenus du club', wages: 'Salaires des joueurs', prices: 'Prix des transferts', injuries: 'Blessures', difficulty: 'Adversaires', patience: 'La direction' } as Record<string, string>,
  injuryLv: ['Aucune', 'Moins', 'Normal', 'Plus'],
  difficultyLv: ['Plus faibles', 'Normal', 'Plus forts'],
  patienceLv: ['Patiente', 'Normal', 'Exigeante'],
  resetBalance: 'Revenir à la normale',
  balanceSaved: 'Réalisme enregistré',
  aboutT: 'À propos',
  versionT: (v: string) => `Version ${v}`,
  madeBy: 'Fait par Semba Games au Caire.',
  howToSub: 'L’essentiel en deux minutes',
  howToBody: [
    ['Ton job', 'Choisis un club et signe le contrat. La direction fixe des objectifs en championnat et en coupe. Atteins-les et ta réputation grimpe ; rate-les et tu peux être limogé.'],
    ['Journées', 'Touche Jouer le match pour le suivre en direct sur le terrain, ou prends le résultat rapide. Les jours de coupe, le match de coupe passe d’abord. Après chaque journée vient une semaine d’entraînement.'],
    ['Tactique', 'Choisis le système, le onze, la mentalité, le pressing et les passes. Les philosophies se battent comme pierre-feuille-ciseaux, et ta maîtrise de chacune grandit à chaque match. Observe l’adversaire avant les gros matchs.'],
    ['Pendant le match', 'Mets pause quand tu veux pour faire des changements (cinq) ou changer de plan. Fais une causerie à la mi-temps. 1X, 2X et 4X changent la vitesse.'],
    ['L’effectif', 'Surveille la forme, le moral et les blessures. Entraîne fort ou fais récupérer, donne un axe à chaque joueur et envoie les blessés à l’infirmerie.'],
    ['Transferts', 'Chaque offre reçoit une réponse claire avec la raison. Prolonge les contrats avant la fin. Les autres clubs chassent aussi : signe-le d’abord pour doubler une rumeur.'],
    ['Argent', 'Billetterie, droits TV et sponsors rentrent ; salaires, staff et entretien sortent. Améliore les installations, engage du staff et finis la saison à l’équilibre.'],
    ['Coupes', 'La coupe nationale est à élimination directe dès le début. Les coupes continentales commencent par des groupes de quatre : les deux premiers vont en phase finale.'],
    ['Ta carrière', 'Gagne de l’expérience et des licences, suis des formations, atteins des paliers et des trophées, et grimpe au classement mondial. De plus grands clubs appelleront.'],
    ['Sauvegarde', 'La carrière s’enregistre seule après chaque match et est vérifiée au chargement. Exporte une sauvegarde depuis Plus pour garder une copie.'],
  ] as [string, string][],
  privacySub: 'Tes données restent sur ton téléphone',
  privacyBody: [
    ['Ce que nous gardons', 'Ta carrière, tes réglages et ta photo d’entraîneur sont enregistrés seulement sur cet appareil, dans le stockage de l’appli. Rien n’est envoyé ni à nous ni à personne.'],
    ['Pas de compte, pas de pistage', 'The Gaffer n’a ni connexion utilisateur, ni pub, ni statistiques, ni traceurs. Le jeu principal reste sur ton appareil ; l’app Android contacte seulement Semba Games pour vérifier les mises à jour, et les futures fonctions en ligne seront clairement indiquées.'],
    ['Fichiers de sauvegarde', 'Une sauvegarde exportée va où tu veux. L’import lit seulement le fichier que tu choisis.'],
    ['Photos', 'La photo de ta carte d’entraîneur reste sur cet appareil et sert seulement à dessiner la carte.'],
    ['Supprimer tes données', 'Recommence depuis l’accueil, ou efface les données de l’appli, et tout disparaît.'],
    ['Contact', 'Des questions ? sembagames.app'],
  ] as [string, string][],
  privacyUpdated: 'Dernière mise à jour : septembre 2026',
  howTo: 'Comment jouer',
  privacy: 'Confidentialité',
};
