// v0.12 text in French.
import type { NewStrings } from './lang-new';

const P = (n: number, one: string, many: string) => (n === 1 ? one : many);

export const NEW_FR: NewStrings = {
  tabs: ['Accueil', 'Effectif', 'Match', 'Transferts', 'Club'],
  hospitalT: 'Infirmerie',
  hospitalSub: (n: number) => (n ? `${n} ${P(n, 'blessé', 'blessés')}` : 'Tout le monde est apte'),
  settingsMore: 'Réglages et plus',
  settingsMoreSub: 'Langue, sauvegardes, éditeur, match rapide, confidentialité',

  today: (n: number) => (n ? `Aujourd’hui : ${n} ${P(n, 'chose vous attend', 'choses vous attendent')}` : 'Rien à signaler'),
  allClear: 'Rien ne vous attend avant le prochain match.',
  todayItems: {
    offers: (n: number) => `${n} ${P(n, 'offre', 'offres')} pour vos joueurs`,
    contracts: (n: number) => `${n} ${P(n, 'contrat se termine', 'contrats se terminent')} cette saison`,
    unavailable: (n: number) => `${n} ${P(n, 'titulaire blessé ou suspendu', 'titulaires blessés ou suspendus')}`,
    tired: (n: number) => `${n} ${P(n, 'titulaire est fatigué', 'titulaires sont fatigués')}`,
    windowOpen: (left: number) => `Mercato ouvert : encore ${left} ${P(left, 'journée', 'journées')}`,
    deadline: 'Dernier jour du mercato : il ferme après cette journée',
    sponsors: (n: number) => `${n} ${P(n, 'emplacement de sponsor libre', 'emplacements de sponsor libres')}`,
    red: 'Le club est dans le rouge',
    thin: (n: number) => `Seulement ${n} joueurs dans l’effectif`,
    jobs: (n: number) => `${n} ${P(n, 'club veut', 'clubs veulent')} vous parler`,
    dev: (n: number) => `${n} points de progression à dépenser`,
    staff: (n: number) => `Votre staff a fait ${n} ${P(n, 'chose', 'choses')} depuis le dernier match`,
  },
  todayActions: { offers: 'Répondre', contracts: 'Prolonger', unavailable: 'Corriger le XI', tired: 'Faire tourner', windowOpen: 'Marché', deadline: 'Marché', sponsors: 'Signer', red: 'Finances', thin: 'Recruter', jobs: 'Voir les offres', dev: 'Entraîner', staff: 'Voir' },
  formT: 'Forme',
  nextMatchT: 'Prochain match',

  ev2: {
    goal: [
      (p: string, c: string) => `BUT ! ${p} marque pour ${c}.`,
      (p: string, c: string) => `BUT ! ${p} trouve la lucarne. ${c} exulte.`,
      (p: string, c: string) => `But pour ${c} ! ${p} ne tremble pas.`,
      (p: string, c: string) => `BUT ! ${p} la met au fond. Les supporters de ${c} explosent.`,
      (p: string, c: string) => `BUT ! Clinique de ${p}. ${c} frappe.`,
    ],
    miss: [
      (p: string) => `${p} tire à côté.`,
      (p: string) => `${p} frôle le poteau.`,
      (p: string) => `Au-dessus de la barre, signé ${p}.`,
      (p: string) => `${p} se précipite. À côté.`,
      (p: string) => `${p} tente de loin. Loin du cadre.`,
      (p: string) => `Demi-occasion pour ${p}, mais c’est à côté.`,
    ],
    save: [
      (p: string) => `Grosse parade de ${p}.`,
      (p: string) => `${p} se couche bien et repousse.`,
      (p: string) => `Du bout des doigts ! ${p} la sort en corner.`,
      (p: string) => `${p} reste debout et bloque.`,
      (p: string) => `Mains fermes de ${p}.`,
      (p: string) => `${p} lit la frappe et capte.`,
    ],
    yellow: [
      (p: string) => `Carton jaune pour ${p}.`,
      (p: string) => `${p} est averti.`,
      (p: string) => `${p} arrive en retard. Jaune.`,
      (p: string) => `${p} averti pour avoir retenu son adversaire.`,
    ],
    red: [
      (p: string) => `CARTON ROUGE ! ${p} est expulsé.`,
      (p: string) => `Rouge ! ${p} doit sortir. À dix.`,
      (p: string) => `Direction le vestiaire : rouge pour ${p}.`,
    ],
    injury: [
      (p: string) => `${p} est blessé et ne peut pas continuer.`,
      (p: string) => `${p} s’arrête. Le kiné demande le changement.`,
      (p: string) => `Mauvaise nouvelle : ${p} sort en boitant.`,
    ],
    sub: [
      (off: string, on: string) => `Changement : ${on} remplace ${off}.`,
      (off: string, on: string) => `Changement : ${off} sort, ${on} entre.`,
      (off: string, on: string) => `Du sang neuf : ${on} à la place de ${off}.`,
    ],
  },
  ratingT: 'Note',
  ratingsT: 'Notes',
  motm: 'Homme du match',
  motmN: (n: number) => `${n}× homme du match`,
  avgRatingT: 'Note moyenne',
  xgT: 'Buts attendus (xG)',
  ftTitle: { W: 'Victoire', D: 'Nul', L: 'Défaite' },
  ftSub: 'Ce que le résultat a changé',
  ftPos: 'Classement',
  ftBoard: 'Confiance de la direction',
  ftFans: 'Supporters',
  ftDev: 'Points de progression',
  ftOut: (name: string, n: number) => `${name} : absent ${n} ${P(n, 'journée', 'journées')}`,
  ftBan: (name: string) => `${name} : suspendu`,
  ftRecord: 'Nouveau record du club',
  ftMilestone: 'Objectif atteint',
  ftContinue: 'Continuer',

  windowNames: { summer: 'Mercato d’été', winter: 'Mercato d’hiver' },
  windowOpenT: (left: number) => `Ouvert : encore ${left} ${P(left, 'journée', 'journées')}`,
  windowShutT: (n: number) => `Mercato fermé : ouvre dans ${n} ${P(n, 'journée', 'journées')}`,
  deadlineT: 'Dernier jour du mercato',
  deadlineSub: 'Dernière chance : le mercato ferme après cette journée. Les clubs enchérissent davantage aujourd’hui.',
  windowClosedBid: 'Le mercato est fermé. Vous pouvez toujours signer des joueurs libres.',

  transfersT: 'Transferts',
  trTabs: ['Marché', 'Suivis', 'Offres', 'Prêts', 'Opérations'],
  shortlistAdd: 'Suivre',
  shortlistRemove: 'Ne plus suivre',
  shortlistEmpty: 'Aucun joueur suivi. Ceux que vous suivez apparaissent ici, et vos recruteurs précisent leur vrai niveau.',
  findPlayers: 'Chercher des joueurs',
  offersEmpty: 'Aucune offre pour vos joueurs pour l’instant. Elles arrivent pendant le mercato, plus souvent pour les joueurs listés.',
  answerBids: 'Répondre aux offres',
  dealsEmpty: 'Aucune opération pour l’instant. Achats, ventes et libres apparaîtront ici.',
  loansInT: 'Prêtés chez nous',
  loansOutT: 'Prêtés ailleurs',
  loansEmpty: 'Aucun prêt cette saison. Empruntez des joueurs hors du XI de leur club, ou prêtez vos jeunes pour qu’ils jouent.',
  loanHint: 'Les prêts durent la saison. Le club qui accueille paie le salaire. Les jeunes reviennent meilleurs.',
  loanInBtn: (fee: string) => `Prêt pour la saison · ${fee}`,
  loanOutBtn: 'Prêter',
  loanTo: 'Le prêter à',
  loanFrom: (club: string) => `Prêté par ${club}`,
  loanAt: (club: string) => `Prêté à ${club}`,
  loanReason: {
    window: 'Les prêts se font seulement pendant le mercato.', budget: 'Pas assez de budget pour les frais de prêt.', wageCap: 'Son salaire dépasserait la masse salariale.',
    squad: 'Effectif complet.', key: 'Titulaire là-bas : pas prêtable.', limit: 'Vous avez déjà 4 prêts dans ce sens.',
    free: 'Un joueur libre signe, il n’est pas prêté.', loaned: 'Déjà prêté.', injured: 'Un joueur blessé ne peut pas être prêté.',
  },
  loanedIn: (name: string) => `${name} arrive en prêt.`,
  loanedOut: (name: string, club: string) => `${name} part en prêt à ${club}.`,
  noLoanClubs: 'Aucun club de son niveau ne le veut en prêt pour l’instant.',
  estimateT: 'Estimation des recruteurs',
  estHint: 'Suivez-le et vos recruteurs connaîtront son vrai niveau en 2 journées.',

  showT: 'Afficher',
  squadViews: ['Note', 'Condition', 'Contrat', 'Valeur', 'Forme'],

  matchTabs: ['Prochain', 'Classement', 'Résultats', 'Coupes', 'Stats'],
  leaderTabs: ['Buts', 'Passes D', 'Notes'],
  worldRankings: 'Classement mondial',

  boardT: 'Direction et objectifs',
  staffRoomT: 'Staff',
  staffRoomSub: (n: number, all: number) => (n ? `${n} tâches sur ${all} déléguées` : 'Vous gérez tout. Déléguez ce que vous voulez.'),
  financesT: 'Finances',
  ticketsT: 'Billetterie',
  sponsorsT: 'Sponsors',
  facilitiesT: 'Infrastructures',
  hireStaffT: 'Recruter du staff',
  historyT: 'Histoire et records',
  historySub: 'Saisons, records, trophées, jeunes du centre',

  staffIntro: 'Confiez n’importe quelle tâche à votre staff. Il s’en charge à chaque journée, aussi bien que sa qualité le permet. Les matchs, c’est toujours vous.',
  staffYours: 'Votre staff',
  qualityT: 'Qualité',
  dutiesT: 'Tâches',
  dutyGroups: { matchday: 'Jour de match', squad: 'Effectif', transfers: 'Transferts', club: 'Club' },
  duties: {
    lineup: ['Composition et changements', 'Choisit le meilleur XI à chaque match.'],
    tactics: ['Tactique', 'Choisit le système et la mentalité selon l’adversaire.'],
    scouting: ['Rapports adverses', 'Achète un rapport avant les gros matchs et applique son plan.'],
    training: ['Entraînement', 'Règle la charge et dépense les points de progression.'],
    medical: ['Infirmerie', 'Paie la rééducation des blessures longues.'],
    morale: ['Moral', 'Parle au groupe quand le moral baisse.'],
    academy: ['Centre de formation', 'Repère des espoirs, promeut les prêts, vend le reste.'],
    contracts: ['Contrats', 'Prolonge ceux qui le méritent dès la journée 5.'],
    selling: ['Ventes', 'Répond aux offres et liste les joueurs en trop.'],
    signing: ['Recrutement', 'Recrute au poste le plus faible pendant le mercato.'],
    loans: ['Prêts', 'Prête les jeunes pour qu’ils jouent.'],
    sponsors: ['Sponsors', 'Signe la meilleure offre pour chaque emplacement libre.'],
    tickets: ['Prix des billets', 'Fixe le prix qui rapporte le plus sans vider les tribunes.'],
  },
  matchDuty: ['Jouer le match', 'Toujours vous.'],
  meT: 'Moi',
  staffT: 'Staff',
  delegateAll: 'Tout déléguer',
  takeAll: 'Tout reprendre en main',
  needStaff: (role: string) => `Recrutez d’abord : ${role.toLowerCase()}`,
  staffLogT: 'Ce qu’a fait votre staff',
  staffLogEmpty: 'Rien pour l’instant. Déléguez une tâche et votre staff notera ici ce qu’il fait.',
  staffLog: {
    'training:load': (a) => `Charge d’entraînement : ${['récupération', 'équilibrée', 'intense'][a.n] ?? 'équilibrée'}.`,
    'training:dev': (a) => `Points de progression pour ${a.pn} (+1 de note).`,
    'medical:rehab': (a) => `A payé la rééducation de ${a.pn}.`,
    'morale:talk': (a) => `Discours au groupe : le moral était à ${a.n}.`,
    'academy:promote': (a) => `A promu ${a.pn} du centre de formation.`,
    'academy:sold': (a) => `A vendu les droits de ${a.pn} pour ${a.money(a.n)}.`,
    'academy:scouted': (a) => `A trouvé ${a.n} ${P(a.n, 'nouvel espoir', 'nouveaux espoirs')}.`,
    'selling:sold': (a) => `A vendu ${a.pn} à ${a.club} pour ${a.money(a.n)}.`,
    'selling:rejected': (a) => `A refusé ${a.money(a.n)} pour ${a.pn}.`,
    'selling:listed': (a) => `A placé ${a.pn} sur la liste des transferts.`,
    'contracts:renewed': (a) => `A prolongé ${a.pn} de ${a.n} ${P(a.n, 'saison', 'saisons')}.`,
    'signing:signed': (a) => `A recruté ${a.pn} ${a.club ? `de ${a.club}` : 'libre'} pour ${a.n ? a.money(a.n) : '0'}.`,
    'loans:out': (a) => `A prêté ${a.pn} à ${a.club}.`,
    'sponsors:signed': (a) => `A signé ${a.pn} comme sponsor : ${a.money(a.n)} par mois.`,
    'tickets:price': (a) => `Prix du billet : ${a.s}.`,
    'tactics:formation': (a) => `Passage au ${a.s}.`,
    'scouting:report': (a) => `A acheté un rapport sur ${a.club}.`,
  },
  staffNames2: { director: 'Directeur sportif' },
  staffEffects2: { director: 'Contrats, offres, recrutement, prêts, sponsors et billetterie quand vous les déléguez' },
  ledgerKeys2: { loans: 'Frais de prêt' },

  histTabs: ['Saisons', 'Records', 'Trophées', 'Formation'],
  seasonsEmpty: 'Votre première saison est en cours. Les saisons terminées sont gardées ici.',
  recordsEmpty: 'Les records apparaissent après quelques matchs.',
  trophiesEmpty: 'Pas encore de trophée. Gagnez un championnat ou une coupe pour remplir la vitrine.',
  gradsEmpty: 'Pas encore de jeune promu. Promouvez un espoir et suivez son histoire ici.',
  recordNames: {
    bigWin: 'Plus large victoire', mostPoints: 'Plus de points en championnat', mostGoals: 'Plus de buts en championnat', unbeaten: 'Plus longue série sans défaite',
    scorer: 'Meilleur buteur sur une saison', bestFinish: 'Meilleur classement', bestBuy: 'Achat record', bestSale: 'Vente record',
  },
  gamesN: (n: number) => `${n} ${P(n, 'match', 'matchs')}`,
  gradLine: (apps: number, goals: number) => `${apps} matchs · ${goals} buts cette saison`,
  trophyKinds: { league: 'Championnat', cup: 'Coupe', continental: 'Coupe continentale', promotion: 'Montée' },

  supportT: 'Soutenir The Gaffer',
  supportBody: 'Un pack Supporter en une fois : tous les styles de club, un badge Supporter sur votre carte et pas de pubs. Le jeu reste complet pour tout le monde.',
  supportBtn: 'Obtenir le pack Supporter',
  supportSoon: 'Le pack Supporter arrive bientôt.',
  supporterBadge: 'Supporter',
  supportThanks: 'Merci de soutenir The Gaffer. Tout est débloqué.',
  looksT: 'Style',
  looks: ['Violet', 'Projecteurs', 'Pelouse', 'Rouge derby'],
  looksLocked: 'Pack Supporter',
  rewardedBtn: 'Regarder une courte pub : rapport gratuit',
  rewardedHint: 'Facultatif. Vous pouvez toujours payer le rapport avec l’argent du club.',
  adFailed: 'Pas de pub disponible. Réessayez plus tard.',
  sponsoredT: 'Sponsorisé',
  howToBody2: [
    ['Votre rôle', 'Choisissez un club et signez le contrat. La direction fixe des objectifs en championnat et en coupe. Atteignez-les et votre réputation grandit ; ratez-les et vous pouvez être limogé.'],
    ['Accueil', 'L’accueil liste ce qui vous attend aujourd’hui, chaque point avec un bouton. Réglez-les, puis jouez le prochain match.'],
    ['Journées', 'Touchez Jouer le match pour le vivre en direct, ou prenez un résultat rapide. Chaque match se termine par des notes, un homme du match et une carte de ce que le résultat a changé.'],
    ['Tactique', 'Choisissez système, XI, mentalité, pressing et jeu de passes. Les philosophies se battent comme pierre-feuille-ciseaux, et votre maîtrise progresse à chaque match. Espionnez l’adversaire avant les gros matchs.'],
    ['Votre staff', 'Club › Staff : confiez n’importe quelle tâche (composition, entraînement, contrats, recrutement et plus) ou faites-la vous-même. Les matchs, c’est toujours vous.'],
    ['Transferts', 'Achetez et vendez pendant le mercato (été et hiver, avec dernier jour). Les joueurs libres signent à tout moment. Suivez des joueurs pour connaître leur vrai niveau, et prêtez ou empruntez pour la saison.'],
    ['Argent', 'Billetterie, droits TV et sponsors rentrent ; salaires, staff et entretien sortent. Améliorez les infrastructures, recrutez du staff et finissez la saison dans le vert.'],
    ['Coupes', 'La coupe nationale est à élimination directe dès le départ. Les coupes continentales commencent par des groupes de quatre : les deux premiers passent.'],
    ['Votre carrière', 'Gagnez de l’XP et des licences, suivez des formations, cumulez objectifs et trophées, battez les records du club. Les grands clubs appelleront.'],
    ['Sauvegarde', 'La carrière s’enregistre après chaque match et est vérifiée au chargement. Exportez une sauvegarde depuis Club › Réglages et plus.'],
  ],
  privacyBody2: [
    ['Ce que nous gardons', 'Votre carrière, vos réglages et la photo d’entraîneur sont enregistrés uniquement sur cet appareil. La vérification des mises à jour demande à Semba Games le dernier numéro de version, sans envoyer de données de carrière.'],
    ['Fonctions en ligne', 'Les pubs et les achats, quand ils sont activés, sont clairement signalés. Les pubs web viennent de Google AdSense, qui peut utiliser des cookies pour les afficher et les mesurer. Les achats passent par Stripe ; nous ne voyons jamais votre carte.'],
    ['Sans compte', 'The Gaffer n’a pas de connexion. Votre carrière reste sur votre appareil, et vous pouvez l’exporter à tout moment depuis les réglages.'],
    ['Sauvegardes', 'Une sauvegarde exportée va où vous le choisissez. L’import ne lit que le fichier choisi.'],
    ['Photos', 'La photo de votre carte d’entraîneur reste sur cet appareil et ne sert qu’à dessiner la carte.'],
    ['Supprimer vos données', 'Recommencez depuis les réglages, ou effacez les données de l’app, et tout disparaît.'],
    ['Contact', 'Des questions ? sembagames.app'],
  ],
};
