// Spanish interface. Names of clubs, players and leagues stay in their English form (the data has EN and AR names).
import type { MsgP, Strings } from './i18n';

const ord = (n: number) => `${n}.º`;

export const es: Strings = {
  live: 'Pretemporada',
  lang: 'ES',
  tagline: ['Dirige el club.', 'Manda en el banquillo.'],
  heroOver: 'Tu carrera',
  heroTitle: 'Acepta el cargo',
  heroBody: 'Elige un club de las cinco grandes ligas de Europa o de las ligas árabes. Gánate a la directiva, a la afición y al vestuario.',
  newCareer: 'Nueva carrera',
  newCareerSub: 'Elige país, liga y club',
  moreWays: 'Más formas de jugar',
  continue: 'Continuar',
  continueSub: 'Aún no hay carrera guardada',
  friends: 'Amigos',
  friendsSub: 'Salas privadas. Muy pronto.',
  quick: 'Partido rápido',
  quickSub: 'Un partido. No cuenta nada.',
  foot: 'Juego no oficial hecho por fans. Los nombres de clubes, ligas y jugadores son ficticios o están cambiados. Sin relación con ningún club, liga o jugador.',
  tabs: ['Inicio', 'Plantilla', 'Partido', 'Liga', 'Más'],
  chooseCountry: 'Elige un país',
  mainLeagues: 'Las cinco grandes',
  arabLeagues: 'Ligas árabes',
  main: 'Principal',
  leagues: (n: number) => (n === 1 ? '1 liga' : `${n} ligas`),
  chooseLeague: 'Elige una liga',
  clubs: (n: number) => `${n} clubes`,
  tier: (n: number) => (n === 1 ? 'Primera división' : `División ${n}`),
  nextClub: 'Siguiente: elige tu club',
  back: 'Atrás',
  soon: 'Toca una liga para ver sus clubes.',
  chooseClub: 'Elige tu club',
  pickClubHint: 'Los grandes exigen títulos. Los pequeños te dan tiempo.',
  takeJob: 'Aceptar el cargo',
  signContract: 'Firmar el contrato',
  replaceWarn: 'Esto sustituye tu carrera guardada.',
  managerName: 'Tu nombre',
  managerDefault: 'The Gaffer',
  strength: 'Nivel',
  budget: 'Presupuesto',
  wageBill: 'Masa salarial',
  perMonth: '/mes',
  boardWants: 'La directiva quiere',
  squadSize: 'Plantilla',
  objective: {
    title: 'Ganar la liga',
    europe: 'Acabar entre los cinco primeros',
    topHalf: 'Acabar en la mitad alta',
    survive: 'Evitar el descenso',
    promotion: 'Conseguir el ascenso',
    playoffs: 'Llegar al play-off',
    midTable: 'Acabar en mitad de tabla',
  },
  season: (y: number) => `Temporada ${y}/${String(y + 1).slice(2)}`,
  welcome: (name: string) => `Bienvenido, ${name}.`,
  nextUp: 'Próximo partido',
  nextUpBody: 'Tu siguiente partido.',
  keyPlayers: 'Jugadores clave',
  seeSquad: 'Ver la plantilla',
  squad: 'Plantilla',
  all: 'Todos',
  groups: ['POR', 'DEF', 'MED', 'DEL'],
  table: 'Liga',
  powerRanking: 'Ranking de pretemporada',
  powerHint: 'Aún no se ha jugado. Ordenado por el mejor once.',
  you: 'Tú',
  player: {
    position: 'Posición', age: 'Edad', nation: 'Nacionalidad', rating: 'Media', potential: 'Potencial',
    value: 'Valor', wage: 'Sueldo', contract: 'Contrato hasta', shirt: 'Dorsal',
  },
  pos: { GK: 'Portero', CB: 'Central', LB: 'Lateral izquierdo', RB: 'Lateral derecho', CDM: 'Pivote', CM: 'Centrocampista', CAM: 'Mediapunta', LW: 'Extremo izquierdo', RW: 'Extremo derecho', ST: 'Delantero' },
  close: 'Cerrar',
  continueOn: (club: string) => club,
  badSave: 'Tu carrera guardada no pasó la comprobación y no se cargó.',
  startOver: 'Empezar de cero',
  startOverSub: 'Borrar esta carrera',
  startOverAsk: '¿Borrar tu carrera?',
  startOverBody: 'Tu club, tu plantilla y tu progreso se borran. No se puede deshacer.',
  delete: 'Borrar',
  cancel: 'Cancelar',
  soonTag: 'Pronto',
  noCareer: 'Empieza una carrera para desbloquear esto.',
  matchday: (n: number) => `Jornada ${n}`,
  match: 'Partido',
  vs: 'vs',
  home: 'Local',
  away: 'Visitante',
  yourXI: 'Tu once',
  autoXI: 'El mejor once elegido por ti (4-3-3). La táctica llega después.',
  watch: 'Jugar el partido',
  quickResult: 'Resultado rápido',
  skip: 'Ir al final',
  done: 'Continuar',
  leagueOver: 'Tu temporada de liga ha terminado.',
  finishSeason: 'Terminar la temporada',
  seasonOver: 'Fin de temporada',
  finished: (pos: string) => `Terminaste ${pos}.`,
  ordinal: ord,
  met: 'Directiva contenta: objetivo cumplido',
  missed: 'Directiva descontenta: objetivo fallado',
  champion: 'Campeones',
  topScorer: 'Máximo goleador',
  nextSeason: (y: number) => `Empezar ${y}/${String(y + 1).slice(2)}`,
  promotedTo: (l: string) => `¡Ascenso! La próxima temporada: ${l}.`,
  relegatedTo: (l: string) => `Descenso. La próxima temporada: ${l}.`,
  stayIn: (l: string) => `La próxima temporada: ${l}.`,
  retiredN: (n: number) => `${n} jugadores se retiraron en todo el mundo; los chavales de la cantera ocuparon su sitio.`,
  moves: 'Ascensos y descensos',
  up: 'Suben',
  down: 'Bajan',
  lastResult: 'Último resultado',
  position: 'Posición',
  points: 'pts',
  tableTab: 'Clasificación',
  resultsTab: 'Resultados',
  scorersTab: 'Goleadores',
  cols: ['PJ', 'G', 'E', 'P', '±', 'Pts'],
  noGames: 'Aún no se ha jugado ningún partido.',
  goals: 'Goles',
  history: 'Historial',
  fullTime: 'Final',
  halfTime: 'Descanso',
  ev: {
    kickoff: 'Arranca el partido.',
    half: 'Descanso.',
    full: 'Final del partido.',
    goal: (p: string, c: string) => `¡GOL! ${p} marca para el ${c}.`,
    miss: (p: string) => `${p} la manda fuera.`,
    save: (p: string) => `Paradón de ${p}.`,
    yellow: (p: string) => `Amarilla para ${p}.`,
    red: (p: string) => `¡ROJA! ${p} se va a la calle.`,
    injury: (p: string) => `${p} se lesiona y no puede seguir.`,
    assist: (p: string) => `Asistencia: ${p}.`,
    sub: (off: string, on: string) => `Cambio: entra ${on} por ${off}.`,
    how: { pen: '(de penalti)', fk: '(de falta)', corner: '(tras un córner)' },
  },
  win: 'Victoria', draw: 'Empate', loss: 'Derrota',
  sorts: ['Posición', 'Media', 'Valor', 'Sueldo', 'Edad', 'Forma física'],
  avgRating: 'Media',
  avgAge: 'Edad media',
  wageCap: 'Tope salarial',
  market: 'Mercado de fichajes',
  marketSub: 'Ficha jugadores y agentes libres',
  freeAgents: 'Agentes libres',
  affordable: 'Dentro del presupuesto',
  allLeagues: 'Todas las ligas',
  showingTop: (n: number) => `Los ${n} primeros.`,
  free: 'Libre',
  askPrice: 'Precio pedido',
  makeOffer: 'Hacer una oferta',
  fee: 'Traspaso',
  years: 'Contrato',
  yearsN: (n: number) => (n === 1 ? '1 temporada' : `${n} temporadas`),
  role: 'Papel en la plantilla',
  roles: { star: 'Estrella', regular: 'Titular', rotation: 'Rotación', prospect: 'Promesa' },
  send: 'Enviar oferta',
  bidReason: {
    budget: 'No hay presupuesto para ese traspaso.',
    wageCap: 'Ese sueldo supera tu tope salarial.',
    squadFull: 'Tu plantilla está llena (32 jugadores).',
    fee: (m: string) => `Quieren al menos ${m}.`,
    wage: (m: string) => `Pide ${m} al mes.`,
    ambition: 'No vendrá a un club de tu nivel.',
    role: 'Solo los jugadores de 21 años o menos pueden ser promesas.',
    injured: 'Está lesionado.',
  },
  signed: (n: string) => `¡${n} fichado!`,
  listForSale: 'Poner en venta',
  unlist: 'Quitar de la lista',
  listed: 'En venta',
  renewTitle: 'Renovar contrato',
  extraYears: 'Temporadas extra',
  renewed: (n: string) => `${n} renovado.`,
  renewReason: {
    wage: (m: string) => `Pide ${m} al mes.`,
    years: (n: number) => `A su edad: ${n === 1 ? '1 temporada' : `${n} temporadas`} como mucho.`,
    wageCap: 'Ese sueldo supera tu tope salarial.',
    unhappy: 'Está descontento y no quiere hablar.',
  },
  expiringN: (n: number) => (n === 1 ? '1 contrato acaba esta temporada' : `${n} contratos acaban esta temporada`),
  expiringHint: 'Renuévalos o se irán gratis.',
  offersN: (n: number) => (n === 1 ? '1 oferta por tus jugadores' : `${n} ofertas por tus jugadores`),
  offers: 'Ofertas',
  accept: 'Aceptar',
  reject: 'Rechazar',
  counter: 'Pedir +20%',
  sold: (n: string, c: string) => `${n} vendido al ${c}.`,
  counterOk: 'Aceptaron el nuevo precio.',
  counterNo: 'Se echaron atrás.',
  sellReason: { squadMin: 'Necesitas al menos 16 jugadores.', buyerBudget: 'Ya no se lo pueden permitir.' },
  thinSquad: (n: number) => `Solo ${n} jugadores. Ficha más para cubrir lesiones y sanciones.`,
  injuredN: (n: number) => `${n} lesionados`,
  bannedN: (n: number) => `${n} sancionados`,
  statusInj: (n: number) => `Lesionado · ${n} jor.`,
  statusBan: (n: number) => `Sancionado · ${n} jor.`,
  fitness: 'Forma física',
  morale: 'Moral',
  attrs: ['Velocidad', 'Disparo', 'Pase', 'Regate', 'Defensa', 'Físico', 'Portería'],
  seasonStats: 'Esta temporada',
  statCols: ['PJ', 'Goles', 'Asist.', 'Amar.', 'Rojas'],
  assistsTab: 'Asistencias',
  leftClub: 'Contratos terminados',
  academyUp: 'Canteranos que suben',
  deals: 'Tus operaciones',
  dealKind: { in: 'Fichado', out: 'Vendido', free: 'Libre', released: 'Despedido' },
  exportSave: 'Exportar partida',
  exportSub: 'Descarga un archivo .gaffer o cópialo',
  download: 'Descargar archivo',
  copy: 'Copiar',
  copied: 'Copiado.',
  importSave: 'Importar partida',
  importSub: 'Carga un archivo .gaffer o pégalo',
  pasteHere: 'Pega aquí una partida',
  load: 'Cargar',
  chooseFile: 'Elegir archivo',
  importBad: {
    format: 'Eso no es una partida de The Gaffer.',
    checksum: 'Esta partida se editó o está dañada, así que se rechazó.',
    world: 'Esta partida no pasó la comprobación del mundo.',
    none: 'No hay nada que cargar.',
  },
  importOk: 'Partida cargada.',
  kit: 'Equipación',
  shirt: 'Camiseta',
  tactics: 'Táctica',
  formation: 'Formación',
  mentality: 'Mentalidad',
  mentalities: ['Autobús', 'Defensiva', 'Equilibrada', 'Ofensiva', 'Todo al ataque'],
  pressing: 'Presión',
  pressings: ['Baja', 'Media', 'Alta'],
  passing: 'Pase',
  passings: ['Corto', 'Mixto', 'Directo'],
  bestXI: 'Mejor once',
  saveTactics: 'Guardar táctica',
  tacticsSaved: 'Táctica guardada.',
  pickFor: (pos: string) => `Elige un jugador para ${pos}`,
  outOfPos: 'Fuera de posición',
  setPiecesT: 'Balón parado',
  captain: 'Capitán',
  penaltiesT: 'Penaltis',
  freeKicksT: 'Faltas',
  cornersT: 'Córners',
  prediction: 'Pronóstico',
  replacedN: (names: string) => `Sustituidos automáticamente (no disponibles): ${names}.`,
  unsaved: 'Cambios sin guardar',
  pause: 'Pausa',
  resume: 'Seguir',
  changes: 'Cambios',
  subsLeft: (n: number) => (n === 1 ? 'Queda 1 cambio' : `Quedan ${n} cambios`),
  makeSub: 'Hacer el cambio',
  subOut: 'Sale',
  subIn: 'Entra',
  feed: 'Narración',
  statsT: 'Estadísticas',
  lineups: 'Alineaciones',
  statNames: ['Posesión', 'Tiros', 'A puerta', 'Córners', 'Faltas', 'Amarillas', 'Rojas'],
  halfTimeTalk: 'Charla del descanso',
  talks: ['No decir nada', 'Motivarlos', 'Calmarlos', 'Mantener la concentración'],
  talkHints: ['', 'Más ataque, un poco más abiertos atrás.', 'Menos faltas y tarjetas.', 'Más sólidos atrás, algo menos arriba.'],
  secondHalf: 'Segunda parte',
  resumeMatch: 'Seguir el partido',
  bench: 'Banquillo',
  coachAge: 'Tu edad',
  ageRule: 'Entre 20 y 80.',
  coachNation: 'Nacionalidad',
  searchClub: 'Buscar clubes',
  saveFailed: 'No se pudo guardar: el almacenamiento del navegador está lleno o bloqueado. Exporta tu partida desde Más.',
  inbox: 'Buzón',
  markAllRead: 'Marcar todo como leído',
  clearAll: 'Borrar todo',
  noMsgs: 'No hay mensajes.',
  inboxKinds: { all: 'Todo', board: 'Directiva', fans: 'Afición', club: 'Club', contract: 'Contratos', offer: 'Ofertas', cup: 'Copas', coach: 'Entrenador', job: 'Ofertas de trabajo', scout: 'Ojeadores' },
  msg: {
    welcome: (p: MsgP) => [`Bienvenido al ${p.club}`, 'La directiva, los jugadores y la afición están listos. Suerte, míster.'],
    bigWin: (p: MsgP) => ['Afición: ¡qué victoria!', `${p.s} ante el ${p.club}. La grada corea tu nombre.`],
    badLoss: (p: MsgP) => ['Directiva: no es suficiente', `${p.s} ante el ${p.club}. Esperamos una reacción.`],
    giantKill: (p: MsgP) => ['¡Matagigantes!', `Ganar al ${p.club} ha sido noticia.`],
    boardWorried: () => ['Directiva: estamos preocupados', 'Los resultados tienen que mejorar pronto.'],
    boardAngry: () => ['Directiva: último aviso', 'Una mala racha más y estás fuera.'],
    boardHappy: () => ['Directiva: gran trabajo', 'La directiva te respalda totalmente.'],
    fansAngry: () => ['La afición está enfadada', 'Hay pancartas en la grada pidiendo cambios.'],
    fansLove: () => ['La afición te adora', 'Tu nombre está en todas las camisetas de la ciudad.'],
    sacked: (p: MsgP) => ['Estás despedido', `El ${p.club} ha rescindido tu contrato. Elige tu próximo destino.`],
    seasonGood: (p: MsgP) => ['Directiva: balance de la temporada', `Acabamos en ${ord(p.n)} posición. Objetivo cumplido. Bien hecho.`],
    seasonBad: (p: MsgP) => ['Directiva: balance de la temporada', `Acabamos en ${ord(p.n)} posición. Objetivo no cumplido.`],
    contractsEnding: (p: MsgP) => ['Contratos que acaban', `${p.n} contratos acaban esta temporada. Renuévalos o se irán gratis.`],
    offerIn: (p: MsgP) => ['Nueva oferta', `El ${p.club} ha hecho una oferta por ${p.player}.`],
    cupThrough: (p: MsgP) => [`${p.s}: ¡pasamos!`, `Eliminamos al ${p.club}.`],
    cupOut: (p: MsgP) => [`${p.s}: eliminados`, `El ${p.club} nos eliminó.`],
    cupWon: (p: MsgP) => [`${p.s}: ¡CAMPEONES!`, `Ganamos al ${p.club} en la final.`],
    groupThrough: (p: MsgP) => [`${p.s}: a las eliminatorias`, `Acabamos ${p.n === 1 ? 'primeros' : 'segundos'} de grupo.`],
    groupOut: (p: MsgP) => [`${p.s}: fuera en la fase de grupos`, `Acabamos ${p.n === 3 ? 'terceros' : 'últimos'} de grupo.`],
    milestone: (p: MsgP) => ['Hito conseguido', p.s],
    licence: (p: MsgP) => ['Licencia conseguida', `Ya tienes la licencia ${p.s}.`],
    course: (p: MsgP) => ['Curso completado', p.s],
    jobOffer: (p: MsgP) => ['Oferta de trabajo', `El ${p.club} te quiere como entrenador.`],
  } as Record<string, (p: MsgP) => string[]>,
  career: 'Tu carrera',
  careerSub: 'Nivel, licencia, cursos, hitos',
  level: 'Nivel',
  reputation: 'Reputación',
  licence: 'Licencia',
  wallet: 'Tu dinero',
  record: 'Balance',
  trophies: 'Títulos',
  noTrophies: 'Aún no hay títulos.',
  trophyKind: { league: 'Liga', cup: 'Copa', continental: 'Continental', promotion: 'Ascenso' },
  nextLicence: (l: string) => `Siguiente: licencia ${l}`,
  licenceCap: (n: number) => `Clubes hasta reputación ${n}`,
  examNeeds: {
    level: (n: number) => `Necesitas nivel ${n}`, matches: (n: number) => `Necesitas ${n} partidos`, fee: (m: string) => `Tasa del examen ${m}`,
    wait: (n: number) => `Próximo examen en ${n} jornadas`, trophy: () => 'Necesitas un título', max: () => 'Licencia máxima conseguida',
  },
  takeExam: 'Hacer el examen',
  examTitle: (l: string) => `Examen de licencia ${l}`,
  examPassed: '¡Aprobado! Nueva licencia.',
  examFailed: 'Esta vez no. Estudia y vuelve a intentarlo.',
  submit: 'Entregar',
  coursesT: 'Cursos',
  courseNames: { conditioning: 'Preparación física moderna', psychology: 'Psicología deportiva', gegenpress: 'Taller de presión', fellowship: 'Beca en academia europea' } as Record<string, string>,
  courseEffects: { conditioning: 'Tu equipo se cansa un 15% menos en los partidos.', psychology: 'Las derrotas afectan menos a la moral; la moral se asienta más alta.', gegenpress: 'La presión alta hace más daño.', fellowship: 'Tus jóvenes progresan más rápido.' } as Record<string, string>,
  takeCourse: (m: string) => `Hacerlo · ${m}`,
  doneTag: 'Hecho',
  notEnough: 'No hay suficiente dinero.',
  milestonesT: 'Hitos',
  msCats: { short: 'Corto plazo', mid: 'Medio plazo', long: 'Largo plazo' },
  msNames: {
    firstWin: 'Primera victoria', streak3: '3 victorias seguidas', streak5: '5 victorias seguidas', unbeaten10: '10 partidos invicto', giantSlayer: 'Matagigantes',
    cupGlory: 'Gloria copera', promotion: 'Para arriba', leagueTitle: 'Campeones de liga', topFlightTitle: 'Campeones de primera', continental: 'Reyes del continente',
    matches100: '100 partidos', winRate55: '55% de victorias tras 50 partidos', twoClubs: 'Títulos con dos clubes', licenceA: 'Licencia A', licencePro: 'Licencia PRO', worldNo1: 'Número uno del mundo',
  } as Record<string, string>,
  jobsT: 'Ofertas de trabajo',
  takeJobQ: (c: string) => `¿Te vas al ${c}?`,
  takeJobBody: 'Tu nuevo club sigue donde está: su plantilla, su calendario, su directiva.',
  sackedTitle: 'Estás despedido',
  sackedBody: 'Elige tu próximo club para seguir.',
  boardFans: 'Directiva y afición',
  confidence: 'Directiva',
  fansT: 'Afición',
  objectivesT: 'Objetivos',
  cupAim: { win: 'Ganar la copa', semi: 'Llegar a semifinales de copa', round2: 'Pasar una eliminatoria de copa' },
  youthAim: (n: number, have: number) => `Dar ${n} partidos a sub-21 (${have} hasta ahora)`,
  cupsTab: 'Copas',
  roundName: (k: number, total: number) => (k < 0 ? 'Fase de grupos' : ['Final', 'Semifinales', 'Cuartos de final', 'Octavos de final', 'Dieciseisavos de final'][total - k - 1] ?? `Ronda de ${2 ** (total - k)}`),
  pens: (a: number, b: number) => `${a}–${b} pen.`,
  bye: 'exento',
  shootout: 'Tanda de penaltis',
  kick: (p: string, ok: boolean) => `${p} ${ok ? 'marca' : 'falla'}`,
  cupOut: (r: string) => `Eliminado en ${r.toLowerCase()}`,
  cupWonT: 'Campeón',
  groupDay: (n: number) => `Fase de grupos · partido ${n} de 6`,
  groupT: (g: number) => `Grupo ${'ABCDEFGH'[g]}`,
  groupStage: 'Fase de grupos',
  knockouts: 'Eliminatorias',
  editName: 'Editar nombre',
  nameEn: 'Nombre en inglés',
  nameAr: 'Nombre en árabe',
  save: 'Guardar',
  lockedBy: (l: string) => `Necesita licencia ${l}`,
  clubT: 'Club',
  topPlayers: 'Mejores jugadores',
  acceptJobShort: 'Oferta',
  clubScreen: 'Club',
  clubSub: 'Dinero, entradas, patrocinadores, instalaciones, personal',
  trainingT: 'Entrenamiento',
  trainingSub: 'Carga, enfoque, puntos de desarrollo',
  hospitalT: 'Enfermería',
  hospitalSub: (n: number) => (n ? `${n} lesionados` : 'Sin lesiones'),
  academyT: 'Cantera',
  academySub: (n: number) => `${n} promesas`,
  finTabs: ['Dinero', 'Entradas', 'Patrocinio', 'Instalaciones', 'Personal'],
  ledgerKeys: {
    tickets: 'Entradas', tv: 'Televisión', sponsors: 'Patrocinadores', prizes: 'Premios', sales: 'Ventas de cantera', donations: 'Donaciones', bonusSponsor: 'Primas de patrocinio',
    milestones: 'Premios por hitos', transfersOut: 'Jugadores vendidos', transfersIn: 'Jugadores comprados', wages: 'Sueldos de jugadores', staff: 'Sueldos del personal',
    upkeep: 'Mantenimiento', facilities: 'Mejoras de instalaciones', bonuses: 'Primas', medical: 'Médico', scouting: 'Ojeo', wageCap: 'Tope salarial',
  } as Record<string, string>,
  perMonthT: 'Al mes',
  thisSeason: 'Esta temporada',
  lastSeason: 'Temporada pasada',
  net: 'Neto',
  inTheRed: 'El club está en números rojos. La directiva pierde la paciencia cada semana.',
  capacity: 'Aforo',
  ticketPrice: 'Precio de la entrada',
  expected: 'Público esperado',
  revenue: 'Ingresos por partido en casa',
  lastGate: (a: number, m: string) => `Último partido en casa: ${a} aficionados, ${m}`,
  setPrice: 'Fijar precio',
  usual: 'Precio habitual aquí',
  slotNames: { shirt: 'Camiseta', kit: 'Marca deportiva', stadium: 'Nombre del estadio', sleeve: 'Manga', commercial: 'Socio comercial' } as Record<string, string>,
  monthsLeft: (n: number) => `Quedan ${n} meses`,
  months: (n: number) => `${n} meses`,
  bonusLeague: 'Prima por la liga',
  bonusCup: 'Prima por la copa',
  sign: 'Firmar',
  askMore: 'Pedir +10%',
  extend: 'Ampliar +12 meses',
  endDeal: 'Romper el acuerdo',
  endDealCost: (m: string) => `Romperlo antes cuesta ${m}`,
  haggleOk: 'Aceptaron un 10% más.',
  haggleNo: 'Se echaron atrás.',
  emptySlots: (n: number) => `${n} huecos de patrocinio vacíos`,
  emptySlotsHint: 'Hay ofertas esperando en Club › Patrocinio.',
  facilityNames: { stadium: 'Estadio', medical: 'Centro médico', training: 'Ciudad deportiva', academy: 'Cantera', scouting: 'Red de ojeadores' } as Record<string, string>,
  facilityEffects: { stadium: '+15% de asientos por nivel', medical: 'Lesiones más cortas, tratamientos más baratos', training: 'Los jugadores progresan más rápido', academy: 'Mejores promesas', scouting: 'Más promesas por prueba de ojeo' } as Record<string, string>,
  upgrade: (m: string) => `Mejorar · ${m}`,
  maxLevel: 'Nivel máximo',
  upkeepT: 'Mantenimiento',
  staffNames: { assistant: 'Segundo entrenador', fitness: 'Preparador físico', doctor: 'Médico del club', psychologist: 'Psicólogo', scout: 'Jefe de ojeadores' } as Record<string, string>,
  staffEffects: { assistant: 'Nivel en partido y entrenamiento', fitness: 'Menos cansancio, menos golpes entrenando', doctor: 'Lesiones más cortas, tratamientos más baratos', psychologist: 'Moral más alta y estable', scout: 'Una promesa más si es bueno' } as Record<string, string>,
  quality: 'Calidad',
  hire: 'Contratar',
  candidates: 'Candidatos',
  staffTotal: (m: string) => `Sueldos del personal: ${m} al mes`,
  bonusT: 'Primas',
  teamBonus: 'Prima al equipo',
  playerBonus: 'Un jugador',
  perPlayer: 'Por jugador',
  fromClub: 'Del club',
  fromWallet: 'De tu dinero',
  pay: 'Pagar',
  bonusPaid: 'Prima pagada. La moral sube.',
  donateT: 'Donar al club',
  donateHint: 'De tu propio dinero. La directiva y la afición lo notan, más cuanto mayor sea el regalo.',
  donate: 'Donar',
  donated: 'Gracias, míster.',
  wageCapT: 'Tope salarial',
  wageCapHint: 'Cada +1 al mes cuesta 12 del presupuesto (y al revés).',
  raise: 'Subir',
  lower: 'Bajar',
  loadT: 'Carga de entrenamiento',
  loads: ['Recuperación', 'Normal', 'Intensa'],
  loadHints: ['Recuperan más forma física, progresan despacio.', 'Forma física y progreso normales.', 'Progresan más rápido, menos forma física, algo de riesgo de lesión.'],
  focusT: 'Enfoque individual',
  focusNone: 'General',
  reportT: 'La semana pasada',
  reportNone: 'Nadie subió de nivel esta semana.',
  improvedN: (n: number) => `${n} jugadores mejoraron (+1)`,
  hurtIn: (p: string) => `${p} se llevó un golpe entrenando.`,
  ceiling: 'Está en su techo: entrenar le mantiene en forma, pero no mejorará.',
  devT: 'Puntos de desarrollo',
  devHint: 'Se ganan con victorias, títulos y objetivos.',
  devUses: { rating: '+1 de media', potential: '+2 de potencial', fitness: '+15 de forma física', morale: 'Charla: +10 de moral para todos' } as Record<string, string>,
  devWhy: { points: 'No hay puntos suficientes.', ceiling: 'Está en su techo.', age: 'Solo para jugadores de 26 años o menos.', full: 'Ya está en plena forma.' } as Record<string, string>,
  choosePlayer: 'Elige un jugador',
  use: 'Usar',
  treatments: { rehab: 'Rehabilitación (−1 jornada)', specialist: 'Especialista (−2 jornadas)', instant: 'Recuperación inmediata' } as Record<string, string>,
  noInjuries: 'No hay lesionados.',
  treated: 'Tratamiento hecho.',
  scoutExam: (m: string) => `Prueba de ojeo · ${m}`,
  scoutFound: (n: number) => `Encontradas ${n} promesas.`,
  academyFull: 'La cantera está llena (8).',
  promoteT: 'Subir',
  releaseT: 'Despedir',
  sellRightsT: (m: string) => `Vender derechos · ${m}`,
  promoted: 'Sube al primer equipo.',
  noProspects: 'Aún no hay promesas. Haz una prueba de ojeo.',
  nicknameT: 'Apodo',
  financeAim: 'Acabar la temporada sin pérdidas',
  playerSavings: 'Primas recibidas',
  philosophyT: 'Filosofía',
  philosophies: { balanced: 'Equilibrada', possession: 'Posesión', counter: 'Contraataque', gegenpress: 'Gegenpress', bus: 'Autobús', wings: 'Juego por bandas', direct: 'Juego directo' } as Record<string, string>,
  philosophyHints: {
    balanced: 'Sin puntos fuertes ni débiles.', possession: 'Tener el balón; gana al autobús y al juego directo.', counter: 'Golpear a la contra; ideal como tapado. Gana a la posesión y al gegenpress.',
    gegenpress: 'Recuperar arriba; cansa. Gana a la posesión y al juego por bandas.', bus: 'Defender atrás: menos goles en las dos áreas. Gana a las bandas y a la contra.',
    wings: 'Necesita extremos rápidos. Gana al juego directo y al autobús.', direct: 'Necesita un delantero fuerte o rápido. Gana al gegenpress y a la contra.',
  } as Record<string, string>,
  mastery: 'Dominio',
  rolesT: 'Roles',
  fullbackT: 'Laterales',
  fullbacks: ['Clásicos', 'Doblando', 'Por dentro'],
  strikerT: 'Delantero',
  strikers: ['Rematador', 'Referencia', 'Falso 9', 'Presionante'],
  trapT: 'Trampa de presión',
  traps: ['Ninguna', 'Bandas', 'Centro', 'Carriles interiores'],
  adviceT: 'Consejos del segundo',
  tips: {
    scoutFirst: () => 'Ójealos primero para ver cómo juegan.',
    mismatch: (a: string, b: string) => `Su ${a.toLowerCase()} gana a nuestro planteamiento. Prueba ${b.toLowerCase()}.`,
    edge: (a: string) => `Nuestra filosofía gana a su ${a.toLowerCase()}. Sigue así.`,
    lowMastery: (n: number) => `La plantilla solo domina esta filosofía al ${n}%. Rinde más con partidos.`,
    tired: (n: number) => (n === 1 ? '1 titular está cansado. Rota o baja la presión.' : `${n} titulares están cansados. Rota o baja la presión.`),
    outOfPos: (n: number) => (n === 1 ? '1 jugador fuera de posición.' : `${n} jugadores fuera de posición.`),
    underdog: () => 'Somos los tapados: una mentalidad más defensiva o el contraataque pueden ayudar.',
    trap: (s: string) => `Pon una trampa de presión por ${s.toLowerCase()} contra ellos.`,
  },
  scoutT: 'Informe del rival',
  scoutBtn: (m: string) => `Ojear al rival · ${m}`,
  predictedShape: 'Dibujo previsto',
  keyThreats: 'Peligros',
  weakSpots: 'Puntos débiles',
  weakWhy: { slow: 'lento', tired: 'cansado', weak: 'defensa más flojo' } as Record<string, string>,
  counterPlan: 'Plan para contrarrestar',
  applyPlan: 'Usar el plan',
  planApplied: 'Plan aplicado.',
  accuracyT: (n: number) => `Fiabilidad del ojeador ${n}%`,
  pitchT: 'Campo',
  speed: 'Velocidad',
  rankingsT: 'Ranking mundial',
  rankingsSub: (n: number) => `Eres el n.º ${n} del mundo`,
  coachesT: 'Entrenadores',
  clubsT: 'Clubes',
  regions: { world: 'Mundo', country: 'Tu país', europe: 'Europa', africa: 'África', asia: 'Asia y Golfo' } as Record<string, string>,
  pointsT: 'Puntos',
  newsT: 'Periódico',
  newsSub: 'Resultados, fichajes, entrenadores, cantera, récords',
  newsCats: { all: 'Todo', results: 'Resultados', transfers: 'Fichajes', managers: 'Entrenadores', youth: 'Cantera', records: 'Récords', crisis: 'Crisis' } as Record<string, string>,
  noNews: 'Aún no hay noticias.',
  news: {
    thrash: (a: string, b: string, s: string) => [`El ${a} arrasa al ${b} ${s}`, `Un golpe sobre la mesa. El ${b} no tuvo respuesta.`],
    newLeader: (a: string) => [`El ${a}, nuevo líder`, 'Hay nuevo líder en lo alto de la tabla.'],
    goals: (p: string, a: string, n: string) => [`${p} llega a ${n} goles en liga`, `El goleador del ${a} no para.`],
    crisis: (a: string) => [`Crisis en el ${a}`, 'Cinco derrotas seguidas. La presión aprieta.'],
    debut: (p: string, a: string) => [`${p} debuta`, `Un canterano juega su primer partido de liga con el ${a}.`],
    promoted: (p: string, a: string) => [`${p} sube al primer equipo`, `El ${a} asciende a un talento de la cantera.`],
    cupFinal: (a: string, b: string, s: string) => [`El ${a} gana la ${s}`, `Ganó al ${b} en la final.`],
    rumour: (p: string, a: string, b: string, n: string) => [`El ${a} quiere a ${p}`, `El jugador del ${b} está en su lista. Probabilidad: ${n}%.`],
    aiTransfer: (p: string, a: string, b: string, s: string) => [`${p} ficha por el ${b}`, `El ${a} acepta ${s}.`],
    userSign: (p: string, a: string, b: string, s: string) => [`${p} firma por el ${a}`, `Cerrado el acuerdo con el ${b}: ${s}.`],
    userSell: (p: string, a: string, b: string, s: string) => [`${p} se marcha al ${a}`, `El ${b} ingresa ${s}.`],
    appointed: (a: string, s: string) => [`${s}, nuevo entrenador del ${a}`, 'Nuevo entrenador, nuevo comienzo.'],
    sacked: (a: string, s: string) => [`El ${a} despide a ${s}`, 'La directiva ha perdido la paciencia.'],
  } as Record<string, (...x: string[]) => string[]>,
  rumoursT: 'Rumores',
  hijack: 'Adelantarse',
  chance: (n: number) => `${n}% de probabilidad`,
  searchT: 'Buscar',
  more: 'Más',
  followSemba: 'Semba Games',
  followSembaSub: 'Nuestros juegos, noticias y novedades',
  settings: 'Ajustes',
  coachCardT: 'Ficha del entrenador',
  ageT: (n: number) => `${n} años`,
  trophiesT: 'Títulos',
  worldRankT: 'Ranking mundial',
  addPhoto: 'Añadir foto',
  changePhoto: 'Cambiar foto',
  removePhoto: 'Quitar foto',
  photoTooBig: 'La foto está en la ficha, pero el móvil no tenía espacio para guardarla',
  photoBad: 'Ese archivo no es una foto que podamos leer',
  shareT: 'Compartir',
  downloadPng: 'Descargar PNG',
  savedAs: (f: string) => `Guardado como ${f}`,
  shareReport: 'Compartir crónica',
  editorT: 'Editor del mundo',
  editorSub: 'Cambia cualquier club o jugador. No se guarda nada hasta que el mundo pasa la comprobación.',
  editorMoreSub: 'Clubes, jugadores, archivos del mundo',
  worldVersion: (n: number) => (n ? `Mundo v${n}` : 'Mundo original'),
  leagueT: 'Liga',
  shortNameT: 'Nombre corto',
  colorsT: 'Colores',
  addPlayer: 'Añadir jugador',
  editPlayer: 'Editar jugador',
  moveToClub: 'Club',
  newPlayer: { en: 'New Player', ar: 'لعيب جديد' },
  discard: 'Descartar',
  saveChanges: 'Guardar cambios',
  worldSaved: (n: number) => `Mundo v${n} guardado`,
  worldIssues: (n: number) => (n === 1 ? '1 problema que arreglar antes de guardar' : `${n} problemas que arreglar antes de guardar`),
  editorMySquad: 'Tu club necesita al menos 11 jugadores',
  worldFile: 'Archivo del mundo',
  exportWorld: 'Exportar mundo',
  exportWorldSub: 'Un archivo .json que puedes editar o compartir',
  importWorld: 'Importar mundo',
  importWorldSub: 'Mismas ligas y clubes; los jugadores pueden cambiar',
  importWorldBad: { format: 'Eso no es un archivo de mundo de The Gaffer', mismatch: 'Ese mundo tiene otros clubes o ligas', invalid: 'Ese mundo no pasó la comprobación' } as Record<string, string>,
  goalWord: '¡GOL!',
  issueShirt: (p: string, n: number, c: string) => `${p}: el dorsal ${n} ya lo tiene otro en el ${c}`,
  issueFew: (c: string, n: number) => `El ${c} solo tiene ${n} jugadores (hacen falta 11)`,
  quickPick: (s: string) => `Elige el equipo ${s.toLowerCase()} de cualquier liga.`,
  kickOffT: 'Empezar',
  coachNation2: 'Segunda nacionalidad',
  noneT: 'Ninguna',
  editorTabs: ['Clubes', 'Ligas', 'Países'],
  leaguesHint: 'Cambia el nombre de una liga o intercambia clubes entre ligas del mismo país a partir de la próxima temporada.',
  editLeague: 'Editar liga',
  editCountry: 'Editar país',
  swapT: 'Intercambiar clubes entre ligas',
  swapHint: 'Se aplica al acabar la temporada, tras ascensos y descensos.',
  swapBtn: 'Intercambiar la próxima temporada',
  queuedSwaps: 'Intercambios de la próxima temporada',
  swapWhen: 'Al final de esta temporada',
  removeT: 'Quitar',
  issueName: (id: string) => `${id}: hay un nombre vacío`,
  cameraT: 'Cámara del campo',
  radarT: 'Radar del once',
  languageT: 'Idioma',
  matchPrefs: 'Partido',
  defaultSpeed: 'Velocidad del partido',
  openOn: 'El partido en directo se abre en',
  balanceT: 'Realismo',
  balanceSub: 'Se guarda con esta carrera. Cámbialo cuando quieras.',
  balanceRows: { income: 'Ingresos del club', wages: 'Sueldos de jugadores', prices: 'Precios de traspaso', injuries: 'Lesiones', difficulty: 'Rivales', patience: 'La directiva' } as Record<string, string>,
  injuryLv: ['No', 'Menos', 'Normal', 'Más'],
  difficultyLv: ['Más flojos', 'Normal', 'Más fuertes'],
  patienceLv: ['Paciente', 'Normal', 'Exigente'],
  resetBalance: 'Volver a lo normal',
  balanceSaved: 'Realismo guardado',
  aboutT: 'Acerca de',
  versionT: (v: string) => `Versión ${v}`,
  madeBy: 'Hecho por Semba Games en El Cairo.',
  howToSub: 'Lo básico en dos minutos',
  howToBody: [
    ['Tu trabajo', 'Elige un club y firma el contrato. La directiva marca objetivos para la liga y la copa. Cúmplelos y tu reputación crece; fállalos y te pueden despedir.'],
    ['Jornadas', 'Pulsa Jugar el partido para verlo en directo en el campo, o elige resultado rápido. Los días de copa, primero va la eliminatoria. Tras cada jornada llega una semana de entrenamiento.'],
    ['Táctica', 'Elige formación, once, mentalidad, presión y pase. Las filosofías se ganan unas a otras como piedra, papel o tijera, y tu dominio de cada una crece con cada partido. Ojea al rival antes de los partidos grandes.'],
    ['Durante el partido', 'Pausa cuando quieras para hacer cambios (cinco) o cambiar el plan. Da una charla en el descanso. 1X, 2X y 4X cambian la velocidad.'],
    ['La plantilla', 'Vigila la forma física, la moral y las lesiones. Entrena fuerte o descansa, da un enfoque a cada jugador y manda a los lesionados a la enfermería.'],
    ['Fichajes', 'Cada oferta recibe una respuesta clara con el motivo. Renueva los contratos antes de que acaben. Otros clubes también buscan jugadores: fíchalo tú antes para adelantarte a un rumor.'],
    ['Dinero', 'Entran entradas, televisión y patrocinadores; salen sueldos, personal y mantenimiento. Mejora las instalaciones, contrata personal y acaba la temporada sin pérdidas.'],
    ['Copas', 'La copa nacional es eliminatoria desde el principio. Las copas continentales empiezan con grupos de cuatro: los dos primeros pasan a las eliminatorias.'],
    ['Tu carrera', 'Gana experiencia y licencias, haz cursos, consigue hitos y títulos, y sube en el ranking mundial. Te llamarán clubes más grandes.'],
    ['Guardar', 'La carrera se guarda sola tras cada partido y se comprueba al cargarla. Exporta una partida desde Más para tener una copia.'],
  ] as [string, string][],
  privacySub: 'Tus datos se quedan en tu móvil',
  privacyBody: [
    ['Qué guardamos', 'Tu carrera, tus ajustes y la foto del entrenador se guardan solo en este dispositivo, en el almacenamiento de la app. No se envía nada ni a nosotros ni a nadie.'],
    ['Sin cuenta ni rastreo', 'The Gaffer no tiene inicio de sesión, anuncios, analíticas ni rastreadores. El juego principal permanece en tu dispositivo; la app Android solo contacta con Semba Games para comprobar actualizaciones y las futuras funciones online estarán claramente indicadas.'],
    ['Archivos de partida', 'Una partida exportada va donde tú elijas. Importar solo lee el archivo que eliges.'],
    ['Fotos', 'La foto que pones en tu ficha de entrenador se queda en este dispositivo y solo se usa para dibujar la ficha.'],
    ['Borrar tus datos', 'Empieza de cero desde la pantalla de inicio, o borra los datos de la app, y todo desaparece.'],
    ['Contacto', '¿Preguntas? sembagames.app'],
  ] as [string, string][],
  privacyUpdated: 'Última actualización: septiembre de 2026',
  howTo: 'Cómo se juega',
  privacy: 'Privacidad',
};
