// Recruitment copy in Spanish (Spain). Type-checked against lang-recruit.ts.
import type { RStrings } from './lang-recruit';

const P = (n: number, one: string, many: string) => (n === 1 ? one : many);

export const R_ES: RStrings = {
  tabs: ['Objetivos', 'Buscar', 'Negociaciones', 'Operaciones', 'Cesiones', 'Necesidades', 'Ojeadores'],
  stages: ['Necesidades y ojeo', 'Lista y búsqueda', 'Negociaciones', 'Operaciones y cesiones'],
  hero: { need: (pos: string) => `Buscamos ${pos.toLowerCase()}`, none: 'Todo puesto tiene recambio.' },
  kpi: { room: 'Margen para fichar', wageRoom: 'Margen salarial / mes', committed: 'Comprometido' },
  talksBtn: (n: number) => `Negociaciones · ${n}`,

  why: {
    noCover: 'Sin recambio', thin: 'Justos', old: 'Titular de 32+', expiring: 'El titular acaba contrato', loanee: 'El titular está cedido',
    weak: 'Eslabón débil', style: 'No encaja en el estilo', manual: 'Decisión tuya',
  },
  needHead: {
    noCover: (pos: string) => `No hay recambio de ${pos.toLowerCase()}.`,
    thin: (pos: string) => `Una lesión y nos quedamos sin ${pos.toLowerCase()}.`,
    old: (pn: string) => `${pn} no es eterno.`,
    expiring: (pn: string) => `${pn} acaba contrato el verano que viene.`,
    loanee: (pn: string) => `${pn} vuelve a su club en mayo.`,
    weak: (pos: string) => `${pos}: ahí somos más débiles.`,
    style: (pn: string) => `${pn} no encaja en nuestra forma de jugar.`,
    manual: (pos: string) => `Quieres otro ${pos.toLowerCase()}.`,
  },
  needEyebrow: 'Por qué buscamos',
  board: 'Los huecos del plan', boardSub: (f: string) => `Plan A · ${f}. Cambia el plan y cambian los huecos.`,
  legend: { red: 'Sin recambio', amber: 'Ojo', ok: 'Cubierto' },
  depth: (d: number, want: number) => `${d} de ${want}`,
  starter: 'Titular',
  picksBtn: 'Propuestas del ojeador', assignBtn: 'Mandar un ojeador', pin: 'Añadir necesidad', pinned: 'Decisión tuya', unpin: 'Quitarla',
  noNeeds: 'Todos los puestos del plan tienen recambio. Busca calidad, no cantidad.',
  addNeed: 'Añade una necesidad tuya',

  scout: {
    pick: (pn: string, k: number) => `${pn} es el que buscamos. Lo conocemos al ${k}%.`,
    unsure: (pn: string, k: number) => `${pn} podría ser, pero solo lo conocemos al ${k}%. Mándame a verlo antes de gastar a ciegas.`,
    none: 'Aún no encaja nadie. Mándame a una liga y dame unas semanas.',
    title: 'Jefe de ojeadores',
  },
  picks: 'Propuestas del ojeador para tus necesidades',
  whyFits: (pos: string, natural: boolean, age: number, k: number) => `${natural ? 'Cubre' : 'Puede cubrir'} ${pos.toLowerCase()} en el plan A · ${age} años · conocido al ${k}%`,
  shortlist: 'Tu lista',
  emptyList: 'La lista está vacía. Marca jugadores en Buscar y los ojeadores empiezan a seguirlos.',

  ability: 'Nivel', ceiling: 'Techo', fit: 'Encaje', known: 'conocido',
  asking: 'Piden', free: 'Libre', wants: 'Quiere / mes', interest: 'Interés',
  interestL: ['Sueño', 'Ilusionado', 'Abierto', 'Frío', 'Paso atrás'],
  prioLabel: 'Lo que más le importa', prio: { money: 'El dinero', role: 'Jugar', ambition: 'La ambición', security: 'La estabilidad' },
  unsettled: 'Descontento en su club',
  unknown: '?',
  offer: 'Hacer oferta', inTalks: 'Negociando', report: 'Informe', star: 'A la lista', unstar: 'Fuera de la lista', loan: 'Cesión',
  compare: { eyebrow: 'Lo que sabemos · nivel', head: 'Cuanto más ancha la barra, menos sabemos.', key: 'Rango estimado', ref: (pn: string, n: number) => `${pn} hoy (${n})` },

  talks: 'Operaciones en marcha', noTalks: 'No hay negociaciones. Haz una oferta desde tus objetivos.', recent: 'Recientes',
  stage: { club: 'Traspaso', terms: 'Contrato', done: 'Firmado', collapsed: 'Caída' },
  status: {
    waiting: (day: string) => `Oferta sobre la mesa · responden el ${day}`,
    counter: (v: string) => `Piden ${v}`,
    rejected: 'Han dicho que no',
    rival: (club: string, v: string) => `${club} ofrece ${v}`,
    terms: (n: number, m: number) => `Agente · ronda ${n} de ${m}`,
    due: (day: string) => `Respuesta antes del ${day}`,
  },
  ends: {
    signed: 'Firmado', walked: 'El agente se levantó', frozen: 'Negociación congelada', hijacked: 'Nos lo han quitado', window: 'Se cerró el mercado',
    withdrawn: 'Te retiraste', gone: 'Se fue a otro club', rejected: 'Rechazada',
  },

  room: {
    title: (pn: string) => `Negociación · ${pn}`,
    stages: ['Traspaso', 'Contrato', 'Firmado'],
    clubHead: 'Traspaso', termsHead: 'Contrato', doneHead: 'Firmado', offHead: 'Negociación rota',
    withClub: (club: string, n: number, m: number) => `Con el ${club} · oferta ${n} de ${m}`,
    withAgent: (name: string, style: string, n: number, m: number) => `Con su agente, ${name} (${style}) · ronda ${n} de ${m}`,
    styles: { fair: 'razonable', hardball: 'duro', greedy: 'codicioso' },
    agreed: (club: string, fee: string) => `Traspaso acordado con el ${club} · ${fee}`,
    onTable: 'Oferta sobre la mesa', freeAgent: 'Jugador libre · sin traspaso',
    table: 'Cómo va la mesa',
    you: (n: number) => `Tú · ${n}`,
    them: (who: string) => who,
    board: (club: string) => `Directiva del ${club}`,
    bidLine: (fee: string, seasons: number, sellOn: number) => `${fee}${seasons > 1 ? ` en ${seasons} temporadas` : ' al contado'}${sellOn ? ` + ${sellOn}% de una futura venta` : ''}.`,
    clubSays: {
      accept: 'Hecho. Habla con su agente.',
      counter: (v: string) => `No llega. ${v} y es vuestro.`,
      reject: 'A ese precio no se vende.',
      insult: '¿Es una broma? Vuelve con una oferta seria.',
      rival: (club: string, v: string) => `El ${club} ofrece ${v}. Superadlo antes de la próxima jornada.`,
    },
    agentSays: {
      open: 'Esto es lo que pide.', close: 'Cerca. Muy cerca.', notThere: 'Todavía no.', insulted: 'Estás ofendiendo a mi cliente.',
      walk: 'Se acabó. Escuchará otras ofertas.', accept: 'Trato hecho.',
    },
    ourLine: 'Nuestra oferta.',
    chip: {
      wage: (v: string) => `${v}/mes`, years: (n: number) => `${n} ${P(n, 'año', 'años')}`,
      signOn: (v: string) => `${v} de prima de fichaje`, release: (v: string) => `cláusula de ${v}`, noRelease: 'Sin cláusula',
      bonus: (v: string) => `${v} por partido`,
    },
    roles: { star: 'Estrella', regular: 'Titular', rotation: 'Rotación', prospect: 'Promesa' },
    patienceClub: 'Paciencia de la directiva', patienceAgent: 'Paciencia del agente',
    yourBid: (n: number) => `Oferta ${n} · la tuya`, yourOffer: (n: number) => `Ronda ${n} · tu oferta`,
    fee: 'Traspaso', feeZone: 'En verde lo aceptarían', pay: 'Pago', payOpts: ['Todo ya', 'En 2 temporadas', 'En 3 temporadas'],
    upfront: 'Al contado', upOpts: ['40%', '60%', '80%'], sellOn: 'Futura venta', sellOpts: ['No', '10%', '15%', '20%'],
    sellOnWhy: 'Un porcentaje de lo que saquemos al venderlo. Para ellos vale menos que el efectivo.',
    instWhy: (v: string) => `${v} la temporada siguiente. Resta margen ya, entero.`,
    wage: 'Sueldo mensual', wageZone: 'En verde probablemente firma', years: 'Duración', role: 'Papel', roleWhy: 'El papel que le prometas te lo va a exigir.',
    clauses: 'Cláusulas', clausesSub: 'Lo que te cuesta cada una',
    signOn: 'Prima de fichaje', signOnWhy: (v: string) => `${v} ahora. Dinero en el bolsillo desde el primer día.`,
    release: 'Cláusula de rescisión', releaseWhy: (v: string) => `Cualquier club que pague ${v} se lo lleva, y no podemos impedirlo.`, releaseOff: 'Sin cláusula: es nuestro hasta que lo vendamos.',
    bonus: 'Prima por partido', bonusWhy: (v: string) => `${v} por cada partido de liga que juegue.`,
    his: 'Lo que pide',
    verdict: 'Si lo mandas',
    clubV: { accept: 'Lo aceptarán', counter: 'Habrá contraoferta', reject: 'Dirán que no', insult: 'Se lo tomarán como un insulto' },
    clubWhy: (e: string) => `Para ellos vale ${e}: los plazos cuentan menos y la futura venta, menos aún.`,
    chance: (p: number) => (p >= 0.75 ? 'Probablemente firma' : p >= 0.5 ? 'Puede salir o no' : p > 0 ? 'Difícil' : 'Así no firma'),
    chanceWhy: (known: boolean) => (known ? 'Sabemos qué le importa.' : 'Aún no sabemos qué le importa. Es nuestra mejor lectura.'),
    roomAfter: 'Margen después', wageRoomAfter: 'Margen salarial después', later: 'Comprometido, próximas temporadas', agentFee: 'Comisión del agente', bill: 'Masa salarial', perYear: '/año',
    send: (n: number) => `Enviar ronda ${n}`, sendBid: 'Enviar oferta', walk: 'Levantarse', meet: 'Darle lo que pide', takeCounter: 'Aceptar su contraoferta',
    payCounter: (v: string) => `Pagar ${v}`, top: (v: string) => `Superarla: ${v}`, waiting: (day: string) => `Responden el ${day}`,
    back: 'Fichajes',
    signed: (pn: string) => `${pn} es nuestro.`,
    frozenFor: (n: number) => `Negociación congelada ${n} ${P(n, 'jornada', 'jornadas')}.`,
    adv: {
      clubLow: 'Por debajo de su precio, como mucho, contraoferta. Tres ofertas y dejan de cogernos el teléfono.',
      clubOk: 'Es su precio. Nos darán la mano.',
      deadline: 'Último día de mercado: responden al momento.',
      termsHigh: (v: string) => `No pases de ${v}. Marca el listón de todas las renovaciones.`,
      termsOk: 'Justo para las dos partes. Yo lo mandaría.',
      termsLow: 'Eso no lo acepta. Muévete en lo que le importa.',
      waiting: 'Solo queda esperar su respuesta.',
    },
    agentFree: 'No hay traspaso: es libre. El agente sí cobra su comisión.',
  },

  bidsFor: 'Ofertas por tus jugadores',
  aiWhy: { unhappy: 'No está contento', expiring: 'Le queda poco contrato', request: 'Ha pedido salir', need: 'Lo necesitan' },
  committed: 'Lo que debemos', commitRow: (season: string, club: string) => `${season} · al ${club}`, noCommit: 'No debemos nada. Todo pagado.',
  stories: 'Las historias',
  loans: {
    in: 'Cedido a nosotros', out: 'Cedido fuera', none: 'Nadie cedido.',
    share: (p: number) => `Pagamos el ${p}% de su sueldo`, shareOut: (p: number) => `Pagan el ${p}% de su sueldo`,
    minutes: { starter: 'Cláusula de titular', rotation: 'Cláusula de rotación', none: 'Sin cláusula de minutos' },
    progress: (apps: number, need: number, days: number) => `${apps} partidos en ${days} jornadas · necesita ${need}`,
    broken: 'Cláusula incumplida', trust: (n: number) => `Su confianza en nosotros ${n}`, recall: 'Repescarlo',
    ask: (pn: string) => `Cesión de ${pn}`, shareQ: 'Parte del sueldo que pagamos', minutesQ: 'Minutos que prometemos', send: 'Pedirlo',
    needs: (s: string) => `Lo cederían si pagamos el ${s} de su sueldo.`, noWay: 'No lo cederán con nada que podamos ofrecer.',
    outTitle: (pn: string) => `Ceder a ${pn}`, where: 'Adónde', theyPay: 'Parte del sueldo que pagan', outSend: 'Mandarlo',
    fee: (v: string) => `Coste de la cesión ${v}`, takes: 'Lo aceptarían', wontTake: 'No aceptan esas condiciones',
  },

  scouts: {
    head: 'Dónde están los ojeadores', slots: (n: number, max: number) => `${n} de ${max} ${P(max, 'misión', 'misiones')} en marcha`,
    slotsWhy: 'Las instalaciones de ojeo fijan cuántas misiones puedes tener.',
    scope: { league: 'Liga', country: 'País', world: 'Todo el mundo' },
    pos: 'Posición', any: 'Cualquier posición', send: 'Mandarlo', remove: 'Traerlo de vuelta',
    coverage: (n: number, k: number) => `${n} jugadores · ${k} bien conocidos`,
    rate: (v: number, t: number) => `+${v} de conocimiento por jornada · +${t} para los de la lista`,
    empty: 'No hay ojeadores fuera. Solo sabemos más por la lista y por los partidos que jugamos.',
    worldPos: 'Todo el mundo necesita una posición.', full: 'Todos los ojeadores están fuera. Trae a uno primero.',
    newOne: 'Nueva misión',
    quote: (n: number, k: number) => `${n} nombres ahí fuera, y por ${k} pondría la mano en el fuego. Dame tiempo.`,
    best: 'A quién conocemos mejor', none: 'Aún no conocemos bien a nadie fuera de la plantilla.',
  },

  tag: { bidAnswer: 'Respuesta', agent: 'Agente', rival: 'Oferta rival', loanClause: 'Cesión', recall: 'Cesión' },
  dec: {
    rival: (pn: string, club: string, v: string, day: string) => `El ${club} ofrece ${v} por ${pn}. Supéralo antes del ${day}.`,
    counter: (pn: string, club: string, v: string) => `El ${club} pide ${v} por ${pn}.`,
    rejected: (pn: string, club: string, v: string) => `El ${club} rechaza ${v} por ${pn}.`,
    insulted: (pn: string, club: string) => `El ${club} se ha reído de nuestra oferta por ${pn}.`,
    agreed: (pn: string, day: string) => `Traspaso acordado por ${pn}. Su agente quiere respuesta antes del ${day}.`,
    agentDue: (pn: string, day: string) => `El agente de ${pn} quiere respuesta antes del ${day}.`,
    clauseRisk: (pn: string, club: string, n: number) => `${pn} necesita ${n} ${P(n, 'partido', 'partidos')} más para contentar al ${club}.`,
    recallQ: (pn: string, club: string) => `El ${club} no pone a ${pn}. ¿Lo repescamos?`,
    rivalBid: (pn: string, club: string, v: string, why: string) => `El ${club} ofrece ${v} por ${pn}.${why ? ` ${why}.` : ''}`,
    askBid: (pn: string, v: string) => `¿Ofrecemos ${v} por ${pn}?`,
  },
  adv: {
    top: (v: string) => `Ve a ${v}. No encontraremos otro igual en este mercado.`,
    letGo: 'Déjalo ir. No vamos a montar una subasta.',
    pay: (v: string) => `${v} es caro pero justo. Págalo.`,
    walk: (v: string) => `${v} es demasiado. Levántate.`,
    rejected: (n: number) => (n > 0 ? `Todavía no se mueven. ${n} ${P(n, 'intento', 'intentos')} más y dejan de contestar.` : 'Ya no contestan.'),
    meet: (v: string) => `Dale ${v} al mes y queda cerrado hoy.`,
    counter: 'La contraoferta del agente nos sirve. Acéptala.',
    talk: 'Hay margen para bajarle. Abre la negociación.',
    clause: (club: string) => `Prometimos al ${club} que jugaría. Si no, no nos ceden a nadie más.`,
    recall: 'Se está pudriendo en su banquillo. Tráelo a casa.',
    bid: (v: string) => `El que mejor encaja en la necesidad principal y podemos pagar. ${v} es una buena primera oferta.`,
  },
  choice: {
    top: (v: string) => `Superarla: ${v}`, letGo: 'Dejarlo ir', pay: (v: string) => `Pagar ${v}`, improve: 'Mejorar la oferta', walk: 'Levantarse',
    meet: 'Darle lo que pide', takeCounter: 'Aceptar su contraoferta', talk: 'Abrir la negociación', playHim: 'Ponerlo', riskIt: 'Arriesgar', recall: 'Repescarlo', leave: 'Dejarlo allí',
  },
  fx: {
    room: (v: string) => `Quedan ${v}`, fees: (v: string) => `Comisiones ${v}`, patience: (n: number) => `${n} ${P(n, 'intento', 'intentos')} más`,
    noDeal: 'Sin operación', rounds: (n: number) => `${n} ${P(n, 'ronda', 'rondas')} de paciencia`, rivalGets: 'Se va con el rival',
    parentHappy: 'Su club, contento', parentAngry: 'Dejan de cedernos', back: 'Vuelve a la plantilla', benchWarm: 'Otro mes en su banquillo',
  },

  news: {
    bid: (pn: string, club: string, club2: string, v: string) => [`El ${club} ofrece ${v} por ${pn}`, `El ${club2} se lo piensa.`],
    agreed: (pn: string, club: string, club2: string, v: string) => [`El ${club} cierra el traspaso de ${pn}`, `${v} al ${club2}. Falta el contrato.`],
    done: (pn: string, club: string, club2: string, v: string) => [`${pn} ficha por el ${club}`, v ? `Llega del ${club2} por ${v}.` : 'Llega libre.'],
    walk: (pn: string, club: string) => [`Se rompe la negociación por ${pn}`, `Su agente dejó plantado al ${club}.`],
    hijack: (pn: string, club: string, club2: string, v: string) => [`El ${club} se adelanta y se lleva a ${pn}`, `${v} al ${club2}. Alguien fue demasiado lento.`],
    aiBid: (pn: string, club: string, v: string, why: string) => [`El ${club} ofrece ${v} por ${pn}`, why],
    aiWhy: { unhappy: 'Lleva semanas sin sonreír.', expiring: 'Se le acaba el contrato.', request: 'Ha pedido salir.', need: 'Necesitan un jugador como él.' },
    release: (pn: string, club: string, club2: string, v: string) => [`El ${club} paga la cláusula de ${pn}`, `${v}, y el ${club2} no puede negarse.`],
    loanIn: (pn: string, club: string, club2: string) => [`${pn} llega cedido al ${club}`, `Desde el ${club2}, por una temporada.`],
  },
  msg: {
    answer: (pn: string, club: string, s: string, v: string) => [
      s === 'accept' ? `El ${club} acepta nuestra oferta por ${pn}` : s === 'counter' ? `Contraoferta del ${club} por ${pn}` : `El ${club} rechaza nuestra oferta por ${pn}`,
      s === 'accept' ? `${v} acordados. Su agente espera.` : s === 'counter' ? `Piden ${v}.` : s === 'insult' ? 'Se lo tomaron como un insulto.' : 'Mejórala o retírate.',
    ],
    hijack: (pn: string, club: string, v: string) => [`${pn} ficha por el ${club}`, `Pagaron ${v} mientras nuestra oferta esperaba.`],
    rival: (pn: string, club: string, v: string) => [`El ${club} entra por ${pn}`, `${v} sobre la mesa. Supéralo antes de la próxima jornada.`],
    release: (pn: string, club: string, v: string) => [`El ${club} paga la cláusula de ${pn}`, `${v}. Se ha ido.`],
    instalments: (v: string, n: number) => [`Plazos pagados: ${v}`, `${n} ${P(n, 'pago vencía', 'pagos vencían')} con la nueva temporada.`],
    picks: (pn: string, n: number, pos: string) => [`Informe del ojeador: ${pn}`, `Primera opción de ${pos.toLowerCase()} · ${n} ${P(n, 'nombre', 'nombres')} en la lista.`],
    loanReport: (pn: string, club: string, apps: number, goals: number, days: number) => [`Informe de cesión: ${pn}`, `${apps} partidos en ${days} jornadas en el ${club}, ${goals} ${P(goals, 'gol', 'goles')}.`],
    brokenIn: (pn: string, club: string) => [`El ${club}, furioso por ${pn}`, 'Prometimos minutos y no se los dimos. Se lo llevarán en el mercado.'],
    brokenOut: (pn: string, club: string) => [`El ${club} no pone a ${pn}`, 'Han incumplido la cláusula de minutos. Podemos repescarlo en el mercado.'],
    takenBack: (pn: string, club: string) => [`El ${club} se lleva de vuelta a ${pn}`, 'Se acabó la cesión.'],
    sellOn: (pn: string, club: string, v: string) => [`Porcentaje de venta pagado por ${pn}`, `${v} al ${club}, como se pactó al ficharlo.`],
  },
  log: {
    rcbid: (pn: string, v: string) => `Ofreció ${v} por ${pn}.`, rcPay: (pn: string, v: string) => `Pagó lo que pedían por ${pn}: ${v}.`,
    rcTop: (pn: string, v: string) => `Superó la oferta rival por ${pn}: ${v}.`, rcSigned: (pn: string, v: string) => `Cerró el contrato de ${pn}: ${v} al mes.`,
    rcWalk: (pn: string) => `Se retiró de la operación de ${pn}.`,
  },
  steps: {
    bid: 'Oferta', agreed: 'Traspaso acordado', counter: 'Contraoferta', reject: 'Rechazo', insult: 'Ofendidos', frozen: 'Congelada', rival: 'Oferta rival', topped: 'Superamos al rival',
    hijacked: 'Nos lo quitan', signed: 'Firmado', walked: 'El agente se va', window: 'Mercado cerrado', withdrawn: 'Nos retiramos', gone: 'Se fue a otro club', talks: 'Empieza la negociación',
    loanIn: 'Llega cedido', loanOut: 'Sale cedido', brokenIn: 'Cláusula incumplida', brokenOut: 'Ellos la incumplen', recalled: 'Repescado', takenBack: 'Se lo llevan',
    release: 'Cláusula pagada', bid_need: 'Oferta: lo necesitan', bid_unhappy: 'Oferta: no está contento', bid_expiring: 'Oferta: acaba contrato', bid_request: 'Oferta: pidió salir',
  },
  ledger: { agentFees: 'Comisiones de agentes', signOn: 'Primas de fichaje', instalments: 'Plazos de traspasos', loanWages: 'Sueldos de cesiones', bonuses: 'Primas por partido', sellOn: 'Porcentajes de venta' },
  no: {
    frozen: 'La negociación está congelada.', waiting: 'Nuestra oferta sigue sobre la mesa.', agreed: 'El traspaso está acordado. Habla con su agente.',
    trust: 'No nos ceden a nadie después de lo de la última vez.', loanTerms: 'Quieren que paguemos más sueldo, o una promesa de minutos.', minutes: 'Allí no tendría esos minutos.',
    buyerBudget: 'No pueden pagarlo.', release: 'La cláusula no puede estar por debajo de su valor.', slots: 'Todos los ojeadores están fuera.', scope: 'Elige adónde mandarlo.',
    done: 'Ya está cubierto.', noClause: 'No hay cláusula de minutos que usar.', loaned: 'Está cedido.',
  },
  note: {
    bidSent: (pn: string) => `Oferta enviada por ${pn}.`, talks: (pn: string) => `Negociación abierta con el agente de ${pn}.`, agreed: (pn: string) => `Traspaso de ${pn} acordado.`,
    assigned: 'El ojeador va para allá.', recalled: (pn: string) => `${pn} vuelve a casa.`,
    close: 'Cerca. Muy cerca.', notThere: 'Todavía no.', insulted: 'Se ha ofendido.', walk: 'El agente se ha levantado.',
  },
};
