// Copy for V2.5 Recruitment: needs, scouts, targets, the negotiation room, loans, and the Today / news / inbox lines
// recruitment writes. English is the reference; Arabic (Egyptian), Spanish and French are type-checked against it in
// lang-recruit-*.ts. Voice: the dugout and the director's office. No exclamation marks, no app words.

const P = (n: number, one: string, many: string) => (n === 1 ? one : many);

export const R_EN = {
  tabs: ['Targets', 'Search', 'Talks', 'Deals', 'Loans', 'Needs', 'Scouts'],
  stages: ['Needs & scouting', 'Shortlist & search', 'Negotiations', 'Deals & loans'],
  hero: { need: (pos: string): string => `Find a ${pos.toLowerCase()}`, none: 'Every spot has cover.' },
  kpi: { room: 'Spending room', wageRoom: 'Wage room / mo', committed: 'Committed' },
  talksBtn: (n: number): string => `Talks · ${n}`,

  // ---------- needs ----------
  why: {
    noCover: 'No cover', thin: 'Thin', old: 'Starter 32+', expiring: 'Starter’s deal ends', loanee: 'Starter only on loan',
    weak: 'Weak link', style: 'Doesn’t suit our style', manual: 'Your call',
  } as Record<string, string>,
  needHead: {
    noCover: (pos: string): string => `No cover at ${pos.toLowerCase()}.`,
    thin: (pos: string): string => `One knock from trouble at ${pos.toLowerCase()}.`,
    old: (pn: string): string => `${pn} won’t go on for ever.`,
    expiring: (pn: string): string => `${pn}’s deal runs out next summer.`,
    loanee: (pn: string): string => `${pn} goes back to his club in May.`,
    weak: (pos: string): string => `${pos} is where we’re weakest.`,
    style: (pn: string): string => `${pn} doesn’t suit the way we play.`,
    manual: (pos: string): string => `You want another ${pos.toLowerCase()}.`,
  },
  needEyebrow: 'Why this search exists',
  board: 'The plan’s gaps', boardSub: (f: string): string => `Plan A · ${f}. Change the plan and the gaps change with it.`,
  legend: { red: 'No cover', amber: 'Watch it', ok: 'Covered' },
  depth: (d: number, want: number): string => `${d} of ${want} deep`,
  starter: 'Starter',
  picksBtn: 'Scout picks', assignBtn: 'Send a scout', pin: 'Add a need', pinned: 'Your call', unpin: 'Drop it',
  noNeeds: 'Every slot in the plan has cover. Shop for quality, not bodies.',
  addNeed: 'Add a need of your own',

  // ---------- the chief scout ----------
  scout: {
    pick: (pn: string, k: number): string => `${pn} is the one. We know him ${k}% of the way.`,
    unsure: (pn: string, k: number): string => `${pn} might be the one, but we only know him ${k}% of the way. Give me an assignment before you spend on a guess.`,
    none: 'Nobody fits yet. Point me at a league and give me a few weeks.',
    title: 'Chief scout',
  },
  picks: 'Scout picks for your needs',
  whyFits: (pos: string, natural: boolean, age: number, k: number): string => `${natural ? 'Covers' : 'Can cover'} ${pos.toLowerCase()} in Plan A · ${age} · known ${k}%`,
  shortlist: 'Your shortlist',
  emptyList: 'Nobody on the shortlist. Star players in Search and the scouts start watching.',

  // ---------- target cards ----------
  ability: 'Ability', ceiling: 'Ceiling', fit: 'Style fit', known: 'known',
  asking: 'Asking', free: 'Free agent', wants: 'Wants / mo', interest: 'Interest',
  interestL: ['Dream move', 'Keen', 'Open', 'Cool', 'Step down'],
  prioLabel: 'Cares most about', prio: { money: 'Money', role: 'Playing time', ambition: 'Ambition', security: 'Security' } as Record<string, string>,
  unsettled: 'Unsettled at his club',
  unknown: '?',
  offer: 'Make an offer', inTalks: 'In talks', report: 'Report', star: 'Shortlist', unstar: 'Off the list', loan: 'Loan',
  compare: { eyebrow: 'What we know · ability', head: 'The wider the bar, the less we know.', key: 'Scouted range', ref: (pn: string, n: number): string => `${pn} today (${n})` },

  // ---------- talks list ----------
  talks: 'Deals in progress', noTalks: 'No talks on. Make an offer from your targets.', recent: 'Recently',
  stage: { club: 'Club fee', terms: 'Personal terms', done: 'Signed', collapsed: 'Off' } as Record<string, string>,
  status: {
    waiting: (day: string): string => `Bid on the table · they answer ${day}`,
    counter: (v: string): string => `They want ${v}`,
    rejected: 'They said no',
    rival: (club: string, v: string): string => `${club} bid ${v}`,
    terms: (n: number, m: number): string => `Agent · round ${n} of ${m}`,
    due: (day: string): string => `Answer by ${day}`,
  },
  ends: {
    signed: 'Signed', walked: 'The agent walked', frozen: 'Talks frozen', hijacked: 'Hijacked', window: 'The window shut',
    withdrawn: 'You pulled out', gone: 'He went elsewhere', rejected: 'Refused',
  } as Record<string, string>,

  // ---------- the negotiation room ----------
  room: {
    title: (pn: string): string => `Talks · ${pn}`,
    stages: ['Club fee', 'Personal terms', 'Signed'],
    clubHead: 'Club fee', termsHead: 'Personal terms', doneHead: 'Signed', offHead: 'Talks off',
    withClub: (club: string, n: number, m: number): string => `With ${club} · bid ${n} of ${m}`,
    withAgent: (name: string, style: string, n: number, m: number): string => `With his agent, ${name} (${style}) · round ${n} of ${m}`,
    styles: { fair: 'fair', hardball: 'hardball', greedy: 'greedy' } as Record<string, string>,
    agreed: (club: string, fee: string): string => `Fee agreed with ${club} · ${fee}`,
    onTable: 'Bid on the table', freeAgent: 'Free agent · no fee to pay',
    table: 'The table so far',
    you: (n: number): string => `You · ${n}`,
    them: (who: string): string => who,
    board: (club: string): string => `${club} board`,
    bidLine: (fee: string, seasons: number, sellOn: number): string => `${fee}${seasons > 1 ? ` over ${seasons} seasons` : ' up front'}${sellOn ? ` + ${sellOn}% sell-on` : ''}.`,
    clubSays: {
      accept: 'Done. Talk to his agent.',
      counter: (v: string): string => `Not enough. ${v} and he’s yours.`,
      reject: 'He’s not for sale at that price.',
      insult: 'Is that a joke? Come back with a serious offer.',
      rival: (club: string, v: string): string => `${club} have offered ${v}. Beat it by the next matchday.`,
    },
    agentSays: {
      open: 'Here’s what it takes.', close: 'Close. Very close.', notThere: 'We’re not there yet.', insulted: 'You’re insulting my client.',
      walk: 'We’re done here. He’ll hear other offers.', accept: 'We have a deal.',
    } as Record<string, string>,
    ourLine: 'Here’s our offer.',
    chip: {
      wage: (v: string): string => `${v}/mo`, years: (n: number): string => `${n} ${P(n, 'yr', 'yrs')}`,
      signOn: (v: string): string => `${v} signing-on`, release: (v: string): string => `${v} release clause`, noRelease: 'No release clause',
      bonus: (v: string): string => `${v} a game`,
    },
    roles: { star: 'Star', regular: 'Starter', rotation: 'Rotation', prospect: 'Prospect' } as Record<string, string>,
    patienceClub: 'Board’s patience', patienceAgent: 'Agent’s patience',
    yourBid: (n: number): string => `Bid ${n} · your offer`, yourOffer: (n: number): string => `Round ${n} · your offer`,
    fee: 'Fee', feeZone: 'They’d likely take it in the green', pay: 'Payment', payOpts: ['All now', 'Over 2 seasons', 'Over 3 seasons'],
    upfront: 'Up front', upOpts: ['40%', '60%', '80%'], sellOn: 'Sell-on', sellOpts: ['None', '10%', '15%', '20%'],
    sellOnWhy: 'A cut of any fee we sell him for later. Worth less to them than cash.',
    instWhy: (v: string): string => `${v} a season later. It lowers the spending room now, all of it.`,
    wage: 'Monthly wage', wageZone: 'He’d likely sign in the green', years: 'Length', role: 'Role', roleWhy: 'A role you promise is a role he’ll hold you to.',
    clauses: 'Clauses', clausesSub: 'What each one costs you',
    signOn: 'Signing-on fee', signOnWhy: (v: string): string => `${v} now. Money in his pocket on day one.`,
    release: 'Release clause', releaseWhy: (v: string): string => `Any club paying ${v} can take him, and we can’t stop it.`, releaseOff: 'Off: he stays ours until we sell.',
    bonus: 'Appearance bonus', bonusWhy: (v: string): string => `${v} for every league game he plays.`,
    his: 'His ask',
    verdict: 'If you send this',
    clubV: { accept: 'They’ll accept', counter: 'Expect a counter', reject: 'They’ll say no', insult: 'They’ll take it as an insult' } as Record<string, string>,
    clubWhy: (e: string): string => `Worth ${e} to them: instalments count for less, a sell-on less again.`,
    chance: (p: number): string => (p >= 0.75 ? 'He’ll probably sign' : p >= 0.5 ? 'Could go either way' : p > 0 ? 'A long shot' : 'He won’t sign this'),
    chanceWhy: (known: boolean): string => (known ? 'We know what he cares about.' : 'We don’t know his priority yet. This is our best read.'),
    roomAfter: 'Spending room after', wageRoomAfter: 'Wage room after', later: 'Committed, later seasons', agentFee: 'Agent fee', bill: 'Wage bill', perYear: '/yr',
    send: (n: number): string => `Send round ${n}`, sendBid: 'Send the bid', walk: 'Walk away', meet: 'Meet his demands', takeCounter: 'Accept his counter',
    payCounter: (v: string): string => `Pay ${v}`, top: (v: string): string => `Top it: ${v}`, waiting: (day: string): string => `They answer ${day}`,
    back: 'Transfers',
    signed: (pn: string): string => `${pn} is ours.`,
    frozenFor: (n: number): string => `Talks frozen for ${n} ${P(n, 'matchday', 'matchdays')}.`,
    adv: {
      clubLow: 'Under their price you get a counter at best. Three bids and they stop picking up.',
      clubOk: 'That’s their price. They’ll shake on it.',
      deadline: 'Deadline day: they answer on the spot.',
      termsHigh: (v: string): string => `Don’t go past ${v}. It sets the bar for every renewal after.`,
      termsOk: 'Fair for both sides. I’d send it.',
      termsLow: 'He won’t take that. Move on the thing he cares about.',
      waiting: 'Nothing to do but wait for their answer.',
    },
    agentFree: 'No fee: he’s a free agent. The agent still takes his cut.',
  },

  // ---------- deals, loans ----------
  bidsFor: 'Bids for your players',
  aiWhy: { unhappy: 'He’s unhappy', expiring: 'His deal is running down', request: 'He asked to leave', need: 'They need him' } as Record<string, string>,
  committed: 'Money we owe', commitRow: (season: string, club: string): string => `${season} · to ${club}`, noCommit: 'Nothing owed. Every deal paid in full.',
  stories: 'The stories',
  loans: {
    in: 'Loaned in', out: 'Loaned out', none: 'Nobody on loan.',
    share: (p: number): string => `We pay ${p}% of his wage`, shareOut: (p: number): string => `They pay ${p}% of his wage`,
    minutes: { starter: 'Starter clause', rotation: 'Rotation clause', none: 'No minutes clause' } as Record<string, string>,
    progress: (apps: number, need: number, days: number): string => `${apps} games in ${days} matchdays · needs ${need}`,
    broken: 'Clause broken', trust: (n: number): string => `Their trust in us ${n}`, recall: 'Recall him',
    ask: (pn: string): string => `Loan for ${pn}`, shareQ: 'Wage share we pay', minutesQ: 'Minutes we promise', send: 'Ask for him',
    needs: (s: string): string => `They’d lend him at ${s} of his wage.`, noWay: 'They won’t lend him on any terms we can offer.',
    outTitle: (pn: string): string => `Loan ${pn} out`, where: 'Where', theyPay: 'Wage share they pay', outSend: 'Send him',
    fee: (v: string): string => `Loan fee ${v}`, takes: 'Would take him', wontTake: 'Won’t take those terms',
  },

  // ---------- scouts ----------
  scouts: {
    head: 'Where the scouts are', slots: (n: number, max: number): string => `${n} of ${max} ${P(max, 'assignment', 'assignments')} out`,
    slotsWhy: 'The scouting facility sets how many assignments you can run.',
    scope: { league: 'League', country: 'Country', world: 'Worldwide' } as Record<string, string>,
    pos: 'Position', any: 'Any position', send: 'Send him', remove: 'Bring him back',
    coverage: (n: number, k: number): string => `${n} players · ${k} known well`,
    rate: (v: number, t: number): string => `+${v} knowledge a matchday · +${t} for shortlisted names`,
    empty: 'No scouts out. Knowledge only grows from the shortlist and the matches we play.',
    worldPos: 'Worldwide needs a position.', full: 'Every scout is out. Bring one back first.',
    newOne: 'New assignment',
    quote: (n: number, k: number): string => `${n} names out there, ${k} of them I’d put my name to. Give me time.`,
    best: 'Who we know best', none: 'Nobody known well outside our own squad yet.',
  },

  // ---------- Today ----------
  tag: { bidAnswer: 'Bid answered', agent: 'Agent', rival: 'Rival bid', loanClause: 'Loan', recall: 'Loan' } as Record<string, string>,
  dec: {
    rival: (pn: string, club: string, v: string, day: string): string => `${club} bid ${v} for ${pn}. Beat it by ${day}.`,
    counter: (pn: string, club: string, v: string): string => `${club} want ${v} for ${pn}.`,
    rejected: (pn: string, club: string, v: string): string => `${club} turn down ${v} for ${pn}.`,
    insulted: (pn: string, club: string): string => `${club} laughed at our bid for ${pn}.`,
    agreed: (pn: string, day: string): string => `Fee agreed for ${pn}. His agent wants an answer by ${day}.`,
    agentDue: (pn: string, day: string): string => `${pn}’s agent wants an answer by ${day}.`,
    clauseRisk: (pn: string, club: string, n: number): string => `${pn} needs ${n} more ${P(n, 'game', 'games')} to keep ${club} happy.`,
    recallQ: (pn: string, club: string): string => `${club} aren’t playing ${pn}. Bring him back?`,
    rivalBid: (pn: string, club: string, v: string, why: string): string => `${club} bid ${v} for ${pn}.${why ? ` ${why}.` : ''}`,
    askBid: (pn: string, v: string): string => `Bid ${v} for ${pn}?`,
  },
  adv: {
    top: (v: string): string => `Go to ${v}. We won’t find another like him this window.`,
    letGo: 'Let him go. We’re not starting an auction.',
    pay: (v: string): string => `${v} is steep but fair. Pay it.`,
    walk: (v: string): string => `${v} is too much. Walk.`,
    rejected: (n: number): string => (n > 0 ? `They’re not budging yet. ${n} more ${P(n, 'try', 'tries')} before they stop picking up.` : 'They’ve stopped picking up.'),
    meet: (v: string): string => `Give him ${v} a month and it’s done today.`,
    counter: 'His agent’s counter works for us. Take it.',
    talk: 'There’s room to talk him down. Open the talks.',
    clause: (club: string): string => `We promised ${club} he’d play. Break it and they won’t lend to us again.`,
    recall: 'He’s rotting on their bench. Bring him home.',
    bid: (v: string): string => `Best fit for our top need that we can afford. ${v} is a fair opening.`,
  },
  choice: {
    top: (v: string): string => `Top it: ${v}`, letGo: 'Let him go', pay: (v: string): string => `Pay ${v}`, improve: 'Improve the bid', walk: 'Walk away',
    meet: 'Meet his demands', takeCounter: 'Accept his counter', talk: 'Open the talks', playHim: 'Pick him', riskIt: 'Risk it', recall: 'Recall him', leave: 'Leave him there',
  },
  fx: {
    room: (v: string): string => `Room left ${v}`, fees: (v: string): string => `Fees ${v}`, patience: (n: number): string => `${n} more ${P(n, 'try', 'tries')}`,
    noDeal: 'No deal', rounds: (n: number): string => `${n} ${P(n, 'round', 'rounds')} of patience`, rivalGets: 'He goes to the rival',
    parentHappy: 'Parent club happy', parentAngry: 'They stop lending to us', back: 'Back in the squad', benchWarm: 'Another month on their bench',
  },

  // ---------- news, inbox, staff log ----------
  news: {
    bid: (pn: string, club: string, club2: string, v: string): [string, string] => [`${club} bid ${v} for ${pn}`, `${club2} are thinking it over.`],
    agreed: (pn: string, club: string, club2: string, v: string): [string, string] => [`${club} agree a fee for ${pn}`, `${v} to ${club2}. Personal terms next.`],
    done: (pn: string, club: string, club2: string, v: string): [string, string] => [`${pn} joins ${club}`, v ? `From ${club2} for ${v}.` : 'On a free transfer.'],
    walk: (pn: string, club: string): [string, string] => [`Talks for ${pn} collapse`, `His agent walked out on ${club}.`],
    hijack: (pn: string, club: string, club2: string, v: string): [string, string] => [`${club} hijack the deal for ${pn}`, `${v} to ${club2}. Someone was too slow.`],
    aiBid: (pn: string, club: string, v: string, why: string): [string, string] => [`${club} bid ${v} for ${pn}`, why],
    aiWhy: { unhappy: 'He hasn’t looked happy for weeks.', expiring: 'His contract is running down.', request: 'He has asked to leave.', need: 'They need a player like him.' } as Record<string, string>,
    release: (pn: string, club: string, club2: string, v: string): [string, string] => [`${club} trigger ${pn}’s release clause`, `${v}, and ${club2} can’t say no.`],
    loanIn: (pn: string, club: string, club2: string): [string, string] => [`${pn} joins ${club} on loan`, `From ${club2} for the season.`],
  },
  msg: {
    answer: (pn: string, club: string, s: string, v: string): [string, string] => [
      s === 'accept' ? `${club} accept our bid for ${pn}` : s === 'counter' ? `${club} counter for ${pn}` : `${club} reject our bid for ${pn}`,
      s === 'accept' ? `${v} agreed. His agent is waiting.` : s === 'counter' ? `They want ${v}.` : s === 'insult' ? 'They took it as an insult.' : 'Improve it or walk away.',
    ],
    hijack: (pn: string, club: string, v: string): [string, string] => [`${pn} signs for ${club}`, `They paid ${v} while our bid waited.`],
    rival: (pn: string, club: string, v: string): [string, string] => [`${club} are in for ${pn}`, `${v} on the table. Beat it before the next matchday.`],
    release: (pn: string, club: string, v: string): [string, string] => [`${club} pay ${pn}’s release clause`, `${v}. He’s gone.`],
    instalments: (v: string, n: number): [string, string] => [`Instalments paid: ${v}`, `${n} ${P(n, 'payment', 'payments')} fell due with the new season.`],
    picks: (pn: string, n: number, pos: string): [string, string] => [`Scout report: ${pn}`, `Top pick for ${pos.toLowerCase()} · ${n} ${P(n, 'name', 'names')} on the list.`],
    loanReport: (pn: string, club: string, apps: number, goals: number, days: number): [string, string] => [`Loan report: ${pn}`, `${apps} games in ${days} matchdays at ${club}, ${goals} ${P(goals, 'goal', 'goals')}.`],
    brokenIn: (pn: string, club: string): [string, string] => [`${club} are furious about ${pn}`, 'We promised minutes and didn’t give them. They’ll take him back at the window.'],
    brokenOut: (pn: string, club: string): [string, string] => [`${club} aren’t playing ${pn}`, 'They broke the minutes clause. We can recall him at the window.'],
    takenBack: (pn: string, club: string): [string, string] => [`${club} take ${pn} back`, 'The loan is over.'],
    sellOn: (pn: string, club: string, v: string): [string, string] => [`Sell-on paid for ${pn}`, `${v} to ${club}, as agreed when we bought him.`],
  },
  log: {
    rcbid: (pn: string, v: string): string => `Bid ${v} for ${pn}.`, rcPay: (pn: string, v: string): string => `Paid their price for ${pn}: ${v}.`,
    rcTop: (pn: string, v: string): string => `Topped the rival bid for ${pn}: ${v}.`, rcSigned: (pn: string, v: string): string => `Agreed terms with ${pn}: ${v} a month.`,
    rcWalk: (pn: string): string => `Walked away from ${pn}.`,
  } as Record<string, (pn: string, v: string) => string>,
  steps: {
    bid: 'Bid', agreed: 'Fee agreed', counter: 'Counter', reject: 'Refused', insult: 'Insulted', frozen: 'Talks frozen', rival: 'Rival bid', topped: 'Topped the rival',
    hijacked: 'Hijacked', signed: 'Signed', walked: 'Agent walked', window: 'Window shut', withdrawn: 'Pulled out', gone: 'Gone elsewhere', talks: 'Talks opened',
    loanIn: 'Loaned in', loanOut: 'Loaned out', brokenIn: 'Clause broken', brokenOut: 'They broke the clause', recalled: 'Recalled', takenBack: 'Taken back',
    release: 'Release clause paid', bid_need: 'Bid: they need him', bid_unhappy: 'Bid: he’s unhappy', bid_expiring: 'Bid: deal running down', bid_request: 'Bid: he asked to leave',
  } as Record<string, string>,
  ledger: { agentFees: 'Agent fees', signOn: 'Signing-on fees', instalments: 'Instalments', loanWages: 'Loan wage shares', bonuses: 'Appearance bonuses', sellOn: 'Sell-on payments' } as Record<string, string>,
  no: {
    frozen: 'Talks are frozen for now.', waiting: 'Our bid is still on the table.', agreed: 'The fee is agreed. Talk to his agent.',
    trust: 'They won’t lend to us after last time.', loanTerms: 'They want more of his wage covered, or a minutes promise.', minutes: 'He wouldn’t get those minutes there.',
    buyerBudget: 'They can’t afford that.', release: 'A release clause can’t be below his value.', slots: 'Every scout is already out.', scope: 'Pick where to send him.',
    done: 'Already covered.', noClause: 'No minutes clause to call on.', loaned: 'He’s on loan.',
  } as Record<string, string>,
  note: {
    bidSent: (pn: string): string => `Bid sent for ${pn}.`, talks: (pn: string): string => `Talks open with ${pn}’s agent.`, agreed: (pn: string): string => `Fee agreed for ${pn}.`,
    assigned: 'Scout on his way.', recalled: (pn: string): string => `${pn} is coming home.`,
    close: 'Close. Very close.', notThere: 'Not there yet.', insulted: 'He’s insulted.', walk: 'The agent walked out.',
  },
};

export type RStrings = typeof R_EN;
