// v2 copy in French: le banc de touche qui parle. Type-checked against English (lang-v2.ts).
import type { XStrings } from './lang-v2';

const P = (n: number, one: string, many: string) => (n === 1 ? one : many);
const WORDS = ['Rien', 'Une chose', 'Deux choses', 'Trois choses', 'Quatre choses', 'Cinq choses'];

export const X_FR: XStrings = {
  nav: { today: 'Aujourd’hui', squad: 'Effectif', match: 'Match', transfers: 'Transferts', club: 'Club', career: 'Carrière', pass: 'Club Pass' },
  back: 'Retour',
  close: 'Fermer',
  cont: 'Continuer',
  open: (n: number) => (n ? `· ${n} en attente` : '· rien en attente'),
  wk: (season: string, n: number) => `${season} · Sem. ${n}`,
  seasonLabel: (y: number) => `${y}/${String((y + 1) % 100).padStart(2, '0')}`,
  place: (n: number) => `${n}${n === 1 ? 'er' : 'e'}`,
  wdl: ['V', 'N', 'D'],
  saved: 'Enregistré',
  notNowShort: 'Pas maintenant',

  title: {
    tag: 'Dirige le club. Tiens le banc.',
    season: 'La saison 2026/27',
    lead: 'Tous les effectifs de Premier League, Liga, Serie A, Bundesliga et Ligue 1 tels qu’ils sont après le mercato d’été, plus les six grands d’Égypte et d’Arabie saoudite. Vrais noms. Nos propres notes.',
    newCareer: 'Lancer une carrière 2026/27',
    newSub: 'Choisis un club. La direction te dira ce qu’elle attend.',
    slots: 'Tes carrières',
    slot: (n: number) => `Emplacement ${n}`,
    empty: 'Emplacement libre',
    cont: 'Continuer',
    oldWorld: 'Ancien monde · noms fictifs',
    oldTitle: 'Ta carrière d’avant la refonte',
    oldBody: 'Elle a été jouée dans l’ancien monde généré, elle garde donc ses noms et clubs fictifs. Rien n’est perdu : continue-la, ou lance une carrière 2026/27 dans l’autre emplacement.',
    contOld: 'Continuer l’ancienne carrière',
    startNew: 'Lancer une nouvelle carrière 2026/27',
    full: 'Les deux emplacements sont pris. Choisis-en un à remplacer.',
    replace: 'Remplacer cette carrière',
    replaceAsk: (club: string) => `Remplacer ta carrière à ${club} ?`,
    replaceBody: 'Cette carrière sera supprimée de l’appareil. Exporte-la d’abord depuis les Réglages si tu risques d’en avoir besoin.',
    cancel: 'La garder',
    quick: 'Match rapide',
    quickSub: 'Deux clubs au choix, un match, rien ne compte.',
    foot: 'Jeu non officiel. Les vrais noms de clubs et de joueurs ne servent que de faits ; blasons et maillots sont nos propres dessins ; les notes sont le jugement de The Gaffer, de personne d’autre. Aucun lien avec un club, une ligue ou un joueur.',
    badSave: 'Une sauvegarde de cet appareil n’a pas passé la vérification et a été laissée telle quelle. Ton autre emplacement va bien.',
    loading: 'Ouverture du bureau…',
    matchday: (n: number) => `Journée ${n}`,
  },
  pick: {
    league: 'Où veux-tu travailler ?',
    leagueSub: 'Sept championnats avec les vrais effectifs 2026/27. Le reste de la pyramide est là pour les adversaires.',
    covered: 'Effectifs réels',
    generated: 'Effectifs générés',
    club: 'Choisis ton club',
    clubSub: 'Les grands clubs veulent des titres. Les petits te laissent du temps.',
    search: 'Chercher un club',
    strength: 'Niveau',
    budget: 'Budget',
    expects: 'La direction attend',
    job: 'Le poste',
    you: 'Toi',
    name: 'Ton nom',
    nameDefault: 'Le Coach',
    age: 'Âge',
    ageRule: 'Entre 20 et 80 ans.',
    nation: 'Nationalité',
    sign: 'Signer le contrat',
    signSub: (club: string) => `${club} t’attend.`,
    slotNote: (n: number) => `Enregistré dans l’emplacement ${n}.`,
    tiers: ['Première division', 'Deuxième division'],
    stars: 'Les meilleurs',
    clubs: (n: number) => `${n} clubs`,
  },

  today: {
    eyebrow: (md: string, opp: string, days: string) => `${md} · ${opp} ${days}`,
    inDays: (n: number) => (n <= 0 ? 'aujourd’hui' : n === 1 ? 'demain' : `dans ${n} jours`),
    head: (n: number, day0: string) => { const day = day0.replace(/\.$/, ''); return (n === 0 ? ['Rien sur ton bureau.', ` Seul ${day} compte.`, ''] : [`${WORDS[Math.min(5, n)]} `, P(n, 't’attend', 't’attendent'), ` avant ${day}.`]) as [string, string, string]; },
    headCup: (n: number) => (n === 0 ? ['Soir de coupe.', ' Rien d’autre ne t’attend.', ''] : [`${WORDS[Math.min(5, n)]} `, P(n, 't’attend', 't’attendent'), ' avant la coupe.']) as [string, string, string],
    seasonDone: ['La saison est finie.', ' Voyons comment elle se termine.', ''],
    sacked: ['La direction t’a remercié.', ' Le téléphone sonne encore.', ''],
    week: 'Les semaines à venir',
    more: (n: number) => `+${n} de plus sur le bureau`,
    fewer: 'Voir moins',
    nothing: 'Rien d’autre ne t’attend. Le staff gère le reste.',
    nothingSub: (list: string) => (list ? `${list} tournent seuls` : 'Chaque service t’attend'),
    review: 'Voir',
    staffDid: (n: number) => (n ? `Le staff a tranché ${n} ${P(n, 'fois', 'fois')} depuis le dernier match` : 'Le staff n’a rien tranché depuis le dernier match'),
    fit: (day: string) => `Disponibles ${day}`,
    fitOf: (a: number, b: number) => `${a} sur ${b}`,
    allFit: 'Tout le monde est là. Choisis dans tout l’effectif.',
    doubt: 'Incertain', banned: 'Suspendu', injured: (n: number) => `Absent ${n} sem.`, tired: (n: number) => `${n} % de forme`,
    pulse: 'Le pouls du club', office: 'Bureau',
    board: 'Direction', fans: 'Supporters', room: 'Vestiaire',
    mood: (v: number) => (v >= 75 ? 'Ravie' : v >= 60 ? 'Confiante' : v >= 45 ? 'Attentive' : v >= 30 ? 'Nerveuse' : 'À bout'),
    fansMood: (v: number) => (v >= 80 ? 'En feu' : v >= 60 ? 'Derrière toi' : v >= 40 ? 'Ça grogne' : 'Contre toi'),
    roomMood: (v: number) => (v >= 75 ? 'Sur un nuage' : v >= 62 ? 'Serein' : v >= 50 ? 'Tendu' : 'Éteint'),
    boardWhy: (obj: string, pos: string) => `${pos} actuellement. Objectif : ${obj.toLowerCase()}.`,
    fansWhy: (res: string) => res,
    roomWhy: (low: string | null) => (low ? `${low} est à surveiller` : 'Personne ne boude cette semaine'),
    table: 'Le classement', after: (n: number) => `Après ${n}`, next: 'Prochain',
    headlines: 'À la une', allNews: 'Toutes les infos',
    lastResult: 'Dernier match',
    home: 'Domicile', away: 'Extérieur', at: (v: string) => v,
    ourGround: 'À domicile', theirGround: 'À l’extérieur',
  },
  fixture: {
    comp: (c: string, md: string) => `${c} · ${md}`,
    win: 'Victoire', draw: 'Nul', loss: 'Défaite',
    pick: 'Choisir le onze', report: 'Rapport', getReport: 'Demander le rapport',
    assistant: 'Adjoint', analyst: 'Analyste',
    advice: {
      scoutFirst: 'On ne les a pas encore regardés. Laisse-moi la semaine avec la vidéo et je te dis où leur faire mal.',
      mismatch: (ph: string) => `Ils sont montés pour battre notre jeu. Passe en ${ph} et c’est nous qui posons les questions.`,
      edge: 'On a le bon plan contre eux. Garde-le, et ménage les jambes.',
      lowMastery: (n: number) => `Les gars ne maîtrisent ce plan qu’à ${n} %. Encore une semaine d’entraînement, ou quelque chose qu’ils connaissent.`,
      tired: (n: number) => `${n} titulaires sont sur la réserve. Fais tourner ou on courra après des ombres à l’heure de jeu.`,
      outOfPos: (n: number) => `${n} ${P(n, 'joueur est', 'joueurs sont')} hors de leur poste dans le onze. Ça va coûter.`,
      underdog: 'Sur le papier, ils sont meilleurs. Recule un peu et laisse-les venir.',
      trap: 'Règle le pressing pour les piéger là où ils aiment jouer. Le rapport dit que ça leur fait mal.',
      fine: 'Rien ne saute aux yeux. Pareil, et on démarre fort.',
    },
  },
  dec: {
    due: { kickoff: 'Avant le coup d’envoi', days: (n: number) => (n <= 1 ? 'Aujourd’hui' : `${n} jours restants`), week: 'Cette semaine', season: 'Avant l’été', window: 'Le mercato ferme ce soir' },
    tag: { welcome: 'Premier jour', offer: 'Offre', condition: 'Forme', contract: 'Contrat', staff: 'Proposition du staff', job: 'Offre d’emploi', tape: 'Analyse', focus: 'Semaine d’entraînement', deadline: 'Dernier jour du mercato' },
    staffPick: 'Choix du staff',
    yourCall: 'C’est ta décision. Celle de personne d’autre.',
    done: (label: string) => `Fait : ${label}`,
    undo: 'Annuler',
    swipe: 'Glisse à droite pour suivre le staff',
    open: 'Ouvrir',
    titles: {
      offer: (club: string, fee: string, pn: string) => `${club} offre ${fee} pour ${pn}`,
      tired: (pn: string, n: number) => `${pn} est à ${n} %`,
      expiring: (pn: string, y: number) => `Le contrat de ${pn} finit en ${y}`,
      job: (club: string) => `${club} veut te parler`,
      tape: (club: string) => `La vidéo de ${club} est prête`,
      focus: () => 'Changer le thème de la semaine ?',
      deadline: (g: string) => `Dernier jour du mercato, et on est courts ${g}`,
      ask_signed: (pn: string, fee: string) => `Recruter ${pn} pour ${fee} ?`,
      ask_renewed: (pn: string, years: number) => `Prolonger ${pn} de ${years} ${P(years, 'an', 'ans')} ?`,
      ask_listed: (pn: string) => `Mettre ${pn} sur la liste des transferts ?`,
      ask_capRaise: (pn: string, v: string, n: number) => `Relever le plafond salarial de ${v} par mois pour garder ${pn}${n > 1 ? ` et ${n - 1} autre${n > 2 ? 's' : ''}` : ''} ?`,
      ask_out: (pn: string, club: string) => `Prêter ${pn} à ${club} ?`,
      ask_sold: (pn: string) => `Vendre les droits de ${pn} ?`,
      ask_rejected: (pn: string) => `Refuser l’offre pour ${pn} ?`,
      ask_load: (load: string) => `Entraînement ${load.toLowerCase()} cette semaine ?`,
      ask_focus: (f: string) => `Semaine « ${f.toLowerCase()} » ?`,
      ask_rehab: (pn: string) => `Payer la rééducation de ${pn} ?`,
      ask_talk: () => 'Réunir le groupe pour parler ?',
      ask_promote: (pn: string) => `Faire monter ${pn} du centre de formation ?`,
      ask_scouted: () => 'Organiser une journée de détection ?',
      ask_plan: (ph: string) => `Jouer « ${ph} » au prochain match ?`,
      ask_formation: (f: string) => `Passer en ${f} ?`,
      ask_mentality: () => 'Changer d’état d’esprit pour le prochain match ?',
      ask_price: (s: string) => `Mettre le billet à ${s} ?`,
      ask_report: () => 'L’analyste a un rapport prêt',
      welcome: () => 'Comment veux-tu mener la maison ?',
    },
    advice: {
      offer_accept: (pn: string, v: string) => `C’est plus qu’il ne vaut pour nous. ${pn} est estimé à ${v}. Prends.`,
      offer_counter: (_pn: string, v: string) => `Proche, mais pas assez. Il vaut ${v}. Pousse-les et on verra s’ils cillent.`,
      offer_reject: (pn: string, v: string) => `Même pas proche pour un joueur comme ${pn}. Il vaut ${v}. Dis-leur non.`,
      offer_accept_money: (pn: string) => `Une somme pareille ne passe pas tous les jours. Moi, je vends ${pn}.`,
      offer_counter_money: () => 'Je vendrais, mais presse-les d’abord.',
      offer_reject_money: () => 'Même moi, je ne vendrais pas à ce prix.',
      offer_accept_loyal: (pn: string) => `Ça me fait mal de perdre ${pn}, mais c’est une vraie offre.`,
      offer_counter_loyal: (pn: string) => `${pn} fait partie de la maison. S’ils le veulent, qu’ils paient.`,
      offer_reject_loyal: (pn: string) => `${pn} n’est pas à vendre. Dis-leur non.`,
      rest: (_pn: string, n: number, sub: string) => `Il nous donnerait ${n} % de lui-même. ${sub} est frais. Repose-le et il sera prêt la semaine prochaine.`,
      rest_cautious: (pn: string, _n: number, sub: string) => `Je ne risque pas ${pn} avec des jambes lourdes. ${sub} fera le travail.`,
      rest_bold: (_pn: string, _n: number, sub: string) => `Même moi je le mettrais au repos cette fois. ${sub} est prêt.`,
      play: (_pn: string, n: number) => `Il est à ${n} % et reste meilleur que le banc. Fais-le jouer et gère son temps de jeu.`,
      renew_yes: (_pn: string, age: number, years: string) => `Il a ${age} ans. ${years} ans et il signe cette semaine. Si on attend, son agent commence à décrocher.`,
      renew_no: (_pn: string, age: number) => `À ${age} ans, je ne m’engagerais pas. Laisse filer et on prend plus jeune.`,
      renew_cap: () => 'Son nouveau salaire ne rentre pas sous le plafond. Relève le plafond ou laisse filer.',
      tape: (club: string) => `Laisse-moi la semaine avec ${club} sur l’ordi et je te montre où ça fuit.`,
      focus_recovery: () => 'Les jambes sont lourdes. Une semaine de récupération rend quatre points de forme à tout le monde.',
      focus_tactical: () => 'On répète le plan. Mieux ils le connaissent, mieux on le joue.',
      focus_opposition: () => 'On a leur vidéo. Une semaine sur eux vaut un demi-point de niveau le jour du match.',
      focus_development: () => 'Les jeunes apprennent plus vite quand la semaine est pour eux. Personne n’est fatigué.',
      deadline: (g: string) => `On est courts ${g}. Un de plus avant minuit, sinon on prie pour que personne ne se blesse.`,
      why_signed: (pn: string, fee: string) => `${pn} comble notre point faible et vaut ${fee}. Son agent signe aujourd’hui.`,
      why_renewed: (pn: string) => `${pn} vaut la peine d’être gardé et le salaire passe.`,
      why_listed: (pn: string) => `L’effectif est trop large. ${pn} est celui qui nous manquerait le moins.`,
      why_capRaise: (pn: string) => `${pn} vaut la peine d’être gardé, mais la masse salariale est au plafond. Le relever coûte un an de hausse d’avance.`,
      why_out: (pn: string) => `${pn} a besoin de matchs, pas d’un siège en tribune.`,
      why_sold: (pn: string) => `${pn} ne percera pas ici. Ses droits valent encore quelque chose.`,
      why_rejected: (pn: string) => `L’offre pour ${pn} est trop courte. Je dirais non.`,
      why_load: () => 'L’état du groupe le dit.',
      why_focus: () => 'C’est ce dont la semaine a besoin.',
      why_rehab: (pn: string) => `${pn} est absent un moment. La rééducation le ramène plus vite.`,
      why_talk: () => 'Le vestiaire est éteint. Un mot de toi le relance.',
      why_promote: (pn: string) => `${pn} est prêt. S’entraîner avec les pros finira le travail.`,
      why_scouted: () => 'Le centre de formation est léger. Une journée de détection en fait sortir deux ou trois.',
      why_plan: (ph: string) => `Le rapport dit que « ${ph} » est la façon de leur faire mal.`,
      why_formation: (f: string) => `Notre meilleur onze colle mieux au ${f}.`,
      why_mentality: () => 'Les chiffres disent de changer d’état d’esprit.',
      why_price: () => 'Plus d’argent aux guichets sans vider les tribunes.',
      why_report: () => 'Il est sur ton bureau.',
      welcome: () => 'Dis-nous à quel point tu veux être proche. Ce que tu laisses, on s’en charge, et tu peux changer ça quand tu veux dans la salle du staff.',
    },
    choices: {
      accept: (fee: string) => `Accepter ${fee}`, counter: (fee: string) => `Demander ${fee}`, reject: () => 'Refuser',
      restHim: (pn: string) => `Repos · ${pn} démarre`, playHim: () => 'Le faire jouer',
      renewYears: (n: number) => `Discuter · ${n} ${P(n, 'an', 'ans')}`, wait: () => 'Laisser filer',
      takeJob: () => 'Accepter le poste', stay: () => 'Je reste',
      watchTape: () => 'Regarder la vidéo', skipTape: () => 'Pas cette semaine',
      focus_recovery: () => 'Récupération', focus_tactical: () => 'Tactique', focus_opposition: () => 'Adversaire', focus_development: () => 'Progression',
      findCover: () => 'Trouver une doublure', standPat: () => 'On ne bouge pas',
      approve: () => 'Oui, vas-y', notNow: () => 'Pas maintenant',
      runUsual: () => 'La répartition habituelle', handsOn: () => 'Aux commandes : je choisis l’équipe', leaveIt: () => 'Je laisse le staff faire',
    },
    fx: {
      cash: (v: string) => `+${v}`, loseStarter: () => 'On perd un titulaire', loseSquad: () => 'Effectif −1', mayWalk: () => 'Ils peuvent partir', stays: () => 'Il reste',
      freshNext: (n: number) => `${n} % la semaine prochaine`, slotLevel: (n: number) => (n >= 0 ? `Niveau +${n}` : `Niveau ${n}`), playsAt: (n: number) => `Joue à ${n} %`, legs: () => 'Jambes en fin de match',
      wagesYear: (v: string) => `Salaires ${v}/an`, moraleUp: () => 'Moral ↑', rivalsCall: () => 'Des rivaux peuvent appeler',
      newClub: () => 'Nouveau club, nouvelle direction', loyalty: () => 'La direction apprécie la fidélité',
      knowThem: () => 'Leur plan, leurs dangers et une parade', noPrep: () => 'On y va à l’aveugle',
      signingsAsk: () => 'Les recrues t’attendent', moreCalls: () => 'Plus de décisions sur ton bureau', fewestCalls: () => 'Le moins de décisions', staffSign: () => 'Le staff peut recruter',
      focusFx_recovery: () => 'Forme +4', focusFx_tactical: () => 'Maîtrise +2', focusFx_opposition: () => 'Avantage contre eux', focusFx_development: () => 'Progression ×1,25',
      toMarket: () => 'Ouvre le marché', thin: () => 'À une blessure du problème',
      fee: (v: string) => `Indemnité ${v}`, listed: () => 'Sur la liste', minutes: () => 'Du vrai temps de jeu', monthly: (v: string) => `+${v}/mois`, backSooner: () => 'Revient plus tôt', plan: () => 'Nouveau plan',
      nothingChanges: () => 'Rien ne change',
    },
    groups: ['au poste de gardien', 'derrière', 'au milieu', 'devant'],
  },
  desk: {
    title: (n: number) => (n ? `${n} ${P(n, 'décision reste', 'décisions restent')} sur ton bureau` : 'Bureau vide'),
    body: 'Si tu continues maintenant, le staff suit son propre avis sur tout ce qui reste ouvert. Rien de ce que tu n’as pas vu n’est signé.',
    take: 'Suivre le staff et continuer',
    leave: 'Les laisser telles quelles',
    stay: 'Je regarde d’abord',
  },

  pre: {
    crowd: (n: string, club: string) => `${n} · ${club} donne de la voix`,
    crowdAway: (n: string) => `${n} · le parcage visiteur est plein`,
    stakesUp: (club: string, pos: string) => `Gagne et tu passes ${pos}. ${club} est sur le chemin.`,
    stakesCup: (round: string) => `${round}. Le perdant rentre chez lui.`,
    stakesPlain: 'Trois points. Rien d’autre ne compte un samedi.',
    sheets: 'Compositions', confirmed: 'Officielles',
    talk: 'Le dernier mot dans le vestiaire',
    talks: [
      ['« Allez le leur prendre. »', 'Les joueurs de grands matchs se transcendent. Les jeunes peuvent se crisper.'],
      ['« On s’en tient au plan. »', 'Posé. Personne ne s’emballe.'],
      ['« Pas de pression. Profitez. »', 'Les jeunes se libèrent. Ceux qui en veulent plus s’éteignent.'],
    ],
    winChance: 'Chances de victoire', ourXg: 'Nos xG prévus', theirXg: 'Les leurs',
    walk: 'Entrer sur le terrain', result: 'Donne-moi le résultat', sim: 'Simuler jusqu’à la prochaine décision', simSub: 'Des résultats rapides jusqu’à ce qu’on ait besoin de toi',
    resume: (m: number) => `Reprendre à la ${m}′`,
    report: 'Rapport de l’analyste',
    threats: 'Attention à eux', weak: 'Où ça fuit', counter: 'La parade', apply: 'L’utiliser', using: 'C’est en place',
    weakWhy: { slow: 'Lent à se retourner', tired: 'À bout de souffle', weak: 'Le maillon faible' },
    accuracy: (n: number) => `Sûrs à ${n} %`,
  },
  live: {
    ht: 'Mi-temps', ft: 'Fin du match', min: (n: number) => `${n}′`,
    moments: 'Temps forts', numbers: 'Les chiffres', touchline: 'Depuis la touche', takes: 'Effet immédiat',
    where: 'Où le ballon a vécu', whereSub: '10 dernières min',
    views: ['Terrain', 'Territoire', 'Nos tirs', 'Les leurs'],
    momentum: 'Dynamique', momentumKey: (a: string, b: string) => `${a} en haut · ${b} en bas`,
    xg: 'Buts attendus', attack: (club: string) => `${club} attaque →`,
    stats: ['Possession', 'Tirs', 'Cadrés', 'Corners', 'Fautes', 'Cartons jaunes'],
    changes: 'Changements', pause: 'Pause', play: 'Reprendre', key: 'Temps forts', speed: 'Vitesse',
    shouts: [['Continuez', 'mentality', 0], ['Écartez', 'width', 2], ['On calme', 'tempo', 0], ['Pressez-les', 'pressing', 2], ['On recule', 'line', 0], ['On y va', 'mentality', 2]],
    assistant: 'Adjoint',
    planB: 'Passer au plan B', planBOn: 'Plan B activé',
    subsLeft: (n: number) => `${n} ${P(n, 'changement restant', 'changements restants')}`,
    off: 'Sort', on: 'Entre', makeSub: 'Faire le changement', pickTwo: 'Choisis qui sort, puis qui entre.',
    confirm: (a: string, b: string) => `${b} remplace ${a}`,
    skip: 'Aller à la fin',
    goal: 'BUT', sound: 'Son',
    ev: {
      goal: (p: string) => `BUT · ${p}`, pen: (p: string) => `Penalty · ${p}`, chance: (p: string) => `Grosse occasion · ${p}`, save: (p: string) => `Arrêt · ${p}`,
      red: (p: string) => `Expulsé · ${p}`, injury: (p: string) => `Blessure · ${p}`,
      goalSub: (xg: string) => `xG ${xg}`, chanceSub: (xg: string) => `xG ${xg}, et ça n’est pas rentré`, redSub: 'À dix', injurySub: 'Il ne peut pas continuer',
    },
    noMoments: 'Rien de notable pour l’instant.',
    resumed: (m: number) => `Repris là où tu l’avais laissé : ${m}′`,
  },
  ht: {
    eyebrow: 'Pourquoi · les analystes',
    change: 'Ce qu’on changerait', tapApply: 'Touche pour appliquer',
    win: (a: number, b: number) => `${a} % → ${b} %`, winLine: (n: number) => `Chances de victoire avec ${n} ${P(n, 'changement', 'changements')}`,
    yourChange: 'Ton changement', second: 'Seconde période', teamTalk: 'Causerie',
    noTips: 'Le moteur ne voit rien de mieux que ce qu’on fait. Continuez.',
    applied: 'C’est fait. Ils le sauront à la reprise.',
    cause: {
      source: ['C’est là qu’on leur fait mal', 'C’est là qu’ils nous font mal'], setpiece: ['Les coups de pied arrêtés sont notre arme', 'Les coups de pied arrêtés nous tuent'],
      midfield: ['Le milieu est à nous', 'Le milieu est à eux'], pressed: ['Leur pressing ne mord pas', 'Leur pressing mord'], pressing: ['Notre pressing mord', 'Notre pressing ne mord pas'],
      duel: ['On gagne les duels', 'On perd les duels'], finish: ['La finition est pour nous', 'La finition nous coûte'],
      keeper: ['Un gardien nous maintient', 'Leur gardien est dans un grand jour'], tired: ['Ils n’ont plus de jambes', 'On n’a plus de jambes'],
      red: ['Ils sont à dix', 'On est à dix'], change: ['Le changement marche', 'Le changement n’a pas marché'], theyChanged: ['Ils ont changé, sans effet', 'Ils ont changé quelque chose'],
    },
    evid: { shots: (n: number) => `${n} ${P(n, 'tir', 'tirs')}`, xg: 'xG', of: (a: number, b: number) => `${a} sur ${b}`, pct: (n: number) => `${n} %`, won: 'récupérés haut', saves: 'arrêts', fit: 'de forme en fin de match', min: (n: number) => `${n}′`, through: 'des actions passent' },
    subIdea: (a: string, b: string) => `${b} remplace ${a}`, subWhy: (a: string, n: number) => `${a} est à ${n} %. Le banc est frais.`,
    heads: {
      deserved: 'On le mérite.', robbed: 'On en fait assez. Le score n’est pas d’accord.', smash: 'On mène, mais avec de la chance.',
      beaten: 'Ils ont été meilleurs. Point.', even: 'Rien ne les sépare.', clinical: 'On a pris nos occasions.', wasteful: 'On devrait mener plus largement.', level: 'Égalité, et ça semble juste.',
    },
  },
  ft: {
    eyebrow: (ground: string) => `Fin du match · ${ground}`,
    xg90: 'Buts attendus · 90 min',
    changed: 'Ce que ça a changé',
    league: 'Championnat', board: 'Direction', fans: 'Supporters', room: 'Vestiaire',
    ratings: 'Notes', all: (n: number) => `Les ${n}`, motm: 'Homme du match',
    heads: {
      W: (club: string, opp: string) => [`${club} bat ${opp}.`, 'Un vrai résultat.', 'Trois points dans la poche.'],
      D: (club: string, opp: string) => [`${club} et ${opp} se quittent dos à dos.`, 'Un point chacun.', 'Match nul.'],
      L: (club: string, opp: string) => [`${opp} bat ${club}.`, 'À oublier.', 'Retour au travail lundi.'],
    },
    tail: { up: (p: string) => ` On monte ${p}.`, down: (p: string) => ` On descend ${p}.`, same: (p: string) => ` Toujours ${p}.` },
    boardQuote: (d: number) => (d >= 2 ? '« Un résultat qui marque. »' : d >= 0 ? '« Comme prévu. »' : d > -2 ? '« On attendait plus. »' : '« Ça ne peut pas se reproduire. »'),
    fansQuote: (d: number) => (d >= 2 ? 'Ils chantaient ton nom' : d >= 0 ? 'Ils sont rentrés contents' : 'Quelques sifflets au coup de sifflet final'),
    roomQuote: (d: number) => (d >= 2 ? 'Ça chante là-dedans' : d >= 0 ? 'Calme et posé' : 'Têtes basses'),
    out: (n: number) => `Absents : ${n}`,
    injuredFor: (pn: string, n: number) => `${pn} absent ${n} ${P(n, 'semaine', 'semaines')}`,
    bannedFor: (pn: string, n: number) => `${pn} suspendu ${n} match${n > 1 ? 's' : ''}`,
    record: 'Nouveau record du club',
    press: 'Partager le compte rendu', done: 'Continuer',
    note: 'Adjoint',
  },
  digest: {
    title: 'Pendant ton absence',
    sub: (a: string, b: string) => `${a} à ${b}`,
    results: 'Résultats', staff: (n: number) => `${n} ${P(n, 'décision', 'décisions')} du staff`,
    stopped: { decision: 'Arrêt : quelque chose t’attend.', season: 'Arrêt : la saison est finie.', max: 'Arrêt : huit journées d’un coup, ça suffit.', big: 'Arrêt : un gros match arrive.', window: 'Arrêt : le mercato a ouvert.' },
    back: 'Retour à Aujourd’hui',
  },

  squad: {
    title: 'L’effectif',
    sub: (n: number) => `Équipe première · ${n} joueurs`,
    facts: { age: 'âge moyen', wages: 'salaires par mois', unhappy: 'mécontents', holes: (n: number) => P(n, 'trou à combler', 'trous à combler') },
    lens: { all: 'Tous', starters: 'Titulaires', ending: 'Fins de contrat', unhappy: 'Mécontents', injured: 'Blessés', loans: 'Prêtés', listed: 'Sur la liste' },
    depth: 'Profondeur', depthSub: 'Titulaire · doublure',
    covered: 'Couvert', thin: 'Juste', hole: 'À une blessure du problème',
    noCover: (pn: string) => `Personne derrière ${pn}`, noCoverSub: 'La cellule de recrutement est prête dès que tu l’es.', shortlist: 'Liste',
    thenNobody: 'puis personne de disponible',
    player: 'Joueur', fit: 'Forme', mood: 'Moral', yrs: 'Ans',
    desk: 'Sur le bureau', deskSub: 'Contrats et mouvements',
    ending: (n: number) => `${n} ${P(n, 'contrat finit', 'contrats finissent')} cette saison`, endingNone: 'Aucun contrat ne finit cette saison.',
    loansOut: (n: number) => `${n} prêtés`, listedN: (n: number) => `${n} sur la liste`,
    training: 'Semaine d’entraînement', medical: 'Infirmerie', academy: 'Centre de formation',
    find: 'Chercher',
    form: (v: string) => `forme ${v}`,
    sub2: { captain: 'capitaine', inj: (n: number) => `absent ${n} sem.`, ban: 'suspendu', loan: 'prêté', listed: 'sur la liste', talks: 'veut parler', young: 'formation' },
  },
  player: {
    back: 'Effectif',
    ability: 'Niveau', ceiling: 'Plafond', form: 'Forme', value: 'Valeur', apps: (n: number) => `${n} matchs`,
    dev: 'Progression', devHead: (age: number, peak: number, up: boolean) => (age >= 31 ? 'Il tient encore. Les années le rattrapent.' : !up ? 'Il est à son niveau. Ce que tu vois, c’est ce que tu as.' : peak <= age + 1 ? 'Presque au sommet. Un dernier effort.' : `Il progresse encore. Pic vers ${peak} ans.`),
    known: 'Connu', own: 'Notre joueur', scouted: (k: number) => `Recruteurs sûrs à ${k} %`,
    good: 'Ses points forts', groups: ['Avec le ballon', 'Sans le ballon', 'Tête et physique'],
    attrs: ['Vitesse', 'Frappe', 'Passe', 'Dribble', 'Défense', 'Physique', 'Gardien'],
    fits: 'Où il joue',
    man: 'L’homme', captain: 'Capitaine', morale: (v: string) => `Moral : ${v}`, moods: ['bas', 'moyen', 'correct', 'bon', 'au top'],
    contract: 'Contrat', expires: 'Expire en juin', perMonth: 'Par mois', secure: 'Sous contrat', ending: 'Se termine', release: 'Clause libératoire', none: 'Aucune', rank: 'Rang salarial',
    renew: 'Proposer une prolongation', list: 'Mettre sur la liste', unlist: 'Retirer de la liste', talk: 'Lui parler', rest: 'Repos au prochain match', unrest: 'De nouveau disponible',
    bid: 'Faire une offre', shortlist: 'Dans la liste', unshortlist: 'Retirer de la liste', loanIn: 'Le faire venir en prêt', loanOut: 'Le prêter',
    rename: 'Renommer',
    season: 'Cette saison', seasonStats: (a: number, g: number, as: number) => `${a} matchs · ${g} buts · ${as} passes déc.`,
    ageNat: (age: number) => `${age}`,
    free: 'Libre',
    onLoan: (club: string) => `Prêté à ${club}`,
    ability2: 'Projection', abilityLine: 'Niveau', projLine: 'Projection du staff', avgLine: 'Moyenne de l’effectif',
  },
  train: {
    title: 'Semaine d’entraînement', sub: 'Intensité et thème',
    load: 'Intensité', loads: ['Légère', 'Normale', 'Intense'], loadFx: ['Les jambes récupèrent. On apprend moins vite.', 'La semaine habituelle.', 'On apprend plus vite, jambes plus lourdes, quelques pépins.'],
    focus: 'Thème de la semaine', focusNames: { recovery: 'Récupération', tactical: 'Tactique', opposition: 'Adversaire', development: 'Progression' },
    focusFx: { recovery: 'Tout le monde +4 de forme pour samedi.', tactical: 'Le plan s’ancre : +2 de maîtrise après le match.', opposition: 'Avec le rapport de l’analyste : un petit avantage le jour du match.', development: 'Les joueurs apprennent 25 % plus vite cette semaine.' },
    report: 'La semaine dernière', improved: (n: number) => `${n} en progrès`, hurt: (n: number) => `${n} avec un pépin`,
    individual: 'Travail individuel', choose: 'Choisis un joueur', attr: 'Travail en plus sur',
    none: 'Rien de plus',
    medical: 'Infirmerie', injuredN: (n: number) => (n ? `${n} ${P(n, 'blessé', 'blessés')}` : 'Tout le monde est apte'), rehab: 'Rééducation', specialist: 'Spécialiste', out: (n: number) => `Absent ${n} sem.`,
    academy: 'Centre de formation', prospects: (n: number) => `${n} ${P(n, 'espoir', 'espoirs')}`, trial: (cost: string) => `Journée de détection · ${cost}`, promote: 'Faire monter', release: 'Libérer', sellRights: (v: string) => `Vendre les droits · ${v}`,
    trialsLeft: (n: number) => `${n} ${P(n, 'journée de détection', 'journées de détection')} cette saison`,
  },

  tac: {
    title: (opp: string) => `Tactique · contre ${opp}`, titleFree: 'Tactique',
    styles: { balanced: 'Équilibré', possession: 'Garder le ballon', counter: 'Bloc et contre', gegenpress: 'Presser puis attaquer la profondeur', bus: 'Garer le bus', wings: 'Par les ailes', direct: 'Jeu direct' },
    forecast: 'Prévision',
    how: 'Notre jeu', changes: (n: number) => `${n} ${P(n, 'changement', 'changements')}`, changed: 'Modifié',
    style: 'Style', shape: 'Système',
    ins: {
      press: ['Pressing', ['Attendre', 'Bloc médian', 'Chasser haut']],
      line: ['Ligne défensive', ['Basse', 'Standard', 'Haute']],
      width: ['Où on attaque', ['Axe', 'Équilibré', 'Largeur']],
      tempo: ['Tempo', ['Patient', 'Normal', 'Rapide']],
      passing: ['Passes', ['Courtes', 'Mixtes', 'Directes']],
      mentality: ['État d’esprit', ['Bus', 'Prudent', 'Équilibré', 'Offensif', 'Tout pour l’attaque']],
    },
    gain: 'Gain', risk: 'Risque',
    trade: {
      press: [['Bas et compact : des jambes fraîches à la 80e.', 'Ils ont le ballon et le temps de choisir.'], ['Dur à traverser, économe pour les jambes.', 'Ni chaud ni froid.'], ['On récupère près de leur surface.', 'Les jambes lâchent vers la 70e, et ils nous prennent de vitesse.']],
      line: [['Rien dans notre dos pour leurs attaquants.', 'Ils s’installent devant notre surface.'], ['Nos centraux sont à l’aise.', 'Un trou entre les lignes quand on presse.'], ['Le terrain rétrécit pour eux.', 'Un ballon dans le dos et c’est une course.']],
      width: [['Du nombre dans l’axe.', 'Facile à fermer.'], ['Rien d’évident à arrêter.', 'Rien d’évident à craindre.'], ['Ça les étire ; nos ailiers ont des un-contre-un.', 'Léger dans l’axe si on le perd.']],
      tempo: [['On garde le ballon et notre bloc.', 'Ils se replacent avant qu’on arrive.'], ['Équilibré.', 'Équilibré.'], ['On les prend avant qu’ils se replacent.', 'On le perd plus souvent.']],
      passing: [['Court et sûr : il est à nous.', 'Lent pour faire mal.'], ['Un peu des deux.', 'Un peu des deux.'], ['Droit sur leur défense.', 'Des ballons à pile ou face au milieu.']],
    },
    mentality: ['Garer le bus', 'Prudent', 'Équilibré', 'Offensif', 'Tout pour l’attaque'],
    board: 'Tableau tactique. Touche un joueur, puis un poste ou un autre joueur pour les échanger.',
    hint: 'Touche pour choisir · encore pour échanger',
    theirPress: (club: string) => `Le système de ${club}`,
    bench: 'Banc', lock: 'Valider le plan', locked: 'Plan validé', undo: 'Annuler', reset: 'Mon meilleur onze',
    role: (pos: string) => `Rôle · ${pos}`, fitFor: 'Son adaptation à chaque poste',
    opp: (f: string, st: string) => `Adversaire · ${f} · ${st}`, oppHow: (club: string) => `Le jeu de ${club}`,
    ours: 'À nous', theirs: 'À eux', even: 'Équilibré',
    lanes: ['Notre gauche', 'Axe', 'Notre droite'],
    danger: 'le danger', engine: 'le moteur', oppManager: (n: string) => `${n} choisit leur équipe`,
    noReport: 'Pas encore de rapport. L’analyste a besoin de la semaine sur eux.',
    familiar: 'Maîtrise', familiarSub: (n: number) => (n >= 80 ? 'Ils le connaissent par cœur' : n >= 55 ? 'Ça vient' : 'Encore en apprentissage'),
    planB: 'Plan B', planBSet: 'Garder comme plan B', planBNone: 'Pas encore de plan B. Prépare un second plan à activer pendant un match.', planBClear: 'Effacer le plan B', useB: 'Passer au plan B',
    setPieces: 'Coups de pied arrêtés', captain: 'Capitaine', penalties: 'Penalties', freeKicks: 'Coups francs', corners: 'Corners', auto: 'Le meilleur disponible',
    swapped: (a: string, b: string) => `${a} et ${b} échangés`,
    outOfPos: (n: number) => `Joue à ${n}`,
    philosophy: 'Philosophie',
  },
  table: {
    tabs: ['Prochain match', 'Calendrier', 'Classement', 'Coupes'],
    pos: '#', club: 'Club', p: 'J', gd: 'Diff', pts: 'Pts', w: 'V', d: 'N', l: 'D',
    scorers: 'Buteurs', assists: 'Passeurs', zones: { up: 'Montée', down: 'Relégation', top: 'Places européennes' },
    round: (n: number) => `Journée ${n}`, noCups: 'Pas de match de coupe cette saison.', group: (g: string) => `Groupe ${g}`,
    bye: 'Exempt', tbd: 'Tirage à venir', winnerGoes: 'Le vainqueur passe',
    finished: 'Joué', upcoming: 'À venir', you: 'Toi',
  },

  tr: {
    title: 'Transferts', window: (open: boolean, left: number) => (open ? `Mercato ouvert · ${left} ${P(left, 'journée restante', 'journées restantes')}` : `Mercato fermé · ouvre dans ${left} ${P(left, 'journée', 'journées')}`),
    deadline: 'Dernier jour du mercato',
    hero: { need: (pos: string) => `Trouver un ${pos.toLowerCase()}`, none: 'Personne à chercher. Pour l’instant.' },
    budget: 'Budget transferts', wageRoom: 'Marge salariale / mois', onList: 'Dans la liste',
    why: 'Pourquoi cette recherche', needHead: (pos: string) => `On est courts au poste : ${pos.toLowerCase()}.`, noNeed: 'Chaque poste a une doublure. Cherche la qualité, pas le nombre.',
    chief: 'Chef recruteur',
    scoutLine: (pn: string, k: number) => `${pn}, c’est lui. On le connaît à ${k} %.`,
    scoutNone: 'Mets quelques noms dans la liste et j’envoie quelqu’un les voir.',
    fog: 'Ce qu’on sait · niveau', fogHead: 'Plus la barre est large, moins on en sait.', fogKey: 'Fourchette des recruteurs', ref: (pn: string, n: number) => `${pn} aujourd’hui (${n})`,
    tabs: ['Liste', 'Recherche', 'Offres', 'Opérations', 'Prêts'],
    known: 'connu', likely: 'Indemnité probable', wants: 'Demande / mois', interest: 'Intérêt',
    interestL: ['Motivé', 'Ouvert', 'Réservé', 'Inconnu'],
    ability: 'Niveau', ceiling: 'Plafond', fit: 'Adaptation',
    bid: 'Faire une offre', inTalks: 'En discussion', report: 'Rapport', ask: 'Demander le prix',
    empty: 'La liste est vide. Cherche sur le marché et marque ceux qui te plaisent : les recruteurs les suivent aussitôt.',
    search: 'Chercher des joueurs', filters: { pos: 'Poste', league: 'Championnat', age: 'Âge', value: 'Prix max.' }, any: 'Tous', results: (n: number) => `${n} joueurs`,
    sort: ['Note des recruteurs', 'Prix', 'Âge', 'Salaire'],
    bids: 'Offres pour tes joueurs', noBids: 'Personne ne demande. Ça change vite pendant un mercato.',
    deals: 'Opérations de la saison', noDeals: 'Aucune opération pour l’instant.', inOut: { in: 'Arrivée', out: 'Départ', free: 'Libre', released: 'Libéré' },
    loans: 'Prêts', noLoans: 'Personne en prêt.', loanedIn: 'Prêtés chez nous', loanedOut: 'Prêtés ailleurs',
    closed: 'Le mercato est fermé. Joueurs libres uniquement jusqu’à l’ouverture.',
  },
  bid: {
    title: (pn: string) => `Offre pour ${pn}`, fee: 'Indemnité', wage: 'Salaire mensuel', years: 'Années', role: 'Rôle',
    roles: { star: 'Star', regular: 'Titulaire', rotation: 'Rotation', prospect: 'Espoir' },
    ask: (v: string) => `Ils veulent ${v}`, demand: (v: string) => `Il demande ${v}`, send: 'Envoyer l’offre',
    afford: 'Après l’opération', budgetLeft: 'Budget restant', wageLeft: 'Marge salariale restante',
    no: {
      budget: 'On ne peut pas payer cette indemnité.', wageCap: 'Ce salaire fait sauter le plafond.', squadFull: 'L’effectif est complet (32).', fee: 'Ils veulent plus.', wage: 'Il veut plus.',
      ambition: 'Il ne descendra pas à notre niveau.', role: 'Trop âgé pour être un espoir.', injured: 'Il est blessé.', sellerThin: 'Ils ne peuvent pas s’en passer : effectif trop juste.',
      gone: 'Il n’est pas disponible.', window: 'Le mercato est fermé.', limit: 'Limite de prêts atteinte.', loaned: 'Déjà prêté.', squad: 'Notre effectif est trop juste.', key: 'C’est un joueur clé chez eux.',
      club: 'Choisis un club.', free: 'Il n’est pas à nous pour le prêter.', lenderThin: 'Ils ne peuvent pas s’en passer.', unhappy: 'Il ne parlera pas tant qu’il est si mécontent.', years: 'Trop d’années pour son âge.',
      terms: 'Ces conditions ne vont pas.', counter: 'Ils veulent plus.', wait: 'Trop tôt pour rediscuter.', fee2: 'Ce n’est pas une hausse.',
    },
    counter: (v: string) => `Ils accepteraient ${v}`,
    renewTitle: (pn: string) => `Prolongation de ${pn}`, renewSend: 'La proposer',
    offersTitle: 'Offres pour tes joueurs', accept: 'Accepter', reject: 'Refuser', counterBtn: (v: string) => `Demander ${v}`,
  },
  note: {
    signed: (pn: string) => `${pn} signe.`, sold: (pn: string) => `${pn} est vendu.`, renewed: (pn: string) => `${pn} prolonge.`,
    loanedIn: (pn: string) => `${pn} arrive en prêt.`, loanedOut: (pn: string) => `${pn} part en prêt.`, counterOk: 'Ils acceptent ton prix.', counterNo: 'Ils se sont retirés.',
    haggleOk: 'Ils ont monté de 10 %.', haggleNo: 'Ils ont retiré l’offre.', rightsSold: (v: string) => `Droits vendus pour ${v}.`, scoutFound: (n: number) => `${n} ${P(n, 'espoir repéré', 'espoirs repérés')}.`,
    tactics: 'Plan validé.', done: 'C’est fait.', refused: 'Impossible :',
  },

  office: {
    title: 'Bureau du club', hero: 'L’argent, la direction, les briques.',
    tabs: ['Argent', 'Direction', 'Installations', 'Staff', 'Commercial'],
    runway: (to: string) => `Trésorerie · jusqu’à ${to}`,
    runwayHead: (ok: boolean, low: string) => (ok ? `Sain toute la saison. Point bas : ${low}.` : `On passe dans le rouge vers ${low}. Il faut changer quelque chose.`),
    cash: 'Trésorerie', wageUse: 'Salaires / plafond', transfer: 'Budget transferts',
    projected: 'Trésorerie prévue', floor: 'Ligne zéro',
    income: 'Recettes par mois', spend: 'Dépenses par mois',
    lines: { gate: 'Billetterie', tv: 'Droits TV', sponsors: 'Commercial', wages: 'Salaires', staff: 'Staff', upkeep: 'Entretien' },
    ledger: 'Cette saison',
    capT: 'Plafond salarial', capMove: 'Déplacer le plafond', capUp: (v: string) => `Coûte ${v} maintenant`, capDown: (v: string) => `Rend ${v}`,
    board: 'Ce que veut la direction', trust: 'Confiance', trustWhy: (n: number) => (n < 30 ? 'Sous 30, ils cherchent un remplaçant.' : n < 50 ? 'Ils surveillent.' : 'Ils sont derrière toi.'),
    obj: { league: 'Championnat', cup: 'Coupe', youth: 'Jeunes', finance: 'Finances' },
    onTrack: 'En bonne voie', close: 'Proche', behind: 'En retard',
    youthLine: (n: number, of: number) => `${n} sur ${of} matchs de championnat pour les moins de 21 ans`,
    financeLine: (ok: boolean) => (ok ? 'Dans le vert' : 'Dans le rouge'),
    facilities: 'Installations', level: (n: number) => `Niveau ${n}`, upgrade: (v: string) => `Construire · ${v}`, maxed: 'Le meilleur qui existe',
    fac: { stadium: 'Stade', medical: 'Centre médical', training: 'Centre d’entraînement', academy: 'Centre de formation', scouting: 'Réseau de recrutement' },
    facFx: { stadium: 'Plus de places, plus de recettes', medical: 'Les blessures guérissent plus vite', training: 'Les joueurs progressent plus vite', academy: 'De meilleurs espoirs', scouting: 'Plus de journées de détection' },
    staff: 'La salle du staff', staffSub: 'Qui fait quoi, et quelle liberté tu leur laisses',
    levels: { me: 'Moi', ask: 'Demande-moi', staff: 'Le staff' },
    levelHelp: { me: 'Rien ne se fait sans toi.', ask: 'Ils préparent et attendent ton feu vert.', staff: 'Ils s’en chargent et te le disent après.' },
    depts: { matchprep: 'Préparation du match', opposition: 'Adversaire', fitness: 'Forme et médical', development: 'Progression', recruitment: 'Recrutement', contracts: 'Contrats et ventes', commercial: 'Commercial' },
    deptSub: { matchprep: 'Onze et plan', opposition: 'Rapports et parade', fitness: 'Charge, thème, rééducation', development: 'Formation et moral', recruitment: 'Recrues et prêts', contracts: 'Prolongations et offres', commercial: 'Sponsors et billets' },
    roles: { assistant: 'Entraîneur adjoint', director: 'Directeur sportif', fitness: 'Préparateur physique', doctor: 'Médecin du club', psychologist: 'Psychologue', scout: 'Chef recruteur' },
    bias: { cautious: 'Prudent', bold: 'Audacieux', youth: 'Mise sur les jeunes', veteran: 'Fait confiance à l’expérience', money: 'L’argent d’abord', loyal: 'Fidèle' },
    biasWhy: { cautious: 'Joue la sécurité : repose tôt, offre peu, peut rater des cibles.', bold: 'Fonce : tire sur les jambes, paie trop cher.', youth: 'Soutient les jeunes.', veteran: 'Veut des joueurs éprouvés.', money: 'Vend quand le prix est bon, parfois avant.', loyal: 'Garde ses joueurs, prolonge presque tout le monde.' },
    quality: (n: number) => `Qualité ${n}`, hire: 'Embaucher', candidates: 'Candidats', wage: (v: string) => `${v}/mois`,
    all: 'Régler tous les services', log: 'Ce que le staff a fait', logEmpty: 'Rien pour l’instant.',
    sponsors: 'Sponsors', offers: 'Offres', sign: 'Signer', haggle: 'Demander 10 % de plus', extend: 'Prolonger', end: 'Rompre',
    slots: { shirt: 'Maillot', kit: 'Équipementier', stadium: 'Nom du stade', sleeve: 'Manche', commercial: 'Partenaire commercial' },
    months: (n: number) => `${n} mois`,
    tickets: 'Billetterie', price: 'Prix du billet', attendance: (n: string, c: string) => `${n} sur ${c} places`, setPrice: 'Fixer le prix',
    settings: 'Réglages et sauvegardes',
  },

  career: {
    title: 'Ta carrière', hero: (n: number) => (n ? `${n} ${P(n, 'trophée', 'trophées')}, et ce n’est pas fini.` : 'Le premier trophée est le plus dur.'),
    totals: { matches: 'Matchs', wins: 'Victoires', trophies: 'Trophées', rep: 'Réputation' },
    tier: (r: number) => (r < 30 ? 'Inconnu' : r < 50 ? 'Régional' : r < 70 ? 'National' : r < 85 ? 'Continental' : 'Mondial'),
    badge: 'Diplôme d’entraîneur', badgeNext: (b: string, n: number) => `${b} après ${n} matchs dirigés`, badgeTop: 'Le plus haut diplôme',
    seasons: 'Saison après saison', now: 'Maintenant', noSeasons: 'Ta première saison s’écrit encore.',
    records: 'Records', recs: { bigWin: 'Plus large victoire', mostPoints: 'Plus de points', mostGoals: 'Plus de buts', unbeaten: 'Plus longue invincibilité', scorer: 'Meilleur buteur sur une saison', bestFinish: 'Meilleur classement', bestBuy: 'Achat record', bestSale: 'Vente record' },
    jobs: 'Des clubs s’intéressent à toi', noJobs: 'Personne n’appelle. Gagne des choses et ils appelleront.', take: 'Accepter le poste', decline: 'Pas intéressé',
    courses: 'Formations', courseBuy: (v: string) => `S’inscrire · ${v}`, done: 'Terminé',
    wallet: 'Ton argent',
    lift: (season: string, club: string) => `${season} · ${club}`,
    trophyKinds: { league: 'Titre de champion', cup: 'Coupe', continental: 'Coupe continentale', promotion: 'Montée' },
    milestones: 'Étapes',
    sacked: 'Limogé', objMet: 'Objectif atteint', objMissed: 'Objectif manqué',
  },

  pass: {
    concept: 'Concept · rien n’est vendu ici',
    title: 'Le Semba Club Pass', lead: 'Pour ceux qui veulent soutenir le studio. Il n’achète jamais de résultats, de joueurs ni de forme.',
    price: '4,99 $', per: 'par mois, pour The Gaffer et Tier One',
    perks: [['Aucune pub dans les deux jeux', 'Les pubs récompensées disparaissent aussi'], ['400 Semba Credits par mois', 'Pour les maillots, blasons et thèmes'], ['Un thème par mois, à garder', 'Même si tu arrêtes'], ['Le badge du pass', 'Sur ta carte d’entraîneur']],
    cta: 'Bientôt',
    note: 'Sur le web, le pass et les crédits sont un aperçu. Les achats n’ouvriront que lorsqu’ils pourront être vérifiés.',
    credits: 'Semba Credits', balance: (n: number) => `${n} cr`, creditsSub: 'Stockés sur cet appareil uniquement. Partagés avec Tier One dans le même navigateur.',
    earn: 'Regarder une pub · +25 cr', earned: '+25 crédits.', adsOff: 'Les pubs ne sont pas activées dans cette version.', daily: (n: number) => `${n} sur 4 aujourd’hui`,
    never: 'Ce que l’argent n’achète jamais', nevers: ['De meilleurs joueurs ou de meilleures notes', 'Des résultats ou de la forme', 'Une progression plus rapide', 'Quoi que ce soit dans le défi du jour ou un classement'],
    looks: 'Thèmes', lookNames: ['Nuit bordeaux', 'Bleu du port', 'Or du désert'], lookPrice: '250 cr · concept',
    items: 'Aussi prévu', itemList: [['Créateur de maillots et de blasons', '400 cr'], ['Emplacement de sauvegarde en plus', '300 cr'], ['Pack de scénarios : trois sauvetages', '500 cr']],
  },

  set: {
    title: 'Réglages', lang: 'Langue', names: 'Noms des joueurs et des clubs', namesReal: 'Vrais noms', namesFictional: 'Noms fictifs',
    namesHelp: 'Le mode fictif garde chaque note, chaque chiffre et chaque couleur, et ne change que les noms. Tu peux revenir en arrière.',
    namesLocked: 'Cette carrière a été créée dans l’ancien monde fictif ; elle reste fictive.',
    sim: '« Simuler jusqu’à la prochaine décision » s’arrête pour', stopAll: 'Toute décision', stopImportant: 'Les importantes', stopBig: 'Aussi les gros matchs',
    match: 'Match', speed: 'Vitesse par défaut', speeds: ['1×', '2×', '4×'], sound: 'Public et sifflet',
    balance: 'Difficulté', saves: 'Sauvegardes', export: 'Exporter cette carrière', import: 'Importer une carrière', exportSub: 'Un fichier .gaffer à garder', importSub: 'Depuis un fichier .gaffer',
    reset: 'Supprimer cette carrière', resetAsk: 'Supprimer cette carrière de cet appareil ?', resetBody: 'C’est irréversible. Exporte-la d’abord si tu risques d’en avoir besoin.', del: 'La supprimer', keep: 'La garder',
    about: 'À propos', howTo: 'Comment jouer', privacy: 'Confidentialité', version: (v: string, b: number) => `The Gaffer ${v} · build ${b}`,
    motion: 'Les animations suivent le réglage « réduire les animations » de ton appareil.',
    world: 'Éditeur du monde', worldSub: 'Renommer les clubs, déplacer les championnats', quick: 'Match rapide',
    menu: 'Écran titre', importOk: 'Carrière importée.', importBad: 'Ce fichier n’a pas passé la vérification.',
  },
  log: {
    'training:focus': (f: string) => `Semaine « ${f.toLowerCase()} ».`,
    'tactics:plan': (ph: string) => `On passe en « ${ph} » pour le prochain match.`,
    'tactics:mentality': () => 'A changé notre état d’esprit pour le prochain match.',
    'tactics:formation': (f: string) => `A changé le système en ${f}.`,
    'scouting:report': (club: string) => `A regardé ${club} en vidéo et écrit le rapport.`,
    'morale:talk': (n: number) => `A parlé au groupe : le vestiaire était à ${n}.`,
  },
  news: { title: 'Actus et messages', inbox: 'Messages', news: 'Actus', empty: 'Journée calme.', read: 'Tout marquer comme lu' },
  season: {
    title: (y: string) => `La saison ${y} est terminée`, finish: (p: string, obj: string) => `On finit ${p}. La direction voulait : ${obj.toLowerCase()}.`,
    met: 'Mission accomplie.', missed: 'Pas assez bien.', up: 'Promus', down: 'Relégués', stay: 'On reste',
    next: (y: string) => `Lancer ${y}`, finishRest: 'Terminer les autres championnats', left: 'Ont quitté le club', kids: 'Montés du centre de formation', retired: (n: number) => `${n} joueurs ont pris leur retraite dans le monde.`,
  },
  common: {
    free: 'Libre', perMonth: '/mois', yrs: (n: number) => `${n} ${P(n, 'an', 'ans')}`, matchday: (n: number) => `Journée ${n}`,
    pos: { GK: 'G', CB: 'DC', LB: 'DG', RB: 'DD', CDM: 'MDC', CM: 'MC', CAM: 'MOC', LW: 'AG', RW: 'AD', ST: 'BU' },
    posLong: { GK: 'Gardien', CB: 'Défenseur central', LB: 'Latéral gauche', RB: 'Latéral droit', CDM: 'Milieu défensif', CM: 'Milieu central', CAM: 'Milieu offensif', LW: 'Ailier gauche', RW: 'Ailier droit', ST: 'Avant-centre' },
    group: ['Gardiens', 'Défenseurs', 'Milieux', 'Attaquants'],
    none: 'Aucun', yes: 'Oui', no: 'Non', cancel: 'Annuler', save: 'Enregistrer', done: 'Terminé',
  },
};
