// Copy for Tactics v3: phase shapes, roles, the new instructions, the engine preview, risk warnings and what the roles
// did (the Why card). English is the reference; lang-tac-{ar,es,fr}.ts are type-checked against it.
// Voice: the coach at the whiteboard. What the role does, then what it costs.
import type { RoleId } from './sim/engine/roles';

type Role = [name: string, short: string, what: string];
export const TX_EN = {
  phase: { ip: 'With the ball', oop: 'Without the ball' } as Record<'ip' | 'oop', string>,
  phaseLong: { ip: 'In possession', oop: 'Out of possession' } as Record<'ip' | 'oop', string>,
  shapeIp: 'Shape with the ball',
  shapeOop: 'Shape without the ball',
  same: 'Same',
  roles: {
    keeper: ['Goalkeeper', 'GK', 'Stays in goal and plays it short to his defenders.'],
    distributor: ['Distributor', 'DIS', 'Joins the build-up as an extra passer. Needs good feet: a nervous passer gets caught.'],
    defender: ['Centre-back', 'CB', 'Defends first and plays the simple pass.'],
    ball_player: ['Ball-playing defender', 'BPD', 'Carries it into midfield and looks for the forward pass. Needs passing.'],
    fullback: ['Full-back', 'FB', 'Supports from behind the play and stays available at the back.'],
    wingback: ['Wing-back', 'WB', 'Bombs on to the touchline: an extra man on the flank, a gap behind him. Tiring.'],
    inverted_fullback: ['Inverted full-back', 'IFB', 'Steps inside into midfield: an extra passer in the middle, less width.'],
    holder: ['Holding midfielder', 'DM', 'Sits in front of the defence and recycles the ball.'],
    playmaker: ['Playmaker', 'PM', 'Everything goes through him: more chances for others, fewer shots of his own. Needs passing.'],
    midfielder: ['Central midfielder', 'CM', 'Links the defence and the attack.'],
    box_to_box: ['Box-to-box', 'B2B', 'Arrives late in the box: more shots from midfield. Needs legs and tires quicker.'],
    attacking_mid: ['Attacking midfielder', 'AM', 'Plays between the lines and feeds the forwards.'],
    shadow_striker: ['Shadow striker', 'SS', 'Runs beyond the striker into the box: more shots, fewer passes.'],
    winger: ['Winger', 'W', 'Stays wide, takes his man on and crosses.'],
    inside_forward: ['Inside forward', 'IF', 'Cuts inside: shots and cut-backs instead of crosses.'],
    advanced_forward: ['Striker', 'ST', 'Plays on the last defender and attacks the box.'],
    target_man: ['Target man', 'TM', 'A focal point: long balls and crosses go to his head. Needs strength.'],
    false_nine: ['False 9', 'F9', 'Drops into midfield to link play: more chances for others, fewer bodies in the box.'],
    line_keeper: ['Keeper', 'GK', 'Stays on his line.'],
    sweeper_keeper: ['Sweeper keeper', 'SK', 'Comes off his line for balls in behind. A long shot can catch him out.'],
    hold_line: ['Hold the line', 'HL', 'Keeps his place in the back line.'],
    step_out: ['Step out', 'SO', 'Meets his man early: wins it higher up, fouls more, leaves space behind.'],
    screen: ['Screen', 'SCR', 'Drops in front of the defence and shuts the middle. Doesn’t press high.'],
    ball_winner: ['Ball winner', 'BW', 'Hunts the ball in midfield: wins it back, fouls more, leaves a hole. Tiring.'],
    hold_shape: ['Hold the shape', 'HS', 'Keeps his place in the block.'],
    track_back: ['Track back', 'TB', 'Follows the runner on his side back.'],
    press_forward: ['Lead the press', 'PR', 'Chases their defenders and keeper: turnovers high up, more fouls. Very tiring.'],
    libero: ['Libero', 'LIB', 'Steps out of the back line into midfield with the ball: an extra passer, a risk if he loses it.'],
    half_back: ['Half-back', 'HB', 'Drops between the centre-backs to start the play: a cleaner build-up, one fewer in midfield.'],
    mezzala: ['Mezzala', 'MEZ', 'Drifts into the half-space and arrives in the box: shots and chances from wide of the middle. Tiring.'],
    wide_playmaker: ['Wide playmaker', 'WP', 'Comes inside from the flank to make the play: more chances for others, fewer crosses.'],
    deep_forward: ['Deep-lying forward', 'DLF', 'Drops to hold it up and link the play, then joins the attack.'],
    poacher: ['Poacher', 'P', 'Lives on the last defender and in the box: more shots, hardly involved in the build-up.'],
    cover: ['Cover', 'CO', 'Drops off to sweep up balls in behind: fewer runs get through, more room in front of him.'],
    press_fullback: ['Press the full-back', 'PFB', 'Goes at their full-back when he gets it: wins it higher on his flank. Tiring.'],
    tuck_in: ['Tuck in', 'TI', 'Narrows into midfield without the ball: shuts the middle, leaves their full-back free.'],
    outlet: ['Stay up', 'UP', 'Doesn’t defend: waits for the break. Faster counters, one fewer in the block.'],
  } as Record<RoleId, Role>,
  roleFor: (phase: string): string => `Role · ${phase}`,
  fit: ['Natural', 'Good fit', 'Can do it', 'Poor fit'] as [string, string, string, string],
  suggest: 'Suggest roles', suggested: 'Roles set to suit the players',
  ins: {
    build: ['Build-up', ['Play out', 'Mixed', 'Go long']],
    cpress: ['When we lose it', ['Regroup', 'Balanced', 'Counter-press']],
    counter: ['When we win it', ['Keep it', 'Break at once']],
    trap: ['Pressing trap', ['None', 'Wings', 'Centre', 'Half-spaces']],
    routine: ['Corners', ['Mixed', 'Big men up', 'Short']],
    marking: ['Marking', ['Zonal', 'Mixed', 'Man']],
    setMark: ['Marking at set pieces', ['Zonal', 'Mixed', 'Man']],
  } as Record<'build' | 'cpress' | 'counter' | 'trap' | 'routine' | 'marking' | 'setMark', [string, string[]]>,
  trade: {
    build: [['Keeper and centre-backs pass it out: more of the ball.', 'A good press wins it near our goal.'], ['Short when it’s on, long when it isn’t.', 'Neither here nor there.'], ['Skips their press.', 'More fifty-fifties; we give it back more.']],
    cpress: [['Everyone drops: their counters dry up.', 'They keep the ball once they have it.'], ['Some chase, some drop.', 'Nothing special.'], ['Win it straight back high up.', 'Tiring; more tactical fouls; bypass it and they’re away.']],
    counter: [['We keep it and build again.', 'Fewer quick chances.'], ['Break the moment we win it.', 'Midfielders sit deeper to launch it.']],
    trap: [['No trap.', 'No trap.'], ['Show them wide and swarm the touchline.', 'The middle is a bit looser.'], ['Force them away from the middle.', 'The flanks are a bit looser.'], ['Press every lane a little.', 'Nowhere is really shut.']],
    routine: [['A mix of deliveries.', 'Nothing special.'], ['Centre-backs go up: more headers.', 'Fewer at the back if it breaks down.'], ['Work it short and keep it.', 'Fewer shots from the corner itself.']],
    marking: [['Everyone holds his area: little room between the lines; fewer fouls.', 'Runners from wide and into the box find space.'], ['Zones, and the nearest man picks up a runner.', 'Nothing special.'], ['Each takes his man: tight on the flanks and in the air.', 'Markers get pulled out of shape: more room in the middle; more fouls.']],
    setMark: [['Players hold zones in the box: first contact at the near post.', 'Attackers running onto it win more headers.'], ['A few hold zones, the rest pick up a man.', 'Nothing special.'], ['Each takes a man in the box: fewer free headers.', 'The second ball at the edge of the box is left open.']],
  } as Record<'build' | 'cpress' | 'counter' | 'trap' | 'routine' | 'marking' | 'setMark', [string, string][]>,
  trapOff: 'A trap needs a press: set Press to Mid-block or higher.',
  mark: 'Man-mark', markNone: 'Nobody', markHint: 'He wins far fewer duels; his marker leaves a hole.',
  preview: {
    title: 'What the engine sees',
    sub: 'Players in each zone, ours v theirs, from the same numbers the match uses',
    rest: (n: string): string => `${n} stay back when we attack`,
    line: (n: number): string => `Back line at ${n}% of the pitch`,
    press: (n: string): string => `${n} press their build-up`,
    box: (n: string): string => `${n} attack the box`,
    zones: { build: 'Build-up', mid: 'Midfield', final: 'Final third', box: 'Box', press: 'Their build-up', screen: 'Midfield', defend: 'Our third' },
  },
  warn: {
    title: 'Risks',
    none: 'Nothing obvious. The engine agrees with the plan.',
    fit: (p: string, role: string): string => `${p} is a poor fit as ${role}: the role works at half strength and he plays below his level.`,
    rest: (n: string): string => `Only ${n} stay back when we attack. Lose it and we’re open to the counter.`,
    pressAlone: (p: string, role: string): string => `${p} is told to ${role.toLowerCase()} while the team sits off: he chases alone and gets bypassed.`,
    trapOff: 'The pressing trap does nothing without a press.',
    slowLine: (p: string): string => `${p} lacks the pace for a high line: balls in behind will hurt.`,
    noBox: 'Crosses and long balls, but hardly anyone in the box to meet them.',
    outlets: (n: number): string => `${n} players stay up without the ball: the block is short of bodies.`,
  },
  why: {
    won: (a: string, role: string, n: number): string => `${a} won it back ${n} times as ${role}.`,
    shots: (a: string, role: string, n: number, x: string): string => `${a} got ${n} shots away as ${role} (${x} xG).`,
    made: (a: string, role: string, n: number, x: string): string => `${a} set up ${n} chances as ${role} (${x} xG).`,
    themWon: (a: string, role: string, n: number): string => `Their ${role.toLowerCase()} ${a} won it back ${n} times.`,
    themShots: (a: string, role: string, n: number, x: string): string => `Their ${role.toLowerCase()} ${a} got ${n} shots away (${x} xG).`,
    themMade: (a: string, role: string, n: number, x: string): string => `Their ${role.toLowerCase()} ${a} set up ${n} chances (${x} xG).`,
    head: ['The role that worked', 'Their role that hurt us'] as [string, string],
  },
  change: (p: string, role: string): string => `${p}: ${role}`,
  live: { roles: 'Roles', rolesSub: 'Changes take effect from the next minute.' },
};
export type TxStrings = typeof TX_EN;
