// V2.6 Training & pathway, French. Type-checked against lang-youth.ts.
import type { YStrings } from './lang-youth';

const P = (n: number, one: string, many: string) => (n <= 1 ? one : many);
const TIERS = ['un solide', 'un prometteur', 'un enthousiasmant', 'un exceptionnel'];

export const Y_FR: YStrings = {
  doors: { train: 'Semaine d’entraînement', medical: 'Staff médical', academy: 'Centre de formation' },
  bands: ['Faible', 'Élevée', 'Forte'],
  intens: ['Légère', 'Normale', 'Intense'],
  tiers: ['un solide', 'un prometteur', 'un enthousiasmant', 'un exceptionnel'],

  tw: {
    title: 'Semaine d’entraînement',
    head: (i: number, focus: string, plans: number): string => `Semaine ${['légère', 'normale', 'intense'][i]}, axée sur ${focus.toLowerCase()}. ${plans ? `${plans} en travail spécifique.` : 'Personne en travail spécifique.'}`,
    intensity: 'Intensité',
    intFx: ['Progression ×0,7. Les jambes récupèrent plus vite.', 'Progression ×1,0. La semaine habituelle.', 'Progression ×1,4. Charge +4 par jour, et les pépins arrivent.'],
    congested: 'Deux matchs cette semaine : pas d’intensité maximale.',
    dropped: 'L’intensité a été levée la semaine dernière : deux matchs.',
    focus: 'Le thème de la semaine',
    load: 'Charge',
    loadSub: 'Qui peut encore enchaîner quatre-vingt-dix minutes',
    loadHidden: 'Un préparateur physique noté 60+ vous donne les chiffres exacts.',
    loadN: (n: number): string => `Charge ${n}`,
    fragile: (n: number): string => `Fragile · ${n} ${P(n, 'match', 'matchs')}`,
    riskX: (x: string): string => `Risque de blessure ×${x}`,
    allFresh: 'Tout le monde peut rejouer.',
    plans: 'Programmes individuels',
    plansN: (n: number, max: number): string => `${n} sur ${max}`,
    plansNone: 'Personne en travail spécifique. Jusqu’à cinq joueurs possibles.',
    plansFull: 'Cinq au maximum. Retirez quelqu’un d’abord.',
    add: 'Ajouter un programme',
    who: 'Joueur',
    attr: 'Travailler une qualité',
    pos: 'Apprendre un nouveau poste',
    attrFx: 'Progression +10 %, le point en plus va à cette qualité, charge +2 par jour.',
    posFx: 'Environ onze journées de travail en plus. Progression −10 % pendant ce temps.',
    learning: (pos: string, pct: number): string => `Apprend ${pos} · ${pct} %`,
    sharpening: (a: string): string => `Travaille ${a}`,
    also: (pos: string): string => `Joue aussi ${pos}`,
    remove: 'Retirer',
    save: 'Lancer le programme',
    report: 'La semaine dernière',
    up: (n: number): string => (n ? `${n} ${P(n, 'a franchi', 'ont franchi')} un palier` : 'Personne n’a franchi de palier'),
    near: 'Tout près du palier suivant',
    knocks: (n: number): string => `${n} ${P(n, 'a pris', 'ont pris')} un coup`,
    academyUp: (n: number): string => `${n} au centre de formation ${P(n, 'a progressé', 'ont progressé')}`,
    quiet: 'Rien n’a bougé cette semaine. Ça viendra.',
  },

  md: {
    title: 'Staff médical',
    head: (out: number, edge: number): string => (out || edge ? `${out} ${P(out, 'blessé', 'blessés')}, ${edge} dans le rouge.` : 'Tout le monde est apte.'),
    out: 'Salle de soins',
    back: (lo: number, hi: number): string => (lo === hi ? `De retour dans ${lo} ${P(lo, 'journée', 'journées')}` : `De retour dans ${lo} à ${hi} journées`),
    orig: (n: number): string => `Absent ${n} journées au départ`,
    fog: (who: string): string => `Estimation de ${who}. Un meilleur médecin l’affine.`,
    fogNone: 'Pas de médecin au club : c’est une supposition.',
    rush: 'Accélérer le retour',
    rushFx: (gain: number, risk: number): string => `${gain} ${P(gain, 'journée', 'journées')} plus tôt · ${risk} % de rechute`,
    rushNotYet: (n: number): string => `Retour accéléré possible à ${n} ${P(n, 'journée', 'journées')} de la fin`,
    edge: 'Dans le rouge',
    edgeSub: 'Jambes lourdes et jambes fragiles',
    thisMatch: (n: number): string => `~${n} % sur ce match`,
    none: 'Personne sur la table de soins.',
    noEdge: 'Personne n’en porte trop. Continuez à faire tourner.',
    rest: 'Le laisser souffler',
    unrest: 'Le rappeler',
  },

  ac: {
    title: 'Centre de formation',
    head: (n: number, loans: number, grads: number): string => `${n} au centre, ${loans} ${P(loans, 'prêté', 'prêtés')}, ${grads} en équipe première.`,
    countdown: (n: number): string => `Arrivée de la promo dans ${n} ${P(n, 'journée', 'journées')}`,
    countdownSub: 'Le directeur du centre n’a pas encore vu la promo de cette année.',
    preview: (tier: string, pos: string): string => `${tier.charAt(0).toUpperCase()}${tier.slice(1)} ${pos.toLowerCase()} dans la promo de cette année`,
    previewSub: (n: number): string => `Ils arrivent dans ${n} ${P(n, 'journée', 'journées')}. Le directeur du centre les a vus.`,
    arrived: (n: number): string => `Jour de la nouvelle promo. ${n} ${P(n, 'nouveau visage', 'nouveaux visages')}.`,
    classOf: (y: string): string => `La promo ${y}`,
    reveal: 'Les découvrir',
    standout: 'Le plus en vue',
    nextYear: 'La prochaine promo arrive la saison prochaine.',
    cap: (n: number, cap: number): string => `${n} places sur ${cap}`,
    over: 'Au-delà de sa capacité : chaque jeune progresse 15 % moins vite.',
    squad: 'Le centre de formation',
    empty: 'Le centre est vide jusqu’à l’arrivée de la promo.',
    ready: 'Prêt',
    late: 'Le temps presse',
    grown: (n: number): string => (n > 0 ? `+${n} cette saison` : n < 0 ? `${n} cette saison` : 'Stable cette saison'),
    promote: 'Faire monter',
    loan: 'Prêter',
    release: 'Libérer',
    word: 'Un mot',
    recall: 'Le rapatrier',
    loanTitle: (pn: string): string => `Où ${pn} doit-il jouer ?`,
    loanSub: 'Un club où il est titulaire lui donne de vraies minutes, et ce sont les minutes qui le font grandir.',
    roles: ['Titulaire', 'Rotation', 'Surtout remplaçant'],
    windowShut: 'Le mercato est fermé. Les prêts se font l’été et à la mi-saison.',
    tooYoung: 'Trop jeune pour être prêté (17 ans et plus).',
    noSpots: 'Aucun club de son niveau n’en veut encore.',
    releaseQ: (pn: string): string => `Libérer ${pn} ? Il devient libre et n’importe quel club peut le signer.`,
    loans: 'En prêt',
    loansNone: 'Personne en prêt. Au mercato, envoyez les suivants là où ils joueront.',
    mins: (n: number): string => `${n} min cette saison`,
    run: (n: number): string => `${n} ${P(n, 'match complet', 'matchs complets')} d’affilée`,
    grads: 'Formés au club',
    gradsNone: 'Aucun joueur formé au club en équipe première pour l’instant.',
    since: (from: number, now: number): string => `${from} → ${now}`,
    apps: (n: number): string => `${n} ${P(n, 'match', 'matchs')}`,
    path: ['Centre', 'Prêt', 'Équipe première'],
  },

  cv: {
    real: 'Historique réel',
    proj: 'Où il va',
    avg: 'Moyenne de notre onze',
    starts: (s: string): string => `Historique depuis ${s}`,
    one: 'L’historique commence ici : chaque journée est désormais enregistrée.',
    academy: 'Centre',
    homegrown: 'Formé au club',
    load: 'Charge',
    minutes: (n: number): string => `${n} min cette saison`,
  },

  tag: { risk: 'Médical', rush: 'Médical', intake: 'Nouvelle promo', ready: 'Formation', loanee: 'Rapport de prêt', benched: 'Rapport de prêt', full: 'Formation', ageout: 'Formation' },
  titles: {
    y_risk: (pn: string, n: number): string => `${pn} peut jouer, mais sa charge est à ${n}`,
    y_rush: (pn: string, n: number): string => `${pn} pourrait revenir avant ${n} ${P(n, 'journée', 'journées')}`,
    y_intake: (n: number): string => `Nouvelle promo : ${n} ${P(n, 'nouveau visage', 'nouveaux visages')}`,
    y_ready: (pn: string, n: number): string => `${pn} frappe à la porte avec ${n}`,
    y_loanee: (pn: string, n: number, club: string): string => `${pn} : ${n} matchs complets d’affilée à ${club}`,
    y_benched: (pn: string, club: string): string => `${pn} ne joue pas à ${club}`,
    y_full: (n: number, cap: string): string => `Le centre compte ${n} jeunes pour ${cap} places`,
    y_ageout: (pn: string, n: number): string => `${pn} a ${n} ans et il est toujours au centre`,
    ask_y_rush: (pn: string): string => `Accélérer le retour de ${pn} ?`,
    ask_y_rest: (pn: string): string => `Laisser souffler ${pn} au prochain match ?`,
    ask_y_loan: (pn: string, club: string): string => `Prêter ${pn} à ${club} ?`,
    ask_y_release: (pn: string): string => `Libérer ${pn} du centre ?`,
  },
  advice: {
    y_risk_rest: (_pn: string, n: number, sub: string): string => `Il peut jouer. Il peut aussi se claquer : environ ${n} % aujourd’hui. ${sub ? `${sub} est frais. ` : ''}Je le laisserais souffler.`,
    y_risk_rest_c: (pn: string, _n: number, sub: string): string => `Pas avec ces jambes. ${pn} reste en dehors${sub ? `, ${sub} entre` : ''}.`,
    y_risk_play: (_pn: string, n: number): string => `Il en porte beaucoup, mais ${n} %, c’est un risque que je prendrais. Qu’il joue, et on le sort tôt.`,
    y_risk_play_b: (_pn: string, n: number): string => `${n} % ? C’est le football. Qu’il joue.`,
    y_risk_rr: (pn: string, n: number): string => `On a accéléré le retour de ${pn}. Environ ${n} % de rechute aujourd’hui. Je le garderais au repos.`,
    y_rush_yes: (_pn: string, n: number): string => `Il a passé la moitié. Si on pousse, il revient plus tôt. ${n} % de rechute sur les trois prochains matchs. Je le ferais.`,
    y_rush_no: (_pn: string, n: number): string => `Je peux accélérer, mais il y a ${n} % de rechute, et plus longue. Laissons guérir.`,
    y_intake: (pn: string, pos: string, n: number): string => `Ils sont tous là. Surveillez ${pn} : ${TIERS[n] ?? 'un prometteur'} ${pos}. Il y a de la place pour tous.`,
    y_intake_full: (pn: string, pos: string, n: number): string => `${pn} est le bon : ${TIERS[n] ?? 'un prometteur'} ${pos}. Mais on dépasse la capacité. Si on garde tout le monde, tout le monde apprend moins vite.`,
    y_ready: (pn: string, n: number): string => `${pn} a le niveau de notre 18e joueur (${n}). L’entraînement avec les pros finira le travail.`,
    y_ready_v: (pn: string): string => `${pn} n’est pas loin. Je préfère qu’il joue d’abord chez les adultes ailleurs.`,
    y_loanee: (pn: string): string => `${pn} joue toutes les semaines. Il n’a pas encore passé de cap, mais ce sont ces minutes qui font grandir un joueur.`,
    y_loanee_up: (pn: string, n: number, s: string): string => `${pn} a ${s} minutes et il a pris ${n} cette saison. Laissons-le là-bas.`,
    y_benched: (pn: string, n: number): string => `${pn} n’a que ${n} minutes. On nous avait promis du temps de jeu. Rapatriez-le et trouvez-lui un club qui le fait jouer.`,
    y_full: (pn: string, n: number): string => `Trop de jeunes, pas assez d’encadrement. ${pn} est celui que je libérerais : plafond vers ${n}.`,
    y_ageout_keep: (pn: string, n: number): string => `${pn} a encore quelque chose, peut-être ${n}. Donnez-lui un numéro ou un prêt.`,
    y_ageout_go: (pn: string): string => `${pn} ne percera pas ici. Laissons-le trouver un club.`,
    why_y_rush: (pn: string, n: number): string => `${pn} a passé la moitié. ${n} % de risque, et on a besoin de lui.`,
    why_y_rest: (pn: string, n: number): string => `${pn} a les jambes lourdes. Environ ${n} % de se blesser.`,
    why_y_loan: (pn: string): string => `${pn} a besoin de jouer chez les adultes. Là-bas, il sera titulaire.`,
    why_y_release: (pn: string): string => `On dépasse la capacité et ${pn} a le moins de chances de percer.`,
  },
  choices: {
    y_ch_rush: (n: number): string => `Accélérer (${n} plus tôt)`,
    y_ch_heal: (): string => 'Laisser guérir',
    y_ch_spec: (v: string): string => `Spécialiste (${v})`,
    y_ch_keepAll: (): string => 'Les garder tous',
    y_ch_trim: (n: number): string => (n === 1 ? 'Libérer le plus faible' : `Libérer les ${n} plus faibles`),
    y_ch_promote: (): string => 'Le faire monter',
    y_ch_loan: (club: string): string => `Le prêter à ${club}`,
    y_ch_leave: (): string => 'Le laisser là-bas',
    y_ch_word: (): string => 'Lui dire qu’on le suit',
    y_ch_recall: (): string => 'Le rapatrier',
    y_ch_release: (pn: string): string => `Libérer ${pn}`,
  },
  fx: {
    y_fx_safe: (): string => 'Aucun risque aujourd’hui',
    y_fx_risk: (n: number): string => `Risque de blessure ~${n} %`,
    y_fx_fragile: (n: number): string => `Fragile encore ${n}`,
    y_fx_sooner: (n: number): string => `Retour ${n} plus tôt`,
    y_fx_relapse: (n: number): string => `${n} % de rechute`,
    y_fx_heal: (n: number): string => `Encore ${n} d’absence`,
    y_fx_room: (n: number, cap: string): string => `${n} places sur ${cap}`,
    y_fx_spread: (n: number, cap: string): string => `${n} pour ${cap} : progression ralentie`,
    y_fx_letGo: (n: number): string => `${n} sur la liste des libres`,
    y_fx_squad: (): string => 'Effectif pro',
    y_fx_proWage: (): string => 'Un salaire de pro',
    y_fx_starter: (): string => 'Il y serait titulaire',
    y_fx_rotation: (): string => 'Rotation là-bas',
    y_fx_academyPace: (): string => 'Rythme du centre',
    y_fx_growing: (n: number): string => (n > 0 ? `+${n} cette saison` : 'Des minutes en banque'),
    y_fx_morale: (): string => 'Moral en hausse',
    y_fx_home: (): string => 'Il perd ses minutes',
    y_fx_reloan: (): string => 'Le prêter ailleurs',
    y_fx_stall: (): string => 'Sa progression cale',
    y_fx_focus: (): string => 'Meilleur encadrement pour les autres',
    y_fx_free: (): string => 'Joueur libre',
  },

  news: {
    y_preview: (club: string, pos: string, tier: string): [string, string] => [`Au centre de ${club}, on parle d’${tier} ${pos.toLowerCase()}`, 'Le directeur du centre a vu la promo. Elle arrive dans dix journées.'],
    y_intake: (club: string, n: number, pn: string, pos: string): [string, string] => [`Nouvelle promo à ${club} : ${n} ${P(n, 'nouveau visage', 'nouveaux visages')}`, pn ? `Celui que tout le monde regardait : ${pn}, ${pos.toLowerCase()}.` : 'Un nouveau groupe commence aujourd’hui.'],
    y_rivalGem: (club: string, pn: string, pos: string, tier: string): [string, string] => [`${club} présente ${tier} ${pos.toLowerCase()}`, `${pn} rejoint leur centre. Retenez ce nom.`],
    y_breakthrough: (pn: string, club: string, n: string): [string, string] => [`${pn}, ${n} ans, s’impose à ${club}`, 'Dix matchs de championnat cette saison pour le joueur formé au club.'],
    y_loaned: (pn: string, club: string): [string, string] => [`${pn} prêté à ${club}`, 'Le jeune du centre part chercher du temps de jeu.'],
  },
  msg: {
    y_preview: (pn: string, pos: string, tier: string): [string, string] => [`Directeur du centre : ${tier} ${pos.toLowerCase()} dans la promo`, `J’ai vu le nouveau groupe. Surveillez ${pn}. Ils arrivent dans dix journées.`],
    y_learned: (pn: string, pos: string): [string, string] => [`${pn} peut désormais jouer ${pos}`, 'Le travail en plus a payé. La compo le prendra en compte à ce poste.'],
    y_reinjured: (pn: string, n: number): [string, string] => [`${pn} rechute`, `On a accéléré son retour. Il est absent ${n} journées de plus.`],
    y_loanReport: (pn: string, n: number, s: string, club: string): [string, string] => [`Rapport de prêt : ${pn} à ${club}`, `${n} minutes cette saison, ${Number(s) > 0 ? `+${s}` : Number(s) < 0 ? `${s}` : 'stable'} depuis l’été.`],
    y_devGone: (n: number): [string, string] => ['Fin des points de développement', `Les ${n} points restants sont devenus du moral pour l’effectif (+5). Désormais, on progresse à l’entraînement et en jouant.`],
  },
  log: {
    'medical:y_rush': (pn: string, n: number): string => `A accéléré le retour de ${pn} (${n} % de rechute)`,
    'medical:y_rest': (pn: string, n: number): string => `A laissé souffler ${pn} : ~${n} % de risque`,
    'academy:y_loan': (pn: string, club: string): string => `A prêté ${pn} à ${club}`,
    'academy:y_release': (pn: string): string => `A libéré ${pn} du centre`,
    'academy:promote': (pn: string): string => `A fait monter ${pn} en équipe première`,
  },
  note: { rushed: 'Il a repris l’entraînement.', promoted: 'Il a un maillot de l’équipe première.' },
  no: {
    congested: 'Deux matchs cette semaine : pas d’intensité maximale.', plans: 'Cinq programmes au maximum.', notYet: 'Trop tôt pour le pousser.', retired: 'Ça n’existe plus : la nouvelle promo l’a remplacé.',
    young: 'Trop jeune pour ça.', pos: 'Choisissez un poste qu’il ne joue pas déjà.', load: 'Choisissez légère, normale ou intense.', unknown: 'Ça n’existe plus.',
  },
};
