// غرفة اللبس (V2.4) بالمصري: كلام الدكة، مش كلام مكاتب. متراجعة على الإنجليزي (lang-dressing.ts).
import type { DStrings } from './lang-dressing';

type Pair = [string, string];
const N = (n: number, one: string, many: string) => (n === 1 ? one : `${n} ${many}`);

export const D_AR: DStrings = {
  title: 'غرفة اللبس',
  eyebrow: (club: string) => `${club} · جوه الأوضة`,
  mood: {
    together: ['الأوضة ', 'معاك', '.'], settled: ['الأوضة ', 'هادية', '.'],
    restless: ['الأوضة ', 'مش مرتاحة', '.'], split: ['الأوضة ', 'متقسمة', '.'],
  },
  moodSub: {
    together: 'نفس الوشوش، نتايج حلوة، ومصدقين كلامك.',
    settled: 'مفيش مشاكل جوه. ومفيش حاجة زيادة برضه.',
    restless: 'في كام واحد مستنيين يشوفوا هتعمل إيه.',
    split: 'كتير منهم بطلوا يسمعوا. صلّحها قبل ما تدفع تمنها في الملعب.',
  },
  facts: { coh: 'تماسك', morale: 'معنويات', trust: 'ثقة', open: (n: number) => (n === 1 ? 'وعد مفتوح' : 'وعود مفتوحة') },
  coh: {
    title: 'التماسك', causes: 'إيه اللي حرّكه', none: 'لسه محدش حرّكه.',
    worth: (v: string) => `يساوي ${v} يوم الماتش قدام فريق عادي`,
    scale: ['متفرتكة', 'عادي', 'إيد واحدة'],
    how: 'بيزيد لما تثبّت نفس التشكيلة وتكسب. الصفقات الجديدة بتلخبطه ست جولات. وخذلان واحد من الكبار بيوجعه أكتر حاجة.',
  },
  cause: {
    settled: () => 'نفس التشكيلة تاني', win: () => 'فوز', loss: () => 'خسارة', drift: () => 'بيهدى',
    bedIn: () => 'الجداد بيتأقلموا', arrival: (pn: string) => `${pn} وصل`,
    leaderBroken: (pn: string) => `وعدك لـ${pn}`, leaderRequest: (pn: string) => `${pn} طلب يمشي`,
    leaderSold: (pn: string) => `${pn} مشي`, armLeader: (pn: string) => `${pn} لبس الشارة`, armFringe: (pn: string) => `${pn} لبس الشارة`,
  },
  tiers: { leader: 'الكبار', core: 'العمود', fringe: 'على الطرف' },
  tierSub: { leader: 'مودهم بيبقى مود الكل.', core: 'عمود الفريق الفقري.', fringe: 'مستنيين فرصة.' },
  leadersSub: 'الأوضة بتسمعلهم. ومعنوياتهم بتشد الباقي.',
  captain: 'الكابتن', armband: 'الشارة', noCaptain: 'محدش لابس الشارة.',
  pickCaptain: 'مين يلبس الشارة؟', pickCaptainSub: 'واحد من الكبار بيرفع الأوضة. واحد على الطرف بيكلّفها.',
  give: 'اديله الشارة',
  word: 'كلمتك', noWord: 'مفيش وعود مفتوحة. محدش ماسك عليك حاجة.',
  status: { open: 'ماشي تمام', slip: 'بيفلت', lost: 'راح', kept: 'اتنفّذ', broken: 'اتكسر' },
  groups: ['حارس', 'مدافع', 'لاعب وسط', 'مهاجم'],
  pledge: (key: string, group: string) => ({
    'role.star': 'إنه نجم الفريق', 'role.starter': 'إنه يلعب أساسي', 'role.rotation': 'دقايق في التدوير', 'role.prospect': 'طريق للفريق الأول',
    contract: 'عقد جديد', keep: 'إنه مش هيتباع الميركاتو ده', sign: `${group} جديد`,
  } as Record<string, string>)[key.startsWith('sign') ? 'sign' : key] ?? key,
  progress: {
    role: (st: number, el: number, need: number, left: number) => `لعب أساسي ${st} من ${el}. الدور محتاج ${need}%، وفاضل ${N(left, 'جولة', 'جولات')}.`,
    prospect: (apps: number, left: number) => `${apps} ماتشات من 10. فاضل ${N(left, 'جولة', 'جولات')} في الدوري، أو إعارة.`,
    contract: (left: number) => `عقد جديد خلال ${N(left, 'جولة', 'جولات')}.`,
    sign: () => 'قبل ما الميركاتو يقفل.',
    keep: () => 'لحد ما الميركاتو يقفل.',
    kept: 'خد باله.', broken: 'مش هينساها.',
  },
  waiting: 'عايز كلمة', unsettled: 'عايز يمشي', talkBtn: 'كلّمه',
  role: { star: 'نجم', starter: 'أساسي', rotation: 'تدوير', prospect: 'موهبة' },
  roleSub: { star: 'أساسي 7 من 10', starter: 'أساسي في نص الماتشات', rotation: 'أساسي 1 من 4', prospect: '10 ماتشات أو إعارة' },
  arch: { driven: 'طموح', steady: 'رزين', volatile: 'متقلب', loyal: 'وفي', mercenary: 'مصلحجي', leader: 'قائد بطبعه' },
  archSub: {
    driven: 'الزقة بتنفع معاه أكتر من الطبطبة.', steady: 'صعب يتهز، وصعب يترفع.', volatile: 'المدح بيطيّره والنقد بيوقعه.',
    loyal: 'بيسامح أكتر من غيره.', mercenary: 'الكلام أقل من الفلوس عنده.', leader: 'الأوضة ماشية على مزاجه.',
  },
  trust: 'الثقة', morale: 'المعنويات',
  cause2: {
    press: 'كلامك في المؤتمر الصحفي',
    'kept.role': 'وعد اتنفّذ', 'kept.contract': 'وعد اتنفّذ', 'kept.keep': 'وعد اتنفّذ', 'kept.sign': 'وعد اتنفّذ',
    'broken.role': 'وعد اتكسر', 'broken.contract': 'وعد اتكسر', 'broken.keep': 'وعد اتكسر', 'broken.sign': 'وعد اتكسر',
    minutes: 'مش بيلعب كفاية', ignored: 'استناك ومجيتش', 'talk.reassure': 'طبطبتك عليه', 'talk.challenge': 'تحدّيك ليه',
    'talk.promise': 'وعدك', armband: 'الشارة', armLost: 'خسر الشارة', listed: 'اتعرض للبيع زي ما طلب', refused: 'طلبه اترفض',
    stayed: 'فضل', renewed: 'عقد جديد', win: 'الفوز', loss: 'الخسارة', draw: 'التعادل', drift: 'بيهدى', leaderBroken: 'واحد من الكبار اتخذل',
  },
  talk: {
    btn: 'كلّمه', title: (pn: string) => `كلمة مع ${pn}`,
    why: {
      asked: 'طلب يقابلك.', request: 'طلب يمشي.', broken: 'إنت كسرت وعدك ليه.', minutes: 'مش بيلعب قد ما دوره بيقول.',
      role: 'بيلعب أكبر من الدور اللي في عقده.', contract: 'عقده قرّب يخلص.', unhappy: 'نفسيته واقعة.', doubts: 'بطّل يصدقك.',
      new: 'لسه جديد هنا. أول انطباع بيفرق.', form: 'كان أحسن واحد في الملعب.',
    },
    none: 'مفيش حاجة تتقال. هو عارف مكانه.',
    wait: 'كلّمته الأسبوع ده. سيبه كام يوم.',
    tones: { reassure: ['طمّنه', 'إيدك على كتفه'], challenge: ['تحدّاه', 'قوله إنت مستني منه إيه'], promise: ['اديله كلمتك', 'وعد هيحاسبك عليه'] },
    staff: 'قراية الجهاز',
    choose: 'هتوعده بإيه؟',
    types: { role: 'دوره', sign: 'صفقة', keep: 'مش للبيع', contract: 'عقد جديد' },
    bind: {
      'role.star': 'يلعب أساسي 7 من الـ10 ماتشات الجاية في الدوري وهو جاهز. لو معملتهاش: الثقة −20.',
      'role.starter': 'يلعب أساسي نص الـ10 ماتشات الجاية في الدوري وهو جاهز. لو معملتهاش: الثقة −20.',
      'role.rotation': 'يلعب أساسي 1 من 4 في الـ10 ماتشات الجاية. لو معملتهاش: الثقة −20.',
      'role.prospect': '10 ماتشات في الـ20 جولة الجاية، أو إعارة. لو معملتهاش: الثقة −20.',
      contract: 'عقد جديد على الترابيزة خلال 8 جولات. لو معملتهاش: الثقة −20.',
      keep: 'ميتباعش قبل ما الميركاتو يقفل. لو بعته، الأوضة كلها هتشوف.',
      sign: 'صفقة جديدة في المركز ده قبل ما الميركاتو يقفل. لو معملتهاش: الثقة −20.',
    },
    signPos: 'أنهي مركز؟',
    giveBtn: 'اديله كلمتك', back: 'رجوع', done: 'تمام',
    delta: (label: string, d: number) => `${label} ${d > 0 ? '+' : d < 0 ? '−' : '±'}${Math.abs(d)}`,
    withdrew: 'سحب طلب الرحيل.',
    reply: {
      'reassure.driven': 'ماشي. أنا بس عايز ألعب.', 'reassure.steady': 'فاهم يا كوتش.', 'reassure.volatile': 'الكلام ده فرق معايا. بجد.',
      'reassure.loyal': 'عارف إنك في ضهري.', 'reassure.mercenary': 'كلام حلو.', 'reassure.leader': 'تمام. هقول للرجالة.',
      'challenge.driven': 'هتشوف. ركّز معايا.', 'challenge.steady': 'وصلت.', 'challenge.volatile': 'هو ده رأيك فيا؟',
      'challenge.loyal': 'مش هخذلك.', 'challenge.mercenary': 'هنشوف مين محتاج مين.', 'challenge.leader': 'عندك حق. أنا اللي هحط المستوى.',
      'promise.steady': 'يبقى اتفقنا.', 'promise.driven': 'هحاسبك عليها.', 'promise.mercenary': 'المرة الجاية اكتبها.',
      'promise.cold': 'سمعت وعود قبل كده.', 'reassure.heard': 'قلت كده المرة اللي فاتت.', 'challenge.cold': 'منك إنت؟ غريبة.',
      'praise.volatile': 'أخبط في حيطة عشانك.', 'praise.steady': 'شكراً يا كوتش. والأسبوع الجاي كمان.',
    },
  },
  no: {
    'dr.nothing': 'مفيش حاجة تتقال. هو عارف مكانه.', 'dr.pledged': 'إنت ادّيته كلمة في حاجة قبل كده.',
    'dr.window': 'بس والميركاتو مفتوح.', 'dr.role': 'كبر على إنه يبقى موهبة.', 'dr.long': 'عقده لسه فيه سنين.',
    'dr.group': 'اختار مركز.', 'dr.already': 'هو لابسها أصلاً.', 'dr.noRequest': 'مطلبش يمشي.',
    wait: 'كلّمته الأسبوع ده. سيبه كام يوم.', gone: 'مبقاش بتاعنا.', trust: 'مش واثق فيك كفاية عشان يمضي.',
    loaned: 'معار.', terms: 'الشروط دي مش ماشية.', role: 'كبر على إنه يبقى موهبة.',
  },
  tag: { talk: 'كلمة', request: 'عايز يمشي', promise: 'كلمتك', armband: 'الشارة', clause: 'الشرط الجزائي' },
  titles: {
    'ask.asked': (pn: string) => `${pn} عايز كلمة`, 'ask.broken': (pn: string) => `${pn} عايز يكلمك عن وعدك`,
    'ask.minutes': (pn: string) => `${pn} عايز يعرف ليه مش بيلعب`, 'ask.role': (pn: string) => `${pn} عايز دور أكبر`,
    'ask.contract': (pn: string) => `${pn} عايز يتكلم في مستقبله`, 'ask.unhappy': (pn: string) => `${pn} عايز كلمة`,
    'ask.doubts': (pn: string) => `${pn} عنده شكوك`, 'ask.request': (pn: string) => `${pn} عايز يمشي`,
    'ask.new': (pn: string) => `${pn} عايز كلمة`, 'ask.form': (pn: string) => `${pn} عايز كلمة`,
    request: (pn: string) => `${pn} طلب رسمي إنه يمشي`,
    clause: (pn: string, fee: string, club: string) => `${club} دفعوا الشرط الجزائي بتاع ${pn}: ${fee}`,
    'due.role.star': (pn: string) => `كلمتك لـ${pn}: نجم الفريق`, 'due.role.starter': (pn: string) => `كلمتك لـ${pn}: يلعب أساسي`,
    'due.role.rotation': (pn: string) => `كلمتك لـ${pn}: دقايق في التدوير`, 'due.contract': (pn: string) => `كلمتك لـ${pn}: عقد جديد`,
    'due.sign': (pn: string, g: string) => `كلمتك لـ${pn}: ${g} جديد`,
    'arm.none': () => 'محدش لابس الشارة', 'arm.lost': (pn: string) => `الأوضة بطلت تمشي ورا ${pn}`,
  },
  advice: {
    reassure: (pn: string, a: string) => `${pn} ${a}. طبطب عليه؛ ده اللي محتاجه دلوقتي.`,
    challenge: (pn: string, a: string) => `${pn} ${a}. تحدّاه. بيستجيب للكلام ده.`,
    'promise.role': () => 'اديله كلمتك على دوره. نقدر ننفّذها، وهو عارف إنها بجد.',
    'promise.contract': () => 'اوعده بعقد جديد. عايز يعرف إن ليه مستقبل هنا.',
    'promise.sign': () => 'اوعده بالصفقة. عايز يشوف طموح.',
    'promise.keep': () => 'قوله إنه مش للبيع.',
    'req.list': (pn: string) => `سيب ${pn} يمشي. اللي عايز يمشي بيلعب كده.`,
    'req.refuse': (_pn: string, n: string) => `ده رقم ${n} عندنا. ارفض، وسيبه يهدى.`,
    'req.promise': () => 'اديله دور حقيقي ويمكن يفضل. متقولهاش لو مش هتعملها.',
    'clause.stay': (_pn: string, n: string) => `واثق فيك (${n}). اطلب منه يفضل؛ أظن هيفضل.`,
    'clause.go': (_pn: string, n: string) => `الثقة ${n}. هيمشي مهما قلنا. خد الفلوس بشياكة.`,
    'due.start': (pn: string) => `نزّل ${pn} أساسي السبت. مش هيكلفنا حاجة وبتحافظ على كلمتك.`,
    'due.cost': (pn: string, n: string) => `نزول ${pn} أساسي هيكلفنا ${n} في المركز ده. كلمتك وقرارك.`,
    'due.none': () => 'مش جاهز يلعب أساسي. يمكن نضطر نسيبها.',
    'due.contract': (_pn: string, n: string) => `حط العقد على الترابيزة: هيمضي بـ${n} في الشهر.`,
    'due.sign': (_pn: string, g: string) => `لسه مديونين له بـ${g}. الميركاتو بيقفل.`,
    arm: (pn: string) => `${pn}. الأوضة ماشية وراه أصلاً.`,
    'arm.home': (pn: string, n: string) => `${pn}. عنده ${n} سنة، ابن النادي، والأوضة ماشية وراه أصلاً.`,
  },
  choices: {
    reassure: 'طمّنه', challenge: 'تحدّاه', list: 'اعرضه للبيع', refuse: 'ارفض', stay: 'اطلب منه يفضل', go: 'سيبه يمشي',
    start: (pn: string) => `نزّل ${pn} أساسي`, letgo: 'سيبها', armband: (pn: string) => `الشارة لـ${pn}`, later: 'مش دلوقتي',
    promise: (what: string) => `اوعده: ${what}`,
  },
  fx: {
    morale: (s: string) => `المعنويات ${s}`, trust: (s: string) => `الثقة ${s}`, coh: (s: string) => `التماسك ${s}`, shrug: 'مش هتفرق كتير',
    bind: 'هيحاسبك عليها', bids: 'العروض هتيجي', stillWants: 'لسه عايز يمشي', withdraw: 'هيسحب الطلب',
    likelyStays: (s: string) => `الثقة ${s}: هيسمع`, likelyGoes: (s: string) => `الثقة ${s}: ماشي`,
    noChange: 'مفيش حاجة هتتغير', onTrack: 'بتحافظ على كلمتك', kept: 'بتحافظ على كلمتك', keepWord: 'إنت وعدته إنه هيفضل',
  },
  news: {
    'dr.broken': (pn: string, what: string): Pair => [`${pn} اتخذل`, `المدرب وعده ${what}. محصلش، والأوضة خدت بالها.`],
    'dr.request': (pn: string): Pair => [`${pn} عايز يمشي`, 'طلب رحيل على مكتب المدرب. والأندية أكيد سمعت.'],
    'dr.settled': (pn: string): Pair => [`${pn} هدي`, 'طلب الرحيل اتشال من على الترابيزة. دلوقتي على الأقل.'],
    'dr.withdrawn': (pn: string): Pair => [`${pn} سحب طلبه`, 'وعد من المدرب غيّر رأيه.'],
    'dr.refused': (pn: string): Pair => ['الطلب اترفض', `النادي بيقول ${pn} مش ماشي. واللاعب مش مبسوط.`],
    'dr.exit': (pn: string, club: string): Pair => [`${pn} مشي`, `راح ${club}. الأوضة خسرت صوت.`],
    'dr.leftFree': (pn: string): Pair => [`${pn} مشي ببلاش`, 'عقده خلص ومشي. ولا مليم للنادي.'],
    'dr.returns': (pn: string, club: string, n: string, s: string): Pair => [`${pn} رجع يواجه ناديه القديم`, `${club}، ${s}. تقييمه: ${n}.`],
    'dr.clauseMet': (pn: string, club: string, n: string): Pair => [`${club} فعّلوا شرط ${pn}`, `${n} كاملين. والشرط الجزائي عمل الباقي.`],
    'dr.stays': (pn: string, club: string): Pair => [`${pn} رفض ${club}`, 'دفعوا الشرط الجزائي. وهو عايز يفضل.'],
    'dr.core': (pn: string, _c: string, n: string): Pair => [`${pn} كسب الأوضة`, `عنده ${n} سنة وابن النادي. الكبار بيسمعوله دلوقتي.`],
    'dr.leader': (pn: string, _c: string, n: string): Pair => [`${pn}، قائد وعنده ${n} سنة`, 'من الأكاديمية لقلب غرفة اللبس.'],
    'dr.armband': (pn: string): Pair => [`${pn} الكابتن الجديد`, 'المدرب سلّمه الشارة.'],
    'dr.armbandHome': (pn: string, _c: string, n: string): Pair => ['من الأكاديمية للشارة', `${pn}، ${n} سنة، كابتن النادي اللي اتربى فيه.`],
  },
  msg: {
    'dr.kept': (pn: string, what: string): Pair => [`وعد اتنفّذ: ${pn}`, `وعدته ${what}. وخد باله.`],
    'dr.broken': (pn: string, what: string): Pair => [`وعد اتكسر: ${pn}`, `وعدته ${what}. الثقة −20، وعايز كلمة.`],
    'dr.request': (pn: string): Pair => [`${pn} طلب يمشي`, 'بطّل يصدقك. اعرضه، ارفض، أو اديله سبب يفضل.'],
    'dr.interest': (pn: string, club: string, fee: string): Pair => [`${club} قدموا عرض لـ${pn}`, `${fee}. عارفين إنه مش مرتاح.`],
    'dr.clause': (pn: string, club: string, fee: string): Pair => [`${club} دفعوا شرط ${pn}`, `${fee}. ملزم، إلا لو هو عايز يفضل.`],
  },
  log: { 'dr.talk.reassure': (pn: string) => `اتكلمت مع ${pn} (طمّنته)`, 'dr.talk.challenge': (pn: string) => `اتكلمت مع ${pn} (تحدّيته)` },
  whyHead: ['الأوضة شالتنا', 'الأوضة خذلتنا'],
  whyGood: (n: number, x: string) => `التماسك ${n}: فريق مستقر بيساوي ${x} لكل لاعب في الملعب.`,
  whyBad: (n: number, x: string) => `التماسك ${n}: فريق مش مستقر كلّفنا ${x} لكل لاعب في الملعب.`,
  ftCoh: 'التماسك', ftCohQuote: (lv: string) => `لعبنا بـ${lv} قدام فريق عادي.`,
  player: {
    room: 'جوه الأوضة', release: 'الشرط الجزائي', none: 'مفيش', role: 'الدور', wantsOut: 'عايز يمشي', refused: 'طلبه اترفض', wantsWord: 'عايز كلمة',
    word: (what: string) => `كلمتك: ${what}`, kept: (what: string) => `وعد اتنفّذ: ${what}`, broken: (what: string) => `وعد اتكسر: ${what}`,
    last: (why: string) => `آخر حاجة: ${why}`,
  },
  renew: { role: 'الدور في العقد الجديد', release: 'الشرط الجزائي', releaseOn: (v: string) => `${v}، وخصم 10% من مرتبه`, off: 'من غير شرط', promiseNote: 'الدور الجديد وعد هيحاسبك عليه.' },
  squad: { door: 'غرفة اللبس', req: 'عايز يمشي', ask: 'عايز كلمة', word: 'كلمتك' },
  today: { roomWhy: (coh: number) => `التماسك ${coh}` },
  note: { talk: 'اتقالت.', stays: (pn: string) => `${pn} فاضل.`, clauseGo: (pn: string) => `${pn} مشي.` },
};
