// Recruitment copy in Egyptian Arabic: the director's office talking, not a ministry. Type-checked against lang-recruit.ts.
import type { RStrings } from './lang-recruit';

const N = (n: number, one: string, two: string, few: string, many = one) => (n === 1 ? one : n === 2 ? two : n >= 3 && n <= 10 ? `${n} ${few}` : `${n} ${many}`);

export const R_AR: RStrings = {
  tabs: ['الأهداف', 'دوّر', 'المفاوضات', 'الصفقات', 'الإعارات', 'الاحتياجات', 'الكشافين'],
  hero: { need: (pos: string) => `دوّر على ${pos}`, none: 'كل مركز عليه بديل.' },
  kpi: { room: 'المساحة للصرف', wageRoom: 'مساحة المرتبات / شهر', committed: 'متزنق فيه' },
  talksBtn: (n: number) => `مفاوضات · ${n}`,

  why: {
    noCover: 'مفيش بديل', thin: 'العدد قليل', old: 'الأساسي 32+', expiring: 'عقد الأساسي بيخلص', loanee: 'الأساسي معار بس',
    weak: 'نقطة ضعف', style: 'مش على طريقتنا', manual: 'قرارك',
  },
  needHead: {
    noCover: (pos: string) => `مفيش بديل في ${pos}.`,
    thin: (pos: string) => `إصابة واحدة وندخل في حيطة في ${pos}.`,
    old: (pn: string) => `${pn} مش هيفضل كده على طول.`,
    expiring: (pn: string) => `عقد ${pn} بيخلص الصيف الجاي.`,
    loanee: (pn: string) => `${pn} راجع لناديه في مايو.`,
    weak: (pos: string) => `${pos} هو أضعف مكان عندنا.`,
    style: (pn: string) => `${pn} مش لايق على طريقة لعبنا.`,
    manual: (pos: string) => `عايز ${pos} كمان.`,
  },
  needEyebrow: 'ليه بندوّر',
  board: 'ثغرات الخطة', boardSub: (f: string) => `الخطة أ · ${f}. غيّر الخطة والثغرات تتغير معاها.`,
  legend: { red: 'مفيش بديل', amber: 'خلي بالك', ok: 'متغطي' },
  depth: (d: number, want: number) => `${d} من ${want}`,
  starter: 'الأساسي',
  picksBtn: 'ترشيحات الكشاف', assignBtn: 'ابعت كشاف', pin: 'زوّد احتياج', pinned: 'قرارك', unpin: 'شيله',
  noNeeds: 'كل مركز في الخطة عليه بديل. اشتري جودة مش عدد.',
  addNeed: 'زوّد احتياج بنفسك',

  scout: {
    pick: (pn: string, k: number) => `${pn} هو المطلوب. عارفينه ${k}%.`,
    unsure: (pn: string, k: number) => `${pn} ممكن يبقى هو، بس عارفينه ${k}% بس. ابعتني أشوفه قبل ما تصرف فلوس على تخمين.`,
    none: 'لسه مفيش حد مناسب. ابعتني على دوري وسيبني كام أسبوع.',
    title: 'كبير الكشافين',
  },
  picks: 'ترشيحات الكشاف لاحتياجاتك',
  whyFits: (pos: string, natural: boolean, age: number, k: number) => `${natural ? 'بيسد' : 'يقدر يسد'} ${pos} في الخطة أ · ${age} سنة · معروف ${k}%`,
  shortlist: 'قايمتك',
  emptyList: 'القايمة فاضية. علّم على لعيبة من «دوّر» والكشافين هيبدأوا يتابعوا.',

  ability: 'المستوى', ceiling: 'السقف', fit: 'على طريقتنا', known: 'معروف',
  asking: 'المطلوب', free: 'لاعب حر', wants: 'عايز / شهر', interest: 'الرغبة',
  interestL: ['حلم عمره', 'متحمس', 'مفتوح', 'بارد', 'نزلة ليه'],
  prioLabel: 'أهم حاجة عنده', prio: { money: 'الفلوس', role: 'يلعب', ambition: 'الطموح', security: 'الأمان' },
  unsettled: 'مش مرتاح في ناديه',
  unknown: '؟',
  offer: 'اعمل عرض', inTalks: 'في مفاوضات', report: 'التقرير', star: 'على القايمة', unstar: 'شيله من القايمة', loan: 'إعارة',
  compare: { eyebrow: 'اللي نعرفه · المستوى', head: 'كل ما الشريط يعرض، كل ما عارفين أقل.', key: 'المدى المتوقع', ref: (pn: string, n: number) => `${pn} النهارده (${n})` },

  talks: 'صفقات شغالة', noTalks: 'مفيش مفاوضات. اعمل عرض من الأهداف.', recent: 'قريب',
  stage: { club: 'سعر النادي', terms: 'الشروط الشخصية', done: 'اتمضى', collapsed: 'اتلغى' },
  status: {
    waiting: (day: string) => `العرض على الترابيزة · الرد ${day}`,
    counter: (v: string) => `عايزين ${v}`,
    rejected: 'رفضوا',
    rival: (club: string, v: string) => `${club} عرضوا ${v}`,
    terms: (n: number, m: number) => `الوكيل · جولة ${n} من ${m}`,
    due: (day: string) => `الرد قبل ${day}`,
  },
  ends: {
    signed: 'اتمضى', walked: 'الوكيل مشي', frozen: 'المفاوضات متجمدة', hijacked: 'اتخطف', window: 'الميركاتو قفل',
    withdrawn: 'انسحبت', gone: 'راح حتة تانية', rejected: 'اترفض',
  },

  room: {
    title: (pn: string) => `مفاوضات · ${pn}`,
    stages: ['سعر النادي', 'الشروط الشخصية', 'اتمضى'],
    clubHead: 'سعر النادي', termsHead: 'الشروط الشخصية', doneHead: 'اتمضى', offHead: 'المفاوضات وقفت',
    withClub: (club: string, n: number, m: number) => `مع ${club} · عرض ${n} من ${m}`,
    withAgent: (name: string, style: string, n: number, m: number) => `مع وكيله ${name} (${style}) · جولة ${n} من ${m}`,
    styles: { fair: 'عادل', hardball: 'ناشف', greedy: 'طماع' },
    agreed: (club: string, fee: string) => `اتفقنا مع ${club} · ${fee}`,
    onTable: 'العرض على الترابيزة', freeAgent: 'لاعب حر · مفيش سعر لنادي',
    table: 'اللي حصل لحد دلوقتي',
    you: (n: number) => `إنت · ${n}`,
    them: (who: string) => who,
    board: (club: string) => `إدارة ${club}`,
    bidLine: (fee: string, seasons: number, sellOn: number) => `${fee}${seasons > 1 ? ` على ${seasons} مواسم` : ' كاش'}${sellOn ? ` + ${sellOn}% من البيعة الجاية` : ''}.`,
    clubSays: {
      accept: 'تمام. كلّم وكيله.',
      counter: (v: string) => `مش كفاية. ${v} وهو بتاعك.`,
      reject: 'مش للبيع بالسعر ده.',
      insult: 'إنت بتهزر؟ تعالى بعرض بجد.',
      rival: (club: string, v: string) => `${club} عرضوا ${v}. زوّد قبل الماتش الجاي.`,
    },
    agentSays: {
      open: 'ده اللي هيخليه يمضي.', close: 'قريب. قريب قوي.', notThere: 'لسه بعيد.', insulted: 'إنت كده بتهين موكلي.',
      walk: 'خلصنا كده. هيسمع عروض تانية.', accept: 'اتفقنا.',
    },
    ourLine: 'ده عرضنا.',
    chip: {
      wage: (v: string) => `${v}/شهر`, years: (n: number) => N(n, 'سنة', 'سنتين', 'سنين', 'سنة'),
      signOn: (v: string) => `${v} مقدم توقيع`, release: (v: string) => `شرط جزائي ${v}`, noRelease: 'من غير شرط جزائي',
      bonus: (v: string) => `${v} للماتش`,
    },
    roles: { star: 'نجم', regular: 'أساسي', rotation: 'تدوير', prospect: 'موهبة' },
    patienceClub: 'صبر الإدارة', patienceAgent: 'صبر الوكيل',
    yourBid: (n: number) => `عرض ${n} · عرضك`, yourOffer: (n: number) => `جولة ${n} · عرضك`,
    fee: 'السعر', feeZone: 'في الأخضر غالبًا هيوافقوا', pay: 'الدفع', payOpts: ['كله دلوقتي', 'على موسمين', 'على 3 مواسم'],
    upfront: 'مقدم', upOpts: ['40%', '60%', '80%'], sellOn: 'نسبة من البيعة', sellOpts: ['لأ', '10%', '15%', '20%'],
    sellOnWhy: 'نسبة من أي فلوس نبيعه بيها بعدين. قيمتها عندهم أقل من الكاش.',
    instWhy: (v: string) => `${v} الموسم الجاي. بتقلل المساحة للصرف من دلوقتي، كلها.`,
    wage: 'المرتب الشهري', wageZone: 'في الأخضر غالبًا هيمضي', years: 'المدة', role: 'الدور', roleWhy: 'أي دور توعده بيه هيحاسبك عليه.',
    clauses: 'الشروط', clausesSub: 'كل شرط بيكلفك إيه',
    signOn: 'مقدم التوقيع', signOnWhy: (v: string) => `${v} دلوقتي. فلوس في جيبه من أول يوم.`,
    release: 'شرط جزائي', releaseWhy: (v: string) => `أي نادي يدفع ${v} ياخده ومنقدرش نمنعه.`, releaseOff: 'مقفول: يفضل بتاعنا لحد ما نبيعه.',
    bonus: 'مكافأة المشاركة', bonusWhy: (v: string) => `${v} في كل ماتش دوري يلعبه.`,
    his: 'طلبه',
    verdict: 'لو بعت ده',
    clubV: { accept: 'هيوافقوا', counter: 'استنى عرض مضاد', reject: 'هيرفضوا', insult: 'هياخدوها إهانة' },
    clubWhy: (e: string) => `قيمته عندهم ${e}: التقسيط بيتحسب أقل، والنسبة أقل كمان.`,
    chance: (p: number) => (p >= 0.75 ? 'غالبًا هيمضي' : p >= 0.5 ? 'ممكن آه وممكن لأ' : p > 0 ? 'صعبة' : 'مش هيمضي على كده'),
    chanceWhy: (known: boolean) => (known ? 'عارفين هو عايز إيه.' : 'لسه مش عارفين أهم حاجة عنده. ده أحسن تقدير عندنا.'),
    roomAfter: 'المساحة بعدها', wageRoomAfter: 'مساحة المرتبات بعدها', later: 'متزنق فيه المواسم الجاية', agentFee: 'عمولة الوكيل', bill: 'المرتبات', perYear: '/سنة',
    send: (n: number) => `ابعت جولة ${n}`, sendBid: 'ابعت العرض', walk: 'انسحب', meet: 'وافق على طلبه', takeCounter: 'وافق على عرضه',
    payCounter: (v: string) => `ادفع ${v}`, top: (v: string) => `زوّد: ${v}`, waiting: (day: string) => `الرد ${day}`,
    back: 'الانتقالات',
    signed: (pn: string) => `${pn} بقى بتاعنا.`,
    frozenFor: (n: number) => `المفاوضات متجمدة ${N(n, 'جولة', 'جولتين', 'جولات')}.`,
    adv: {
      clubLow: 'تحت سعرهم أحسن حاجة عرض مضاد. 3 عروض وبعدها مش هيردوا.',
      clubOk: 'ده سعرهم. هيسلّموا عليه.',
      deadline: 'آخر يوم في الميركاتو: الرد على طول.',
      termsHigh: (v: string) => `متعديش ${v}. ده هيبقى السقف لكل تجديد بعد كده.`,
      termsOk: 'عادل للطرفين. أنا كنت بعته.',
      termsLow: 'مش هياخد ده. اتحرك في الحاجة اللي تهمه.',
      waiting: 'مفيش غير إننا نستنى ردهم.',
    },
    agentFree: 'مفيش سعر: لاعب حر. بس الوكيل برضه ليه عمولته.',
  },

  bidsFor: 'عروض على لعيبتك',
  aiWhy: { unhappy: 'مش مبسوط', expiring: 'عقده بيخلص', request: 'طلب يمشي', need: 'محتاجينه' },
  committed: 'فلوس علينا', commitRow: (season: string, club: string) => `${season} · لـ ${club}`, noCommit: 'مفيش حاجة علينا. كل صفقة اتدفعت كاملة.',
  stories: 'الحكايات',
  loans: {
    in: 'جاي إعارة', out: 'رايح إعارة', none: 'مفيش حد معار.',
    share: (p: number) => `بندفع ${p}% من مرتبه`, shareOut: (p: number) => `بيدفعوا ${p}% من مرتبه`,
    minutes: { starter: 'شرط أساسي', rotation: 'شرط تدوير', none: 'من غير شرط دقايق' },
    progress: (apps: number, need: number, days: number) => `${apps} ماتش في ${days} جولة · محتاج ${need}`,
    broken: 'الشرط اتكسر', trust: (n: number) => `ثقتهم فينا ${n}`, recall: 'رجّعه',
    ask: (pn: string) => `إعارة ${pn}`, shareQ: 'نسبة المرتب اللي بندفعها', minutesQ: 'الدقايق اللي بنوعد بيها', send: 'اطلبه',
    needs: (s: string) => `هيعيروه لو دفعنا ${s} من مرتبه.`, noWay: 'مش هيعيروه بأي شروط نقدر عليها.',
    outTitle: (pn: string) => `إعارة ${pn} برّه`, where: 'فين', theyPay: 'نسبة المرتب اللي بيدفعوها', outSend: 'ابعته',
    fee: (v: string) => `رسوم الإعارة ${v}`, takes: 'هياخدوه', wontTake: 'مش هياخدوه بالشروط دي',
  },

  scouts: {
    head: 'الكشافين فين', slots: (n: number, max: number) => `${n} من ${max} مهمات شغالة`,
    slotsWhy: 'منشأة الكشافة هي اللي بتحدد عدد المهمات.',
    scope: { league: 'دوري', country: 'دولة', world: 'العالم كله' },
    pos: 'المركز', any: 'أي مركز', send: 'ابعته', remove: 'رجّعه',
    coverage: (n: number, k: number) => `${n} لاعب · ${k} عارفينهم كويس`,
    rate: (v: number, t: number) => `+${v} معرفة كل جولة · +${t} للي على القايمة`,
    empty: 'مفيش كشافين برّه. المعرفة بتزيد من القايمة والماتشات اللي بنلعبها بس.',
    worldPos: 'العالم كله محتاج مركز.', full: 'كل الكشافين برّه. رجّع واحد الأول.',
    newOne: 'مهمة جديدة',
    quote: (n: number, k: number) => `${n} اسم برّه، ${k} منهم أحط اسمي عليهم. سيبني شوية.`,
    best: 'اللي عارفينهم أكتر', none: 'لسه مفيش حد نعرفه كويس برّه الفريق.',
  },

  tag: { bidAnswer: 'رد على العرض', agent: 'الوكيل', rival: 'عرض منافس', loanClause: 'إعارة', recall: 'إعارة' },
  dec: {
    rival: (pn: string, club: string, v: string, day: string) => `${club} عرضوا ${v} في ${pn}. زوّد قبل ${day}.`,
    counter: (pn: string, club: string, v: string) => `${club} عايزين ${v} في ${pn}.`,
    rejected: (pn: string, club: string, v: string) => `${club} رفضوا ${v} في ${pn}.`,
    insulted: (pn: string, club: string) => `${club} ضحكوا على عرضنا في ${pn}.`,
    agreed: (pn: string, day: string) => `اتفقنا على سعر ${pn}. وكيله عايز رد قبل ${day}.`,
    agentDue: (pn: string, day: string) => `وكيل ${pn} عايز رد قبل ${day}.`,
    clauseRisk: (pn: string, club: string, n: number) => `${pn} محتاج ${N(n, 'ماتش', 'ماتشين', 'ماتشات')} كمان عشان ${club} ميزعلوش.`,
    recallQ: (pn: string, club: string) => `${club} مش بيلعّبوا ${pn}. نرجّعه؟`,
    rivalBid: (pn: string, club: string, v: string, why: string) => `${club} عرضوا ${v} في ${pn}.${why ? ` ${why}.` : ''}`,
    askBid: (pn: string, v: string) => `نعرض ${v} في ${pn}؟`,
  },
  adv: {
    top: (v: string) => `روح لـ ${v}. مش هنلاقي زيه الميركاتو ده.`,
    letGo: 'سيبه. مش هنعمل مزاد.',
    pay: (v: string) => `${v} غالي بس معقول. ادفع.`,
    walk: (v: string) => `${v} كتير. انسحب.`,
    rejected: (n: number) => (n > 0 ? `لسه مش راضيين يتحركوا. فاضل ${N(n, 'محاولة', 'محاولتين', 'محاولات')} وبعدها مش هيردوا.` : 'بطّلوا يردوا.'),
    meet: (v: string) => `اديله ${v} في الشهر وتخلص النهارده.`,
    counter: 'عرض الوكيل ماشي معانا. خده.',
    talk: 'فيه مساحة ننزّله. افتح المفاوضات.',
    clause: (club: string) => `وعدنا ${club} إنه هيلعب. لو كسرنا الوعد مش هيعيرونا تاني.`,
    recall: 'قاعد على دكتهم بيصدّي. رجّعه.',
    bid: (v: string) => `أنسب واحد لأهم احتياج وفي حدود فلوسنا. ${v} بداية معقولة.`,
  },
  choice: {
    top: (v: string) => `زوّد: ${v}`, letGo: 'سيبه', pay: (v: string) => `ادفع ${v}`, improve: 'حسّن العرض', walk: 'انسحب',
    meet: 'وافق على طلبه', takeCounter: 'وافق على عرضه', talk: 'افتح المفاوضات', playHim: 'نزّله', riskIt: 'خاطر', recall: 'رجّعه', leave: 'سيبه هناك',
  },
  fx: {
    room: (v: string) => `المساحة الباقية ${v}`, fees: (v: string) => `عمولات ${v}`, patience: (n: number) => N(n, 'محاولة كمان', 'محاولتين كمان', 'محاولات كمان'),
    noDeal: 'مفيش صفقة', rounds: (n: number) => `صبر ${N(n, 'جولة', 'جولتين', 'جولات')}`, rivalGets: 'هيروح للمنافس',
    parentHappy: 'ناديه مبسوط', parentAngry: 'مش هيعيرونا تاني', back: 'راجع للفريق', benchWarm: 'شهر كمان على دكتهم',
  },

  news: {
    bid: (pn: string, club: string, club2: string, v: string) => [`${club} يعرضوا ${v} في ${pn}`, `${club2} بيفكروا.`],
    agreed: (pn: string, club: string, club2: string, v: string) => [`${club} يتفقوا على سعر ${pn}`, `${v} لـ ${club2}. فاضل الشروط الشخصية.`],
    done: (pn: string, club: string, club2: string, v: string) => [`${pn} ينضم لـ ${club}`, v ? `من ${club2} بـ ${v}.` : 'انتقال حر.'],
    walk: (pn: string, club: string) => [`مفاوضات ${pn} تنهار`, `وكيله ساب ${club} ومشي.`],
    hijack: (pn: string, club: string, club2: string, v: string) => [`${club} يخطفوا ${pn}`, `${v} لـ ${club2}. في حد كان بطيء.`],
    aiBid: (pn: string, club: string, v: string, why: string) => [`${club} يعرضوا ${v} في ${pn}`, why],
    aiWhy: { unhappy: 'بقاله أسابيع مش مبسوط.', expiring: 'عقده قرب يخلص.', request: 'طلب يمشي.', need: 'محتاجين لاعب زيه.' },
    release: (pn: string, club: string, club2: string, v: string) => [`${club} يدفعوا الشرط الجزائي لـ ${pn}`, `${v}، و${club2} ميقدروش يقولوا لأ.`],
    loanIn: (pn: string, club: string, club2: string) => [`${pn} ينضم لـ ${club} إعارة`, `من ${club2} للموسم.`],
  },
  msg: {
    answer: (pn: string, club: string, s: string, v: string) => [
      s === 'accept' ? `${club} وافقوا على عرضنا في ${pn}` : s === 'counter' ? `${club} ردوا بعرض مضاد في ${pn}` : `${club} رفضوا عرضنا في ${pn}`,
      s === 'accept' ? `اتفقنا على ${v}. وكيله مستني.` : s === 'counter' ? `عايزين ${v}.` : s === 'insult' ? 'خدوها إهانة.' : 'حسّن العرض أو انسحب.',
    ],
    hijack: (pn: string, club: string, v: string) => [`${pn} يمضي لـ ${club}`, `دفعوا ${v} وإحنا عرضنا مستني.`],
    rival: (pn: string, club: string, v: string) => [`${club} دخلوا على ${pn}`, `${v} على الترابيزة. زوّد قبل الماتش الجاي.`],
    release: (pn: string, club: string, v: string) => [`${club} دفعوا الشرط الجزائي لـ ${pn}`, `${v}. مشي.`],
    instalments: (v: string, n: number) => [`أقساط اتدفعت: ${v}`, `${N(n, 'قسط', 'قسطين', 'أقساط')} استحقوا مع الموسم الجديد.`],
    picks: (pn: string, n: number, pos: string) => [`تقرير الكشاف: ${pn}`, `أول ترشيح لـ ${pos} · ${N(n, 'اسم', 'اسمين', 'أسامي')} على القايمة.`],
    loanReport: (pn: string, club: string, apps: number, goals: number, days: number) => [`تقرير الإعارة: ${pn}`, `${apps} ماتش في ${days} جولة مع ${club}، ${goals} جول.`],
    brokenIn: (pn: string, club: string) => [`${club} متضايقين جدًا بسبب ${pn}`, 'وعدناهم بدقايق ومدّيناهمش. هياخدوه في الميركاتو.'],
    brokenOut: (pn: string, club: string) => [`${club} مش بيلعّبوا ${pn}`, 'كسروا شرط الدقايق. نقدر نرجّعه في الميركاتو.'],
    takenBack: (pn: string, club: string) => [`${club} رجّعوا ${pn}`, 'الإعارة خلصت.'],
    sellOn: (pn: string, club: string, v: string) => [`نسبة البيعة اتدفعت عن ${pn}`, `${v} لـ ${club}، زي ما اتفقنا لما جبناه.`],
  },
  log: {
    rcbid: (pn: string, v: string) => `عرض ${v} في ${pn}.`, rcPay: (pn: string, v: string) => `دفع سعرهم في ${pn}: ${v}.`,
    rcTop: (pn: string, v: string) => `زوّد على المنافس في ${pn}: ${v}.`, rcSigned: (pn: string, v: string) => `اتفق مع ${pn}: ${v} في الشهر.`,
    rcWalk: (pn: string) => `انسحب من ${pn}.`,
  },
  steps: {
    bid: 'عرض', agreed: 'اتفاق على السعر', counter: 'عرض مضاد', reject: 'رفض', insult: 'إهانة', frozen: 'تجميد', rival: 'عرض منافس', topped: 'زوّدنا',
    hijacked: 'اتخطف', signed: 'اتمضى', walked: 'الوكيل مشي', window: 'الميركاتو قفل', withdrawn: 'انسحبنا', gone: 'راح حتة تانية', talks: 'بدأت المفاوضات',
    loanIn: 'جه إعارة', loanOut: 'راح إعارة', brokenIn: 'الشرط اتكسر', brokenOut: 'هما كسروا الشرط', recalled: 'اترجّع', takenBack: 'خدوه',
    release: 'الشرط الجزائي اتدفع', bid_need: 'عرض: محتاجينه', bid_unhappy: 'عرض: مش مبسوط', bid_expiring: 'عرض: عقده بيخلص', bid_request: 'عرض: طلب يمشي',
  },
  ledger: { agentFees: 'عمولات الوكلاء', signOn: 'مقدمات التوقيع', instalments: 'أقساط', loanWages: 'نسب مرتبات الإعارة', bonuses: 'مكافآت المشاركة', sellOn: 'نسب البيعات' },
  no: {
    frozen: 'المفاوضات متجمدة دلوقتي.', waiting: 'عرضنا لسه على الترابيزة.', agreed: 'السعر اتفقنا عليه. كلّم الوكيل.',
    trust: 'مش هيعيرونا بعد اللي حصل.', loanTerms: 'عايزين ندفع نسبة أكبر من مرتبه، أو نوعد بدقايق.', minutes: 'مش هياخد الدقايق دي هناك.',
    buyerBudget: 'ميقدروش يدفعوا ده.', release: 'الشرط الجزائي ميبقاش أقل من قيمته.', slots: 'كل الكشافين برّه.', scope: 'اختار هنبعته فين.',
    done: 'متغطي خلاص.', noClause: 'مفيش شرط دقايق نستخدمه.', loaned: 'معار.',
  },
  note: {
    bidSent: (pn: string) => `العرض راح في ${pn}.`, talks: (pn: string) => `المفاوضات بدأت مع وكيل ${pn}.`, agreed: (pn: string) => `اتفقنا على سعر ${pn}.`,
    assigned: 'الكشاف في الطريق.', recalled: (pn: string) => `${pn} راجع.`,
    close: 'قريب. قريب قوي.', notThere: 'لسه بعيد.', insulted: 'اتضايق.', walk: 'الوكيل مشي.',
  },
};
