export default (dev) => [
  ['tactics', 'Change the formation', ['nav:Match'], /Without the ball/],
  ['table', 'See the league table', ['nav:Match', 'Table'], /Pts/],
  ['fixtures', 'See the fixtures', ['nav:Match', 'Fixtures'], /Matchday/],
  ['player', 'Open a player', ['nav:Squad', 'EMAM ASHOUR'], /Emam Ashour/],
  ['search', 'Search the market', ['nav:Transfers', 'Search'], /./],
  ['money', 'Check the money', ['nav:Club'], /runway/i],
  ['board', 'Check the board’s objectives', ['nav:Club', 'Board'], /./],
  ['facility', 'Upgrade a facility', ['nav:Club', 'Facilities'], /Build/],
  ['staff', 'Set what the staff handle', ['nav:Club', 'Staff'], /./],
  ['room', 'Visit the dressing room', ['nav:Squad', 'Dressing room'], /./],
  ['training', 'Set the training week', ['nav:Squad', 'Training week'], /./],
  ['medical', 'Check the medical room', ['nav:Squad', 'Medical'], /./],
  ['academy', 'Visit the academy', ['nav:Squad', 'Academy'], /./],
  ['career', 'Career history and legends', dev === 'd' ? ['nav:Career'] : ['nav:Club', 'Career'], /Club legends/],
  ['pass', 'Club Pass and looks', dev === 'd' ? ['nav:Club Pass'] : ['nav:Club', 'Club Pass'], /Looks/],
  ['settings', 'Change language / saves', ['nav:Club', 'Settings and saves'], /Language/],
  ['news', 'Read the news', ['nav:Club', 'Board', 'News'], /./],
  ['play', 'Get to the next match', ['Continue'], /Walk out/],
];
