// Rival voice packs, English (banter lane). Four fictional football-Twitter archetypes; no real people, accounts or
// club employees (docs/LEGAL_NAMES.md). PG-13: banter about calls, records and sources, never about a person's life.
//   @BackPageBants  tabloid · screenshot-and-ratio · "L + you fell for it" · CAPS · the reel
//   @ITK_Kev        anonymous ITK · "my source at the club" · a day early · cryptic emojis · lowercase
//   @PressBoxPete   old school · slow · "I don't do rumours" · full sentences · quietly lethal
//   @ClubModFC      the fan-page mod · lives for a ratio and a "we go again" · admin energy
// {rec} your record against them, {p} the player you duelled on, {name} your byline. The first 8 lines of each
// cn.taunt state pool are the pre-3.4 lines (kept: old feed items point at them by index); {name} only appears after.
// Every state pool is the same length in EN, AR and ES (lib/rivals.ts tauntIndex sizes by EN; scripts/i18n-check.mjs).
export default {
  en: {
    rival: { clubmod: '@ClubModFC', clubmodO: 'Fan page admin · lives for a ratio' },
    cn: {
      rivals: { blurb: { clubmod: 'Runs the fan page. Never posts a story, never misses a ratio. “We go again.”' } },
      taunt: {
        tabloid: {
          losing: [
            '{rec} to me. Frame it, mate.', 'Called {p} before you’d had your coffee. {rec}.', 'EXCLUSIVE: you’re slow. Sources: the scoreboard, {rec}.', 'You spent all week on {p}. I spent a minute. Guess who was right.', 'My replies are full of your followers. Tell them I said hi.', 'Another one for the reel. {rec} and counting.', 'Here we go? Here you went. Wrong way.', 'I’d offer you a job, but we have standards. Low ones, mind.',
            'L + you fell for it + {rec}.', 'Screenshotted your {p} post before you could delete it. It’s pinned now.', 'RATIO. {rec}. Have a lovely evening.', 'Source: trust me bro. That was your whole file on {p}.', 'Imagine going Confirmed on {p} with a barber and a dream. 😂', 'The reel’s got a new intro clip. Guess who’s in it.', 'BREAKING: {name} wrong again. In other news, water wet.', '{name} calls it, the opposite happens. Reliable in its own way.', 'Medical booked? Mate, the only thing booked was your L.', 'I don’t need sources. I just wait for {name} to post and go the other way.',
            'Agent tweet was fake. Your call was faker. {rec}.', 'The lads in the office have a sweepstake on how wrong you’ll be. Nobody won this week: everyone said “very”.', 'You: “announce him”. The club: announced someone else. 😂', '{p} deal was cooked and so were you.', 'Quote-tweeting this in July when it ages even worse.', '{rec}. Not a rivalry. A public service announcement.', 'Delete it, {name}. We’ve all got it saved anyway.', 'Your sources are my sources’ ex-sources.', 'Your followers are DMing me for the real story. I send them my link.', 'You posted {p} at Confirmed. Confirmed wrong, to be fair.',
            'Hard to be this loud and this wrong. Respect, sort of.', 'Ran your {p} tweet on the back page. Under “Things That Didn’t Happen”.', 'Rumour: {name} is good at this. Status: FAKE.', 'Every window, same film: I post, you scramble, I win. {rec}.', 'Add it to the thread. The thread is very long now.', 'Told my editor about you. He laughed. He never laughs.', 'You, day one: “trust me”. You, day seven: nothing. 😂', 'Clip’s at 2M views, {name}. You’re famous. Wrong famous.', 'I could have written your {p} call for you. I did, actually, in the replies, a day earlier.', 'Sit down. The grown-ups are posting.', '{rec}. Rent free, no eviction notice.', 'Big call, {name}. Big miss. Big reel.',
          ],
          winning: [
            'Fine. {rec}. Don’t let it go to your head.', 'Lucky on {p}. Even a broken clock, etc.', 'Deleting my tweet. Not because of you.', 'Alright, you had {p}. I had lunch.', 'Stop quote-tweeting me. We get it. {rec}.', 'My editor asked who you are. Cheers for that.', 'Fluke. Fluke. Fluke. {rec}. Fluke.', 'You’re costing me followers and I don’t have many sensible ones.',
            'Okay {name}. You got one. The reel is still longer than your record.', 'Screenshot THIS then. Actually don’t.', 'Post deleted. Account fine. Ego bruised. {rec}.', 'You were right on {p}. I was right about it being Tuesday.', 'Muting the word “{p}” for a week. Nothing to do with you.', 'My source at the club was the club shop. Bad source.', 'Congratulations on reading a physio report. Real journalism.', 'You called {p}. I called a taxi. Different priorities.', 'This is why I don’t check the scoreboard. {rec}. Horrible.', '{rec}. Nobody tell the group chat.',
            'Ratio’d by someone with fewer followers. New low. Genuinely.', 'The replies are calling me cooked. The replies have a point.', 'Fair. I owe you a pint. I won’t pay it.', 'Enjoy it, {name}. Windows come round quick.', 'I’m still louder. Loud counts for something. Not points, apparently.', 'Wrong on {p}. Right about everything else in my life. Mostly.', 'You had the story. I had the headline font. One of us got paid.', 'The reel has an outtake now. It’s me.', 'We go again. Wait, that’s the mod’s line. Whatever. {rec}.', 'Reposted your {p} call. Without credit, obviously.',
            'Two right in a row? Who’s feeding you?', 'You’re on a run, {name}. Runs end. Usually on my timeline.', 'Aura check: yours up, mine cooked. Temporary.', 'I’ll allow it. Once. {rec}.', 'Quiet from me today. The desk wants a word about {p}.', 'Not a ratio if I don’t look at it. Not looking.', 'My editor pinned your post on the office wall. Pure spite.', 'Right call, wrong account. Mine should have been right. Physics agrees.', 'Take the W, {name}. I’m taking the afternoon off.', '{rec}. Frame it yourself, I’m busy.', 'The tabloid concedes. Briefly. In small print.', 'You know what, well done. I hate typing that even more than Kev does.',
          ],
          level: [
            '{rec}. Next one’s mine, and I’m posting it first.', 'Both on {p}. Great minds. Well, one of us.', 'Level. For now. I post at dawn.', 'Honours even. I’ll be louder next time.', 'Shared the scoop on {p}. I’ll take the credit, you take the shares.', 'Dead level. The tie-breaker is volume, and I win volume.', 'Even stevens. Enjoy it, it won’t last.', 'We both had {p}. Only one of us used capitals.',
            'Level, {name}. The reel is on pause, not deleted.', 'Same call on {p}. I said it in 72pt. Yours was a whisper.', '{rec}. Boring. Somebody be wrong next time.', 'Two accounts, one story, zero drama. Fix it, {name}.', 'Split decision. The crowd wanted blood.', 'Draw. I still got more likes. Likes are the real table.', 'Copied my {p} homework and got the same mark. Suspicious.', 'Even. Which is a loss for me, honestly. I’m supposed to be winning.', 'Tied on {p}. My version had a photo. Yours had a source. Photo wins.', 'Level pegging. The reel needs content. Slip up.',
            'We agree. I feel ill.', 'One each. Best of a thousand.', 'Both right on {p}. I was louder, so it counts double in my head.', 'Deadlock. Deadline Day will sort it. Deadline Day always sorts it.', 'You matched me. Nobody matches me. {rec}.', 'Tied. I’m blaming the algorithm.', 'Same result, different fonts. Mine bigger.', 'Level. I’m putting the reel on YouTube to pass the time.', 'The scoreboard says {rec}. The scoreboard is being dramatic.', 'Draw. Rematch at dawn. Bring sources.',
            'Even. My replies say I lost. My replies are wrong. Probably.', 'Honours even, {name}. Honour was never really my thing.', 'You had {p} too. Fine. Great. Lovely.', 'Tied, and I hate a tie more than an L. At least an L is content.', 'We both called it. Only one of us made a graphic.', 'Level. Somebody at the club is talking to both of us. I’ll find out who.', '{rec}. Next window one of us gets clipped. Won’t be me.', 'Even. I’ve got the ratio ready anyway. Just in case.', 'Draw. Which means the reel has a two-part special.', 'Split. I’ll take the headline, you take the footnote.', 'All square. Announce a winner. Announce me.', 'Level, and I posted first. History remembers the first post.',
          ],
        },
        itk: {
          losing: [
            '{rec}. My people spoke. Yours, less so.', 'Told you on {p}. Actual sources, look into it.', 'Some of us get texts from car parks. Some of us guess.', '{rec}. I’d share my contacts, but they’d never pick up for you.', 'Called {p}. The agent says thanks for the clicks.', 'Keep refreshing. I’ll keep being right.', 'You rang the barber? Bold. {rec}.', 'Pinned tweet updated: another one on you.',
            'told you. 👀 {rec}.', 'my source at the club said {p} on day 1. you said it on day 6. said it wrong.', 'a day early, like always. ask yourself how, {name}.', 'not a rumour. a fact. you posted the rumour. 🤫', 'more soon. for you: more L’s. {rec}.', 'source: the club. your source: vibes.', '🩺 booked. ✈️ landed. 📝 signed. you: “not convinced”. 😂', 'the network doesn’t miss. {name} does. {rec}.', 'i don’t post often. when i do, {name} deletes.', 'you’ll see. you saw. 👀',
            'mute me if you want, {name}. the timeline will still be right.', '{rec}. i know people. you know a barber.', 'the {p} call was in my drafts before your window opened.', 'i said “keep an eye on a third club”. you kept an eye on the wrong one.', 'not gloating. just stating. {rec}.', 'relaxed. 🔜 was the whole tweet and it aged like wine.', 'car park text at 11pm beats a physio at noon. every time.', 'don’t ask me how i knew about {p}. you wouldn’t like the answer.', 'trust the process. mine, obviously. yours is “ring Sal”.', 'a source who’s never wrong vs a source with clippers. you chose clippers.',
            '📝 done. you: “dead”. respectfully, {name}: no.', 'kept the receipts. i always keep the receipts. {rec}.', 'the club knew. i knew. you found out with everyone else.', 'you were confident. confidence isn’t a contact. 👀', 'i was in the replies a day before you were in the story.', '{rec}. they’ll tell you eventually. i get told first.', 'it’s not luck when it happens every window, {name}.', 'my DMs: full. your call on {p}: wrong. connected? maybe.', 'deleted your {p} tweet yet? doesn’t matter, i quoted it.', 'not saying who. never saying who. saying {rec} though.', 'you went loud. i went early. early wins.', 'when it goes quiet, it’s because they’re signing. you posted in the quiet.',
          ],
          winning: [
            '{rec}. My source is having a word with himself.', 'You had {p}. My guy was on holiday.', 'Okay, fair. Who’s your contact? Asking for a friend.', 'Muting you for a week. Nothing personal.', 'Credit where it’s due: {rec}. I hate typing that.', 'My DMs said otherwise. My DMs are fired.', 'A bad week for the network. {rec}.', 'Alright. You know people. Don’t make it a personality.',
            'fair. {name} had {p}. i had a wrong car park.', 'my source at the club has been moved to a different club. by me.', 'not my finest window. {rec}. moving on. 🤫', 'you were early. i was earlier and wrong. worst combo.', 'who’s feeding you, {name}? genuinely. business enquiry.', 'the network had an off day. it happens. rarely. {rec}.', '👀 on you now. you’ve got a leak i don’t have.', 'i’ll take the L quietly. that’s the difference between us: quietly.', 'you had {p} right. i had emojis. emojis don’t score.', 'told the group chat you got lucky. the group chat didn’t buy it.',
            'ok that one’s yours. don’t tag me.', 'my guy swore on his kids. his kids need a word with him.', '{rec}. fine. drafts deleted.', 'you don’t have sources. you have a source. one good one. annoying.', 'i said “keep an eye”. you kept two. {p} was yours.', 'quiet from me this window. reflecting. 🔜 back.', 'respect, {name}. said with gritted teeth and lowercase.', 'i hate that you read the physio. it’s so obvious. it works.', 'the pinned tweet is coming down. not because of you. because of you.', 'i’ll be a day early next time. this time i was a day wrong.',
            'good call on {p}. my source has been sent to the barber.', '{rec}. contacts drying up. wells do that.', 'you were right and you weren’t even cryptic about it. disgusting.', 'the network has been notified. the network is embarrassed.', 'take it, {name}. i’m taking my phone off the club’s WiFi.', 'one window. one. don’t build a shrine.', 'i was told the opposite by someone very senior. very senior, very wrong.', 'you ring people. i wait for texts. this week, ringing won.', 'if you tell me who your contact is i’ll stop posting about you. deal? no? fine. {rec}.', 'my {p} tweet has been left up. as a monument.', 'right, you’re on a run. runs are noted. 👀', 'ok. {rec}. more soon. hopefully better soon.',
          ],
          level: [
            '{rec}. We read the same room.', 'Both right on {p}. My source says hi.', 'Level. Someone’s leaking to both of us.', 'Honours even. I’ll be earlier next window.', 'Same call on {p}. Mine had more emojis.', 'Dead level. The network is watching.', '{rec}. Neither of us is buying the other a coffee.', 'Tied. Let’s see who the physio likes more.',
            'same call, same day. suspicious, {name}. 👀', 'level. mine was cryptic though. bonus points in spirit.', '{rec}. the club is talking to both of us. i’ll fix that.', 'we both had {p}. i had it with a 🔜. that’s craft.', 'draw. my source says you’ve got a source. worrying.', 'tied. not used to sharing. 🤫', 'ok you’re keeping up. keeping up isn’t ahead. {rec}.', 'level pegging. i’m going back to the car park.', 'both right on {p}. one of us was told, one of us worked it out. both fine.', 'even. next time i post at 6am. set an alarm, {name}.',
            'same read on {p}. did you ring my guy? did my guy ring you?', 'dead heat. the network hates a dead heat.', '{rec}. neither of us is wrong yet. give it a window.', 'tied. you wrote a paragraph, i wrote 👀. same result. mine faster.', 'level. i’ll allow it. barely.', 'we agree on {p}. don’t make it a thing.', 'the replies are asking who was first. me. by a day. as usual. still a draw though.', 'even. the physio is playing us both.', 'draw. someone in that building talks too much.', 'split. next one i’m going full cryptic. three emojis, no words.',
            'level with {name}. noting it. not enjoying it.', 'both right. both early. only one of us was mysterious about it.', '{rec}. more soon. same time, same club.', 'tied. i’ll get the tie-breaker from a car park near you.', 'we both called {p}. the source pool is shrinking.', 'honours even. honour is a strange word for this job.', 'draw. i’m told there’s a bigger story coming. i’m told a lot of things.', 'level. next window: earlier, quieter, righter.', 'same call. i used fewer letters. efficiency.', 'even. someone give the network something to work with.', 'tied on {p}. the group chat is bored of us.', 'level. 👀 for now.',
          ],
        },
        insider: {
          losing: [
            '{rec}. Ring the physio before you post, son.', 'I was right on {p} on day five. Patience is free.', 'Twenty years in the press box. You’ve had a week. {rec}.', 'Loud is not the same as right. {rec}.', 'I don’t post often. When I do, check the record.', 'You went Confirmed on vibes. I went on a medical.', 'Slow down. The story isn’t going anywhere. Well, {p} might.', 'I’ll send you my reading list. It’s one line: wait.',
            'I don’t do rumours. You do. That is the whole difference, {name}.', 'A medical is not a signing. Write that on the wall above your desk.', 'You posted first. I posted correctly. Only one of those is a job.', '{rec}. I take no pleasure in it. Some, then.', 'The {p} story was in the club’s body language a week ago. You read the barber.', 'Two sources, {name}. Two. Not one man with clippers.', 'I have never been ratio’d. I have never posted anything worth ratioing. Think about that.', 'Confirmed means confirmed. You used it as an adjective.', 'You’ll get there. Most do, after enough windows like this one. {rec}.', 'The record says {rec}. The record doesn’t shout.',
            'I waited. You didn’t. {p} was never going to be quick.', 'Deadline Day is a clock, not an excuse. You filed like it was both.', 'The press box heard about {p} on Tuesday. We didn’t tweet it. We checked it.', '{rec}. I’d be gentler if it helped. It doesn’t.', 'You read a jet as a signing. Jets go to holidays too, son.', 'I had one line on {p}, on day five, and it was right. That’s the whole craft.', 'Nobody remembers who was first, {name}. Everybody remembers who was wrong.', 'The agent told you what he tells everyone. I know because he told me, and I waited.', 'Your call had energy. Mine had a medical.', 'The trouble with being loud is that everyone hears the correction too.',
            '{rec}. Bring a notebook next time.', 'I understand the pressure of the timeline. I don’t feel it. That’s the trick.', 'You confused a story with a hope. Common at your stage.', 'I asked the training ground. You asked the internet. {p} went where the training ground said.', 'Quietly, {name}: that was a poor call and you knew it when you hit post.', 'The physio opens on day three for a reason. The reason is you.', 'I’ll say this once. Check the medical. Then check it again.', 'Twenty years and I still don’t post before the paperwork. You posted before the coffee.', 'Slow is fine. Wrong isn’t. {rec}.', 'Nothing personal, {name}. The record is just the record.', 'You went early on {p} to beat me. You didn’t beat the facts.', 'Filed nothing, would have been the right call. You filed something.',
          ],
          winning: [
            '{rec}. Noted. It won’t happen often.', 'You had {p} before me. Well found.', 'Good call. I’ll be having a word with my man at the training ground.', 'Fair play. You did the legwork.', '{rec}. I’ve started reading your posts. Don’t tell anyone.', 'You beat me to {p}. Most don’t.', 'Credit to you. My contact was at a christening.', 'One day you’ll explain how. Not today, I suspect.',
            'Well done, {name}. Properly. That was a journalist’s call.', 'Your {p} read was better than mine. That sentence cost me something.', 'I was slow and, for once, slow was also wrong. {rec}.', 'Two circles before you posted. I noticed. Good habit.', 'I’d have waited another day on {p}. You didn’t need to. Fair.', 'The press box talked about your call this morning. Kindly, mostly.', 'Right, and early, and Confirmed. Don’t make me get used to it.', '{rec}. I keep the record honestly. It says you.', 'My man at the training ground has been quietly retired.', 'A good week for you, {name}. I remember mine. Enjoy it and check the next one twice.',
            'The record moves against me. It happens rarely enough that I notice.', 'You didn’t chase the agent. That’s why you were right on {p}.', 'Old habits: I waited for the paperwork. New habits, yours: the paperwork waited for you.', 'I’ll not call it luck. Luck doesn’t read a physio.', 'Right on {p}. I said in the press box that you would be. Nobody believed me either.', '{rec}. Bring the same discipline next window and I’ll be worried.', 'You’re learning what not to post. That’s most of the job.', 'I was wrong. Three words I write more easily than the tabloid does.', 'Credit, {name}. I don’t deal in it often, so spend it wisely.', 'The younger reporters are quoting you. Deal with that responsibly.',
            'You filed late and right. That’s my whole method. Get your own.', 'Good call on {p}. The kit man told you, didn’t he. He tells nobody.', 'I read your thread twice. Once to check it, once because it was good.', 'Well found. Now do it again when nobody’s watching.', '{rec}. The record is patient. So am I.', 'Beat me fair. The press box has a rule about that: say so. So: fair.', 'That was reporting. The other two won’t say it. I will.', 'Right, {name}. Quietly right, which is the best kind.', 'I don’t concede often. Consider this the once.', 'One more like {p} and I’ll have to start ringing you.', 'A good call ages well. Yours has. Mine’s in the bin.', 'You out-waited me. I didn’t know that was possible.',
          ],
          level: [
            '{rec}. We both did the homework.', 'Same answer on {p}. Some of us took longer.', 'Level. Nothing wrong with that.', 'We agree on {p}. Don’t make a habit of it.', 'Even. The honest way.', '{rec}. The record’s clean on both sides.', 'Both right. The tabloid won’t like it.', 'Honours even. See you on Deadline Day.',
            'Same call on {p}, same day, different fonts. Mine smaller.', 'Level, {name}. Two people did their job. It shouldn’t be news.', 'We agreed. I checked twice, you checked once. The result forgave you.', '{rec}. No complaints. Few compliments either.', 'Both right on {p}. The agent will claim he told us both. He told neither.', 'Even. If you keep this up I’ll have to learn your name.', 'A draw between people who wait is just two correct sentences.', 'Level. I still filed later. I still slept better.', 'Same story. I attributed mine. Do that.', 'Honours even, and honour is the point, {name}.',
            'We both read the medical. That’s the whole secret. Now everyone knows.', 'Tied. I don’t mind a tie. The tabloid minds enough for all of us.', '{rec}. Nobody was loud, nobody was wrong. A good week for the trade.', 'Both right on {p}. Mine had a second paragraph. Nobody read it.', 'Level. I’ll take that from someone with your record.', 'Same call. You’ll notice I didn’t use the word Confirmed until Friday.', 'Even. We’ll settle it on a story that actually needs settling.', 'Two correct calls and a quiet press box. Ideal, frankly.', 'Draw. I’ll write it up properly. You tweet it.', 'Level, and both of us ignored the barber. Progress.',
            'We agree on {p}. The ITK will say he had it first. He had it vaguest.', '{rec}. Evens. Good.', 'Same answer. I got there by the training ground. You?', 'Level. I was going to say something cutting. Nothing came. That’s praise.', 'Both right. Both waited. The kids won’t understand.', 'Tied, {name}. Keep the standard and it’ll stay tied, which suits me.', 'A draw with you costs me nothing. A draw with the tabloid would.', 'Even. The record only counts what happened. That’s why I like it.', 'Same read on {p}. Different route. Both roads go through the physio.', 'Level. See you on day five. That’s when I post.', 'Two right calls. One of them was quiet about it. Try that.', 'Honours even. I don’t need the last word. I’ll take it anyway.',
          ],
        },
        clubmod: {
          losing: [
            'RATIO. {rec}. The fan page has spoken.', 'L + wrong + we saw it + {rec}.', '{name} said {p} was done. Admin said no. Admin was right. We go again.', 'The mod does not miss. {name} does not hit. Balance.', 'Announce him, they said. Announced someone else, they did. 😂', 'Pinned your {p} take. For education.', 'Cooked. Absolutely cooked. {rec}.', 'Poll in the replies: was {name} wrong? 100% yes. 4,000 votes.', 'Our guy was never going. Our guy is still our guy. Unfollowed you for the scare.', 'Fan page > national press. {rec}. Proof attached.',
            'You put us in shambles for nothing. Admin has receipts.', 'In shambles? Nah, we were fine. YOU were in shambles. {rec}.', '“Sources close to {p}”. The sources were closed, mate.', 'Aura: negative. Call: wrong. Reel: growing. {rec}.', 'The whole group chat laughed. I screenshotted the laughing.', 'Delete it, {name}. We’ve got it in 4K anyway.', 'Admin called it from the car park at 7am. Nationals caught up Sunday. Wrong.', 'Every fan page in the country is quoting you. Not kindly.', 'Ratio speedrun, any%. New record. {rec}.', 'Believe the fans, not the press. Especially not this press.',
            'You had a source at the club. The club has a source at your account. That’s why you were wrong.', 'We go again. You go home. {rec}.', 'Mod alert 🚨: {name} wrong about {p}. Story at 11. Also at 12, 1, 2 and 3.', 'Fumbled the bag. Fumbled the call. Fumbled the ratio.', 'Big platform, tiny hit rate. Admin has a spreadsheet.', 'The page is 18 and it has a better record than you. {rec}.', 'Announce the apology. We’ll wait. We won’t wait.', 'Unpinned your post from our page. Repinned it in the “clowns” highlight.', 'Ran a poll: “trust {name}?” Options were No and Absolutely Not.', 'Your notifications must be a war zone. Good. We built it.',
            'You went Confirmed. We went to sleep. We woke up right. {rec}.', 'Admin has zero sources and a better record. Let that sink in.', 'Called {p} wrong in front of the whole fanbase. Bold.', 'This is why we don’t trust the media. Exhibit A: {name}.', 'Cooked, boiled, roasted. Pick one. All apply. {rec}.', 'Lost the plot, lost the call, lost the ratio. Hat-trick.', 'The replies are a museum now. You’re the main exhibit.', 'Nice try, {name}. The fans knew. The fans always know. Well, this time.', 'Aura down bad. Record {rec}. Admin thriving.', 'We go again. Every window. You should try it.',
          ],
          winning: [
            'Fine. {rec}. Admin is not happy. Admin is never happy.', 'You had {p}. We had hope. Hope lost.', 'Ok that was correct. Blocked anyway. Emotional reasons.', 'The page conceded. Briefly. Deleted the concession.', 'We go again. That’s all I’ve got. {rec}.', 'Admin was wrong and the fans are in shambles. Real shambles this time.', 'Right call, {name}. Not sharing it. Sharing it privately.', 'Announce him. Fine. You said it first. Whatever.', 'The mod has been humbled. The mod will be back tomorrow at 7am.', 'Fans 0, press 1. First time for everything. {rec}.',
            'Ok {name} maybe you do know people. Still not following you.', 'Poll: did admin get it wrong? Yes 51%, No 49%. Suspiciously close.', 'You were right about {p}. Our replies are a funeral.', 'Admin has taken a step back from the page. Admin is the page. Awkward.', 'Cooked. Us this time. Rare. Mark the date.', 'Aura check: yours up, page down. We rebuild.', 'W for the journo. L for the fanbase. Announce the bloke I suppose.', 'You called it. I’m allowing it. Only because I have to.', 'Fair enough. {rec}. Please don’t quote this.', 'Turns out the press are right sometimes. Rare, like a clean sheet.',
            'The page had a bad week. {name} had a good one. Both temporary.', 'Right about {p}. I hate it. Repinned it anyway for “balance”.', 'Admin was in the car park at 7am for nothing. Nothing!', 'I said “never trust the media”. I stand by it. You were still right.', 'Respect, quietly. Loudly I’m still saying ratio.', 'One right call doesn’t make you a fan, {name}. It makes you correct. Different.', 'Deleted my take. The fans deleted their takes. Only your take survived. {rec}.', 'The mods’ group chat is silent. Silence means you won.', 'Our source was a lad in the pub. Your source was better. We go again.', 'Admin apologises to nobody. Admin notes that {name} was right. Not an apology.',
            'Fine, you’re good. Doesn’t mean I like you. {rec}.', 'You saw it before the fans. The fans have noticed. The fans are annoyed.', 'Page unpinned its own take and pinned yours. Under protest.', 'Right on {p}. First person outside the fanbase we’ve ever agreed with.', 'The comments are demanding admin resign. Admin cannot resign. Admin is 17.', 'We go again. You go on. Fair.', 'Give the journo the W. Give admin a lie down.', 'Won’t say you were right. Will say we were wrong. Same thing, worse wording.', 'Kept your post up for once. Learning.', 'Aura: yours. Record: {rec}. Vibes: terrible here.',
          ],
          level: [
            'Both right about {p}. Admin still posted first. Admin always posts first.', 'Level. The fan page is officially press now.', 'Same call. Ours had a crest emoji. Yours had words. Both fine.', 'Tied, {name}. Awkward. We go again.', '{rec}. Neither of us wrong. The replies are confused.', 'Draw. The fans wanted a ratio. Nobody to ratio. Tragic.', 'Both had {p}. The page had it as a poll, which counts.', 'Level. Unfollowed you anyway, on principle.', 'Same story, same day. You got paid for yours. Injustice.', 'Even. The page is furious about not being able to be furious.',
            'Agreed with a journalist. Feels wrong. Shower needed.', 'Draw. Admin still has more followers. Admin checks daily.', 'Level. One of us should have been wrong. Vote in the replies who.', 'You matched the fan page. The fan page is the standard. Congrats.', 'Both right on {p}. I’m claiming it. You claim it too. Fine.', 'Tied. Announce a tiebreaker. Announce him.', 'Nobody in shambles. Weird week.', 'Level with {name}. Blocking and unblocking to process it.', 'We both called it. The mods’ chat said “W for football”. Cringe. True though.', 'Even. Rematch at the next window. Bring your best cope.',
            'Draw. The page has pinned both takes. Ours slightly bigger.', 'Same call on {p}. Mine had 12 fire emojis. Grown-up version yours.', 'Level. The fans are asking who to be angry at. Pick someone.', 'We go again. Both of us, apparently.', 'Tied. Admin was going to ratio you and had nothing to work with. Rude.', 'Both right. Admin has released a statement: “we go again”.', 'Even. {rec}. Boring. Somebody be cooked next time.', 'Same result. The page did a graphic. Did you do a graphic? No. Page wins spiritually.', 'Level with a journo. Don’t tell the other pages.', 'Draw. I’ll take it. The fans won’t. The fans never do.',
            'Both called {p}. Only one of us has a pinned “WE GO AGAIN” that fits every mood.', 'Tied. Aura equal. Unacceptable.', 'Level. I’m running a poll on whether it counts.', 'Same day, same call, same energy. You’re a fan page now, {name}.', 'Draw. Admin is neither thriving nor cooked. Limbo.', 'Both right. The replies are still fighting anyway. Beautiful.', 'We agree. Screenshot it, it won’t happen again.', 'Even. Fine. Announce the next one first and we’ll talk.', 'Level. The page respects it. The page will forget by Monday.', 'Tied, {name}. Ratio deferred, not cancelled.',
          ],
        },
      },
    },
    rv: {
      tabloid: {
        hwg: {
          right: ['HERE WE GO? Fine. Here it went. Screenshot deleted.', 'Gold frame and all. Alright, {p} was yours.', 'The reel needed a good bit. You gave it one. Annoying.', 'Loudest post on the timeline and it was right. Learnt that from me.', 'Announced. Gutted. Well played on {p}.', 'Big capitals, big call, big W. Copying your font.', 'One HERE WE GO doesn’t make a career. Ask me how I know.', 'Fair. Enjoy your one. Reel’s still longer.'],
          wrong: ['HERE WE GO? Here you went. 😂 Clipped.', 'A gold frame on a wrong call. Poetry. {p} says hi from elsewhere.', 'L + you fell for it + it had CAPITALS.', 'Screenshotted before the delete. Pinned forever.', 'HERE WE GO → THERE HE WENT. Somewhere else.', 'Ratio incoming. Bring a coat.', 'The reel has a new opening. It’s in 72pt.', 'You confirmed {p}. Reality declined.'],
        },
        uturn: ['Delete & repost. The two-step. Classic {name}.', 'Deleted faster than the {p} medical. We saw it.', 'Screenshotted before you deleted it 📸 As always.', 'Sat nav energy. “Recalculating.”', 'One post, one delete, one ratio. Efficient.', 'Bro is editing history in real time. History has receipts.', 'Repost all you like. The reel keeps the original.', 'The U-turn on this man. 😂'],
        dd: ['Deadline Day. Sixty seconds. I need five. You need a miracle.', 'Clock’s running. I’ve already posted. Twice.', 'Deadline Day is my Christmas. Your calls are the cracker jokes.', 'Post something. Anything. The reel needs a finale.', 'Sixty seconds, three posts, one of us right. Same as always.', 'Quick post? Quick miss. Go on.', 'The window shuts at midnight. Your credibility shut at noon.', 'DEADLINE DAY. CAPITALS MANDATORY.'],
        ddlive: {
          open: ['Deadline Day Live. Every reporter in the game, one board. Ratio’s public today.', 'The real board is open. Post before the whistle or post nothing. I know which you’ll do.', 'Everybody on the same five. Nowhere to hide, {name}.', 'Live board. Live L’s. Let’s go.'],
          close: ['Whistle. Board shut. Results at midnight, tears by breakfast.', 'That’s Deadline Day. Now we wait for the table and the ratio.', 'Board’s closed. Your calls are in. Some of them, anyway.', 'Window shut. Reel open.'],
          lead: ['Top of the live table? Enjoy the view. It’s a long way down.', 'Leading on Deadline Day. Screenshot it, it won’t last past the paperwork.', 'Ahead of me on the board, {name}. Temporary. Everything is.'],
          trail: ['Below me on the live table. Where you belong, respectfully. Not respectfully.', 'The board says I’m ahead. The board is a wise board.', 'Trailing on Deadline Day. The reel is watching, {name}.'],
        },
      },
      itk: {
        hwg: {
          right: ['told you it was done. you said it louder. fine. 👀', 'here we go. i said 🔜 a day earlier. same thing, fewer letters.', 'ok {p} was done. we both knew. one of us used capitals.', 'gold frame? the source didn’t need a frame.', 'confirmed, and right. take it. 🤫', 'the club knew. i knew. you posted it big. all true.', 'here we go. i prefer 📝 but sure.', 'fair. you had it. don’t tag me in the celebration.'],
          wrong: ['here we go? my source said no. 🤫 {rec}.', 'i posted “keep an eye on a third club”. you posted a gold frame. 👀', 'told you {p} wasn’t done. loudly wrong is still wrong.', 'not a rumour: you were wrong. a fact.', 'the capitals didn’t help. the source would have.', 'here we went. somewhere else. i said so.', 'my drafts had this L in them a day early.', 'you: HERE WE GO. me: 🔜❌. me right.'],
        },
        uturn: ['deleted and reposted. the timeline remembers. 👀', 'a u-turn a day late. i was a day early. maths.', 'repost noted. original noted harder.', 'sat nav energy from {name}. recalculating.', 'delete it all you want. the quote tweets stay.', 'second attempt at {p}. first one screenshotted. 🤫', 'the network saw the original. the network is laughing quietly.', 'reposted. still wrong? we’ll see. 🔜'],
        dd: ['deadline day. 60 seconds. i already know. 👀', 'the clock is for you. my source texted an hour ago.', 'three posts, sixty seconds. i need one. 🔜', 'deadline day is when the car park gets busy. i’m in the car park.', 'post before the clock or don’t. the club has already decided.', 'sixty seconds. the medical was this morning. keep up.', 'quick post? quick and wrong is a genre. yours.', 'DD. 🤫 more soon. much sooner than you.'],
        ddlive: {
          open: ['deadline day live. real board, real sagas. my sources are awake. are yours?', 'everyone on the same five. i had two of them yesterday. 👀', 'live board open. post before the whistle. i posted before the board.', 'real deadline. real texts. real early. 🔜'],
          close: ['board shut. the paperwork decides now. i already know how. 🤫', 'whistle gone. results at midnight. i’ll be asleep. i already know.', 'that’s the live board closed. the group chat is not closed.', 'closed. my sources are quiet. quiet means signed.'],
          lead: ['top of the live table? for now. paperwork lands late. 👀', 'leading on deadline day. i led yesterday, quietly, in the drafts.', 'ahead of me, {name}. noted. temporary. 🔜'],
          trail: ['below me on the live board. the network is ahead. as usual.', 'trailing on deadline day. the source was right. the source is always right.', 'board says i’m ahead of {name}. board is well informed.'],
        },
      },
      insider: {
        hwg: {
          right: ['Confirmed and correct. That is the only kind that counts. Well done.', 'A gold frame on a right call. I’d have used plain text, but I can’t fault it.', '{p} is done, and you said so properly. Noted in the record.', 'Right at Confirmed. Two circles first, I hope. It read that way.', 'The paperwork agrees with you. Rarest thing in the trade.', 'Here we go, they say. I say: accurate. Same thing, fewer capitals.', 'Loud and right. I’ll allow the loud when the right is that clean.', 'Good. Now do it again quietly and I’ll start worrying.'],
          wrong: ['Confirmed is a word with a meaning, son. Look it up. Then look at {p}.', 'A gold frame doesn’t make a fact. A medical does. There wasn’t one.', 'Loud is not the same as right. Today it wasn’t even close.', 'You confirmed a hope. I don’t do hopes.', 'I said wait. You said here we go. {p} said neither.', 'Every reporter gets one of these. Make it one.', 'The record notes a Confirmed miss. The record is not kind about those.', 'Check the medical. Then check it again. Then don’t post a gold frame.'],
        },
        uturn: ['A correction. Good. Now file the first one correctly next time.', 'Deleted and reposted. I don’t delete, because I don’t post before I know.', 'The U-turn is honest, at least. The original wasn’t reporting.', 'Twenty years, no corrections. Not luck. Patience.', 'You changed your mind on {p}. Fine. Change your method.', 'A repost is a receipt for a rushed post.', 'Two posts, one story. One too many.', 'Corrected. The record notes both.'],
        dd: ['Deadline Day. Sixty seconds is a long time if you already know.', 'The clock frightens people into posting. Don’t be people.', 'Three posts. I’ll use one, at the end, and it’ll be right.', 'Deadline Day is where reputations go to be tested. Check the physio first.', 'Sixty seconds. I’ve had a week. So have you. Use it.', 'Quick post is for people who didn’t ring anyone.', 'The window shuts at midnight. Truth doesn’t care about the clock.', 'Deadline Day. Same rules. Slow down.'],
        ddlive: {
          open: ['Deadline Day Live. Real sagas, one board. The paperwork decides, not the noise.', 'Every reporter on the same five. Good. A fair test at last.', 'The board is open until 23:00. I’ll file before then. Not much before.', 'Live board. Real clubs. Ring someone before you post, {name}.'],
          close: ['Board closed. Now the only thing that matters is what actually happened.', 'The whistle’s gone. Results at midnight. I can wait.', 'Live board shut. Everyone posted. Not everyone reported.', 'That’s the deadline. The record will be updated properly, tomorrow.'],
          lead: ['You lead the live table. The paperwork hasn’t landed. Neither has my call yet.', 'Ahead of me on Deadline Day. Enjoy it; keep it by being right, not early.', 'Leading, {name}. The table is a snapshot. The record is the film.'],
          trail: ['You’re below me on the live board. Slow was right again.', 'Trailing on Deadline Day. Nothing wrong with that unless you rushed.', 'The board has me ahead of {name}. Twenty years of not rushing.'],
        },
      },
      clubmod: {
        hwg: {
          right: ['ANNOUNCE HIM. Fine. {name} said it first. Fine.', 'HERE WE GO and it was actually here we go. The page is emotional.', 'Announced. The journo was right. The mod is coping in the replies.', 'Gold frame, right call. We go again. Positively, this time.', 'Our guy is our guy. {p} is home. Credit where it hurts.', 'The fanbase is thriving and it’s {name}’s fault. Weird sentence.', 'HERE WE GO ✅. Admin allowed it.', 'Called it, gold framed it, landed it. The page has pinned it. Under protest.'],
          wrong: ['HERE WE GO? Here we DON’T. In shambles. Because of you.', 'You put a gold frame on it and the club put {p} on a plane elsewhere. Cooked.', 'Announce him, they said. Announced who? Exactly. RATIO.', 'The whole fanbase got excited off a gold frame. Admin is furious.', 'HERE WE GO → HERE WE WENT → we go again.', 'Poll in the replies: was that the worst HERE WE GO ever? Trending yes.', 'Aura gone. Frame gone. Call gone. {rec}.', 'We were in shambles for NOTHING. Blocked.'],
        },
        uturn: ['Deleted and reposted. The page has both. The page has everything.', 'Sat nav journalism. Recalculating. We go again.', 'Screenshotted the original 📸 posted the repost 📸 posted the ratio 📸', 'Two takes on {p} in one day. Admin has one take a decade. Bad ones, but one.', 'Delete & repost = admit & lose.', 'The U-turn! The fans have receipts. The fans always have receipts.', 'Repost noted. Ratio maintained.', 'Changed your mind on {p}? The page never changes its mind. That’s our whole problem.'],
        dd: ['DEADLINE DAY. Admin has not slept. Admin will not sleep.', 'Sixty seconds. Announce him. ANNOUNCE HIM.', 'Deadline Day and the page is on 4% battery and 100% cope.', 'Three posts, one minute, all wrong probably. Go on then.', 'Clock’s running. The fans are refreshing. Admin is refreshing harder.', 'Deadline Day. If you’re wrong today the ratio is permanent.', 'The whole fanbase is watching the clock. Don’t post rubbish.', 'DD. We go again. Announce somebody.'],
        ddlive: {
          open: ['DEADLINE DAY LIVE. Everyone on the same board. The page is ready. The page has coffee.', 'Real sagas, real board, real ratios. Post it, {name}. We’re all watching.', 'Live board open. Admin’s calls are in. Admin is never wrong on the day. (Admin is often wrong on the day.)', 'The whole game on five sagas. In shambles already.'],
          close: ['Whistle. Board shut. Now we wait and refresh and refresh and refresh.', 'Board closed. Results at midnight. The fans will be awake. Obviously.', 'That’s Deadline Day Live done. Announce the table. ANNOUNCE IT.', 'Closed. The page is in shambles. Standard.'],
          lead: ['{name} leading the live table. The page demands a recount.', 'Top of the board on Deadline Day. Cooked when the paperwork lands, hopefully. Not hopefully. Fine, hopefully.', 'Ahead of the page on the live table. Temporary. Announce a collapse.'],
          trail: ['Below the fan page on the live table. Fan page > press. As predicted.', 'Trailing on Deadline Day. We go again. You go again harder.', 'The board has admin above {name}. The board is based.'],
        },
      },
    },
  },
};
